import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createGamerBro} from '../playground-v2/gamer-bro.js?v=pass6';
import {createAdvancedTube,ADVANCED_TUBE_ID} from '../src/advanced-tube-v1.js?v=pass6';

const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const qp=new URLSearchParams(location.search),requested=qp.get('hero'),saved=localStorage.getItem('gamerBroCharacter');
const unlocked=localStorage.getItem('gamerBrosCitrusUnlocked')==='1';
const playable=new Set(['gb1','gb2',...(unlocked?['citrus']:[])]),id=playable.has(requested)?requested:(playable.has(saved)?saved:'gb2');
const HEROES={gb1:{name:'GB1',kind:'gamer',colorway:'pink'},gb2:{name:'GB2',kind:'gamer',colorway:'teal'},citrus:{name:'CITRUS',kind:'glb',file:'../pass1-v1/assets/recovered/characters/sprite_hero.glb'}};
const H=HEROES[id]||HEROES.gb2;localStorage.setItem('gamerBroCharacter',id);
const $=s=>document.querySelector(s),canvas=$('#game'),heroName=$('#heroName'),menu=$('#menu'),gemsEl=$('#gems'),coinsEl=$('#coins'),foesEl=$('#foes'),objective=$('#objective'),pad=$('#pad'),stick=$('#stick'),jumpBtn=$('#jump'),runBtn=$('#run'),actionBtn=$('#action'),toastEl=$('#toast'),boot=$('#boot'),status=$('#status'),bar=$('#bar'),fatal=$('#fatal'),errorEl=$('#error'),complete=$('#complete'),completeTitle=$('#completeTitle');heroName.textContent=H.name;menu.onclick=()=>location.href='../';completeTitle.onclick=()=>location.href='../';
const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.2:1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x77b8dd);scene.fog=new THREE.Fog(0x8cc7e2,42,92);const camera=new THREE.PerspectiveCamera(48,1,.08,180);camera.layers.enable(1);scene.add(new THREE.HemisphereLight(0xf5fdff,0x31533c,2.45));const sun=new THREE.DirectionalLight(0xfff4d6,3.8);sun.position.set(-24,35,19);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:1536,mobile?1024:1536);sun.shadow.camera.left=-45;sun.shadow.camera.right=45;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-45;sun.shadow.camera.near=1;sun.shadow.camera.far=110;scene.add(sun);const fill=new THREE.DirectionalLight(0xa6dfff,.65);fill.position.set(22,15,-22);scene.add(fill);
const loader=new GLTFLoader(),textureLoader=new THREE.TextureLoader();const world=new THREE.Group(),actors=new THREE.Group(),fx=new THREE.Group();scene.add(world,actors,fx);
function progress(t,n){status.textContent=t;bar.style.width=n+'%'}function toast(t,ms=1500){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),ms)}function shadows(r,cast=!mobile){r.traverse?.(o=>{if(o.isMesh){o.castShadow=cast;o.receiveShadow=true}});return r}function fitHeight(root,h){root.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(root),s=b.getSize(new THREE.Vector3()),k=h/Math.max(.001,s.y);root.scale.multiplyScalar(k);root.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(root);const c=b.getCenter(new THREE.Vector3());root.position.x-=c.x;root.position.z-=c.z;root.position.y-=b.min.y;return root}
let mapRoot=null,mapBounds=new THREE.Box3(),groundMeshes=[],mapMeshCount=0,palette=null;
const normalM=new THREE.Matrix3(),down=new THREE.Vector3(0,-1,0),ray=new THREE.Raycaster();
function mapCollisionCandidate(o){const n=(o.name||'').toLowerCase();if(/coin|gem|jewel|heart|key|bee|slime|bomb|cannon|bullet|flower|grassblade|tree|bush|sign|fence|ladder|chest/.test(n))return false;return true;}
async function loadMap(){progress('Loading exact downloaded starter level…',18);const [g,pal]=await Promise.all([loader.loadAsync('../assets/vendor/leap-land/tutorial-starter-level.glb'),textureLoader.loadAsync('../assets/vendor/leap-land/palette.png')]);palette=pal;palette.colorSpace=THREE.SRGBColorSpace;palette.flipY=false;palette.magFilter=THREE.NearestFilter;palette.minFilter=THREE.NearestMipmapNearestFilter;mapRoot=g.scene;world.add(mapRoot);mapRoot.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(mapRoot),sz=b.getSize(new THREE.Vector3()),scale=52/Math.max(.001,sz.x,sz.z);mapRoot.scale.multiplyScalar(scale);mapRoot.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(mapRoot);const c=b.getCenter(new THREE.Vector3());mapRoot.position.x-=c.x;mapRoot.position.z-=c.z;mapRoot.position.y-=b.min.y;mapRoot.updateMatrixWorld(true);mapBounds.setFromObject(mapRoot);mapRoot.traverse(o=>{if(!o.isMesh)return;mapMeshCount++;o.castShadow=!mobile;o.receiveShadow=true;if(o.geometry?.attributes?.uv){const src=Array.isArray(o.material)?o.material[0]:o.material;const mat=new THREE.MeshStandardMaterial({map:palette,color:0xffffff,roughness:.82,metalness:0,side:src?.side??THREE.FrontSide});o.material=mat}if(mapCollisionCandidate(o))groundMeshes.push(o)});if(groundMeshes.length<3){groundMeshes=[];mapRoot.traverse(o=>{if(o.isMesh)groundMeshes.push(o)})}window.__levelSource='leap-land-tutorial-starter';window.__mapMeshCount=mapMeshCount;window.__mapBounds={min:mapBounds.min.toArray(),max:mapBounds.max.toArray(),size:mapBounds.getSize(new THREE.Vector3()).toArray()};window.__visibleMapIsImported=true;}
function groundAt(x,z,fromY=null){if(!groundMeshes.length)return null;const top=fromY??(mapBounds.max.y+10);ray.set(new THREE.Vector3(x,top,z),down);ray.far=Math.max(30,mapBounds.max.y-mapBounds.min.y+25);const hits=ray.intersectObjects(groundMeshes,false);for(const h of hits){if(!h.face)continue;normalM.getNormalMatrix(h.object.matrixWorld);const n=h.face.normal.clone().applyNormalMatrix(normalM);if(n.y>.48)return h.point.y}return null;}
function within(x,z,m=1){return x>mapBounds.min.x+m&&x<mapBounds.max.x-m&&z>mapBounds.min.z+m&&z<mapBounds.max.z-m}
function findGroundNear(tx,tz,maxRadius=18){const y0=groundAt(tx,tz);if(y0!=null)return new THREE.Vector3(tx,y0,tz);for(let r=1;r<=maxRadius;r+=1.2){for(let i=0;i<20;i++){const a=i/20*Math.PI*2,x=tx+Math.cos(a)*r,z=tz+Math.sin(a)*r;if(!within(x,z,.4))continue;const y=groundAt(x,z);if(y!=null)return new THREE.Vector3(x,y,z)}}return null;}
let spawn=new THREE.Vector3(),tubePos=new THREE.Vector3();function chooseRoute(){const size=mapBounds.getSize(new THREE.Vector3()),center=mapBounds.getCenter(new THREE.Vector3());const candidates=[[center.x-size.x*.22,center.z+size.z*.16],[center.x,center.z],[center.x-size.x*.16,center.z-size.z*.1]];let s=null;for(const [x,z] of candidates){s=findGroundNear(x,z,12);if(s)break}if(!s)throw new Error('Could not find a walkable spawn on imported level');spawn.copy(s);const tx=center.x+size.x*.28,tz=center.z-size.z*.22;const t=findGroundNear(tx,tz,18)||findGroundNear(center.x+size.x*.2,center.z+size.z*.2,18)||s.clone().add(new THREE.Vector3(10,0,-8));const ty=groundAt(t.x,t.z);tubePos.set(t.x,ty??t.y,t.z);window.__spawnPoint=spawn.toArray();window.__tubePosition={x:tubePos.x,y:tubePos.y,z:tubePos.z};}
let player=null,visual=null,adapter=null,mixer=null;async function createPlayer(){progress('Loading Gamer Bro…',38);player=new THREE.Group();actors.add(player);if(H.kind==='gamer'){adapter=createGamerBro(THREE,renderer,{colorway:H.colorway,detail:mobile?'low':'high',height:2.72});visual=adapter.root;adapter.setMotion?.('idle');player.add(visual)}else{const g=await loader.loadAsync(H.file);visual=fitHeight(g.scene,2.72);player.add(visual);if(g.animations?.length){mixer=new THREE.AnimationMixer(visual);mixer.clipAction(g.animations.find(a=>/idle/i.test(a.name))||g.animations[0]).play()}}shadows(visual,!mobile);player.position.copy(spawn).add(new THREE.Vector3(0,.04,0));player.rotation.y=Math.PI;window.__characterReady=id;window.__playerPosition=player.position;}
const ENEMY_FILES=[['STUMP','../pass1-v1/assets/recovered/characters/stump.glb'],['GHOST','../pass1-v1/assets/recovered/characters/ghost.glb'],['CTHULHU','../pass1-v1/assets/recovered/characters/cthulhu.glb'],['YETI','../pass1-v1/assets/recovered/characters/yeti.glb']],enemies=[];let kills=0;
async function createEnemy(name,file,pos,index){const g=await loader.loadAsync(file),o=fitHeight(g.scene,2.72);shadows(o,!mobile);o.position.copy(pos).add(new THREE.Vector3(0,.03,0));actors.add(o);let mix=null;if(g.animations?.length){mix=new THREE.AnimationMixer(o);mix.clipAction(g.animations.find(a=>/idle|walk/i.test(a.name))||g.animations[0]).play()}enemies.push({name,o,mix,home:o.position.clone(),phase:index*1.7,alive:true});}
function enemyPoint(i){const a=[.35,1.9,3.45,5.1][i],r=Math.min(10,Math.max(5,mapBounds.getSize(new THREE.Vector3()).x*.16)),tx=spawn.x+Math.cos(a)*r,tz=spawn.z+Math.sin(a)*r;return findGroundNear(tx,tz,8)||spawn.clone();}
async function createEnemies(){progress('Placing four recovered enemies at matching scale…',51);await Promise.all(ENEMY_FILES.map((e,i)=>createEnemy(e[0],e[1],enemyPoint(i),i)));foesEl.textContent=`FOES · ${kills} / ${enemies.length}`;window.__enemyCount=enemies.length;window.__enemyScaleTarget=2.72;window.__enemyDebugPositions=enemies.map(e=>e.o.position.toArray());}
function damageEnemy(e){if(!e?.alive)return;e.alive=false;e.o.visible=false;kills++;foesEl.textContent=`FOES · ${kills} / ${enemies.length}`;toast(`${e.name} CLEARED`);if(kills===enemies.length){objective.textContent='ALL ENEMIES CLEARED · ENTER THE ADVANCED TUBE';toast('ADVANCED TUBE ONLINE',2200)}window.__enemyKills=kills;}
window.__damageEnemy=i=>damageEnemy(enemies[i]);window.__defeatAllEnemies=()=>enemies.forEach(damageEnemy);
const pickupSources={gem:null,coin:null},pickups=[];let gemCount=0,coinCount=0;async function pickupSource(path){const g=await loader.loadAsync(path);return fitHeight(g.scene,.68)}
function routePoint(t,offset=0){const base=spawn.clone().lerp(tubePos,t),d=tubePos.clone().sub(spawn);d.y=0;const len=Math.max(.001,d.length());d.multiplyScalar(1/len);const side=new THREE.Vector3(-d.z,0,d.x);base.addScaledVector(side,offset);const p=findGroundNear(base.x,base.z,4);return p||base;}
async function createPickups(){progress('Adding coin + gem comparison pickups…',61);pickupSources.gem=await pickupSource('../assets/vendor/kenney-platformer/models/jewel.glb');pickupSources.coin=await pickupSource('../assets/vendor/kenney-platformer/models/coin-gold.glb');for(let i=0;i<16;i++){const kind=i%2===0?'gem':'coin',t=.08+(i/15)*.84,off=(i%4<2?-1:1)*(1.2+(i%3)*.35),p=routePoint(t,off),o=pickupSources[kind].clone(true);o.position.copy(p).add(new THREE.Vector3(0,1.0,0));actors.add(o);pickups.push({kind,o,baseY:o.position.y,phase:i*.43,alive:true})}window.__gemSeed=pickups.filter(p=>p.kind==='gem').length;window.__coinSeed=pickups.filter(p=>p.kind==='coin').length;gemsEl.textContent=`GEMS · 0 / ${window.__gemSeed}`;coinsEl.textContent=`COINS · 0 / ${window.__coinSeed}`;}
let portal=null,portalPrewarmed=false,levelComplete=false;function createTube(){progress('Installing refined Gamer Bros transfer tube…',70);portal=createAdvancedTube(THREE,{mobile});portal.root.position.copy(tubePos);portal.root.userData.component=ADVANCED_TUBE_ID;world.add(portal.root);portal.setCharge(0);window.__advancedTubeReady=true;window.__advancedTubeComponent=ADVANCED_TUBE_ID;}
async function prewarm(){progress('Prewarming tube shaders…',79);try{const p=renderer.compileAsync?.(scene,camera);if(p?.then)await p;else renderer.compile?.(scene,camera)}catch(e){console.warn('[Pass6] compile warmup fallback',e)}portalPrewarmed=true;window.__advancedTubePrewarmed=true;}
function finishLevel(){if(levelComplete)return;levelComplete=true;localStorage.setItem('gamerBrosCitrusUnlocked','1');localStorage.setItem('gamerBrosLevel1Complete','1');window.__levelComplete=true;window.__citrusUnlocked=true;portal?.setCharge(1);objective.textContent='LEVEL 1 COMPLETE · CITRUS UNLOCKED';toast('CITRUS UNLOCKED!',2200);setTimeout(()=>complete.classList.add('show'),700);}
const inp={x:0,y:0,run:false},keys={};let stickPointer=null,vy=0,grounded=true,camYaw=Math.PI*.12,camPitch=.28,camDist=9.4,lookPointer=null,lastX=0,lastY=0,lastLook=0;
function setStick(x,y){const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,lim=r.width*.34;let dx=x-cx,dy=y-cy,d=Math.hypot(dx,dy);if(d>lim){dx=dx/d*lim;dy=dy/d*lim}const nx=dx/lim,ny=-dy/lim,mag=Math.hypot(nx,ny);if(mag<.12){inp.x=inp.y=0}else{const k=(mag-.12)/.88/mag;inp.x=nx*k;inp.y=ny*k}stick.style.transform=`translate3d(${dx}px,${dy}px,0)`}function clearStick(){stickPointer=null;inp.x=inp.y=0;stick.style.transform='translate3d(0,0,0)'}pad.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();stickPointer=e.pointerId;pad.setPointerCapture?.(e.pointerId);setStick(e.clientX,e.clientY)});pad.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer){e.preventDefault();setStick(e.clientX,e.clientY)}});pad.addEventListener('pointerup',e=>{if(e.pointerId===stickPointer)clearStick()});pad.addEventListener('pointercancel',clearStick);runBtn.onpointerdown=e=>{e.preventDefault();inp.run=true;runBtn.classList.add('active')};runBtn.onpointerup=runBtn.onpointercancel=runBtn.onpointerleave=()=>{inp.run=false;runBtn.classList.remove('active')};function jump(){if(grounded&&!levelComplete){vy=8.5;grounded=false;adapter?.play?.('jump')}}jumpBtn.onpointerdown=e=>{e.preventDefault();jump();jumpBtn.classList.add('active')};jumpBtn.onpointerup=jumpBtn.onpointercancel=()=>jumpBtn.classList.remove('active');addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'){e.preventDefault();jump()}if(e.code==='KeyE')fire()});addEventListener('keyup',e=>keys[e.code]=false);
const pinch=new Map();canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){pinch.set(e.pointerId,[e.clientX,e.clientY]);if(pinch.size===1){lookPointer=e.pointerId;lastX=e.clientX;lastY=e.clientY}return}lookPointer=e.pointerId;lastX=e.clientX;lastY=e.clientY});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'&&pinch.has(e.pointerId)){pinch.set(e.pointerId,[e.clientX,e.clientY]);if(pinch.size===2){const a=[...pinch.values()],d=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);if(canvas._pd)camDist=THREE.MathUtils.clamp(canvas._base-(d-canvas._pd)*.008,6.5,13);else{canvas._pd=d;canvas._base=camDist}return}}if(e.pointerId!==lookPointer||pinch.size>1)return;camYaw-=(e.clientX-lastX)*.0028;camPitch=THREE.MathUtils.clamp(camPitch+(e.clientY-lastY)*.0021,.1,.58);lastX=e.clientX;lastY=e.clientY;lastLook=performance.now()});function endLook(e){pinch.delete(e.pointerId);canvas._pd=0;if(e.pointerId===lookPointer)lookPointer=null}canvas.addEventListener('pointerup',endLook);canvas.addEventListener('pointercancel',endLook);
const starShape=new THREE.Shape();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?.42:1,x=Math.cos(a)*r,y=Math.sin(a)*r;i?starShape.lineTo(x,y):starShape.moveTo(x,y)}starShape.closePath();const starGeo=new THREE.ShapeGeometry(starShape),shotColors=[0xff70c9,0x6fe7ff,0xffd45e,0x9d77ff,0x77eda4],projectiles=[];function forward(){return new THREE.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y))}function fire(){if(!player||levelComplete)return;const d=forward(),origin=player.position.clone().add(new THREE.Vector3(0,1.45,0));for(let i=0;i<5;i++){const o=new THREE.Mesh(starGeo,new THREE.MeshBasicMaterial({color:shotColors[i],side:THREE.DoubleSide,transparent:true,opacity:.96,depthWrite:false}));o.scale.setScalar(.23);o.position.copy(origin);fx.add(o);const v=d.clone().applyAxisAngle(new THREE.Vector3(0,1,0),(i-2)*.07).multiplyScalar(10.5);projectiles.push({o,v,life:1.35})}window.__powerCount=(window.__powerCount||0)+1;adapter?.play?.('attack')}actionBtn.onpointerdown=e=>{e.preventDefault();actionBtn.classList.add('active');fire()};actionBtn.onpointerup=actionBtn.onpointercancel=()=>actionBtn.classList.remove('active');
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize,{passive:true});resize();let last=performance.now(),animT=0;const dir=new THREE.Vector3(),fwd=new THREE.Vector3(),right=new THREE.Vector3(),look=new THREE.Vector3(),desired=new THREE.Vector3();
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,(now-last)/1000);last=now;animT+=dt;if(!player){renderer.render(scene,camera);return}let ix=inp.x+(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),iy=inp.y+(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),mag=Math.min(1,Math.hypot(ix,iy));if(mag>.05&&!levelComplete){const l=Math.hypot(ix,iy);ix/=l;iy/=l;fwd.set(-Math.sin(camYaw),0,-Math.cos(camYaw));right.set(Math.cos(camYaw),0,-Math.sin(camYaw));dir.copy(fwd).multiplyScalar(iy).addScaledVector(right,ix).normalize();const speed=(inp.run||keys.ShiftLeft||keys.ShiftRight)?6.1:3.8,nx=player.position.x+dir.x*speed*mag*dt,nz=player.position.z+dir.z*speed*mag*dt,gy=within(nx,nz,.05)?groundAt(nx,nz,player.position.y+4):null;if(gy!=null){const step=gy-(player.position.y-.04);if(step<1.15&&step>-2.4){player.position.x=nx;player.position.z=nz;if(grounded)player.position.y=THREE.MathUtils.lerp(player.position.y,gy+.04,1-Math.exp(-dt*12))}}const target=Math.atan2(dir.x,dir.z),diff=Math.atan2(Math.sin(target-player.rotation.y),Math.cos(target-player.rotation.y));player.rotation.y+=diff*(1-Math.exp(-dt*8));if(now-lastLook>1200){const follow=target+Math.PI,cd=Math.atan2(Math.sin(follow-camYaw),Math.cos(follow-camYaw));camYaw+=cd*(1-Math.exp(-dt*1.3))}}vy-=18*dt;player.position.y+=vy*dt;const gy=groundAt(player.position.x,player.position.z,player.position.y+4);if(gy!=null&&player.position.y<=gy+.04&&player.position.y>gy-2.2){player.position.y=gy+.04;vy=0;grounded=true}else grounded=false;if(player.position.y<mapBounds.min.y-5){player.position.copy(spawn).add(new THREE.Vector3(0,.04,0));vy=0;grounded=true;toast('BACK TO START')}try{adapter?.update(animT,dt,mag);mixer?.update(dt)}catch{}
for(const e of enemies){if(!e.alive)continue;e.mix?.update(dt*.9);const t=now*.001+e.phase,eGy=groundAt(e.home.x+Math.sin(t*.55)*.55,e.home.z+Math.cos(t*.48)*.4,e.home.y+5);e.o.position.x=e.home.x+Math.sin(t*.55)*.55;e.o.position.z=e.home.z+Math.cos(t*.48)*.4;if(eGy!=null)e.o.position.y=eGy+.03;e.o.rotation.y+=dt*.28}
for(const p of pickups){if(!p.alive)continue;p.phase+=dt;p.o.rotation.y+=dt*2.1;p.o.position.y=p.baseY+Math.sin(p.phase*2.5)*.12;if(Math.hypot(p.o.position.x-player.position.x,p.o.position.z-player.position.z)<1.15&&Math.abs(p.o.position.y-(player.position.y+1))<1.6){p.alive=false;p.o.visible=false;if(p.kind==='gem'){gemCount++;gemsEl.textContent=`GEMS · ${gemCount} / ${window.__gemSeed}`}else{coinCount++;coinsEl.textContent=`COINS · ${coinCount} / ${window.__coinSeed}`}window.__pickupCounts={gems:gemCount,coins:coinCount}}}
for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.life-=dt;p.o.position.addScaledVector(p.v,dt);p.o.rotation.z+=dt*8;for(const e of enemies){if(e.alive&&p.o.position.distanceTo(e.o.position)<1.45){damageEnemy(e);p.life=0;break}}if(p.life<=0){fx.remove(p.o);projectiles.splice(i,1)}}if(portal){portal.setCharge(kills===enemies.length?1:0);portal.update(now*.001,dt);const d=Math.hypot(player.position.x-tubePos.x,player.position.z-tubePos.z);if(d<1.6&&!levelComplete){if(kills<enemies.length){if(!frame._warn||now-frame._warn>1800){toast(`${enemies.length-kills} ENEMIES REMAIN`);frame._warn=now}}else finishLevel()}}
look.set(player.position.x,player.position.y+1.4,player.position.z);desired.set(look.x+Math.sin(camYaw)*Math.cos(camPitch)*camDist,look.y+Math.sin(camPitch)*camDist+1.15,look.z+Math.cos(camYaw)*Math.cos(camPitch)*camDist);camera.position.lerp(desired,1-Math.exp(-dt*5.3));camera.lookAt(look);window.__frameCount=(window.__frameCount||0)+1;window.__moveDebug={x:player.position.x,y:player.position.y,z:player.position.z,grounded,mag};renderer.render(scene,camera)}
(async()=>{try{await loadMap();progress('Finding walkable route on imported geometry…',29);chooseRoute();await createPlayer();await createEnemies();await createPickups();createTube();requestAnimationFrame(frame);await prewarm();progress('Ready — this is the actual Leap Land starter world.',100);window.__pass6Ready=true;window.__pass6World='real-leap-land-starter';window.__noFlatPortal=true;setTimeout(()=>boot.classList.add('hide'),240)}catch(e){console.error(e);errorEl.textContent=String(e?.message||e);fatal.classList.add('show')}})();
