const chunkPaths=['01.txt','02.txt','03.txt','04.txt','05.txt','06.txt','07.txt','08.txt','09.txt','10.txt'].map(n=>new URL(`../src/chunks/${n}`,import.meta.url));

function patchRuntime(source){
  const applied=[];
  const rep=(find,replace,label,critical=true)=>{
    if(!source.includes(find)){
      console.warn('[hybrid clean miss]',label);
      if(critical) throw new Error(`Hybrid clean rebuild missing: ${label}`);
      return false;
    }
    source=source.replace(find,replace);applied.push(label);return true;
  };

  rep('wallInst.instanceMatrix.needsUpdate=true;if(wallInst.instanceColor)wallInst.instanceColor.needsUpdate=true;env.add(wallInst);','wallInst.instanceMatrix.needsUpdate=true;if(wallInst.instanceColor)wallInst.instanceColor.needsUpdate=true;wallInst.visible=false;env.add(wallInst);','hide room wall');
  rep('const ceilingMat=stoneDark.clone();ceilingMat.side=THREE.DoubleSide;ceilingMat.color.setHex(0x4a424e);envMesh(new THREE.CylinderGeometry(ROOM_R+.18,ROOM_R+.18,.32,80),ceilingMat,new THREE.Vector3(0,ROOM_H,0),false);','const ceilingMat=stoneDark.clone();ceilingMat.side=THREE.DoubleSide;ceilingMat.color.setHex(0x4a424e);const openCeiling=envMesh(new THREE.CylinderGeometry(ROOM_R+.18,ROOM_R+.18,.32,80),ceilingMat,new THREE.Vector3(0,ROOM_H,0),false);openCeiling.visible=false;','hide ceiling');
  rep('cornice.castShadow=false;cornice.receiveShadow=true;env.add(cornice);','cornice.castShadow=false;cornice.receiveShadow=true;cornice.visible=false;env.add(cornice);','hide cornice');
  rep('[archFoot,archBlocks,archCaps,archTrim,reliefOuter,reliefInner,voussoir,alcoves].forEach(m=>{m.instanceMatrix.needsUpdate=true;if(m.instanceColor)m.instanceColor.needsUpdate=true;});','[archFoot,archBlocks,archCaps,archTrim,reliefOuter,reliefInner,voussoir,alcoves].forEach(m=>{m.instanceMatrix.needsUpdate=true;if(m.instanceColor)m.instanceColor.needsUpdate=true;m.visible=false;});','hide arches');
  rep('[buttBase,buttBlocks,buttCaps].forEach(m=>m.instanceMatrix.needsUpdate=true);','[buttBase,buttBlocks,buttCaps].forEach(m=>{m.instanceMatrix.needsUpdate=true;m.visible=false;});','hide buttresses');
  rep('[torchBack,torchBracket,torchCup].forEach(m=>m.instanceMatrix.needsUpdate=true);','[torchBack,torchBracket,torchCup].forEach(m=>{m.instanceMatrix.needsUpdate=true;m.visible=false;});torchFlame.visible=false;torchCore.visible=false;','hide wall torches');
  rep('[lanternChain,lanternCap,lanternFrame,lanternGlass,lanternGlow].forEach(m=>m.instanceMatrix.needsUpdate=true);','[lanternChain,lanternCap,lanternFrame,lanternGlass,lanternGlow].forEach(m=>{m.instanceMatrix.needsUpdate=true;m.visible=false;});','hide hanging lanterns');
  rep('function canLeaveRoom(nx,nz){const r=Math.hypot(nx,nz);if(r<=ROOM_R-.62)return true;return nz>ROOM_R-.95&&Math.abs(nx)<2.75;}','function canLeaveRoom(nx,nz){return true;}','remove room boundary');
  rep('const PLAYER_RADIUS=.34,STEP_HEIGHT=.52,GRAVITY=8.25,JUMP_V=5.05,DOUBLE_JUMP_V=4.65,HOLD_BOOST_V=3.95,HOLD_BOOST_INTERVAL=.22;','const PLAYER_RADIUS=.34,STEP_HEIGHT=.90,GRAVITY=8.25,JUMP_V=5.05,DOUBLE_JUMP_V=4.65,HOLD_BOOST_V=3.95,HOLD_BOOST_INTERVAL=.22;','forgiving step height');

  rep('color: 0x0b0c14, roughness: 0.24, metalness: 0.55, clearcoat: 0.75, clearcoatRoughness: 0.10, envMapIntensity: 1.45','color: 0x18233d, roughness: 0.22, metalness: 0.42, clearcoat: 0.82, clearcoatRoughness: 0.08, envMapIntensity: 1.45','native glasses frame');
  rep('color: 0xff2fbb, emissive: 0x8a0a66, emissiveIntensity: 0.45,','color: 0xff45c2, emissive: 0x790d63, emissiveIntensity: 0.52,','native lenses');
  rep('M.cup = new THREE.MeshPhysicalMaterial({ color: new THREE.Color(P.cup), roughness: 0.40, metalness: 0.05, clearcoat: 0.30, envMapIntensity: 1.0 });','M.cup = new THREE.MeshPhysicalMaterial({ color: 0x25c6cf, roughness: 0.36, metalness: 0.06, clearcoat: 0.42, envMapIntensity: 1.0 });','native headphone cup');
  rep('M.cupAccent = new THREE.MeshPhysicalMaterial({ color: new THREE.Color(P.cupAccent), roughness: 0.34, metalness: 0.06, clearcoat: 0.40, envMapIntensity: 1.15 });','M.cupAccent = new THREE.MeshPhysicalMaterial({ color: 0xff9d35, roughness: 0.30, metalness: 0.07, clearcoat: 0.48, envMapIntensity: 1.15 });','native headphone accent');
  rep('M.pad = new THREE.MeshPhysicalMaterial({ color: 0x1a1c26, roughness: 0.85, metalness: 0.0, sheen: 0.6, sheenColor: new THREE.Color(0x6a7288), envMapIntensity: 0.5 });','M.pad = new THREE.MeshPhysicalMaterial({ color: 0x26324a, roughness: 0.82, metalness: 0.0, sheen: 0.6, sheenColor: new THREE.Color(0x6a7288), envMapIntensity: 0.5 });','native headphone pad');
  rep('M.trim = new THREE.MeshPhysicalMaterial({ color: new THREE.Color(P.trim), roughness: 0.32, metalness: 0.05, clearcoat: 0.45, envMapIntensity: 1.2 });','M.trim = new THREE.MeshPhysicalMaterial({ color: 0xef4fa8, roughness: 0.30, metalness: 0.05, clearcoat: 0.48, envMapIntensity: 1.2 });','native trim');
  rep('M.cup.color.set(P.cup); M.cupAccent.color.set(P.cupAccent);\n    M.trim.color.set(P.trim); M.shoe.color.set(P.shirt);','M.cup.color.set(0x25c6cf); M.cupAccent.color.set(0xff9d35);\n    M.trim.color.set(0xef4fa8); M.shoe.color.set(P.shirt);','preserve two-tone colorway');
  rep('  const LOCKS = [','  const LOCKS = [\n    [[-0.46,2.34,0.31],[-0.28,2.66,0.49],[0.02,2.94,0.41],1.15],\n    [[-0.20,2.38,0.38],[0.05,2.74,0.56],[0.39,2.94,0.40],1.18],\n    [[0.08,2.38,0.38],[0.36,2.69,0.52],[0.70,2.80,0.30],1.12],','native hero hair silhouette');

  rep('const moveKeys={up:false,down:false,left:false,right:false,run:false,jump:false,jumpQueued:false};','const moveKeys={up:false,down:false,left:false,right:false,run:false,jump:false,jumpQueued:false};const analogMove={x:0,y:0,active:false,pointerId:null};','analog state');
  rep("const f=(moveKeys.up?1:0)-(moveKeys.down?1:0),sd=(moveKeys.right?1:0)-(moveKeys.left?1:0),len=Math.hypot(f,sd);\n      let dx=0,dz=0;\n      if(len>0){\n        const moveYaw=(cameraMode==='orbit'?yaw+Math.PI:(followLock?player.yaw:yaw+Math.PI));\n        const fx=Math.sin(moveYaw),fz=Math.cos(moveYaw),rx=Math.sin(moveYaw+Math.PI/2),rz=Math.cos(moveYaw+Math.PI/2);\n        dx=(fx*f+rx*sd)/len;dz=(fz*f+rz*sd)/len;\n        const ty=Math.atan2(dx,dz),diff=Math.atan2(Math.sin(ty-player.yaw),Math.cos(ty-player.yaw));player.yaw+=diff*Math.min(1,dt*10.5);\n      }\n      const targetSpeed=len>0?(moveKeys.run?4.65:2.85):0;player.speed+=(targetSpeed-player.speed)*Math.min(1,dt*(targetSpeed>player.speed?7.5:10));","const kx=(moveKeys.right?1:0)-(moveKeys.left?1:0),ky=(moveKeys.up?1:0)-(moveKeys.down?1:0);let sx=analogMove.active?analogMove.x:kx,sy=analogMove.active?-analogMove.y:ky;let len=Math.hypot(sx,sy);if(len<.075){sx=0;sy=0;len=0;}const inputMag=Math.min(1,len);if(len>1){sx/=len;sy/=len;len=1;}let dx=0,dz=0;if(len>0){const fx=-Math.sin(yaw),fz=-Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw);dx=fx*sy+rx*sx;dz=fz*sy+rz*sx;const dl=Math.hypot(dx,dz)||1;dx/=dl;dz/=dl;const ty=Math.atan2(dx,dz),diff=Math.atan2(Math.sin(ty-player.yaw),Math.cos(ty-player.yaw));player.yaw+=diff*(1-Math.exp(-8.5*dt));}const speedScale=THREE.MathUtils.smoothstep(inputMag,.075,.88),targetSpeed=len>0?(moveKeys.run?6.35:3.75)*speedScale:0;player.speed=THREE.MathUtils.damp(player.speed,targetSpeed,targetSpeed>player.speed?7.5:11,dt);",'camera-relative movement');
  rep("document.querySelectorAll('[data-move]').forEach(btn=>{const key=btn.dataset.move;const set=v=>{moveKeys[key]=v;hint.classList.add('fade');};btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture?.(e.pointerId);set(true);});for(const ev of ['pointerup','pointercancel','pointerleave'])btn.addEventListener(ev,()=>set(false));});","const movePad=document.getElementById('movePad'),stickKnob=document.getElementById('stickKnob');function updateStick(e){const r=movePad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,lim=r.width*.34;let x=e.clientX-cx,y=e.clientY-cy,d=Math.hypot(x,y);if(d>lim){x=x/d*lim;y=y/d*lim;}analogMove.x=x/lim;analogMove.y=y/lim;analogMove.active=Math.hypot(analogMove.x,analogMove.y)>.035;stickKnob.style.transform=`translate3d(${x}px,${y}px,0)`;hint.classList.add('fade');}movePad.addEventListener('pointerdown',e=>{e.preventDefault();analogMove.pointerId=e.pointerId;movePad.setPointerCapture?.(e.pointerId);updateStick(e);});movePad.addEventListener('pointermove',e=>{if(e.pointerId!==analogMove.pointerId)return;e.preventDefault();updateStick(e);});function releaseStick(e){if(e&&analogMove.pointerId!==null&&e.pointerId!==analogMove.pointerId)return;analogMove.x=analogMove.y=0;analogMove.active=false;analogMove.pointerId=null;stickKnob.style.transform='translate3d(0,0,0)';}movePad.addEventListener('pointerup',releaseStick);movePad.addEventListener('pointercancel',releaseStick);movePad.addEventListener('lostpointercapture',releaseStick);",'analog joystick');

  rep("const viewOrder=['hero','gamer','front','profile','back','face','portal','room'];let viewIndex=0,yaw=views.hero.yaw,pitch=views.hero.pitch,distance=views.hero.distance,targetYaw=yaw,targetPitch=pitch,targetDistance=distance,autoOrbit=false,dragging=false,lastX=0,lastY=0,pinchDist=0;","const viewOrder=['hero','gamer','front','profile','back','face','portal','room'];let viewIndex=0,yaw=views.hero.yaw,pitch=.34,distance=13.4,targetYaw=yaw,targetPitch=pitch,targetDistance=distance,autoOrbit=false,dragging=false,lastX=0,lastY=0,pinchDist=0,followDistance=13.4,recenterClock=0;",'camera state');
  rep("function applyCamera(dt=.016){if(cameraMode==='orbit'||heroPortalState!=='outside'){yaw+=(targetYaw-yaw)*.085;pitch+=(targetPitch-pitch)*.085;distance+=(targetDistance-distance)*.09;target.lerp(targetLook,.085);}else{targetLook.set(player.x,player.y+1.35,player.z);target.lerp(targetLook,.14);const desired=followLock?player.yaw+Math.PI:targetYaw;const dy=Math.atan2(Math.sin(desired-yaw),Math.cos(desired-yaw));yaw+=dy*Math.min(1,dt*(followLock?7.2:4.2));const dp=cameraMode==='tight'?.16:.24,dd=cameraMode==='tight'?3.65:6.10;pitch+=(dp-pitch)*Math.min(1,dt*6);distance+=(dd-distance)*Math.min(1,dt*5.5);}const cp=Math.cos(pitch);camera.position.set(target.x+Math.sin(yaw)*cp*distance,target.y+Math.sin(pitch)*distance+(cameraMode==='tight'?.18:.48),target.z+Math.cos(yaw)*cp*distance);camera.lookAt(target);}","function applyCamera(dt=.016){if(cameraMode==='orbit'||heroPortalState!=='outside'){yaw+=(targetYaw-yaw)*.085;pitch+=(targetPitch-pitch)*.085;distance+=(targetDistance-distance)*.09;target.lerp(targetLook,.085);}else{targetLook.set(player.x,player.y+1.45,player.z);target.lerp(targetLook,1-Math.exp(-8*dt));if(dragging||analogMove.active)recenterClock=0;else recenterClock+=dt;if(!dragging&&!analogMove.active&&recenterClock>.85&&followLock){const behind=player.yaw+Math.PI,dy=Math.atan2(Math.sin(behind-yaw),Math.cos(behind-yaw));yaw+=dy*(1-Math.exp(-1.75*dt));pitch=THREE.MathUtils.damp(pitch,cameraMode==='tight'?.24:.34,2.5,dt);}distance=THREE.MathUtils.damp(distance,cameraMode==='tight'?7.6:followDistance,3.8,dt);}const cp=Math.cos(pitch);camera.position.set(target.x+Math.sin(yaw)*cp*distance,target.y+Math.sin(pitch)*distance+(cameraMode==='tight'?.55:1.05),target.z+Math.cos(yaw)*cp*distance);camera.lookAt(target);}",'camera follow');
  rep("renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;autoOrbit=false;renderer.domElement.setPointerCapture?.(e.pointerId);hint.classList.add('fade');});","renderer.domElement.style.touchAction='none';renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;autoOrbit=false;renderer.domElement.setPointerCapture?.(e.pointerId);recenterClock=0;hint.classList.add('fade');});",'camera pointer start');
  rep("renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;if(cameraMode==='orbit'||!followLock){targetYaw-=dx*.006;targetPitch=clamp(targetPitch+dy*.0047,-.24,.48);}});","renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;if(cameraMode==='orbit'){targetYaw-=dx*.0052;targetPitch=clamp(targetPitch+dy*.0039,-.24,.58);}else{yaw-=dx*.0052;pitch=clamp(pitch+dy*.0036,.08,.62);targetYaw=yaw;targetPitch=pitch;recenterClock=0;}});",'direct camera drag');
  rep("renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();targetDistance=clamp(targetDistance+Math.sign(e.deltaY)*.65,1.7,20.0);hint.classList.add('fade');},{passive:false});","renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();if(cameraMode!=='orbit')followDistance=clamp(followDistance+Math.sign(e.deltaY)*1.1,7.5,30);else targetDistance=clamp(targetDistance+Math.sign(e.deltaY)*.75,1.7,30);hint.classList.add('fade');},{passive:false});",'camera wheel');
  rep("renderer.domElement.addEventListener('touchmove',e=>{if(e.touches.length===2){const dx=e.touches[0].clientX-e.touches[1].clientX,dy=e.touches[0].clientY-e.touches[1].clientY,d=Math.hypot(dx,dy);if(pinchDist)targetDistance=clamp(targetDistance+(pinchDist-d)*.016,1.7,20.0);pinchDist=d;}},{passive:false});renderer.domElement.addEventListener('touchend',()=>pinchDist=0,{passive:true});","renderer.domElement.addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();dragging=false;const dx=e.touches[0].clientX-e.touches[1].clientX,dy=e.touches[0].clientY-e.touches[1].clientY,d=Math.hypot(dx,dy);if(pinchDist){if(cameraMode!=='orbit')followDistance=clamp(followDistance+(pinchDist-d)*.040,7.5,30);else targetDistance=clamp(targetDistance+(pinchDist-d)*.025,1.7,30);}pinchDist=d;}},{passive:false});renderer.domElement.addEventListener('touchend',()=>pinchDist=0,{passive:true});",'camera pinch');

  rep('controllerGroup.position.set(0,1.025,.675);controllerGroup.rotation.x=-.12;controllerGroup.visible=false;body.add(controllerGroup);','controllerGroup.position.set(0,1.00,.60);controllerGroup.rotation.x=-.10;controllerGroup.visible=false;body.add(controllerGroup);','controller placement');
  rep("armL.rotation.x=THREE.MathUtils.lerp(armLX,-1.04,actionBlend);\n    armR.rotation.x=THREE.MathUtils.lerp(armRX,-1.04,actionBlend);\n    armL.rotation.z=THREE.MathUtils.lerp(armLZ,.62,actionBlend);\n    armR.rotation.z=THREE.MathUtils.lerp(armRZ,-.62,actionBlend);\n    armL.position.x=THREE.MathUtils.lerp(-.505,-.425,actionBlend);\n    armR.position.x=THREE.MathUtils.lerp(.505,.425,actionBlend);\n    armL.position.z=THREE.MathUtils.lerp(.02,.09,actionBlend);\n    armR.position.z=THREE.MathUtils.lerp(.02,.09,actionBlend);","armL.rotation.x=THREE.MathUtils.lerp(armLX,-.72,actionBlend);\n    armR.rotation.x=THREE.MathUtils.lerp(armRX,-.08,actionBlend);\n    armL.rotation.z=THREE.MathUtils.lerp(armLZ,1.28,actionBlend);\n    armR.rotation.z=THREE.MathUtils.lerp(armRZ,-1.24,actionBlend);\n    armL.position.x=THREE.MathUtils.lerp(-.505,-.34,actionBlend);\n    armR.position.x=THREE.MathUtils.lerp(.505,.39,actionBlend);\n    armL.position.y=THREE.MathUtils.lerp(1.145,1.20,actionBlend);\n    armR.position.y=THREE.MathUtils.lerp(1.145,1.12,actionBlend);\n    armL.position.z=THREE.MathUtils.lerp(.02,.15,actionBlend);\n    armR.position.z=THREE.MathUtils.lerp(.02,.11,actionBlend);",'two-hand controller pose');
  rep("function toggleAction(force){if(heroPortalState!=='outside'||phase!=='idle')return;actionActive=force===undefined?!actionActive:!!force;bro.setAction(actionActive);actionTouchBtn.classList.toggle('active',actionActive);actionTouchBtn.textContent=actionActive?'LASER: ON':'ACTION';hint.classList.add('fade');}\n    actionTouchBtn.addEventListener('click',()=>toggleAction());","function setActionPressed(v){if(heroPortalState!=='outside'||phase!=='idle')v=false;actionActive=!!v;bro.setAction(actionActive);actionTouchBtn.classList.toggle('active',actionActive);actionTouchBtn.textContent='ZAP';hint.classList.add('fade');}actionTouchBtn.addEventListener('pointerdown',e=>{e.preventDefault();actionTouchBtn.setPointerCapture?.(e.pointerId);setActionPressed(true);});for(const ev of ['pointerup','pointercancel','lostpointercapture','pointerleave'])actionTouchBtn.addEventListener(ev,()=>setActionPressed(false));",'hold controller zap');
  rep("bro.controllerEmitter.getWorldPosition(laserOrigin);bro.controllerEmitter.getWorldQuaternion(controllerWorldQ);laserDir.set(0,0,1).applyQuaternion(controllerWorldQ).normalize();laserOrigin.addScaledVector(laserDir,.12);\n      laserRay.set(laserOrigin,laserDir);const hits=laserRay.intersectObject(env,true).filter(h=>!h.object.isSprite&&h.distance>.18);if(hits.length)laserEnd.copy(hits[0].point);else laserEnd.copy(laserOrigin).addScaledVector(laserDir,24);","bro.controllerEmitter.getWorldPosition(laserOrigin);bro.controllerEmitter.getWorldQuaternion(controllerWorldQ);laserDir.set(0,0,1).applyQuaternion(controllerWorldQ).normalize();laserOrigin.addScaledVector(laserDir,.12);const hits=[];laserEnd.copy(laserOrigin).addScaledVector(laserDir,24);",'safe controller beam');
  rep("if(k==='f'&&!e.repeat)toggleAction();","if(k==='f'&&!e.repeat)setActionPressed(true);",'keyboard zap down');
  rep("if(k==='shift')moveKeys.run=false;if(k===' ')moveKeys.jump=false;});","if(k==='shift')moveKeys.run=false;if(k===' ')moveKeys.jump=false;if(k==='f')setActionPressed(false);});",'keyboard zap up');
  source=source.replaceAll("actionTouchBtn.textContent='ACTION';","actionTouchBtn.textContent='ZAP';");

  const marker='    // Abyss cue only outside the room; quality stays in geometry/materials above it.';
  if(!source.includes(marker)) throw new Error('Hybrid clean landscape marker missing');
  const expansion=`
    function terrainTex90(grass){const c=document.createElement('canvas');c.width=c.height=384;const g=c.getContext('2d');g.fillStyle=grass?'#3f772c':'#67503a';g.fillRect(0,0,384,384);for(let i=0;i<2200;i++){const x=Math.random()*384,y=Math.random()*384,a=.025+Math.random()*.075;g.fillStyle=grass?(Math.random()<.55?'rgba(143,180,76,'+a+')':'rgba(23,70,29,'+a+')'):(Math.random()<.5?'rgba(185,145,88,'+a+')':'rgba(50,38,28,'+a+')');g.fillRect(x,y,1+Math.random()*3,1+Math.random()*3);}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(5,5);t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return t;}
    const grass90=new THREE.MeshPhysicalMaterial({map:terrainTex90(true),roughness:.94,metalness:0,envMapIntensity:.5}),dirt90=new THREE.MeshStandardMaterial({map:terrainTex90(false),roughness:.96}),bark90=new THREE.MeshStandardMaterial({color:0x5a3723,roughness:.92}),leaf90=new THREE.MeshPhysicalMaterial({color:0x3f903a,roughness:.78,sheen:.2,sheenColor:new THREE.Color(0x8edb66)}),leafDark90=new THREE.MeshStandardMaterial({color:0x276d2f,roughness:.9}),mount90=new THREE.MeshStandardMaterial({color:0x4f5963,roughness:.96,flatShading:true}),snow90=new THREE.MeshStandardMaterial({color:0xa8bac4,roughness:.92,flatShading:true});
    function plateau90(x,z,r,y=0,grass=true){extMesh(new THREE.CylinderGeometry(r*.96,r,1.7,48),dirt90,new THREE.Vector3(x,y-.78,z),0,true);extMesh(new THREE.CylinderGeometry(r*.96,r*.97,.20,48),grass?grass90:floorMat,new THREE.Vector3(x,y+.03,z),0,false);addDiscSurface(x,z,r*.92,y+.14);}
    function bridge90(x1,z1,x2,z2,w,y){const dx=x2-x1,dz=z2-z1,d=Math.hypot(dx,dz),rot=Math.atan2(dx,dz);extMesh(new THREE.BoxGeometry(w+.28,.42,d),stoneDark,new THREE.Vector3((x1+x2)/2,y-.18,(z1+z2)/2),rot,true);extMesh(new THREE.BoxGeometry(w,.14,d-.05),floorMat,new THREE.Vector3((x1+x2)/2,y+.07,(z1+z2)/2),rot,false);addRectSurface((x1+x2)/2,(z1+z2)/2,w-.14,d-.10,y+.15,rot);}
    function ramp90(x,z,w,d,y0,y1){const m=extMesh(new THREE.BoxGeometry(w,.20,d),floorMat,new THREE.Vector3(x,(y0+y1)/2-.04,z),0,true);m.rotation.x=Math.atan2(y1-y0,d);addRampSurface(x,z,w-.12,d-.08,y0,y1,0);}
    ramp90(0,17.7,5.8,22.0,.02,.39);
    plateau90(0,34,16.5,.25,true);
    plateau90(-18,33,8.4,.72,true);plateau90(18,33,8.4,.72,true);
    bridge90(-12.0,33,-14.0,33,4.4,.64);bridge90(12.0,33,14.0,33,4.4,.64);
    bridge90(0,47,0,49.0,5.0,.60);plateau90(0,57,11.8,1.15,true);
    ramp90(0,68,5.0,12,1.29,2.10);plateau90(0,78,10.2,2.0,true);
    bridge90(-8.0,58,-15.0,63,3.5,1.35);bridge90(8.0,58,15.0,63,3.5,1.35);plateau90(-21,67,7.5,1.75,true);plateau90(21,67,7.5,1.75,true);
    const treeN=44,trunk90=new THREE.InstancedMesh(new THREE.CylinderGeometry(.18,.28,2.3,8),bark90,treeN),crown90=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,2),leaf90,treeN),crownB90=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),leafDark90,treeN);trunk90.castShadow=crown90.castShadow=true;ext.add(trunk90,crown90,crownB90);const zones90=[[0,34,15.0,.25],[-18,33,7.5,.72],[18,33,7.5,.72],[0,57,10.6,1.15],[-21,67,6.6,1.75],[21,67,6.6,1.75],[0,78,9.0,2.0]];let ti90=0;outer90:for(let zi=0;zi<zones90.length;zi++){const[cx,cz,rr,yy]=zones90[zi];for(let k=0;k<8;k++){if(ti90>=treeN)break outer90;const a=k/8*Math.PI*2+zi*.73,r=rr*(.68+.22*((k*7%10)/10)),x=cx+Math.cos(a)*r,z=cz+Math.sin(a)*r,sc=.82+((k+zi)%5)*.1;dummy.rotation.set(0,a*.37,0);dummy.position.set(x,yy+1.15*sc,z);dummy.scale.set(sc,sc,sc);dummy.updateMatrix();trunk90.setMatrixAt(ti90,dummy.matrix);dummy.position.set(x,yy+2.55*sc,z);dummy.scale.set(1.15*sc,1.42*sc,1.12*sc);dummy.updateMatrix();crown90.setMatrixAt(ti90,dummy.matrix);dummy.position.set(x+.35*sc,yy+3.25*sc,z-.1*sc);dummy.scale.set(.72*sc,.88*sc,.72*sc);dummy.updateMatrix();crownB90.setMatrixAt(ti90,dummy.matrix);ti90++;}}for(;ti90<treeN;ti90++){dummy.position.set(0,-30,0);dummy.scale.set(.001,.001,.001);dummy.updateMatrix();trunk90.setMatrixAt(ti90,dummy.matrix);crown90.setMatrixAt(ti90,dummy.matrix);crownB90.setMatrixAt(ti90,dummy.matrix);}trunk90.instanceMatrix.needsUpdate=crown90.instanceMatrix.needsUpdate=crownB90.instanceMatrix.needsUpdate=true;
    const rockN=28,rock90=new THREE.InstancedMesh(new THREE.DodecahedronGeometry(.62,1),stoneDark,rockN);rock90.castShadow=true;rock90.receiveShadow=true;ext.add(rock90);for(let i=0;i<rockN;i++){const z=24+(i*13%58),side=i%2?-1:1,x=side*(13+(i*7%16)),y=z>72?2:z>48?1.15:.4;dummy.position.set(x,y+.28,z);dummy.rotation.set(i*.43,i*.77,i*.21);const sc=.55+(i%6)*.16;dummy.scale.set(sc,sc*(.55+(i%3)*.15),sc*.8);dummy.updateMatrix();rock90.setMatrixAt(i,dummy.matrix);}rock90.instanceMatrix.needsUpdate=true;
    const mN=20,m90=new THREE.InstancedMesh(new THREE.ConeGeometry(1,1,7),mount90,mN),snowM90=new THREE.InstancedMesh(new THREE.ConeGeometry(1,1,7),snow90,mN);ext.add(m90,snowM90);for(let i=0;i<mN;i++){const a=i/mN*Math.PI*2,r=62+(i%5)*5,h=18+(i%7)*2.7,rad=7+(i%4)*1.8,x=Math.cos(a)*r,z=42+Math.sin(a)*r;dummy.position.set(x,h*.5-4,z);dummy.rotation.set(0,a+.2,0);dummy.scale.set(rad,h,rad);dummy.updateMatrix();m90.setMatrixAt(i,dummy.matrix);dummy.position.set(x,h-5,z);dummy.scale.set(rad*.42,h*.22,rad*.42);dummy.updateMatrix();snowM90.setMatrixAt(i,dummy.matrix);}m90.instanceMatrix.needsUpdate=snowM90.instanceMatrix.needsUpdate=true;
  `;
  source=source.replace(marker,expansion+'\n'+marker);applied.push('connected landscape');

  rep("let phase='idle',phaseT=0,heroPortalState='outside',heroLoadT=0;","let phase='idle',phaseT=0,heroPortalState='outside',heroLoadT=0;let portalEntryArmed=true;",'portal arm state');
  rep('      if(player.y<-6.25)resetPlayerToPavement();','      if(player.y<-6.25)resetPlayerToPavement();\n      const portalEntryDistance=Math.hypot(player.x,player.z);\n      if(!portalEntryArmed&&heroPortalState===\'outside\'&&phase===\'idle\'&&portalEntryDistance>2.55)portalEntryArmed=true;\n      if(portalEntryArmed&&heroPortalState===\'outside\'&&phase===\'idle\'&&portalEntryDistance<1.75&&player.y<1.35){portalEntryArmed=false;player.speed=0;loadHero();return;}','automatic portal entry');
  rep("if(p>=1){heroPortalState='loaded';bro.setHome(0,0,0);gamerRoot.position.y=HERO_IN.y;setPhase('idle');requestShadowUpdate(2);}","if(p>=1){heroPortalState='loaded';bro.setHome(0,0,0);gamerRoot.position.y=HERO_IN.y;setPhase('idle');requestShadowUpdate(2);setTimeout(()=>{if(heroPortalState==='loaded'&&phase==='idle')activatePortal();},150);}",'portal auto activate');
  const resetNeedle="    function resetTest(){\n      actionActive=false;bro.setAction(false);actionTouchBtn.classList.remove('active');actionTouchBtn.textContent='ZAP';phase='idle';phaseT=0;resetVisualState();gamerMotion='idle';bro.setMotion('idle');restoreHeroOutside();activateBtn.textContent='ACTIVATE PORTAL';activateBtn.disabled=true;dropBtn.disabled=!gamerVisible;dropBtn.textContent='LOAD HERO';phaseLine.textContent='1 · IDLE · PLAYABLE';requestShadowUpdate(2);syncPortalCharacterUI();\n    }";
  const resetInsert=resetNeedle+"\n    function finishPortalTravel(){resetTest();const safeX=0,safeZ=57,safeSurface=surfaceHeight(safeX,safeZ);player.x=safeX;player.z=safeZ;player.y=safeSurface===null?1.29:safeSurface;player.yaw=Math.PI;player.vy=0;player.speed=0;player.grounded=true;bro.setHome(player.x,player.z,player.yaw);gamerRoot.position.y=player.y;portalEntryArmed=false;cameraMode='follow';followLock=true;recenterClock=0;yaw=player.yaw+Math.PI;targetYaw=yaw;pitch=.34;targetPitch=.34;distance=followDistance;targetDistance=followDistance;targetLook.set(player.x,player.y+1.45,player.z);target.copy(targetLook);orbitBtn.textContent='CAM: FOLLOW';orbitBtn.classList.add('active');followLockBtn.textContent='FOLLOW LOCK: ON';followLockBtn.classList.add('active');actionTouchBtn.textContent='ZAP';requestShadowUpdate(2);}";
  rep(resetNeedle,resetInsert,'portal finish helper');
  rep("if(p>=1){heroPortalState='gone';heroGhost.visible=false;setPhase('dissipate');syncPortalCharacterUI();}","if(p>=1){heroPortalState='gone';gamerRoot.visible=false;heroGhost.visible=false;heroParticlePoints.visible=false;finishPortalTravel();}",'immediate portal finish');
  rep("if(typeof selectView==='function')setTimeout(()=>selectView('portal'),0);","if(typeof selectView==='function')setTimeout(()=>selectView('portal'),70);",'portal camera');

  rep("setTimeout(()=>hint.classList.add('fade'),9000);resetTest();cameraMode='follow';followLock=true;orbitBtn.textContent='CAM: FOLLOW';orbitBtn.classList.add('active');followLockBtn.textContent='FOLLOW LOCK: ON';followLockBtn.classList.add('active');targetLook.set(player.x,player.y+1.35,player.z);requestShadowUpdate(2);boot.classList.add('hidden');ui.classList.add('show');","setTimeout(()=>hint.classList.add('fade'),9000);resetTest();cameraMode='follow';followLock=true;followDistance=13.4;pitch=targetPitch=.34;distance=13.4;orbitBtn.textContent='CAM: FOLLOW';orbitBtn.classList.add('active');followLockBtn.textContent='FOLLOW LOCK: ON';followLockBtn.classList.add('active');targetLook.set(player.x,player.y+1.45,player.z);requestShadowUpdate(2);boot.classList.add('hidden');ui.classList.add('show');",'camera startup');

  console.info('[Hybrid v0.9 clean Phase 2B]',applied);
  return source;
}

try{
  const parts=await Promise.all(chunkPaths.map(async url=>{const r=await fetch(url,{cache:'no-cache'});if(!r.ok)throw new Error(`Failed ${url.pathname}: ${r.status}`);return r.text();}));
  const source=patchRuntime(parts.join(''));
  const url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));
  try{await import(url);}finally{URL.revokeObjectURL(url);}
}catch(error){
  console.error(error);document.getElementById('boot')?.remove();const fatal=document.getElementById('fatal'),text=document.getElementById('fatalText');if(fatal)fatal.style.display='grid';if(text)text.textContent='Hybrid clean rebuild could not load. '+(error?.message||String(error));
}
