import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createGamerBro} from './playground-v2/gamer-bro.js?v=pass9';

const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const CHARACTERS=[
 {id:'gb1',name:'GB1',power:'Prism Star Volley',accent:'#ff58b7',kind:'gamer',colorway:'pink'},
 {id:'gb2',name:'GB2',power:'Prism Star Volley',accent:'#58e2e0',kind:'gamer',colorway:'teal'}
];
if(localStorage.getItem('gamerBrosCitrusUnlocked')==='1')CHARACTERS.push({id:'citrus',name:'Citrus',power:'Rainbow Star Comet',accent:'#ff9a3d',kind:'glb',file:'./pass1-v1/assets/recovered/characters/sprite_hero.glb',unlocked:true});
const canvas=document.getElementById('previewCanvas'),preview=document.getElementById('preview'),rail=document.getElementById('characterRail'),nameEl=document.getElementById('characterName'),powerEl=document.getElementById('characterPower'),loading=document.getElementById('loading'),playBtn=document.getElementById('playBtn'),fail=document.getElementById('fail'),failText=document.getElementById('failText');
const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.35:1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.16;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.05,100);camera.position.set(0,1.75,6.3);camera.layers.enable(1);scene.add(new THREE.HemisphereLight(0xeaf7ff,0x2d163c,2.35));const key=new THREE.DirectionalLight(0xffffff,3.35);key.position.set(4,7,5);scene.add(key);const rim=new THREE.DirectionalLight(0xff83d3,2.5);rim.position.set(-5,3,-4);scene.add(rim);
const floor=new THREE.Mesh(new THREE.CircleGeometry(2.15,64),new THREE.MeshStandardMaterial({color:0x181022,roughness:.48,metalness:.2,transparent:true,opacity:.78}));floor.rotation.x=-Math.PI/2;floor.position.y=-.02;scene.add(floor);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.58,.022,10,96),new THREE.MeshBasicMaterial({color:0x78e6ff,transparent:true,opacity:.58}));ring.rotation.x=Math.PI/2;ring.position.y=.01;scene.add(ring);
const loader=new GLTFLoader();let current=null,currentAdapter=null,currentMixer=null,currentId=null,loadToken=0,dragging=false,lastX=0,userYaw=0,animT=0;
function fit(root,target=3.05){root.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(root),s=b.getSize(new THREE.Vector3()),scale=target/Math.max(s.y,.001);root.scale.multiplyScalar(scale);root.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(root);const ctr=b.getCenter(new THREE.Vector3());root.position.x-=ctr.x;root.position.z-=ctr.z;root.position.y-=b.min.y;root.updateMatrixWorld(true);root.userData.previewBaseY=root.position.y;return root;}
async function make(c){let root,adapter=null,mixer=null;if(c.kind==='gamer'){adapter=createGamerBro(THREE,renderer,{colorway:c.colorway,detail:mobile?'low':'high',height:2.62});root=adapter.root;adapter.setMotion('idle');fit(root,3.05);}else{const g=await loader.loadAsync(c.file);root=g.scene;fit(root,3.05);if(g.animations?.length){mixer=new THREE.AnimationMixer(root);const clip=g.animations.find(a=>/idle/i.test(a.name))||g.animations[0];mixer.clipAction(clip).play();}}root.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=false;}});return{root,adapter,mixer};}
function buildRail(){for(const c of CHARACTERS){const b=document.createElement('button');b.className='charBtn';b.dataset.id=c.id;b.style.setProperty('--accent',c.accent);b.innerHTML=`<b>${c.name}</b><small>${c.unlocked?'LEVEL 1 UNLOCK · ':''}${c.power}</small>`;b.onclick=()=>select(c.id);rail.appendChild(b);}}
async function select(id){const c=CHARACTERS.find(x=>x.id===id)||CHARACTERS[1];currentId=c.id;localStorage.setItem('gamerBroCharacter',c.id);nameEl.textContent=c.name;powerEl.textContent=c.unlocked?'LEVEL 1 UNLOCK · '+c.power:c.power;ring.material.color.set(c.accent);rail.querySelectorAll('.charBtn').forEach(b=>b.classList.toggle('active',b.dataset.id===c.id));loading.textContent='Loading current character…';loading.style.opacity='1';const token=++loadToken;try{const made=await make(c);if(token!==loadToken)return;if(current)scene.remove(current);current=made.root;currentAdapter=made.adapter;currentMixer=made.mixer;scene.add(current);current.rotation.y=.18;userYaw=0;loading.style.opacity='0';let visibleMeshes=0;current.traverse(o=>{if(o.isMesh&&camera.layers.test(o.layers))visibleMeshes++;});window.__titleVisibleMeshCount=visibleMeshes;window.__titleCharacterReady=c.id;}catch(err){console.error(err);loading.textContent='Preview unavailable — choose another character';}}
function resize(){const r=preview.getBoundingClientRect(),w=Math.max(1,r.width|0),h=Math.max(1,r.height|0);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}addEventListener('resize',resize,{passive:true});new ResizeObserver(resize).observe(preview);resize();
canvas.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;userYaw+=(e.clientX-lastX)*.008;lastX=e.clientX});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);
playBtn.onclick=()=>{const id=CHARACTERS.some(c=>c.id===currentId)?currentId:'gb2';location.href=`./pass9-v1/?hero=${encodeURIComponent(id)}&v=1`};
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;animT+=dt;if(current){try{if(currentAdapter)currentAdapter.update(animT,dt,0);if(currentMixer)currentMixer.update(dt);}catch{}current.rotation.y+=dragging?0:dt*.24;current.rotation.y+=userYaw;userYaw=0;current.position.y=(current.userData.previewBaseY||0)+Math.sin(now*.0017)*.026;}ring.rotation.z+=dt*.18;renderer.render(scene,camera)}
try{buildRail();let saved=localStorage.getItem('gamerBroCharacter');if(!CHARACTERS.some(c=>c.id===saved))saved='gb2';select(saved||'gb2');requestAnimationFrame(frame);window.__titlePass9=true;window.__playableRoster=CHARACTERS.map(c=>c.id);}catch(err){console.error(err);failText.textContent=String(err?.message||err);fail.classList.add('show')}