import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createGamerBro} from './playground-v2/gamer-bro.js?v=pass2';
import {createV04Sprite} from './room01-v1/v04-sprites.js?v=pass2';

const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const CHARACTERS=[
 {id:'gb1',name:'GB1',power:'Prism Star Burst',accent:'#ff58b7',kind:'gamer',colorway:'pink'},
 {id:'gb2',name:'GB2',power:'Prism Star Burst',accent:'#58e2e0',kind:'gamer',colorway:'teal'},
 {id:'citrus',name:'Citrus / Dash v04',power:'Multicolour Star Burst',accent:'#ff9a3d',kind:'v04',v04:'dash'},
 {id:'ghost',name:'Ghost v04 · Pink',power:'Spectral Phase Wave',accent:'#f19bff',kind:'v04',v04:'ghost',pink:true},
 {id:'ghost_glb',name:'Ghost · Animated',power:'Spectral Phase Wave',accent:'#a788ff',kind:'glb',file:'./pass1-v1/assets/recovered/characters/ghost.glb'},
 {id:'stump',name:'Stump',power:'Root Shockwave',accent:'#92d56d',kind:'glb',file:'./pass1-v1/assets/recovered/characters/stump.glb'},
 {id:'cthulhu',name:'Cthulhu',power:'Void Orb',accent:'#a66cff',kind:'glb',file:'./pass1-v1/assets/recovered/characters/cthulhu.glb'},
 {id:'yeti',name:'Yeti',power:'Frost Orb',accent:'#bcefff',kind:'glb',file:'./pass1-v1/assets/recovered/characters/yeti.glb'}
];
const canvas=document.getElementById('previewCanvas'),preview=document.getElementById('preview'),rail=document.getElementById('characterRail'),nameEl=document.getElementById('characterName'),powerEl=document.getElementById('characterPower'),loading=document.getElementById('loading'),playBtn=document.getElementById('playBtn'),fail=document.getElementById('fail'),failText=document.getElementById('failText');
const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.35:1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.05,100);camera.position.set(0,1.75,6.3);scene.add(new THREE.HemisphereLight(0xeaf7ff,0x2d163c,2.35));const key=new THREE.DirectionalLight(0xffffff,3.35);key.position.set(4,7,5);scene.add(key);const rim=new THREE.DirectionalLight(0xc76dff,2.35);rim.position.set(-5,3,-4);scene.add(rim);
const floor=new THREE.Mesh(new THREE.CircleGeometry(2.15,64),new THREE.MeshStandardMaterial({color:0x181022,roughness:.48,metalness:.2,transparent:true,opacity:.78}));floor.rotation.x=-Math.PI/2;floor.position.y=-.02;scene.add(floor);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.58,.022,10,96),new THREE.MeshBasicMaterial({color:0x78e6ff,transparent:true,opacity:.58}));ring.rotation.x=Math.PI/2;ring.position.y=.01;scene.add(ring);
const loader=new GLTFLoader();let current=null,currentAdapter=null,currentId=null,loadToken=0,dragging=false,lastX=0,userYaw=0;
function setPinkGhost(root){root.traverse(o=>{if(!o.isMesh||!o.material)return;const mats=Array.isArray(o.material)?o.material:[o.material];for(const m0 of mats){const m=m0;m.transparent=true;if(m.color&&m.color.getHex()===0x8b61d7){m.color.set(0xe6a1f2);if(m.emissive)m.emissive.set(0x57204f);m.opacity=.9;}}});}
function fit(root,target=3.05){root.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(root),s=b.getSize(new THREE.Vector3()),scale=target/Math.max(s.y,.001);root.scale.multiplyScalar(scale);root.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(root);const ctr=b.getCenter(new THREE.Vector3());root.position.x-=ctr.x;root.position.z-=ctr.z;root.position.y-=b.min.y;root.updateMatrixWorld(true);root.userData.previewBaseY=root.position.y;return root;}
async function make(c){let root,adapter=null;if(c.kind==='gamer'){adapter=createGamerBro(THREE,renderer,{colorway:c.colorway,detail:mobile?'low':'high',height:2.62});root=adapter.root;fit(root,3.05);}else if(c.kind==='v04'){adapter=createV04Sprite(THREE,c.v04,{height:2.45,mobile});root=adapter.root;fit(root,3.05);if(c.pink)setPinkGhost(root);}else{const g=await loader.loadAsync(c.file);root=g.scene;fit(root,3.05);if(g.animations?.length){const mixer=new THREE.AnimationMixer(root),clip=g.animations.find(a=>/idle/i.test(a.name))||g.animations[0];mixer.clipAction(clip).play();adapter={root,update:dt=>mixer.update(dt)};}}root.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=false;}});return{root,adapter};}
function buildRail(){for(const c of CHARACTERS){const b=document.createElement('button');b.className='charBtn';b.dataset.id=c.id;b.style.setProperty('--accent',c.accent);b.innerHTML=`<b>${c.name}</b><small>${c.power}</small>`;b.onclick=()=>select(c.id);rail.appendChild(b);}}
async function select(id){const c=CHARACTERS.find(x=>x.id===id)||CHARACTERS[1];currentId=c.id;localStorage.setItem('gamerBroCharacter',c.id);nameEl.textContent=c.name;powerEl.textContent=c.power;ring.material.color.set(c.accent);rail.querySelectorAll('.charBtn').forEach(b=>b.classList.toggle('active',b.dataset.id===c.id));loading.textContent='Loading current character…';loading.style.opacity='1';const token=++loadToken;try{const made=await make(c);if(token!==loadToken)return;if(current)scene.remove(current);current=made.root;currentAdapter=made.adapter;scene.add(current);current.rotation.y=.18;userYaw=0;loading.style.opacity='0';window.__titleCharacterReady=c.id;}catch(err){console.error(err);loading.textContent='Preview unavailable — choose another character';}}
function resize(){const r=preview.getBoundingClientRect(),w=Math.max(1,r.width|0),h=Math.max(1,r.height|0);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}addEventListener('resize',resize,{passive:true});new ResizeObserver(resize).observe(preview);resize();
canvas.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;userYaw+=(e.clientX-lastX)*.008;lastX=e.clientX});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);
playBtn.onclick=()=>{const id=currentId||'gb2';location.href=`./pass2-v1/?hero=${encodeURIComponent(id)}`};
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;if(current){try{currentAdapter?.update?.(dt,0);}catch{}current.rotation.y+=dragging?0:dt*.24;current.rotation.y+=userYaw;userYaw=0;current.position.y=(current.userData.previewBaseY||0)+Math.sin(now*.0017)*.026;}ring.rotation.z+=dt*.18;renderer.render(scene,camera)}
try{buildRail();const saved=localStorage.getItem('gamerBroCharacter');select(CHARACTERS.some(c=>c.id===saved)?saved:'gb2');requestAnimationFrame(frame);window.__titlePass2=true;}catch(err){console.error(err);failText.textContent=String(err?.message||err);fail.classList.add('show')}
