import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createGamerBro} from '../playground-v2/gamer-bro.js?v=pass8';
import {createCrystalLibraryTubeV2} from '../src/crystal-library-tube-v2.js?v=1';

const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const qp=new URLSearchParams(location.search),requested=qp.get('hero'),saved=localStorage.getItem('gamerBroCharacter');
const id=requested==='gb1'||requested==='gb2'?requested:(saved==='gb1'||saved==='gb2'?saved:'gb2'),colorway=id==='gb1'?'pink':'teal';localStorage.setItem('gamerBroCharacter',id);
const $=s=>document.querySelector(s),canvas=$('#game'),heroName=$('#heroName'),menu=$('#menu'),objective=$('#objective'),pad=$('#pad'),stick=$('#stick'),jumpBtn=$('#jump'),runBtn=$('#run'),retry=$('#retry'),toastEl=$('#toast'),boot=$('#boot'),status=$('#status'),bar=$('#bar'),fatal=$('#fatal'),errorEl=$('#error');heroName.textContent=id.toUpperCase();menu.onclick=()=>location.href='../';
function progress(t,n){status.textContent=t;bar.style.width=n+'%'}function toast(t,ms=1500){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),ms)}

// Crystal Library v2 renderer/camera baseline.
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=1.40;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1:1.35));
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8fcbe4);scene.fog=new THREE.Fog(0x9fd1e4,34,72);const camera=new THREE.PerspectiveCamera(36,1,.15,125);camera.layers.enable(1);
scene.add(new THREE.HemisphereLight(0xe8fbff,0x355342,1.85));const sun=new THREE.DirectionalLight(0xffefd4,2.25);sun.position.set(-14,24,13);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:1536,mobile?1024:1536);sun.shadow.camera.left=-28;sun.shadow.camera.right=28;sun.shadow.camera.top=28;sun.shadow.camera.bottom=-28;sun.shadow.camera.near=1;sun.shadow.camera.far=70;sun.shadow.bias=-.00025;sun.shadow.normalBias=.03;scene.add(sun);const rim=new THREE.DirectionalLight(0x8d71ff,.38);rim.position.set(15,10,-12);scene.add(rim);
const loader=new GLTFLoader(),world=new THREE.Group();scene.add(world);const ray=new THREE.Raycaster(),down=new THREE.Vector3(0,-1,0),walkMeshes=[];let worldBounds=new THREE.Box3(),arenaRoot=null;

const heightCache=new Map();function hkey(x,z){return `${Math.round(x*8)},${Math.round(z*8)}`}function groundAt(x,z,cache=true){const key=hkey(x,z);if(cache&&heightCache.has(key))return heightCache.get(key);const top=worldBounds.max.y+12;ray.set(new THREE.Vector3(x,top,z),down);ray.far=(top-worldBounds.min.y)+24;const hits=ray.intersectObjects(walkMeshes,false);const y=hits.length?hits[0].point.y:null;if(cache)heightCache.set(key,y);return y}
function horizontalFlat(x,z,r=1.15){const vals=[];for(const [dx,dz] of [[0,0],[r,0],[-r,0],[0,r],[0,-r],[r*.7,r*.7],[-r*.7,r*.7],[r*.7,-r*.7],[-r*.7,-r*.7]]){const y=groundAt(x+dx,z+dz);if(y===null)return null;vals.push(y)}const min=Math.min(...vals),max=Math.max(...vals);return{y:vals[0],range:max-min}}
function chooseSites(){const b=worldBounds,size=b.getSize(new THREE.Vector3()),spots=[];for(let ix=1;ix<12;ix++)for(let iz=1;iz<12;iz++){const x=THREE.MathUtils.lerp(b.min.x+2,b.max.x-2,ix/12),z=THREE.MathUtils.lerp(b.min.z+2,b.max.z-2,iz/12),f=horizontalFlat(x,z);if(f&&f.range<.34)spots.push({x,z,y:f.y,range:f.range,center:Math.hypot(x,z)})}if(!spots.length){for(let ix=1;ix<9;ix++)for(let iz=1;iz<9;iz++){const x=THREE.MathUtils.lerp(b.min.x+1,b.max.x-1,ix/9),z=THREE.MathUtils.lerp(b.min.z+1,b.max.z-1,iz/9),y=groundAt(x,z);if(y!==null)spots.push({x,z,y,range:.4,center:Math.hypot(x,z)})}}if(!spots.length)throw new Error('Authored arena has no usable walk surface.');spots.sort((a,b)=>(a.range*8+a.center*.018)-(b.range*8+b.center*.018));const tube=spots[0];let spawn=spots.filter(s=>{const d=Math.hypot(s.x-tube.x,s.z-tube.z);return d>5&&d<9}).sort((a,b)=>Math.abs(Math.hypot(a.x-tube.x,a.z-tube.z)-6.5)-Math.abs(Math.hypot(b.x-tube.x,b.z-tube.z)-6.5))[0];if(!spawn)spawn=spots[Math.min(spots.length-1,6)];return{tube,spawn,size}}

async function buildArena(){progress('Loading recovered authored pond → ruins → bridge → shrine arena…',15);const g=await loader.loadAsync('../pass1-v1/assets/recovered/terrain/concept_arena.glb');arenaRoot=g.scene;arenaRoot.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(arenaRoot),s=b.getSize(new THREE.Vector3()),m=34/Math.max(s.x,s.z,1),ctr=b.getCenter(new THREE.Vector3());arenaRoot.scale.setScalar(m);arenaRoot.position.set(-ctr.x*m,0,-ctr.z*m);arenaRoot.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(arenaRoot);arenaRoot.position.y=-b.min.y;arenaRoot.updateMatrixWorld(true);world.add(arenaRoot);worldBounds=new THREE.Box3().setFromObject(arenaRoot);arenaRoot.traverse(o=>{if(!o.isMesh)return;o.castShadow=!mobile;o.receiveShadow=true;const mats=Array.isArray(o.material)?o.material:[o.material],tag=((o.name||'')+' '+mats.map(x=>x?.name||'').join(' ')).toLowerCase();if(!/water|foam|gem|crystal|core|fx|particle/.test(tag))walkMeshes.push(o)});if(!walkMeshes.length)arenaRoot.traverse(o=>{if(o.isMesh)walkMeshes.push(o)});window.__worldSource='recovered-authored-concept-arena';window.__worldRoute='pond-ramp-ruins-rope-bridge-shrine';window.__enemyCount=0;window.__authoredWorldOnly=true;return chooseSites()}

let bro,heroRoot,tube,sites;const player={x:0,y:0,z:0,yaw:Math.PI,vy:0,speed:0,grounded:true,jumpCount:0,holdJumpTimer:0};const moveKeys={up:false,down:false,left:false,right:false,run:false,jump:false,jumpQueued:false},analogMove={x:0,y:0,active:false,pointerId:null};const PLAYER_RADIUS=.34,STEP_HEIGHT=.50,GRAVITY=8.25,JUMP_V=5.05,DOUBLE_JUMP_V=4.65,HOLD_BOOST_V=3.95,HOLD_BOOST_INTERVAL=.22;
async function createPlayer(){progress('Restoring Crystal Library v2 movement and Gamer Bro rig…',42);bro=createGamerBro(THREE,renderer,{colorway,detail:mobile?'low':'high',height:2.62});heroRoot=bro.root;bro.all.forEach(m=>{m.layers.enable(0);m.layers.enable(1)});bro.setRoomLight(1);scene.add(heroRoot);player.x=sites.spawn.x;player.z=sites.spawn.z;player.y=sites.spawn.y+.02;player.yaw=Math.atan2(sites.tube.x-player.x,sites.tube.z-player.z);bro.setHome(player.x,player.z,player.yaw);heroRoot.position.y=player.y;window.__characterReady=id;window.__playerPosition=player;window.__movementBaseline='crystal-library-v2';window.__cameraBaseline='crystal-library-v2'}

function createTube(){progress('Restoring the actual Crystal Library v2 tube…',62);tube=createCrystalLibraryTubeV2({renderer,scene,camera,bro,heroRoot,mobile,onComplete:()=>{objective.textContent='TRANSMISSION COMPLETE · CRYSTAL LIBRARY V2 BASELINE';retry.classList.add('show');toast('TRANSMISSION COMPLETE',2200)}});tube.root.position.set(sites.tube.x,sites.tube.y-.42,sites.tube.z);window.__tubeComponent='crystal-library-v2-tube';window.__tubePosition={x:sites.tube.x,y:sites.tube.y,z:sites.tube.z};window.__portalRequiresEnemies=false;window.__tubeTransferComplete=false}
retry.onclick=()=>{player.x=sites.spawn.x;player.z=sites.spawn.z;player.y=sites.spawn.y+.02;player.yaw=Math.atan2(sites.tube.x-player.x,sites.tube.z-player.z);player.vy=0;player.speed=0;player.grounded=true;bro.setHome(player.x,player.z,player.yaw);heroRoot.position.y=player.y;tube.reset(heroRoot.position);window.__tubeTransferComplete=false;retry.classList.remove('show');objective.textContent='EXPLORE · CRYSTAL LIBRARY V2 TUBE IS ALWAYS ACTIVE'};

// Exact Crystal Library v2 follow camera values plus terrain occlusion protection.
const target=new THREE.Vector3(),targetLook=new THREE.Vector3();let yaw=.06,pitch=.34,distance=13.4,followDistance=13.4,recenterClock=0,dragging=false,lastX=0,lastY=0,pinchDist=0,lookPointer=null;
function cameraDesired(dt){const portalActive=tube&&tube.state!=='idle';if(portalActive){targetLook.set(tube.root.position.x,tube.root.position.y+2.9,tube.root.position.z);target.lerp(targetLook,.085);yaw=THREE.MathUtils.damp(yaw,.06,3.0,dt);pitch=THREE.MathUtils.damp(pitch,.10,3.0,dt);distance=THREE.MathUtils.damp(distance,12.20,3.4,dt)}else{targetLook.set(player.x,player.y+1.45,player.z);target.lerp(targetLook,1-Math.exp(-8*dt));if(dragging||analogMove.active)recenterClock=0;else recenterClock+=dt;if(!dragging&&!analogMove.active&&recenterClock>.85){const behind=player.yaw+Math.PI,dy=Math.atan2(Math.sin(behind-yaw),Math.cos(behind-yaw));yaw+=dy*(1-Math.exp(-1.75*dt));pitch=THREE.MathUtils.damp(pitch,.34,2.5,dt)}distance=THREE.MathUtils.damp(distance,followDistance,3.8,dt)}const cp=Math.cos(pitch),desired=new THREE.Vector3(target.x+Math.sin(yaw)*cp*distance,target.y+Math.sin(pitch)*distance+1.05,target.z+Math.cos(yaw)*cp*distance);const dir=desired.clone().sub(target),len=dir.length();if(len>0&&walkMeshes.length){ray.set(target,dir.normalize());ray.far=len;const hit=ray.intersectObjects(walkMeshes,false)[0];if(hit&&hit.distance<len-.2)desired.copy(target).addScaledVector(dir,Math.max(2.9,hit.distance-.38))}camera.position.lerp(desired,1-Math.exp(-16*dt));camera.lookAt(target)}

function updatePlayer(dt){if(!bro||!tube||tube.state!=='idle')return;const kx=(moveKeys.right?1:0)-(moveKeys.left?1:0),ky=(moveKeys.up?1:0)-(moveKeys.down?1:0);let sx=analogMove.active?analogMove.x:kx,sy=analogMove.active?-analogMove.y:ky,len=Math.hypot(sx,sy);if(len<.075){sx=0;sy=0;len=0}const inputMag=Math.min(1,len);if(len>1){sx/=len;sy/=len;len=1}let dx=0,dz=0;if(len>0){const fx=-Math.sin(yaw),fz=-Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw);dx=fx*sy+rx*sx;dz=fz*sy+rz*sx;const dl=Math.hypot(dx,dz)||1;dx/=dl;dz/=dl;const ty=Math.atan2(dx,dz),diff=Math.atan2(Math.sin(ty-player.yaw),Math.cos(ty-player.yaw));player.yaw+=diff*(1-Math.exp(-8.5*dt))}const speedScale=THREE.MathUtils.smoothstep(inputMag,.075,.88),targetSpeed=len>0?(moveKeys.run?6.35:3.75)*speedScale:0;player.speed=THREE.MathUtils.damp(player.speed,targetSpeed,targetSpeed>player.speed?7.5:11,dt);const currentH=groundAt(player.x,player.z),nx=player.x+dx*player.speed*dt,nz=player.z+dz*player.speed*dt,nextH=groundAt(nx,nz);if(nextH!==null&&(currentH===null||nextH-currentH<=STEP_HEIGHT)){player.x=nx;player.z=nz}
  if(moveKeys.jumpQueued){if(player.grounded){player.vy=JUMP_V;player.grounded=false;player.jumpCount=1;player.holdJumpTimer=HOLD_BOOST_INTERVAL}else if(player.jumpCount<2){player.vy=Math.max(player.vy,DOUBLE_JUMP_V);player.jumpCount=2;player.holdJumpTimer=HOLD_BOOST_INTERVAL}moveKeys.jumpQueued=false}
  if(moveKeys.jump&&!player.grounded){player.holdJumpTimer-=dt;if(player.holdJumpTimer<=0){player.vy=Math.max(player.vy,HOLD_BOOST_V);player.holdJumpTimer=HOLD_BOOST_INTERVAL}}
  player.vy-=GRAVITY*dt;player.y+=player.vy*dt;const ground=groundAt(player.x,player.z);if(ground!==null&&player.vy<=0&&player.y<=ground+.035){player.y=ground+.02;player.vy=0;player.grounded=true;player.jumpCount=0}else if(ground===null||player.y>ground+.08)player.grounded=false;
  if(player.y<worldBounds.min.y-5){player.x=sites.spawn.x;player.z=sites.spawn.z;player.y=sites.spawn.y+.02;player.vy=0;player.speed=0;player.grounded=true;toast('BACK ON THE TRAIL')}
  const motion=player.speed<.14?'idle':(player.speed<3.7?'walk':'run');bro.setMotion(motion);bro.setHome(player.x,player.z,player.yaw);heroRoot.position.y=player.y;window.__heroMotion=motion;
  const d=Math.hypot(player.x-sites.tube.x,player.z-sites.tube.z);if(d<tube.entryRadius&&player.grounded&&tube.prewarmed){player.speed=0;bro.setMotion('idle');tube.trigger();objective.textContent='CRYSTAL LIBRARY V2 · TRANSMISSION IN PROGRESS'}
}

const keyMap={KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};addEventListener('keydown',e=>{if(keyMap[e.code])moveKeys[keyMap[e.code]]=true;if(e.code==='ShiftLeft'||e.code==='ShiftRight')moveKeys.run=true;if(e.code==='Space'){e.preventDefault();if(!moveKeys.jump)moveKeys.jumpQueued=true;moveKeys.jump=true}});addEventListener('keyup',e=>{if(keyMap[e.code])moveKeys[keyMap[e.code]]=false;if(e.code==='ShiftLeft'||e.code==='ShiftRight')moveKeys.run=false;if(e.code==='Space')moveKeys.jump=false});
function setStick(x,y){const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,lim=r.width*.34;let dx=x-cx,dy=y-cy,d=Math.hypot(dx,dy);if(d>lim){dx=dx/d*lim;dy=dy/d*lim}let nx=dx/lim,ny=dy/lim;if(Math.hypot(nx,ny)<.035){nx=ny=0}analogMove.x=nx;analogMove.y=ny;analogMove.active=Math.hypot(nx,ny)>.035;stick.style.transform=`translate3d(${dx}px,${dy}px,0)`}function clearStick(){analogMove.pointerId=null;analogMove.x=analogMove.y=0;analogMove.active=false;stick.style.transform='translate3d(0,0,0)'}pad.addEventListener('pointerdown',e=>{e.preventDefault();analogMove.pointerId=e.pointerId;pad.setPointerCapture?.(e.pointerId);setStick(e.clientX,e.clientY)});pad.addEventListener('pointermove',e=>{if(e.pointerId===analogMove.pointerId)setStick(e.clientX,e.clientY)});pad.addEventListener('pointerup',e=>{if(e.pointerId===analogMove.pointerId)clearStick()});pad.addEventListener('pointercancel',clearStick);
function pressJump(e){e.preventDefault();if(!moveKeys.jump)moveKeys.jumpQueued=true;moveKeys.jump=true;jumpBtn.classList.add('active')}function releaseJump(){moveKeys.jump=false;jumpBtn.classList.remove('active')}jumpBtn.addEventListener('pointerdown',pressJump);jumpBtn.addEventListener('pointerup',releaseJump);jumpBtn.addEventListener('pointercancel',releaseJump);runBtn.addEventListener('pointerdown',e=>{e.preventDefault();moveKeys.run=true;runBtn.classList.add('active')});for(const ev of['pointerup','pointercancel','pointerleave'])runBtn.addEventListener(ev,()=>{moveKeys.run=false;runBtn.classList.remove('active')});
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){if(lookPointer===null){lookPointer=e.pointerId;lastX=e.clientX;lastY=e.clientY}}else{dragging=true;lookPointer=e.pointerId;lastX=e.clientX;lastY=e.clientY}canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==lookPointer)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;yaw-=dx*.0052;pitch=clamp(pitch+dy*.0036,.08,.62);recenterClock=0});function endLook(e){if(e.pointerId===lookPointer){lookPointer=null;dragging=false}}canvas.addEventListener('pointerup',endLook);canvas.addEventListener('pointercancel',endLook);canvas.addEventListener('wheel',e=>{followDistance=clamp(followDistance+Math.sign(e.deltaY)*1.1,7.5,30)},{passive:true});
let touches=new Map();canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size===2){const a=[...touches.values()];pinchDist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}}});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'&&touches.has(e.pointerId)){touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size===2){const a=[...touches.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinchDist)followDistance=clamp(followDistance+(pinchDist-d)*.040,7.5,30);pinchDist=d}}});for(const ev of['pointerup','pointercancel'])canvas.addEventListener(ev,e=>{touches.delete(e.pointerId);if(touches.size<2)pinchDist=0});
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize,{passive:true});resize();

let last=performance.now(),elapsed=0,frames=0;function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;elapsed+=dt;updatePlayer(dt);if(tube)tube.update(elapsed,dt);if(bro&&tube?.state==='idle')bro.update(elapsed,dt,.05);cameraDesired(dt);renderer.render(scene,camera);frames++;window.__frameCount=frames}

(async()=>{try{sites=await buildArena();await createPlayer();createTube();target.set(player.x,player.y+1.45,player.z);targetLook.copy(target);progress('Prewarming the exact dissolve shaders before play…',82);requestAnimationFrame(frame);await tube.prewarm();progress('Gold baseline ready.',100);window.__pass8Ready=true;window.__fullGround=true;window.__portalTestUngated=true;setTimeout(()=>boot.classList.add('hide'),120)}catch(err){console.error(err);boot.style.display='none';fatal.classList.add('show');errorEl.textContent=String(err?.message||err)}})();
