import * as THREE from 'three';
import { createGamerBro } from '../playground-v2/gamer-bro.js?v=pass14';
import { createCrystalLibraryTubeV2 } from '../src/crystal-library-tube-v2.js?v=1';
import { createAssetLibrary } from './assets.js?v=14.0.0';
import { createLevelLabWorld } from './world.js?v=14.0.0';
import { createEnemySystem } from './enemies.js?v=14.0.0';
import { createPrismBreaker } from './power.js?v=14.0.0';

window.__pass14ModuleStarted=true;window.__bootPhase='module-started';
const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const $=s=>document.querySelector(s),canvas=$('#game'),boot=$('#boot'),fatal=$('#fatal'),errorEl=$('#error'),statusEl=$('#status'),barEl=$('#bar'),objectiveEl=$('#objective'),heroNameEl=$('#heroName'),healthEl=$('#health'),coinsEl=$('#coins'),gemsEl=$('#gems'),chargeBar=$('#chargeBar'),pad=$('#pad'),stick=$('#stick'),jumpBtn=$('#jump'),runBtn=$('#run'),actionBtn=$('#action'),menuBtn=$('#menu'),retryBtn=$('#retry'),toastEl=$('#toast');
const qp=new URLSearchParams(location.search),ci=qp.has('ci'),requested=qp.get('hero'),saved=localStorage.getItem('gamerBroCharacter'),heroId=requested==='gb1'||requested==='gb2'?requested:(saved==='gb1'||saved==='gb2'?saved:'gb2'),colorway=heroId==='gb1'?'pink':'teal';localStorage.setItem('gamerBroCharacter',heroId);heroNameEl.textContent=heroId.toUpperCase();menuBtn.onclick=()=>location.href='../';retryBtn.onclick=()=>location.reload();
const setPhase=(t,p)=>{window.__bootPhase=t;statusEl.textContent=t;barEl.style.width=`${p}%`};function toast(t,ms=900){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toast._timer);toast._timer=setTimeout(()=>toastEl.classList.remove('show'),ms)}function fail(e){console.error(e);errorEl.textContent=`${e?.message||e||'Unknown startup failure'}\nPhase: ${window.__bootPhase||'unknown'}`;fatal.classList.add('show')}

const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,alpha:false,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=1.28;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1:1.35));renderer.shadowMap.enabled=!mobile;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x88cbe1);scene.fog=new THREE.Fog(0xa8d7e1,60,150);const camera=new THREE.PerspectiveCamera(39,1,.12,210);camera.layers.enable(1);scene.add(new THREE.HemisphereLight(0xf2fbff,0x395a39,mobile?2.1:1.8));const sun=new THREE.DirectionalLight(0xfff0d7,mobile?1.85:2.3);sun.position.set(-26,38,24);sun.castShadow=!mobile;if(!mobile){sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;sun.shadow.camera.near=1;sun.shadow.camera.far=120;sun.shadow.bias=-.0002;sun.shadow.normalBias=.03}scene.add(sun);const rim=new THREE.DirectionalLight(0x776dff,.24);rim.position.set(25,18,-28);scene.add(rim);

const assets=createAssetLibrary({mobile});const world=createLevelLabWorld({scene,assets,mobile,setPhase});let sites=null,bro=null,heroRoot=null,tube=null,tubeWarm=false,tubeWarmPromise=null,enemies=null,power=null;const heroBaseScale=new THREE.Vector3(1,1,1);
const player={x:0,y:0,z:0,yaw:Math.PI,vy:0,speed:0,grounded:true,jumpCount:0,holdTimer:0,hearts:5,damageCooldown:0,springCooldown:0,boostX:0,boostZ:0};const input={up:false,down:false,left:false,right:false,run:false,jump:false,jumpQueued:false},analog={x:0,y:0,active:false,pointerId:null};const WALK=9.375,RUN=15.875,GRAVITY=8.4,JUMP=5.15,DOUBLE=4.7,HOLD=3.95,HOLD_INTERVAL=.22,STEP=.95;
let coins=0,gems=0,checkpoint=0,hitPause=0,complete=false;const checkpoints=[];
function updateHUD(){healthEl.textContent='♥'.repeat(Math.max(0,player.hearts))+'♡'.repeat(Math.max(0,5-player.hearts));coinsEl.textContent=String(coins);gemsEl.textContent=String(gems)}
function checkpointPosition(){return checkpoints[Math.max(0,Math.min(checkpoint,checkpoints.length-1))]||sites?.spawn||{x:0,z:30,y:0}}
function resetPlayer(death=false){const p=death?checkpointPosition():sites.spawn;player.x=p.x;player.z=p.z;player.y=(world.groundAt(p.x,p.z)??p.y)+.04;player.yaw=Math.PI;player.vy=0;player.speed=0;player.boostX=player.boostZ=0;player.grounded=true;player.jumpCount=0;player.holdTimer=0;player.springCooldown=.4;if(death)player.hearts=5;if(bro){bro.setMotion('idle');bro.setHome(player.x,player.z,player.yaw);heroRoot.position.y=player.y;heroRoot.scale.copy(heroBaseScale);bro.update(0,0,0)}updateHUD()}
async function createPlayer(){setPhase('Creating Gamer Bro…',55);bro=createGamerBro(THREE,renderer,{colorway,detail:mobile?'low':'high',height:2.62});heroRoot=bro.root;heroBaseScale.copy(heroRoot.scale);bro.all.forEach(m=>{m.layers.enable(0);m.layers.enable(1)});bro.setRoomLight(1);scene.add(heroRoot);resetPlayer(false);window.__characterReady=heroId}
function beginTubeWarm(){if(tubeWarmPromise||!tube)return tubeWarmPromise;tubeWarmPromise=tube.prewarm().then(()=>{tubeWarm=true;window.__tubeWarmReady=true}).catch(e=>{console.warn('[Pass14 tube prewarm]',e);tubeWarmPromise=null});return tubeWarmPromise}
function createTube(){tube=createCrystalLibraryTubeV2({renderer,scene,camera,bro,heroRoot,mobile,onComplete:()=>{complete=true;objectiveEl.textContent='HERO SLICE COMPLETE · SPRINGLINE TERRACE';retryBtn.classList.add('show');toast('SPRINGLINE TERRACE COMPLETE',2200)}});tube.root.position.set(sites.tube.x,sites.tube.y-.42,sites.tube.z);tube.entryRadius=Math.max(2.8,tube.entryRadius||0);window.__tubeComponent='crystal-library-v2-tube'}
function damagePlayer(){if(player.damageCooldown>0||complete||tube?.state!=='idle')return;player.damageCooldown=1;player.hearts--;updateHUD();toast(`HIT · ${player.hearts} HEART${player.hearts===1?'':'S'} LEFT`,760);if(player.hearts<=0){toast('RESPAWNING AT CHECKPOINT',1100);setTimeout(()=>resetPlayer(true),420)}}
function enemyKilled(){coins+=2;gems+=1;updateHUD();toast('ENEMY DOWN · +2 COINS · +1 GEM',900)}

const camTarget=new THREE.Vector3(),camLook=new THREE.Vector3();let camYaw=.06,camPitch=.33,camDistance=12.8,recenter=0,dragging=false,lastX=0,lastY=0;
function updateCamera(dt){const portal=tube&&tube.state!=='idle';if(portal){camLook.set(tube.root.position.x,tube.root.position.y+2.8,tube.root.position.z);camTarget.lerp(camLook,.09);camYaw=THREE.MathUtils.damp(camYaw,.03,3,dt);camPitch=THREE.MathUtils.damp(camPitch,.13,3,dt);camDistance=THREE.MathUtils.damp(camDistance,11.8,3.2,dt)}else{camLook.set(player.x,player.y+1.45,player.z);camTarget.lerp(camLook,1-Math.exp(-8*dt));if(dragging||analog.active)recenter=0;else recenter+=dt;if(!dragging&&!analog.active&&recenter>.65){const behind=player.yaw+Math.PI,d=Math.atan2(Math.sin(behind-camYaw),Math.cos(behind-camYaw));camYaw+=d*(1-Math.exp(-1.65*dt));camPitch=THREE.MathUtils.damp(camPitch,.33,2.2,dt)}}const cp=Math.cos(camPitch),desired=new THREE.Vector3(camTarget.x+Math.sin(camYaw)*cp*camDistance,camTarget.y+Math.sin(camPitch)*camDistance+1,camTarget.z+Math.cos(camYaw)*cp*camDistance);camera.position.lerp(desired,1-Math.exp(-14*dt));const kick=power?.cameraKick||0;if(kick>0){camera.position.x+=Math.cos(camYaw)*kick*.12;camera.position.y+=kick*.07;camera.position.z-=Math.sin(camYaw)*kick*.12}camera.lookAt(camTarget)}
function objective(){if(complete)return;if(player.z>8)objectiveEl.textContent='READ · FOLLOW THE REAL GRASS RAMP';else if(player.z>-24)objectiveEl.textContent='LEARN · STEP ON THE SPRING';else if(player.z>-52)objectiveEl.textContent='DEVELOP · CLIMB THE PLATFORM RAMP';else if(player.z>-74)objectiveEl.textContent='CHOOSE · SAFE ROUTE OR HIGH SPRING LOOP';else if(player.z>-103)objectiveEl.textContent='TEST · CLEAR THE COMBAT TERRACE';else objectiveEl.textContent='PAYOFF · REACH THE CRYSTAL TUBE'}
function updateCheckpoint(){if(player.z<-55&&checkpoint<1){checkpoint=1;toast('CHECKPOINT · SPLIT TERRACE',650)}if(player.z<-86&&checkpoint<2){checkpoint=2;toast('CHECKPOINT · COMBAT TERRACE',650)}}
function activateSpring(){if(player.springCooldown>0||!player.grounded)return;for(const s of world.springs){if(Math.hypot(player.x-s.x,player.z-s.z)>1.45)continue;const dx=s.target.x-player.x,dz=s.target.z-player.z,l=Math.hypot(dx,dz)||1;player.boostX=dx/l*s.strengthForward;player.boostZ=dz/l*s.strengthForward;player.vy=s.strengthY;player.grounded=false;player.jumpCount=1;player.springCooldown=.95;toast(s.mandatory?'SPRINGLINE LAUNCH':'MASTERY SPRING · HIGH ROUTE',700);return}}
function updatePlayer(dt,t){if(!bro||!tube||tube.state!=='idle'||complete)return;player.damageCooldown=Math.max(0,player.damageCooldown-dt);player.springCooldown=Math.max(0,player.springCooldown-dt);
  const kx=(input.right?1:0)-(input.left?1:0),ky=(input.up?1:0)-(input.down?1:0);let sx=analog.active?analog.x:kx,sy=analog.active?-analog.y:ky,len=Math.hypot(sx,sy);if(len<.075){sx=0;sy=0;len=0}const mag=Math.min(1,len);if(len>1){sx/=len;sy/=len}let dx=0,dz=0;if(len>0){const fx=-Math.sin(camYaw),fz=-Math.cos(camYaw),rx=Math.cos(camYaw),rz=-Math.sin(camYaw);dx=fx*sy+rx*sx;dz=fz*sy+rz*sx;const dl=Math.hypot(dx,dz)||1;dx/=dl;dz/=dl;const want=Math.atan2(dx,dz),diff=Math.atan2(Math.sin(want-player.yaw),Math.cos(want-player.yaw));player.yaw+=diff*(1-Math.exp(-11*dt))}
  const chargeScale=power?.charging?.42:1,target=len>0?(input.run?RUN:WALK)*THREE.MathUtils.smoothstep(mag,.075,.9)*chargeScale:0;player.speed=THREE.MathUtils.damp(player.speed,target,target>player.speed?8:12,dt);
  const vx=dx*player.speed+player.boostX,vz=dz*player.speed+player.boostZ,nx=player.x+vx*dt,nz=player.z+vz*dt,ch=world.groundAt(player.x,player.z),nh=world.groundAt(nx,nz);
  if(!player.grounded||nh!==null&&(ch===null||nh-ch<=STEP)){player.x=nx;player.z=nz}
  player.boostX*=Math.exp(-(player.grounded?8:1.1)*dt);player.boostZ*=Math.exp(-(player.grounded?8:1.1)*dt);
  if(input.jumpQueued){if(player.grounded){player.vy=JUMP;player.grounded=false;player.jumpCount=1;player.holdTimer=HOLD_INTERVAL}else if(player.jumpCount<2){player.vy=Math.max(player.vy,DOUBLE);player.jumpCount=2;player.holdTimer=HOLD_INTERVAL}input.jumpQueued=false}
  if(input.jump&&!player.grounded){player.holdTimer-=dt;if(player.holdTimer<=0){player.vy=Math.max(player.vy,HOLD);player.holdTimer=HOLD_INTERVAL}}
  player.vy-=GRAVITY*dt;player.y+=player.vy*dt;const g=world.groundAt(player.x,player.z);if(g!==null&&player.vy<=0&&player.y<=g+.07){player.y=g+.04;player.vy=0;player.grounded=true;player.jumpCount=0}else if(g===null||player.y>g+.11)player.grounded=false;
  activateSpring();if(player.y<world.getBounds().min.y-7){resetPlayer(true);toast('BACK AT CHECKPOINT',650)}updateCheckpoint();
  const motion=player.speed<.14?'idle':player.speed<WALK*.9?'walk':'run';bro.setMotion(motion);bro.setHome(player.x,player.z,player.yaw);bro.update(t,dt,power?.charging?1:0);heroRoot.position.y=player.y;heroRoot.rotation.x=-Math.min(.12,(power?.recoil||0)*.28);heroRoot.scale.copy(heroBaseScale).multiplyScalar(1+(power?.charging?.018:0));
  const d=Math.hypot(player.x-sites.tube.x,player.z-sites.tube.z);if(d<tube.entryRadius&&player.grounded){if(tubeWarm||tube.prewarmed){player.speed=0;bro.setMotion('idle');tube.trigger();objectiveEl.textContent='CRYSTAL LIBRARY V2 · TRANSMISSION'}else{objectiveEl.textContent='PORTAL CHARGING…';beginTubeWarm()}}
}
function updateCollectibles(){for(const c of world.collectibles){if(c.taken)continue;const d=Math.hypot(player.x-c.x,player.z-c.z);if(d>1.15)continue;c.taken=true;c.root.visible=false;if(c.type==='coin'){coins++;toast('+1 COIN',350)}else if(c.type==='gem'){gems++;toast('+1 GEM',420)}else if(c.type==='chest'){gems+=c.rewardGems||3;coins+=5;toast('MASTERY CHEST · +5 COINS · +3 GEMS',1100)}else if(c.type==='heart'){player.hearts=Math.min(5,player.hearts+1);toast('HEART RESTORED',520)}updateHUD()}}
function updateHazards(){for(const h of world.hazards){if(Math.hypot(player.x-h.x,player.z-h.z)<h.radius+0.45&&Math.abs(player.y-h.root.position.y)<2)damagePlayer()}}

function bindControls(){const map={KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};addEventListener('keydown',e=>{if(map[e.code])input[map[e.code]]=true;if(e.code==='ShiftLeft'||e.code==='ShiftRight')input.run=true;if(e.code==='Space'){e.preventDefault();if(!input.jump)input.jumpQueued=true;input.jump=true}if(['KeyE','KeyX','KeyJ','KeyK'].includes(e.code)&&!e.repeat){power?.start();actionBtn.classList.add('charging')}});addEventListener('keyup',e=>{if(map[e.code])input[map[e.code]]=false;if(e.code==='ShiftLeft'||e.code==='ShiftRight')input.run=false;if(e.code==='Space')input.jump=false;if(['KeyE','KeyX','KeyJ','KeyK'].includes(e.code)){power?.release();actionBtn.classList.remove('charging')}});
  function setStick(x,y){const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,lim=r.width*.34;let dx=x-cx,dy=y-cy,d=Math.hypot(dx,dy);if(d>lim){dx=dx/d*lim;dy=dy/d*lim}let nx=dx/lim,ny=dy/lim;if(Math.hypot(nx,ny)<.04){nx=0;ny=0}analog.x=nx;analog.y=ny;analog.active=true;stick.style.transform=`translate(${nx*lim}px,${ny*lim}px)`}
  pad.addEventListener('pointerdown',e=>{analog.pointerId=e.pointerId;pad.setPointerCapture(e.pointerId);setStick(e.clientX,e.clientY)});pad.addEventListener('pointermove',e=>{if(e.pointerId===analog.pointerId)setStick(e.clientX,e.clientY)});function stopStick(e){if(e.pointerId!==analog.pointerId)return;analog.active=false;analog.pointerId=null;analog.x=analog.y=0;stick.style.transform='translate(0,0)'}pad.addEventListener('pointerup',stopStick);pad.addEventListener('pointercancel',stopStick);
  function hold(btn,key){btn.addEventListener('pointerdown',e=>{e.preventDefault();if(key==='jump'&&!input.jump)input.jumpQueued=true;input[key]=true});const up=e=>{e.preventDefault();input[key]=false};btn.addEventListener('pointerup',up);btn.addEventListener('pointercancel',up)}hold(jumpBtn,'jump');hold(runBtn,'run');
  actionBtn.addEventListener('pointerdown',e=>{e.preventDefault();actionBtn.setPointerCapture?.(e.pointerId);if(power?.start())actionBtn.classList.add('charging')});const release=e=>{e.preventDefault();power?.release();actionBtn.classList.remove('charging')};actionBtn.addEventListener('pointerup',release);actionBtn.addEventListener('pointercancel',release);actionBtn.addEventListener('lostpointercapture',()=>{power?.release();actionBtn.classList.remove('charging')});
  canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;dragging=true;lastX=e.clientX;lastY=e.clientY});addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;camYaw-=dx*.0031;camPitch=THREE.MathUtils.clamp(camPitch+dy*.0023,.05,.72)});addEventListener('pointerup',()=>dragging=false);addEventListener('wheel',e=>{camDistance=THREE.MathUtils.clamp(camDistance+Math.sign(e.deltaY)*.75,8.2,17)},{passive:true})
}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize,{passive:true});resize();
let last=performance.now(),elapsed=0;function frame(now=performance.now()){requestAnimationFrame(frame);let dt=Math.min(.033,Math.max(.001,(now-last)/1000));last=now;if(hitPause>0){hitPause=Math.max(0,hitPause-dt);updateCamera(dt);renderer.render(scene,camera);return}elapsed+=dt;updatePlayer(dt,elapsed);power?.update(dt,elapsed);const hs=power?.consumeHitStop()||0;if(hs>0)hitPause=Math.max(hitPause,hs);enemies?.update(dt,elapsed);world.update(dt,elapsed);updateCollectibles();updateHazards();objective();chargeBar.style.width=`${Math.round((power?.charge||0)*100)}%`;tube?.update(dt);updateCamera(dt);renderer.render(scene,camera)}

(async()=>{try{
  setPhase('Loading real playable geometry…',10);sites=await world.build();world.refreshBounds();const validation=world.validateRoutes();window.__pass14RouteValidation=validation;if(!validation.main.ok)throw new Error(`Main-route probe failed: ${JSON.stringify(validation.main.failures.slice(0,3))}`);if(!validation.optional.ok)throw new Error(`Optional-route probe failed: ${JSON.stringify(validation.optional.failures.slice(0,3))}`);document.documentElement.dataset.routeMain='1';document.documentElement.dataset.routeOptional='1';
  checkpoints.push(sites.spawn,{x:sites.split.x,z:sites.split.z,y:sites.split.y},{x:sites.arena.x,z:sites.arena.z,y:sites.arena.y});
  await createPlayer();createTube();setPhase('Spawning animated enemies…',72);enemies=createEnemySystem({assets,parent:world.root,groundAt:world.groundAt,getPlayerPosition:v=>v.set(player.x,player.y,player.z),damagePlayer,onEnemyKilled:enemyKilled,toast});await enemies.spawnAll(sites.enemySpawns);document.documentElement.dataset.enemies=String(enemies.enemies.length);
  power=createPrismBreaker({scene,bro,getHeroState:()=>player,getEnemies:()=>enemies.living(),damageEnemy:(e,serial,opts)=>enemies.damage(e,serial,opts),toast,mobile});bindControls();updateHUD();setPhase('Springline Terrace ready',100);boot.classList.add('hide');window.__pass14Ready=true;window.__pass='pass14-level-lab';document.documentElement.dataset.pass14Ready='1';last=performance.now();frame();
  if(!ci)setTimeout(()=>beginTubeWarm(),mobile?1800:650);
}catch(e){fail(e)}})();
