import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';

// Targeted portal pass for Nature Adventure v2.
// Keep the proven charge -> convert -> dissipate -> afterglow language, but move all
// hero traversal, particle allocation and dissolve-program preparation out of the
// conversion frame. If this still hitches on real devices, the transition engine can
// be replaced wholesale without touching the world/gameplay build.

const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const nativeRender=THREE.WebGLRenderer.prototype.render;
const loader=new GLTFLoader();
const state={renderer:null,scene:null,camera:null,player:null,visual:null,root:null,core:null,coreMat:null,halo:null,ring:null,light:null,crystals:[],particles:null,particleGeo:null,particleBase:null,portalPos:new THREE.Vector3(),portalYaw:0,phase:'boot',phaseAt:0,freezePos:new THREE.Vector3(),heroBox:new THREE.Box3(),heroBottom:0,heroTop:2.6,dissolve:0,dissolveCut:-999,materials:[],warned:false,warm:false,warmStarted:false,ready:false,lastRender:performance.now(),lastPlayer:new THREE.Vector3(),archReady:false};

// A tiny independent input observer doubles as a fail-safe for the authored terrain
// spawn. It only moves the player when Nature Adventure itself received input but did
// not move that frame, so it never doubles normal movement.
const bridgeInput={x:0,y:0,run:false,keys:Object.create(null),pointer:null};
addEventListener('keydown',e=>bridgeInput.keys[e.code]=true,true);
addEventListener('keyup',e=>bridgeInput.keys[e.code]=false,true);
function padAxes(clientX,clientY){const el=document.getElementById('pad');if(!el)return;const r=el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,lim=Math.max(20,r.width*.34);let dx=clientX-cx,dy=clientY-cy,d=Math.hypot(dx,dy);if(d>lim){dx=dx/d*lim;dy=dy/d*lim}bridgeInput.x=dx/lim;bridgeInput.y=-dy/lim;}
function bindPad(){const el=document.getElementById('pad');if(!el)return;el.addEventListener('pointerdown',e=>{bridgeInput.pointer=e.pointerId;padAxes(e.clientX,e.clientY)},true);el.addEventListener('pointermove',e=>{if(e.pointerId===bridgeInput.pointer)padAxes(e.clientX,e.clientY)},true);el.addEventListener('pointerup',e=>{if(e.pointerId===bridgeInput.pointer){bridgeInput.pointer=null;bridgeInput.x=bridgeInput.y=0}},true);el.addEventListener('pointercancel',()=>{bridgeInput.pointer=null;bridgeInput.x=bridgeInput.y=0},true);el.addEventListener('touchstart',e=>{if(e.touches[0])padAxes(e.touches[0].clientX,e.touches[0].clientY)},{passive:true,capture:true});el.addEventListener('touchmove',e=>{if(e.touches[0])padAxes(e.touches[0].clientX,e.touches[0].clientY)},{passive:true,capture:true});el.addEventListener('touchend',()=>{bridgeInput.x=bridgeInput.y=0},{passive:true,capture:true});const run=document.getElementById('run');run?.addEventListener('pointerdown',()=>bridgeInput.run=true,true);for(const evt of ['pointerup','pointercancel','pointerleave'])run?.addEventListener(evt,()=>bridgeInput.run=false,true);}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',bindPad,{once:true});else bindPad();

function toast(text,ms=1450){const el=document.getElementById('toast');if(!el)return;el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),ms);}
function isDescendant(o,parent){for(let p=o;p;p=p.parent)if(p===parent)return true;return false;}
const ray=new THREE.Raycaster(),down=new THREE.Vector3(0,-1,0),normalM=new THREE.Matrix3();
function groundAt(x,z,expected=0){if(!state.scene)return null;ray.set(new THREE.Vector3(x,expected+14,z),down);ray.far=32;const hits=ray.intersectObjects(state.scene.children,true);let best=null,score=1e9;for(const h of hits){if(!h.face||!h.object?.isMesh)continue;if(state.player&&isDescendant(h.object,state.player))continue;if(state.root&&isDescendant(h.object,state.root))continue;const mat=Array.isArray(h.object.material)?h.object.material[0]:h.object.material;if(mat?.transparent&&mat.opacity<.9)continue;normalM.getNormalMatrix(h.object.matrixWorld);const n=h.face.normal.clone().applyNormalMatrix(normalM);if(n.y<.42)continue;const dy=h.point.y-expected;if(dy>.72||dy<-3.0)continue;const s=Math.abs(dy)+(dy>0?.2:0);if(s<score){score=s;best=h;}}
return best?.point.y??null;}
function groundInitial(x,z){if(!state.scene)return null;ray.set(new THREE.Vector3(x,25,z),down);ray.far=55;const hits=ray.intersectObjects(state.scene.children,true);for(const h of hits){if(!h.face||!h.object?.isMesh)continue;if(state.player&&isDescendant(h.object,state.player))continue;const mat=Array.isArray(h.object.material)?h.object.material[0]:h.object.material;if(mat?.transparent&&mat.opacity<.9)continue;normalM.getNormalMatrix(h.object.matrixWorld);const n=h.face.normal.clone().applyNormalMatrix(normalM);if(n.y>.42&&h.point.y>-3&&h.point.y<8)return h.point.y;}return null;}

function findPlayer(){const ref=window.__playerPosition;if(!ref||!state.scene)return null;let found=null;state.scene.traverse(o=>{if(!found&&o.position===ref)found=o});return found;}
function fitRoot(root,target=5.15){root.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(root),s=b.getSize(new THREE.Vector3()),k=target/Math.max(.001,s.y);root.scale.multiplyScalar(k);root.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(root);const c=b.getCenter(new THREE.Vector3());root.position.x-=c.x;root.position.z-=c.z;root.position.y-=b.min.y;return root;}

function portalShaderMaterial(){return new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},uCharge:{value:.18}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`varying vec2 vUv;uniform float uTime;uniform float uCharge;void main(){vec2 p=vUv-.5;float r=length(p)*2.0;float a=atan(p.y,p.x);float swirl=sin(a*5.0-r*12.0+uTime*3.0)*.5+.5;float bands=sin(r*22.0-uTime*4.2+swirl*2.2)*.5+.5;float edge=smoothstep(1.0,.80,r);float center=smoothstep(1.0,.05,r);vec3 cyan=vec3(.18,.92,1.0),pink=vec3(1.0,.20,.72),violet=vec3(.42,.24,1.0);vec3 col=mix(cyan,pink,swirl);col=mix(col,violet,bands*.35);float alpha=edge*(.34+.46*bands+.22*uCharge)*center;float sparkle=pow(max(0.0,sin(a*13.0+uTime*5.0-r*17.0)),12.0)*.45;gl_FragColor=vec4(col*(.72+bands*.72+sparkle+uCharge*.55),alpha);}`});}

function buildPortal(){const root=new THREE.Group();state.root=root;state.scene.add(root);
  const coreMat=portalShaderMaterial(),core=new THREE.Mesh(new THREE.CircleGeometry(1.48,64),coreMat);core.position.y=2.48;core.position.z=.06;core.renderOrder=3;root.add(core);state.core=core;state.coreMat=coreMat;
  const bronze=new THREE.MeshPhysicalMaterial({color:0xb87942,metalness:.76,roughness:.22,clearcoat:.72,clearcoatRoughness:.12,emissive:0x241006,emissiveIntensity:.22});
  const ring=new THREE.Mesh(new THREE.TorusGeometry(1.61,.105,12,72),bronze);ring.position.y=2.48;root.add(ring);state.ring=ring;
  const haloMat=new THREE.MeshBasicMaterial({color:0x82efff,transparent:true,opacity:.42,blending:THREE.AdditiveBlending,depthWrite:false});
  const halo=new THREE.Mesh(new THREE.TorusGeometry(1.76,.035,8,72),haloMat);halo.position.y=2.48;halo.position.z=.03;root.add(halo);state.halo=halo;
  const crystalMat=[0xff62c9,0x7aeaff,0xa879ff].map(c=>new THREE.MeshPhysicalMaterial({color:c,emissive:c,emissiveIntensity:1.1,metalness:.08,roughness:.16,clearcoat:1,clearcoatRoughness:.05,transparent:true,opacity:.94}));
  for(let i=0;i<8;i++){const a=i/8*Math.PI*2,c=new THREE.Mesh(new THREE.OctahedronGeometry(.22,0),crystalMat[i%3]);c.scale.set(.65,1.8,.65);c.position.set(Math.cos(a)*1.88,2.48+Math.sin(a)*1.88,.06);c.rotation.z=-a+.4;root.add(c);state.crystals.push(c);}
  const light=new THREE.PointLight(0x77eaff,7.5,12,1.7);light.position.set(0,2.5,1);root.add(light);state.light=light;
  const candidates=[[-31,5],[-34,10],[-26,12],[-10,7]];let placed=false;for(const [x,z] of candidates){const y=groundInitial(x,z);if(y!=null){state.portalPos.set(x,y,z);placed=true;break;}}if(!placed)state.portalPos.set(-10,0,7);root.position.copy(state.portalPos);
  const dx=(window.__playerPosition?.x??0)-root.position.x,dz=(window.__playerPosition?.z??0)-root.position.z;state.portalYaw=Math.atan2(dx,dz);root.rotation.y=state.portalYaw;root.scale.setScalar(.94);state.ready=true;state.phase='idle';window.__naturePortalReady=true;window.__naturePortalState='idle';window.__naturePortalPosition={x:root.position.x,y:root.position.y,z:root.position.z};
  // Main frame is a recovered authored stone arch. The procedural rings/core are only
  // the energy assembly, not a replacement environment asset.
  loader.loadAsync('../pass1-v1/assets/recovered/kit/arch.glb').then(g=>{const arch=fitRoot(g.scene,5.1);arch.traverse(o=>{if(o.isMesh){o.castShadow=!mobile;o.receiveShadow=true;const mats=Array.isArray(o.material)?o.material:[o.material];o.material=(Array.isArray(o.material)?mats:mats[0]);}});root.add(arch);arch.position.z=-.08;state.archReady=true;window.__naturePortalArch=true;}).catch(e=>console.warn('[Crystal Gate] stone arch unavailable',e));
}

function installDissolve(){if(!state.visual||state.materials.length)return;state.visual.updateMatrixWorld(true);state.heroBox.setFromObject(state.visual);state.heroBottom=state.heroBox.min.y+.02;state.heroTop=state.heroBox.max.y-.02;
  const seen=new Set();state.visual.traverse(o=>{if(!o.isMesh||!o.material)return;const src=Array.isArray(o.material)?o.material:[o.material],out=[];for(const original of src){if(!original||original.isShaderMaterial){out.push(original);continue;}let m=original;if(seen.has(original)){m=original.clone();}else{m=original.clone();seen.add(original);}const prior=m.onBeforeCompile?.bind(m),priorKey=m.customProgramCacheKey?.bind(m);m.onBeforeCompile=shader=>{prior?.(shader);shader.uniforms.uPortalDissolve={value:state.dissolve};shader.uniforms.uPortalCut={value:state.dissolveCut};shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying float vPortalWorldY;').replace('#include <project_vertex>','#include <project_vertex>\nvPortalWorldY=(modelMatrix*vec4(transformed,1.0)).y;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nuniform float uPortalDissolve;uniform float uPortalCut;varying float vPortalWorldY;').replace('#include <dithering_fragment>',`if(uPortalDissolve>.5){float pn=fract(sin(dot(gl_FragCoord.xy+vec2(vPortalWorldY*17.13),vec2(12.9898,78.233)))*43758.5453);float threshold=uPortalCut+(pn-.5)*.23;if(vPortalWorldY<threshold)discard;float edge=1.0-smoothstep(.02,.24,abs(vPortalWorldY-uPortalCut));gl_FragColor.rgb+=vec3(1.0,.16,.68)*edge*1.35;}\n#include <dithering_fragment>`);m.userData._portalShader=shader;};m.customProgramCacheKey=()=>`${priorKey?.()||''}|nature-portal-dissolve-v1`;m.needsUpdate=true;state.materials.push(m);out.push(m);}o.material=Array.isArray(o.material)?out:out[0];});
  const count=mobile?150:280,pos=new Float32Array(count*3),base=new Float32Array(count*3),col=new Float32Array(count*3),size=state.heroBox.getSize(new THREE.Vector3()),center=state.heroBox.getCenter(new THREE.Vector3());for(let i=0;i<count;i++){const j=i*3,x=center.x+(Math.random()-.5)*size.x*.82,y=state.heroBottom+Math.random()*(state.heroTop-state.heroBottom),z=center.z+(Math.random()-.5)*size.z*.72;base[j]=x-state.player.position.x;base[j+1]=y-state.player.position.y;base[j+2]=z-state.player.position.z;pos[j]=x;pos[j+1]=y;pos[j+2]=z;const c=new THREE.Color([0xff59c7,0x75eaff,0xb080ff,0xffd75f][i%4]);col[j]=c.r;col[j+1]=c.g;col[j+2]=c.b;}
  const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3).setUsage(THREE.DynamicDrawUsage));geo.setAttribute('color',new THREE.BufferAttribute(col,3));const mat=new THREE.PointsMaterial({size:mobile?.065:.075,vertexColors:true,transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false,sizeAttenuation:true});const pts=new THREE.Points(geo,mat);pts.frustumCulled=false;state.scene.add(pts);state.particles=pts;state.particleGeo=geo;state.particleBase=base;
  window.__naturePortalPrepared=true;
}
function setDissolve(active,cut){state.dissolve=active?1:0;state.dissolveCut=cut;for(const m of state.materials){const s=m.userData._portalShader;if(s){s.uniforms.uPortalDissolve.value=state.dissolve;s.uniforms.uPortalCut.value=cut;}}}
function warmPortal(){if(state.warmStarted||!state.renderer||!state.scene||!state.camera)return;state.warmStarted=true;const done=()=>{state.warm=true;window.__naturePortalPrewarmed=true;};try{const p=state.renderer.compileAsync?.(state.scene,state.camera);if(p?.then)p.then(done).catch(e=>{console.warn('[Crystal Gate] compile prewarm fallback',e);done()});else{state.renderer.compile?.(state.scene,state.camera);done();}}catch(e){console.warn('[Crystal Gate] prewarm fallback',e);done();}}

function beginPortal(now){if(!state.ready||state.phase!=='idle')return;if(!state.warm){warmPortal();toast('CRYSTAL GATE · WARMING ENERGY');return;}state.phase='charge';state.phaseAt=now;state.freezePos.copy(state.player.position);state.lastPlayer.copy(state.freezePos);window.__naturePortalState='charge';toast('CRYSTAL GATE · TRANSFER LOCKED',1800);}
function updateParticles(p){if(!state.particles)return;const arr=state.particleGeo.attributes.position.array,base=state.particleBase,center=state.portalPos.clone().add(new THREE.Vector3(0,2.48,0));for(let i=0;i<arr.length;i+=3){const t=i/3,seed=(t*12.9898)%6.283,scatter=Math.sin(seed+p*8)*.22*(1-p),sx=state.freezePos.x+base[i],sy=state.freezePos.y+base[i+1],sz=state.freezePos.z+base[i+2],pull=Math.max(0,(p-.18)/.82);arr[i]=THREE.MathUtils.lerp(sx,center.x,pull)+Math.cos(seed)*scatter;arr[i+1]=THREE.MathUtils.lerp(sy,center.y,pull)+p*.7+Math.sin(seed*1.7)*scatter;arr[i+2]=THREE.MathUtils.lerp(sz,center.z,pull)+Math.sin(seed)*scatter;}state.particleGeo.attributes.position.needsUpdate=true;}
function animatePortal(now,dt){if(!state.ready)return;const t=now*.001;state.coreMat.uniforms.uTime.value=t;state.ring.rotation.z=t*.16;state.halo.rotation.z=-t*.28;state.halo.material.opacity=.34+Math.sin(t*2.3)*.08;for(let i=0;i<state.crystals.length;i++){const c=state.crystals[i];c.rotation.y+=dt*(.35+i*.02);c.material.emissiveIntensity=.85+Math.sin(t*2.8+i)*.32;}state.light.intensity=7+Math.sin(t*3.1)*1.6;
  if(state.phase==='idle'){const dx=state.player.position.x-state.root.position.x,dz=state.player.position.z-state.root.position.z,d=Math.hypot(dx,dz);state.coreMat.uniforms.uCharge.value=.18;if(d<5.2&&!state.warned){state.warned=true;toast('CRYSTAL GATE AHEAD · STEP INTO THE LIGHT',1900);}if(d>6.5)state.warned=false;if(d<1.65)beginPortal(now);return;}
  state.player.position.copy(state.freezePos);const elapsed=(now-state.phaseAt)/1000;
  if(state.phase==='charge'){const p=Math.min(1,elapsed/.78);state.coreMat.uniforms.uCharge.value=.2+p*1.15;state.root.scale.setScalar(.94+p*.035);state.light.intensity=7+p*13;if(p>=1){state.phase='convert';state.phaseAt=now;window.__naturePortalState='convert';state.particles.material.opacity=.92;setDissolve(true,state.heroBottom-.2);}}
  else if(state.phase==='convert'){const p=Math.min(1,elapsed/.72);const cut=THREE.MathUtils.lerp(state.heroBottom-.2,state.heroTop+.18,p);setDissolve(true,cut);state.particles.material.opacity=.95;updateParticles(p*.58);state.coreMat.uniforms.uCharge.value=1.35;state.root.scale.setScalar(.975+Math.sin(p*Math.PI)*.028);if(p>=1){state.phase='dissipate';state.phaseAt=now;window.__naturePortalState='dissipate';}}
  else if(state.phase==='dissipate'){const p=Math.min(1,elapsed/.62);setDissolve(true,state.heroTop+.35);updateParticles(.58+p*.42);state.particles.material.opacity=1-p*.75;state.coreMat.uniforms.uCharge.value=1.5-p*.45;if(p>=1){state.phase='afterglow';state.phaseAt=now;window.__naturePortalState='afterglow';state.visual.visible=false;}}
  else if(state.phase==='afterglow'){const p=Math.min(1,elapsed/.58);state.particles.material.opacity=.25*(1-p);state.coreMat.uniforms.uCharge.value=1.05-p*.35;state.light.intensity=18*(1-p)+7;if(p>=1){window.__naturePortalState='transfer';const hero=encodeURIComponent(localStorage.getItem('gamerBroCharacter')||'gb2');location.href=`../hybrid-v09/?from=nature-adventure&hero=${hero}&portal=prewarmed`;}}
}

function fallbackMovement(dt){if(!state.player||!state.camera||state.phase!=='idle')return;let ix=bridgeInput.x+(bridgeInput.keys.KeyD||bridgeInput.keys.ArrowRight?1:0)-(bridgeInput.keys.KeyA||bridgeInput.keys.ArrowLeft?1:0),iy=bridgeInput.y+(bridgeInput.keys.KeyW||bridgeInput.keys.ArrowUp?1:0)-(bridgeInput.keys.KeyS||bridgeInput.keys.ArrowDown?1:0),mag=Math.min(1,Math.hypot(ix,iy));if(mag<.05){state.lastPlayer.copy(state.player.position);return;}const alreadyMoved=Math.hypot(state.player.position.x-state.lastPlayer.x,state.player.position.z-state.lastPlayer.z);if(alreadyMoved>.004){state.lastPlayer.copy(state.player.position);return;}const l=Math.hypot(ix,iy);ix/=l;iy/=l;const f=new THREE.Vector3(state.player.position.x-state.camera.position.x,0,state.player.position.z-state.camera.position.z);if(f.lengthSq()<.001)f.set(0,0,1);f.normalize();const r=new THREE.Vector3(f.z,0,-f.x),dir=f.multiplyScalar(iy).addScaledVector(r,ix).normalize(),speed=(bridgeInput.run||bridgeInput.keys.ShiftLeft||bridgeInput.keys.ShiftRight)?7.4:4.6,step=speed*mag*Math.min(.04,dt),nx=state.player.position.x+dir.x*step,nz=state.player.position.z+dir.z*step,gy=groundAt(nx,nz,state.player.position.y);if(gy!=null){state.player.position.x=nx;state.player.position.z=nz;state.player.position.y=THREE.MathUtils.lerp(state.player.position.y,gy+.03,.28);const target=Math.atan2(dir.x,dir.z),diff=Math.atan2(Math.sin(target-state.player.rotation.y),Math.cos(target-state.player.rotation.y));state.player.rotation.y+=diff*(1-Math.exp(-dt*12));window.__bridgeMoveApplied=(window.__bridgeMoveApplied||0)+1;}state.lastPlayer.copy(state.player.position);}

function initialize(renderer,scene,camera){state.renderer=renderer;state.scene=scene;state.camera=camera;state.player=findPlayer();if(!state.player)return false;state.visual=state.player.children[0]||state.player;state.lastPlayer.copy(state.player.position);installDissolve();buildPortal();const idle=()=>warmPortal();if('requestIdleCallback'in window)requestIdleCallback(idle,{timeout:900});else setTimeout(idle,120);window.__naturePortalTarget='crystal-library';return true;}

THREE.WebGLRenderer.prototype.render=function(scene,camera){const now=performance.now(),dt=Math.min(.04,(now-state.lastRender)/1000);state.lastRender=now;if(window.__pass42Ready&&!state.ready){if(!initialize(this,scene,camera)){state.scene=scene;state.camera=camera;state.renderer=this;}}
  if(state.ready){fallbackMovement(dt);animatePortal(now,dt);if(state.phase!=='idle'&&state.phase!=='boot'){state.player.position.copy(state.freezePos);const center=state.portalPos.clone().add(new THREE.Vector3(0,2.4,0)),side=new THREE.Vector3(Math.sin(state.portalYaw+1.05)*5.6,2.5,Math.cos(state.portalYaw+1.05)*5.6);camera.position.lerp(center.clone().add(side),1-Math.exp(-dt*2.5));camera.lookAt(center.clone().lerp(state.freezePos.clone().add(new THREE.Vector3(0,1.2,0)),.42));}}
  return nativeRender.call(this,scene,camera);
};

window.__naturePortalBridge=true;
