import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createGamerBro} from '../playground-v2/gamer-bro.js?v=pass7';
import {createAdvancedTube,ADVANCED_TUBE_ID} from '../src/advanced-tube-v1.js?v=pass7';
import {createTubeTransition} from './tube-transition.js?v=1';

const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const qp=new URLSearchParams(location.search),requested=qp.get('hero'),saved=localStorage.getItem('gamerBroCharacter');
const id=requested==='gb1'||requested==='gb2'?requested:(saved==='gb1'||saved==='gb2'?saved:'gb2'),colorway=id==='gb1'?'pink':'teal';localStorage.setItem('gamerBroCharacter',id);
const $=s=>document.querySelector(s),canvas=$('#game'),heroName=$('#heroName'),menu=$('#menu'),coinsEl=$('#coins'),gemsEl=$('#gems'),foesEl=$('#foes'),objective=$('#objective'),pad=$('#pad'),stick=$('#stick'),jumpBtn=$('#jump'),runBtn=$('#run'),actionBtn=$('#action'),toastEl=$('#toast'),boot=$('#boot'),status=$('#status'),bar=$('#bar'),fatal=$('#fatal'),errorEl=$('#error');heroName.textContent=id.toUpperCase();menu.onclick=()=>location.href='../';
const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.15:1.55));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x7bb9de);scene.fog=new THREE.Fog(0x9fd1e8,45,88);const camera=new THREE.PerspectiveCamera(46,1,.08,150);camera.layers.enable(1);scene.add(new THREE.HemisphereLight(0xf5ffff,0x31593e,2.5));const sun=new THREE.DirectionalLight(0xfff2d2,3.6);sun.position.set(-20,32,18);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:1536,mobile?1024:1536);sun.shadow.camera.left=-38;sun.shadow.camera.right=38;sun.shadow.camera.top=38;sun.shadow.camera.bottom=-38;sun.shadow.camera.near=1;sun.shadow.camera.far=90;scene.add(sun);const fill=new THREE.DirectionalLight(0xb0ddff,.5);fill.position.set(18,12,-18);scene.add(fill);
const loader=new GLTFLoader(),world=new THREE.Group(),actors=new THREE.Group(),fx=new THREE.Group();scene.add(world,actors,fx);const BASE='../assets/vendor/kenney-platformer/models/';
function progress(t,n){status.textContent=t;bar.style.width=n+'%'}function toast(t,ms=1450){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),ms)}function shadowize(r,cast=!mobile){r.traverse(o=>{if(o.isMesh){o.castShadow=cast;o.receiveShadow=true}});return r}
const templates={};async function load(name){if(templates[name])return templates[name];const g=await loader.loadAsync(BASE+name+'.glb');templates[name]=g.scene;return g.scene}
function sized(src,{x=1,y=1,z=1,align='bottom'}={}){const c=src.clone(true);c.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(c),s=b.getSize(new THREE.Vector3());c.scale.set(x/Math.max(.001,s.x),y/Math.max(.001,s.y),z/Math.max(.001,s.z));c.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(c);const ctr=b.getCenter(new THREE.Vector3()),wrap=new THREE.Group();c.position.x-=ctr.x;c.position.z-=ctr.z;c.position.y-=align==='top'?b.max.y:b.min.y;wrap.add(c);shadowize(wrap);return wrap}
function place(src,opt,pos,ry=0,parent=world){const o=sized(src,opt);o.position.set(...pos);o.rotation.y=ry;parent.add(o);return o}
function fitHeight(src,h){const c=src.clone(true);c.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(c),s=b.getSize(new THREE.Vector3()),k=h/Math.max(.001,s.y);c.scale.multiplyScalar(k);c.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(c);const ctr=b.getCenter(new THREE.Vector3()),w=new THREE.Group();c.position.set(-ctr.x,-b.min.y,-ctr.z);w.add(c);shadowize(w);return w}

const colliders=[],cameraOccluders=[];function circleCollider(x,z,r,ref=null){colliders.push({type:'circle',x,z,r,ref})}function boxCollider(x,z,w,d,ref=null){colliders.push({type:'box',x,z,w,d,ref})}function blocked(x,z){for(const c of colliders){if(c.ref&&c.ref.visible===false)continue;if(c.type==='circle'){if(Math.hypot(x-c.x,z-c.z)<c.r)return true}else if(Math.abs(x-c.x)<c.w/2&&Math.abs(z-c.z)<c.d/2)return true}return false}
function groundY(x,z){if(x>=-18.2&&x<=18.2&&z>=-15.3&&z<=16.2)return 0;if(x>=-7.6&&x<=7.6&&z<-15.3&&z>=-19.3)return THREE.MathUtils.clamp((-z-15.3)/4,0,1)*1.6;if(x>=-10.2&&x<=10.2&&z<-19.3&&z>=-24.4)return 1.6;return null}
async function buildWorld(){progress('Loading real Kenney terrain and scenery…',14);const names=['block-grass-low-large','block-grass-overhang-large','block-grass-large-slope','tree','tree-pine','tree-pine-small','flowers','flowers-tall','mushrooms','rocks','stones','hedge','fence-low-straight','crate','coin-gold','jewel'];await Promise.all(names.map(load));
  progress('Building one connected grassy adventure island…',26);for(let xi=0;xi<7;xi++)for(let zi=0;zi<6;zi++){const x=-15+xi*5,z=-12.5+zi*5,edge=xi===0||xi===6||zi===0||zi===5,src=templates[edge?'block-grass-overhang-large':'block-grass-low-large'];place(src,{x:5.25,y:1.05,z:5.25,align:'top'},[x,0,z],edge&&zi===0?Math.PI:0)}
  for(const x of[-7.5,-2.5,2.5,7.5])place(templates['block-grass-overhang-large'],{x:5.2,y:1.4,z:5.2,align:'top'},[x,1.6,-21.8],Math.PI);
  for(const x of[-5,0,5])place(templates['block-grass-large-slope'],{x:5.1,y:1.62,z:4.2,align:'bottom'},[x,-.02,-17.3],Math.PI);
  const trees=[[-15,-10,'tree',4.7],[-16,-2,'tree-pine',4.4],[-15,8,'tree',4.6],[-11,13,'tree-pine-small',3.5],[12,13,'tree',4.5],[16,8,'tree-pine',4.4],[16,-3,'tree',4.8],[14,-11,'tree-pine',4.2],[-8,-22,'tree-pine',4.0],[8,-22,'tree',4.2]];
  for(const [x,z,n,h] of trees){const y=groundY(x,z)??0,o=place(templates[n],{x:h*.78,y:h,z:h*.78},[x,y,z],Math.random()*6);circleCollider(x,z,.85,o);cameraOccluders.push(o)}
  for(const [x,z] of[[-12,4],[-8,12],[7,12],[12,4],[13,-7],[-11,-8],[-5,-22],[5,-22]]){const y=groundY(x,z)??0;place(templates.flowers,{x:1.5,y:.9,z:1.5},[x,y,z],Math.random()*6)}
  for(const [x,z] of[[-14,1],[-6,10],[5,10],[14,1],[10,-12],[-9,-11],[0,-22]]){const y=groundY(x,z)??0;place(templates.mushrooms,{x:1.15,y:.72,z:1.15},[x,y,z],Math.random()*6)}
  for(const [x,z] of[[-16,12],[15,11],[-14,-12],[15,-13],[-9,-20],[9,-20]]){const y=groundY(x,z)??0,o=place(templates.rocks,{x:1.5,y:1.2,z:1.4},[x,y,z],Math.random()*6);circleCollider(x,z,.7,o);cameraOccluders.push(o)}
  for(const [x,z,ry] of[[-11,6,0],[11,6,0],[-11,-5,0],[11,-5,0]]){const y=groundY(x,z)??0,o=place(templates.hedge,{x:4.2,y:1.25,z:1.0},[x,y,z],ry);boxCollider(x,z,4.2,1.0,o);cameraOccluders.push(o)}
  for(const [x,z] of[[-7,14],[7,14]]){const y=groundY(x,z)??0,o=place(templates['fence-low-straight'],{x:4.3,y:1.0,z:.35},[x,y,z]);boxCollider(x,z,4.3,.45,o)}
  window.__worldSource='kenney-platformer-kit';window.__fullGround=true;window.__ladderCount=0;window.__worldBuilt=true;
}

let player,visual,adapter,actionGlow=0;const spawn=new THREE.Vector3(0,.04,12.8),tubePos=new THREE.Vector3(6,0,9.2);async function createPlayer(){progress('Loading Gamer Bro and walk animation…',40);player=new THREE.Group();actors.add(player);adapter=createGamerBro(THREE,renderer,{colorway,detail:mobile?'low':'high',height:2.92});visual=adapter.root;adapter.setMotion('idle');player.add(visual);player.position.copy(spawn);player.rotation.y=Math.PI;window.__playerPosition=player.position;window.__characterReady=id;window.__heroMotion='idle'}
function pinkGhost(root){root.traverse(o=>{if(!o.isMesh||!o.material)return;const a=Array.isArray(o.material)?o.material:[o.material],out=a.map(src=>{const m=src.clone();if(m.color&&!/eye|pupil/i.test(o.name||'')){m.color.set(0xf0a4d5);if('metalness'in m)m.metalness=.76;if('roughness'in m)m.roughness=.14;if('clearcoat'in m){m.clearcoat=1;m.clearcoatRoughness=.05}if(m.emissive){m.emissive.set(0x4d1338);m.emissiveIntensity=.32}}return m});o.material=Array.isArray(o.material)?out:out[0]})}
const enemyDefs=[['STUMP','stump.glb',-10,2,false],['GHOST','ghost.glb',10,1,true],['CTHULHU','cthulhu.glb',-8,-9,false],['YETI','yeti.glb',10,-9,false]],enemies=[];async function createEnemies(){progress('Placing matching-scale recovered enemies…',52);await Promise.all(enemyDefs.map(async([name,file,x,z,pink],i)=>{const g=await loader.loadAsync('../pass1-v1/assets/recovered/characters/'+file),o=fitHeight(g.scene,2.9);if(pink)pinkGhost(o);const gy=groundY(x,z)??0;o.position.set(x,gy+(name==='GHOST'?.55:.03),z);actors.add(o);let mixer=null;if(g.animations?.length){mixer=new THREE.AnimationMixer(o);mixer.clipAction(g.animations.find(a=>/idle|walk/i.test(a.name))||g.animations[0]).play()}enemies.push({name,o,mixer,alive:true,home:o.position.clone(),phase:i*1.53})}));foesEl.textContent=`FOES · 0 / ${enemies.length}`;window.__enemyCount=enemies.length;window.__enemyScaleTarget=2.9}
let kills=0;function burst(pos){for(let i=0;i<12;i++){const s=new THREE.Mesh(new THREE.OctahedronGeometry(.07,0),new THREE.MeshBasicMaterial({color:[0xff69c8,0x70e9ff,0xffd96b,0xa879ff][i%4],transparent:true,opacity:.95}));s.position.copy(pos).add(new THREE.Vector3(0,1.1,0));fx.add(s);s.userData.v=new THREE.Vector3((Math.random()-.5)*4,1+Math.random()*3,(Math.random()-.5)*4);s.userData.life=.55;}}function defeatEnemy(e){if(!e?.alive)return;e.alive=false;e.o.visible=false;kills++;foesEl.textContent=`FOES · ${kills} / ${enemies.length}`;burst(e.o.position);toast(`${e.name} CLEARED`);window.__enemyKills=kills}

const crates=[];function createCrates(){for(const [x,z] of[[-5,5],[5,2],[-4,-6],[6,-5]]){const gy=groundY(x,z)??0,o=place(templates.crate,{x:1.2,y:1.2,z:1.2},[x,gy,z],Math.random()*.4,actors);const c={o,x,z,alive:true};crates.push(c);circleCollider(x,z,.72,o)}}function breakCrate(c){if(!c?.alive)return;c.alive=false;c.o.visible=false;burst(c.o.position);toast('CRATE SMASHED')}

const pickups=[];let coins=0,gems=0;function createPickups(){const route=[[-3,12],[-7,9],[-10,5],[-9,0],[-6,-4],[-3,-8],[0,-11],[4,-9],[8,-6],[10,-1],[9,4],[6,7],[2,6],[-2,4],[-5,1],[-3,-2],[0,-5],[3,-2],[5,1],[4,5]];route.forEach((p,i)=>{const kind=i%2?'coin':'gem',src=templates[kind==='coin'?'coin-gold':'jewel'],gy=groundY(p[0],p[1])??0,o=fitHeight(src,.68);o.position.set(p[0],gy+.9,p[1]);actors.add(o);pickups.push({kind,o,baseY:o.position.y,phase:i*.4,alive:true})});window.__coinSeed=10;window.__gemSeed=10;coinsEl.textContent='COINS · 0 / 10';gemsEl.textContent='GEMS · 0 / 10'}

let tube,transition;function createTube(){progress('Installing the refined advanced tube…',66);tube=createAdvancedTube(THREE,{mobile});tube.root.position.copy(tubePos);tube.root.userData.component=ADVANCED_TUBE_ID;world.add(tube.root);window.__advancedTubeReady=true;window.__advancedTubeComponent=ADVANCED_TUBE_ID;window.__tubePosition={x:tubePos.x,y:tubePos.y,z:tubePos.z}}

const inp={x:0,y:0,run:false},keys={};let stickPointer=null,vy=0,grounded=true,camYaw=Math.PI,camPitch=.34,camDist=10.6,lookPointer=null,lastX=0,lastY=0,lastLook=0;function setStick(x,y){const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,lim=r.width*.34;let dx=x-cx,dy=y-cy,d=Math.hypot(dx,dy);if(d>lim){dx=dx/d*lim;dy=dy/d*lim}const nx=dx/lim,ny=-dy/lim,mag=Math.hypot(nx,ny);if(mag<.11){inp.x=inp.y=0}else{const k=(mag-.11)/.89/mag;inp.x=nx*k;inp.y=ny*k}stick.style.transform=`translate3d(${dx}px,${dy}px,0)`}function clearStick(){stickPointer=null;inp.x=inp.y=0;stick.style.transform='translate3d(0,0,0)'}pad.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();stickPointer=e.pointerId;pad.setPointerCapture?.(e.pointerId);setStick(e.clientX,e.clientY)});pad.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer){e.preventDefault();setStick(e.clientX,e.clientY)}});pad.addEventListener('pointerup',e=>{if(e.pointerId===stickPointer)clearStick()});pad.addEventListener('pointercancel',clearStick);runBtn.onpointerdown=e=>{e.preventDefault();inp.run=true};runBtn.onpointerup=runBtn.onpointercancel=runBtn.onpointerleave=()=>inp.run=false;function jump(){if(grounded&&transition?.state.phase==='idle'){vy=8.9;grounded=false}}jumpBtn.onpointerdown=e=>{e.preventDefault();jump()};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'){e.preventDefault();jump()}if(e.code==='KeyE')fire()});addEventListener('keyup',e=>keys[e.code]=false);
const pinch=new Map();canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){pinch.set(e.pointerId,[e.clientX,e.clientY]);if(pinch.size===1){lookPointer=e.pointerId;lastX=e.clientX;lastY=e.clientY}return}lookPointer=e.pointerId;lastX=e.clientX;lastY=e.clientY});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'&&pinch.has(e.pointerId)){pinch.set(e.pointerId,[e.clientX,e.clientY]);if(pinch.size===2){const a=[...pinch.values()],d=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);if(canvas._pd)camDist=THREE.MathUtils.clamp(canvas._base-(d-canvas._pd)*.007,7.8,13);else{canvas._pd=d;canvas._base=camDist}return}}if(e.pointerId!==lookPointer||pinch.size>1)return;camYaw-=(e.clientX-lastX)*.0019;camPitch=THREE.MathUtils.clamp(camPitch+(e.clientY-lastY)*.00145,.18,.56);lastX=e.clientX;lastY=e.clientY;lastLook=performance.now()});function endLook(e){pinch.delete(e.pointerId);canvas._pd=0;if(e.pointerId===lookPointer)lookPointer=null}canvas.addEventListener('pointerup',endLook);canvas.addEventListener('pointercancel',endLook);

const starShape=new THREE.Shape();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?.42:1,x=Math.cos(a)*r,y=Math.sin(a)*r;i?starShape.lineTo(x,y):starShape.moveTo(x,y)}starShape.closePath();const starGeo=new THREE.ShapeGeometry(starShape),shotColors=[0xff70c9,0x6fe7ff,0xffd45e,0xa879ff,0x77eda4],shots=[];let actionUntil=0;function facing(){return new THREE.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y)).normalize()}function targetForAction(){const f=facing(),near=[];for(const e of enemies){if(!e.alive)continue;const d=e.o.position.clone().sub(player.position),dist=Math.hypot(d.x,d.z);d.y=0;if(dist<.01)continue;d.normalize();const dot=f.dot(d);if(dist<5.2||(dist<10&&dot>.18))near.push({e,score:dist-dot*2.4})}near.sort((a,b)=>a.score-b.score);return near[0]?.e||null}function fire(){if(!player||transition?.state.phase!=='idle')return;actionUntil=performance.now()+220;const target=targetForAction(),dir=target?target.o.position.clone().sub(player.position).setY(0).normalize():facing(),origin=player.position.clone().add(new THREE.Vector3(0,1.5,0));for(let i=0;i<5;i++){const o=new THREE.Mesh(starGeo,new THREE.MeshBasicMaterial({color:shotColors[i],side:THREE.DoubleSide,transparent:true,opacity:.97,depthWrite:false}));o.scale.setScalar(.24);o.position.copy(origin);fx.add(o);shots.push({o,v:dir.clone().applyAxisAngle(new THREE.Vector3(0,1,0),(i-2)*.045).multiplyScalar(12),life:.75})}if(target)setTimeout(()=>defeatEnemy(target),135);else{let best=null,bd=4.3;for(const c of crates){if(!c.alive)continue;const d=Math.hypot(c.x-player.position.x,c.z-player.position.z);if(d<bd){best=c;bd=d}}if(best)setTimeout(()=>breakCrate(best),120)}window.__powerCount=(window.__powerCount||0)+1;}
actionBtn.onpointerdown=e=>{e.preventDefault();fire()};

const camRay=new THREE.Raycaster(),camDir=new THREE.Vector3();function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize,{passive:true});resize();let last=performance.now(),animT=0;const dir=new THREE.Vector3(),fwd=new THREE.Vector3(),right=new THREE.Vector3(),look=new THREE.Vector3(),desired=new THREE.Vector3();
function updateCamera(dt){look.set(player.position.x,player.position.y+1.5,player.position.z);desired.set(look.x+Math.sin(camYaw)*Math.cos(camPitch)*camDist,look.y+Math.sin(camPitch)*camDist+1.2,look.z+Math.cos(camYaw)*Math.cos(camPitch)*camDist);camDir.copy(desired).sub(look);const len=camDir.length();camDir.normalize();camRay.set(look,camDir);camRay.far=len;const hits=camRay.intersectObjects(cameraOccluders,true);if(hits.length){const safe=Math.max(4.6,hits[0].distance-.45);desired.copy(look).addScaledVector(camDir,safe);desired.y+=.7}camera.position.lerp(desired,1-Math.exp(-dt*5.6));camera.lookAt(look)}
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,(now-last)/1000);last=now;animT+=dt;if(!player){renderer.render(scene,camera);return}const free=transition?.state.phase==='idle';let ix=inp.x+(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),iy=inp.y+(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),mag=Math.min(1,Math.hypot(ix,iy)),running=inp.run||keys.ShiftLeft||keys.ShiftRight;if(mag>.04&&free){const l=Math.hypot(ix,iy);ix/=l;iy/=l;fwd.set(-Math.sin(camYaw),0,-Math.cos(camYaw));right.set(Math.cos(camYaw),0,-Math.sin(camYaw));dir.copy(fwd).multiplyScalar(iy).addScaledVector(right,ix).normalize();const speed=running?7.55:5.15,dx=dir.x*speed*mag*dt,dz=dir.z*speed*mag*dt;let nx=player.position.x+dx,nz=player.position.z;if(groundY(nx,nz)!=null&&!blocked(nx,nz))player.position.x=nx;nx=player.position.x;nz=player.position.z+dz;if(groundY(nx,nz)!=null&&!blocked(nx,nz))player.position.z=nz;const gy=groundY(player.position.x,player.position.z);if(gy!=null&&grounded)player.position.y=THREE.MathUtils.lerp(player.position.y,gy+.04,1-Math.exp(-dt*12));const target=Math.atan2(dir.x,dir.z),diff=Math.atan2(Math.sin(target-player.rotation.y),Math.cos(target-player.rotation.y));player.rotation.y+=diff*(1-Math.exp(-dt*9));if(now-lastLook>1350){const follow=target+Math.PI,cd=Math.atan2(Math.sin(follow-camYaw),Math.cos(follow-camYaw));camYaw+=cd*(1-Math.exp(-dt*.95))}}
  if(free){vy-=18*dt;player.position.y+=vy*dt;const gy=groundY(player.position.x,player.position.z);if(gy!=null&&player.position.y<=gy+.04&&vy<=0){player.position.y=gy+.04;vy=0;grounded=true}else grounded=false;if(player.position.y<-5){player.position.copy(spawn);vy=0;grounded=true;toast('BACK TO THE GARDEN')}}
  const motion=free&&mag>.04?(running||mag>.72?'run':'walk'):'idle';adapter.setMotion(motion);adapter.setAction(now<actionUntil);adapter.update(animT,dt,now<actionUntil?1:0);window.__heroMotion=motion;
  for(const e of enemies){if(!e.alive)continue;e.mixer?.update(dt);const t=now*.001+e.phase;e.o.rotation.y+=dt*.18;if(e.name==='GHOST')e.o.position.y=e.home.y+Math.sin(t*1.7)*.14}
  for(const p of pickups){if(!p.alive)continue;p.phase+=dt;p.o.rotation.y+=dt*2;p.o.position.y=p.baseY+Math.sin(p.phase*2.5)*.1;if(Math.hypot(p.o.position.x-player.position.x,p.o.position.z-player.position.z)<1.15){p.alive=false;p.o.visible=false;if(p.kind==='coin'){coins++;coinsEl.textContent=`COINS · ${coins} / 10`}else{gems++;gemsEl.textContent=`GEMS · ${gems} / 10`}window.__pickupCounts={coins,gems}}}
  for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.life-=dt;s.o.position.addScaledVector(s.v,dt);s.o.rotation.z+=dt*9;if(s.life<=0){fx.remove(s.o);shots.splice(i,1)}}for(let i=fx.children.length-1;i>=0;i--){const o=fx.children[i];if(!o.userData.life)continue;o.userData.life-=dt;o.userData.v.y-=6*dt;o.position.addScaledVector(o.userData.v,dt);o.material.opacity=Math.max(0,o.userData.life/.55);if(o.userData.life<=0)fx.remove(o)}
  transition?.update(now,dt);updateCamera(dt);window.__frameCount=(window.__frameCount||0)+1;window.__moveDebug={x:player.position.x,y:player.position.y,z:player.position.z,mag,motion,blocked:blocked(player.position.x,player.position.z)};renderer.render(scene,camera)}

(async()=>{try{await buildWorld();await createPlayer();await createEnemies();createCrates();createPickups();createTube();progress('Prewarming tube dissolve and transfer shaders…',78);transition=createTubeTransition(THREE,{renderer,scene,camera,player,visual,tube,tubePos,mobile,onTransfer:()=>{window.__tubeTransferComplete=true;if(qp.get('smoke')==='1'){toast('TUBE TRANSFER TEST COMPLETE');return}const hero=encodeURIComponent(id);location.href=`../hybrid-v09/?from=kenney-gardens&hero=${hero}&portal=prewarmed`;}});requestAnimationFrame(frame);await transition.prewarm();progress('Ready — tube is online now. Enemies are optional.',100);objective.textContent='ADVANCED TUBE ONLINE · ENEMIES OPTIONAL · EXPLORE THE GARDENS';window.__pass7Ready=true;window.__pass7World='kenney-gardens';window.__portalRequiresEnemies=false;setTimeout(()=>boot.classList.add('hide'),220)}catch(e){console.error(e);errorEl.textContent=String(e?.message||e);fatal.classList.add('show')}})();
