import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createGamerBro} from '../playground-v2/gamer-bro.js?v=pass2-4';

const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const CHAR={
  gb1:{name:'GB1',kind:'gamer',colorway:'pink',accent:0xff58b7,power:'star'},
  gb2:{name:'GB2',kind:'gamer',colorway:'teal',accent:0x58e2e0,power:'star'},
  citrus:{name:'Citrus',kind:'glb',file:'../pass1-v1/assets/recovered/characters/sprite_hero.glb',accent:0xff9a3d,power:'star'},
  ghost:{name:'Ghost',kind:'glb',file:'../pass1-v1/assets/recovered/characters/ghost.glb',accent:0xf1a0d4,power:'wave',metalPink:true},
  stump:{name:'Stump',kind:'glb',file:'../pass1-v1/assets/recovered/characters/stump.glb',accent:0x92d56d,power:'wave'},
  cthulhu:{name:'Cthulhu',kind:'glb',file:'../pass1-v1/assets/recovered/characters/cthulhu.glb',accent:0xa66cff,power:'orb'},
  yeti:{name:'Yeti',kind:'glb',file:'../pass1-v1/assets/recovered/characters/yeti.glb',accent:0xbcefff,power:'orb'}
};
const alias={hero:'gb2',sprite_hero:'citrus',ghost_glb:'ghost'};
const qs=new URLSearchParams(location.search);let id=alias[qs.get('hero')]||qs.get('hero')||alias[localStorage.getItem('gamerBroCharacter')]||localStorage.getItem('gamerBroCharacter')||'gb2';if(!CHAR[id])id='gb2';const H=CHAR[id];localStorage.setItem('gamerBroCharacter',id);
const $=s=>document.querySelector(s),canvas=$('#c'),pad=$('#pad'),stick=$('#stick'),runBtn=$('#run'),jumpBtn=$('#jump'),actionBtn=$('#action'),modeBtn=$('#mode'),boot=$('#boot'),status=$('#status'),bar=$('#bar'),fatal=$('#fatal'),err=$('#err'),zoneEl=$('#zone');$('#heroName').textContent=H.name.toUpperCase();$('#menu').onclick=()=>location.href='../';
const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.2:1.55));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8fc7df);scene.fog=new THREE.Fog(0x8fc7df,48,115);const camera=new THREE.PerspectiveCamera(50,1,.08,180);camera.layers.enable(1);const world=new THREE.Group(),decor=new THREE.Group(),fxRoot=new THREE.Group();scene.add(world,decor,fxRoot);scene.add(new THREE.HemisphereLight(0xf1fbff,0x31523e,2));const sun=new THREE.DirectionalLight(0xffe9c5,3.2);sun.position.set(-20,30,16);sun.castShadow=true;scene.add(sun);const pinkRim=new THREE.DirectionalLight(0xff8fd3,.45);pinkRim.position.set(-15,9,12);scene.add(pinkRim);const loader=new GLTFLoader();
const mat=(color,rough=.9)=>new THREE.MeshStandardMaterial({color,roughness:rough});function add(g,m,p=[0,0,0],r=[0,0,0],s=[1,1,1],parent=world){const o=new THREE.Mesh(g,m);o.position.set(...p);o.rotation.set(...r);o.scale.set(...s);o.castShadow=!mobile;o.receiveShadow=true;parent.add(o);return o}
add(new THREE.BoxGeometry(52,1.4,82),mat(0x675c46),[0,-.72,-8]);add(new THREE.BoxGeometry(50,.28,80),mat(0x70ad54),[0,-.14,-8]);const pathMat=mat(0xbba97d,1);for(let z=27;z>-48;z-=3.7){const x=Math.sin(z*.15)*2.2;add(new THREE.BoxGeometry(5.1,.07,3),pathMat,[x,.045,z],[0,Math.sin(z*.09)*.08,0]);}
function tree(x,z,c=0x46945b,s=1){const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(s);decor.add(g);add(new THREE.CylinderGeometry(.27,.43,3.7,8),mat(0x825536),[0,1.85,0],[0,0,0],[1,1,1],g);const lm=mat(c);for(const [x1,y1,z1,k] of [[0,3.8,0,1.15],[-.65,3.5,.1,.8],[.68,3.55,.05,.82],[0,4.35,-.1,.7]])add(new THREE.IcosahedronGeometry(.9,1),lm,[x1,y1,z1],[0,0,0],[k,k,k],g)}
for(const p of[[-19,22,0x45a36a,1],[-16,12,0x45a36a,.9],[-5,19,0x45a36a,.9],[19,-16,0x7ca943,1],[17,-29,0x7ca943,.9],[2,-25,0x7ca943,.9],[18,-40,0x7ca943,1]])tree(...p);for(let i=0;i<14;i++){const t=i/13;add(new THREE.BoxGeometry(1.2,.2,1.8),mat(0x8c603c),[-4.5+9*t,.18+Math.sin(Math.PI*t)*.17,1-11*t],[0,-.68,0]);}
function label(text,x,z,color){const c=document.createElement('canvas');c.width=512;c.height=128;const x2=c.getContext('2d');x2.fillStyle='rgba(7,16,26,.8)';x2.roundRect(8,8,496,112,24);x2.fill();x2.strokeStyle=color;x2.lineWidth=5;x2.stroke();x2.fillStyle='#fff';x2.font='900 42px system-ui';x2.textAlign='center';x2.textBaseline='middle';x2.fillText(text,256,64);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.position.set(x,3.8,z);s.scale.set(7.2,1.8,1);decor.add(s)}label('KAYKIT GARDENS',-10,18,'#70ecbf');label('KENNEY SKY RUINS',10,-25,'#ffd76b');
const cache=new Map();async function asset(url){if(cache.has(url))return cache.get(url);const g=await loader.loadAsync(url),r=g.scene;cache.set(url,r);return r}function fitClone(src,pos,width){const o=src.clone(true);o.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(o),s=b.getSize(new THREE.Vector3()),k=width/Math.max(s.x,s.z,.001);o.scale.setScalar(k);o.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(o);const c=b.getCenter(new THREE.Vector3());o.position.set(pos[0]-c.x,pos[1]-b.min.y,pos[2]-c.z);o.traverse(q=>{if(q.isMesh){q.castShadow=!mobile;q.receiveShadow=true}});decor.add(o);return o}let kitCount=0;async function loadKits(){const KAY='https://raw.githubusercontent.com/KayKit-Game-Assets/KayKit-Prototype-Bits-1.0/main/addons/kaykit_prototype_bits/Assets/gltf/',KEN='https://raw.githubusercontent.com/KenneyNL/Starter-Kit-3D-Platformer/main/models/';try{const[f,st,w]=await Promise.all([asset(KAY+'Floor.gltf'),asset(KAY+'Primitive_Stairs.gltf'),asset(KAY+'Primitive_Wall.gltf')]);for(const p of[[-11,.03,20],[-6,.03,16],[-15,.03,12],[-8,.03,8]]){fitClone(f,p,7);kitCount++}fitClone(st,[-12,.03,3],5);fitClone(w,[-18,.03,15],5);kitCount+=2}catch(e){console.warn('KayKit optional load',e)}try{const[p,m,l,r]=await Promise.all([asset(KEN+'platform.glb'),asset(KEN+'platform-medium.glb'),asset(KEN+'platform-large.glb'),asset(KEN+'platform-grass-large-round.glb')]);fitClone(r,[10,.03,-15],9);fitClone(l,[12,.03,-24],10);fitClone(m,[7,.03,-33],7);for(const q of[[4,.03,-18],[16,.03,-19],[5,.03,-29],[15,.03,-31],[9,.03,-40]])fitClone(p,q,4);kitCount+=8}catch(e){console.warn('Kenney optional load',e)}window.__environmentAssets=kitCount;status.textContent=`Ready · ${kitCount} imported kit pieces`;bar.style.width='100%'}
function metallicGhost(root){root.traverse(o=>{if(!o.isMesh||!o.material)return;const a=Array.isArray(o.material)?o.material:[o.material];const b=a.map(src=>{const m=src.clone();if(m.color&&!/eye|pupil/i.test(o.name||'')){const c=m.color,lum=.21*c.r+.72*c.g+.07*c.b;if(lum>.08){m.color.set(0xf0a0d2);if('metalness'in m)m.metalness=.78;if('roughness'in m)m.roughness=.13;if('clearcoat'in m){m.clearcoat=1;m.clearcoatRoughness=.05}if(m.emissive){m.emissive.set(0x55183e);m.emissiveIntensity=.3}}}return m});o.material=Array.isArray(o.material)?b:b[0]});const l=new THREE.PointLight(0xff9adb,2.5,5,2);l.position.set(-.7,2.1,1.1);root.add(l)}
let player=new THREE.Group(),visual=null,adapter=null,mixer=null;player.position.set(0,.02,25);world.add(player);async function buildPlayer(){if(H.kind==='gamer'){adapter=createGamerBro(THREE,renderer,{colorway:H.colorway,detail:mobile?'low':'high',height:2.62});visual=adapter.root;adapter.setHome(0,0,0);adapter.setMotion('idle');player.add(visual)}else{const g=await loader.loadAsync(H.file);visual=g.scene;visual.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(visual),s=b.getSize(new THREE.Vector3()),k=2.55/Math.max(s.y,.001);visual.scale.setScalar(k);visual.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(visual);const c=b.getCenter(new THREE.Vector3());visual.position.set(-c.x,-b.min.y,-c.z);if(H.metalPink)metallicGhost(visual);player.add(visual);if(g.animations?.length){mixer=new THREE.AnimationMixer(visual);const clip=g.animations.find(a=>/walk|run/i.test(a.name))||g.animations.find(a=>/idle/i.test(a.name))||g.animations[0];mixer.clipAction(clip).play()}}visual.traverse(o=>{if(o.isMesh){o.castShadow=!mobile;o.receiveShadow=true}});let n=0;visual.traverse(o=>{if(o.isMesh&&camera.layers.test(o.layers))n++});window.__characterMeshCount=n;window.__characterReady=id}
const input={x:0,y:0,run:false},keys={};window.__gbInput=input;addEventListener('keydown',e=>{keys[e.code]=true});addEventListener('keyup',e=>{keys[e.code]=false});let activePointer=null;function joy(x,y){const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,L=r.width*.34;let dx=x-cx,dy=y-cy,d=Math.hypot(dx,dy);if(d>L){dx=dx/d*L;dy=dy/d*L}input.x=dx/L;input.y=-dy/L;stick.style.transform=`translate3d(${dx}px,${dy}px,0)`;window.__inputState={x:input.x,y:input.y}}
function release(){activePointer=null;input.x=input.y=0;stick.style.transform='translate3d(0,0,0)';window.__inputState={x:0,y:0}}
pad.addEventListener('pointerdown',e=>{e.preventDefault();activePointer=e.pointerId;pad.setPointerCapture?.(e.pointerId);joy(e.clientX,e.clientY)},{passive:false});pad.addEventListener('pointermove',e=>{if(e.pointerId===activePointer){e.preventDefault();joy(e.clientX,e.clientY)}},{passive:false});pad.addEventListener('pointerup',e=>{if(e.pointerId===activePointer)release()});pad.addEventListener('pointercancel',release);pad.addEventListener('touchstart',e=>{if(e.touches[0]){e.preventDefault();joy(e.touches[0].clientX,e.touches[0].clientY)}},{passive:false});pad.addEventListener('touchmove',e=>{if(e.touches[0]){e.preventDefault();joy(e.touches[0].clientX,e.touches[0].clientY)}},{passive:false});pad.addEventListener('touchend',e=>{if(!e.touches.length)release()},{passive:false});
runBtn.onpointerdown=e=>{e.preventDefault();input.run=true;runBtn.classList.add('active')};runBtn.onpointerup=runBtn.onpointercancel=runBtn.onpointerleave=()=>{input.run=false;runBtn.classList.remove('active')};let vy=0,grounded=true;jumpBtn.onpointerdown=e=>{e.preventDefault();if(grounded){vy=7.6;grounded=false}jumpBtn.classList.add('active')};jumpBtn.onpointerup=jumpBtn.onpointercancel=()=>jumpBtn.classList.remove('active');
let mode='unique',powerFlash=0,effects=[];const modes=['unique','star','orb','wave'];modeBtn.onclick=()=>{mode=modes[(modes.indexOf(mode)+1)%modes.length];modeBtn.querySelector('strong').textContent=mode.toUpperCase()};function fwd(){return new THREE.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y))}function pushFx(o,life,v){fxRoot.add(o);effects.push({o,life,v});window.__powerCount=(window.__powerCount||0)+1}function fire(){const p=mode==='unique'?H.power:mode,d=fwd(),base=player.position.clone().add(new THREE.Vector3(0,1.35,0)).addScaledVector(d,1);if(p==='star'){const sh=new THREE.Shape();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?.45:1,x=Math.cos(a)*r,y=Math.sin(a)*r;i?sh.lineTo(x,y):sh.moveTo(x,y)}sh.closePath();const cols=id==='citrus'?[0xff4fa3,0xffb33f,0x79e6ff,0xa875ff,0x75f09f]:[H.accent,0xffffff,0xff70c9,0xffc85b];for(let i=0;i<5;i++){const o=new THREE.Mesh(new THREE.ShapeGeometry(sh),new THREE.MeshBasicMaterial({color:cols[i],side:THREE.DoubleSide,transparent:true}));o.scale.setScalar(.17+i*.025);o.position.copy(base);pushFx(o,1.1,d.clone().add(new THREE.Vector3((i-2)*.05,0,0)).normalize().multiplyScalar(10))}}else if(p==='orb'){const o=new THREE.Mesh(new THREE.SphereGeometry(.36,18,14),new THREE.MeshStandardMaterial({color:H.accent,emissive:H.accent,emissiveIntensity:4}));o.position.copy(base);pushFx(o,1.4,d.clone().multiplyScalar(8.5))}else{const g=new THREE.Group();for(let i=0;i<3;i++){const o=new THREE.Mesh(new THREE.TorusGeometry(1+i*.18,.06,8,56),new THREE.MeshBasicMaterial({color:id==='ghost'?(i===0?0xff9bd7:i===1?0xffffff:0x7eeaff):H.accent,transparent:true,opacity:.7}));o.rotation.x=Math.PI/2;g.add(o)}g.position.copy(player.position);g.position.y=.1;pushFx(g,.9,new THREE.Vector3())}powerFlash=1;try{adapter?.setAction?.(true);setTimeout(()=>adapter?.setAction?.(false),220)}catch{}}
actionBtn.onpointerdown=e=>{e.preventDefault();actionBtn.classList.add('active');fire()};actionBtn.onpointerup=actionBtn.onpointercancel=()=>actionBtn.classList.remove('active');addEventListener('keydown',e=>{if(e.code==='Space'&&grounded){vy=7.6;grounded=false}if(e.code==='KeyE')fire()});
let camYaw=0,camPitch=.34,camDist=7.5,lookId=null,lx=0,ly=0;canvas.addEventListener('pointerdown',e=>{lookId=e.pointerId;lx=e.clientX;ly=e.clientY});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==lookId)return;camYaw-=(e.clientX-lx)*.006;camPitch=THREE.MathUtils.clamp(camPitch+(e.clientY-ly)*.004,.12,.72);lx=e.clientX;ly=e.clientY});canvas.addEventListener('pointerup',()=>lookId=null);canvas.addEventListener('pointercancel',()=>lookId=null);
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize,{passive:true});resize();
let last=performance.now(),elapsed=0;const dir=new THREE.Vector3(),look=new THREE.Vector3(),cam=new THREE.Vector3();function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,(now-last)/1000);last=now;elapsed+=dt;window.__frameCount=(window.__frameCount||0)+1;let x=input.x+((keys.KeyD||keys.ArrowRight)?1:0)-((keys.KeyA||keys.ArrowLeft)?1:0),y=input.y+((keys.KeyW||keys.ArrowUp)?1:0)-((keys.KeyS||keys.ArrowDown)?1:0);const mag=Math.min(1,Math.hypot(x,y));if(mag>.01){const len=Math.hypot(x,y)||1;x/=len;y/=len;const forward=new THREE.Vector3(-Math.sin(camYaw),0,-Math.cos(camYaw)),right=new THREE.Vector3(Math.cos(camYaw),0,-Math.sin(camYaw));dir.copy(forward).multiplyScalar(y).addScaledVector(right,x).normalize();player.position.addScaledVector(dir,(input.run||keys.ShiftLeft||keys.ShiftRight?7.3:4.5)*mag*dt);player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,Math.atan2(dir.x,dir.z),1-Math.exp(-dt*12))}player.position.x=THREE.MathUtils.clamp(player.position.x,-23,23);player.position.z=THREE.MathUtils.clamp(player.position.z,-47,29);vy-=18.5*dt;player.position.y+=vy*dt;if(player.position.y<=.02){player.position.y=.02;vy=0;grounded=true}else grounded=false;window.__playerPosition={x:player.position.x,y:player.position.y,z:player.position.z};window.__movementMagnitude=mag;powerFlash=Math.max(0,powerFlash-dt*2.5);try{if(adapter){adapter.setMotion(mag>.05?(input.run?'run':'walk'):'idle');adapter.update(elapsed,dt,powerFlash)}}catch(e){window.__adapterError=String(e?.message||e)}try{mixer?.update(dt*(mag>.05?1.25:.7))}catch{}const zone=player.position.z>2?'KAYKIT GARDENS':player.position.z>-11?'BRIDGE · MIX ZONE':'KENNEY SKY RUINS';zoneEl.textContent=zone;look.set(player.position.x,player.position.y+1.35,player.position.z);cam.set(look.x+Math.sin(camYaw)*Math.cos(camPitch)*camDist,look.y+Math.sin(camPitch)*camDist+1,look.z+Math.cos(camYaw)*Math.cos(camPitch)*camDist);camera.position.lerp(cam,1-Math.exp(-dt*8));camera.lookAt(look);for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;if(e.v.lengthSq())e.o.position.addScaledVector(e.v,dt);else{const s=1+dt*4;e.o.scale.multiplyScalar(s);e.o.traverse(q=>{if(q.material?.opacity!=null)q.material.opacity=Math.max(0,e.life/.9*.7)})}if(e.life<=0){fxRoot.remove(e.o);effects.splice(i,1)}}renderer.render(scene,camera)}
(async()=>{try{status.textContent='Loading your character…';bar.style.width='25%';await buildPlayer();window.__pass2Ready=true;status.textContent='Playable · environment details loading…';bar.style.width='65%';requestAnimationFrame(frame);setTimeout(()=>boot.classList.add('hide'),120);loadKits();}catch(e){console.error(e);err.textContent=String(e?.message||e);fatal.classList.add('show')}})();
