import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createGamerBro} from '../playground-v2/gamer-bro.js?v=pass2-3';

const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const CHAR={
 gb1:{name:'GB1',accent:0xff58b7,power:'star',kind:'gamer',colorway:'pink'},
 gb2:{name:'GB2',accent:0x58e2e0,power:'star',kind:'gamer',colorway:'teal'},
 citrus:{name:'Citrus',accent:0xff9a3d,power:'star',kind:'glb',file:'../pass1-v1/assets/recovered/characters/sprite_hero.glb'},
 ghost:{name:'Ghost',accent:0xf2a0d4,power:'wave',kind:'glb',file:'../pass1-v1/assets/recovered/characters/ghost.glb',metalPink:true},
 stump:{name:'Stump',accent:0x92d56d,power:'wave',kind:'glb',file:'../pass1-v1/assets/recovered/characters/stump.glb'},
 cthulhu:{name:'Cthulhu',accent:0xa66cff,power:'orb',kind:'glb',file:'../pass1-v1/assets/recovered/characters/cthulhu.glb'},
 yeti:{name:'Yeti',accent:0xbcefff,power:'orb',kind:'glb',file:'../pass1-v1/assets/recovered/characters/yeti.glb'}
};
const aliases={hero:'gb2',sprite_hero:'citrus',ghost_glb:'ghost'};
const q=new URLSearchParams(location.search);let chosen=q.get('hero')||localStorage.getItem('gamerBroCharacter')||'gb2';chosen=aliases[chosen]||chosen;const id=CHAR[chosen]?chosen:'gb2',H=CHAR[id];localStorage.setItem('gamerBroCharacter',id);
const $=s=>document.querySelector(s),canvas=$('#c'),heroName=$('#heroName'),menu=$('#menu'),zoneEl=$('#zone'),modeBtn=$('#mode'),pad=$('#pad'),stick=$('#stick'),jumpBtn=$('#jump'),runBtn=$('#run'),actionBtn=$('#action'),boot=$('#boot'),status=$('#status'),bar=$('#bar'),fatal=$('#fatal'),err=$('#err');heroName.textContent=H.name.toUpperCase();menu.onclick=()=>location.href='../';
const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.2:1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x88bdd8);scene.fog=new THREE.Fog(0x88bdd8,52,118);const camera=new THREE.PerspectiveCamera(50,1,.08,180);camera.layers.enable(1);const world=new THREE.Group(),decor=new THREE.Group(),effects=new THREE.Group();scene.add(world,decor,effects);scene.add(new THREE.HemisphereLight(0xedfbff,0x31503c,1.95));const sun=new THREE.DirectionalLight(0xffe7bd,3.15);sun.position.set(-20,31,19);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:1536,mobile?1024:1536);sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;sun.shadow.camera.near=1;sun.shadow.camera.far=115;scene.add(sun);const fill=new THREE.DirectionalLight(0x9bd9ff,.6);fill.position.set(19,12,-20);scene.add(fill);const pinkFill=new THREE.DirectionalLight(0xff9bd8,.34);pinkFill.position.set(-15,8,14);scene.add(pinkFill);const loader=new GLTFLoader();
function progress(text,n){status.textContent=text;bar.style.width=n+'%'}function shadows(root,cast=true){root.traverse?.(o=>{if(o.isMesh){o.castShadow=cast;o.receiveShadow=true;}});return root}function mesh(g,m,p=[0,0,0],r=[0,0,0],s=[1,1,1],parent=world){const o=new THREE.Mesh(g,m);o.position.set(...p);o.rotation.set(...r);o.scale.set(...s);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
const grass=new THREE.MeshStandardMaterial({color:0x6dab53,roughness:.94}),earth=new THREE.MeshStandardMaterial({color:0x655b47,roughness:1}),stoneDark=new THREE.MeshStandardMaterial({color:0x52616d,roughness:.96}),wood=new THREE.MeshStandardMaterial({color:0x8a5b37,roughness:.92}),pathMat=new THREE.MeshStandardMaterial({color:0xb5a47d,roughness:1});
mesh(new THREE.BoxGeometry(52,1.4,82),earth,[0,-.72,-8]);mesh(new THREE.BoxGeometry(50,.28,80),grass,[0,-.14,-8]);for(let z=26;z>-47;z-=3.8){const x=Math.sin(z*.15)*2.4;mesh(new THREE.BoxGeometry(5.2,.08,3.0),pathMat,[x,.045,z],[0,Math.sin(z*.11)*.08,0]);}
function tree(x,z,kind='kay',s=1){const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(s);decor.add(g);mesh(new THREE.CylinderGeometry(.28,.44,3.8,8),wood,[0,1.9,0],[0,0,0],[1,1,1],g);const lm=new THREE.MeshStandardMaterial({color:kind==='kay'?0x43a66b:0x79a944,roughness:.9});for(const[ox,oy,oz,sc]of[[0,3.8,0,1.1],[-.68,3.48,.1,.78],[.67,3.55,.04,.82],[.02,4.38,-.1,.68]])mesh(new THREE.IcosahedronGeometry(.92,1),lm,[ox,oy,oz],[0,0,0],[sc,sc,sc],g);return g}
for(const p of[[-19,22,'kay',1],[-18,13,'kay',.9],[-5,21,'kay',.95],[-6,10,'kay',.82],[19,-16,'ken',1],[18,-28,'ken',.92],[2,-23,'ken',.86],[18,-39,'ken',1]])tree(...p);for(let i=0;i<18;i++){const side=i%2?-1:1,z=23-i*4,x=side*(9+(i%4)*2.3);mesh(new THREE.DodecahedronGeometry(.55+(i%3)*.11,0),stoneDark,[x,.35,z],[.2,i*.55,.12],[1.25,.7,1]);}
for(let i=0;i<14;i++){const t=i/13,x=-4.7+9.4*t,z=1-11.5*t,y=.16+Math.sin(Math.PI*t)*.18;mesh(new THREE.BoxGeometry(1.18,.20,1.85),wood,[x,y,z],[0,-.69,0]);}
function label(text,x,z,color){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='rgba(7,16,26,.78)';ctx.roundRect(8,8,496,112,24);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=5;ctx.stroke();ctx.fillStyle='#fff';ctx.font='900 42px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,64);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));sp.position.set(x,3.8,z);sp.scale.set(7.2,1.8,1);decor.add(sp)}label('KAYKIT GARDENS',-10,18,'#70ecbf');label('KENNEY SKY RUINS',10,-25,'#ffd76b');
const assetCache=new Map();async function asset(url){if(assetCache.has(url))return assetCache.get(url);const g=await loader.loadAsync(url),root=g.scene;shadows(root,!mobile);assetCache.set(url,root);return root}function cloneFit(src,{pos=[0,0,0],width=null,height=null,rotY=0,parent=decor}={}){const o=src.clone(true);o.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(o),sz=b.getSize(new THREE.Vector3()),k=1;if(width)k*=width/Math.max(sz.x,sz.z,.001);if(height)k*=height/Math.max(sz.y,.001);o.scale.setScalar(k);o.rotation.y=rotY;o.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(o);const ctr=b.getCenter(new THREE.Vector3());o.position.set(pos[0]-ctr.x,pos[1]-b.min.y,pos[2]-ctr.z);parent.add(o);return o}
const KAY='https://raw.githubusercontent.com/KayKit-Game-Assets/KayKit-Prototype-Bits-1.0/main/addons/kaykit_prototype_bits/Assets/gltf/',KEN='https://raw.githubusercontent.com/KenneyNL/Starter-Kit-3D-Platformer/main/models/';let environmentAssets=0;
async function buildKayKit(){try{const[floor,stairs,wall,coin,slope]=await Promise.all([asset(KAY+'Floor.gltf'),asset(KAY+'Primitive_Stairs.gltf'),asset(KAY+'Primitive_Wall.gltf'),asset(KAY+'Coin_A.gltf'),asset(KAY+'Primitive_Slope.gltf')]);for(const[x,z,r]of[[-11,20,0],[-6,17,.2],[-15,14,-.25],[-9,11,.15],[-16,8,.1],[-7,5,-.15]]){cloneFit(floor,{pos:[x,.03,z],width:7,rotY:r});environmentAssets++;}cloneFit(stairs,{pos:[-12,.03,2],width:5,rotY:Math.PI});environmentAssets++;cloneFit(slope,{pos:[-4,.03,4],width:6,rotY:.3});environmentAssets++;for(const[x,z,r]of[[-19,18,.2],[-18,9,-.15],[-4,15,0],[-3,7,.1]]){cloneFit(wall,{pos:[x,.03,z],width:4.6,rotY:r});environmentAssets++;}for(let i=0;i<8;i++){const o=cloneFit(coin,{pos:[-12+Math.sin(i*.7)*3.8,1.15,20-i*1.8],height:.75,rotY:i*.5});o.userData.spin=true;environmentAssets++;}}catch(e){console.warn('KayKit assets unavailable; fallback remains playable',e)}}
async function buildKenney(){try{const[plat,med,large,round,coin,flag,grassObj,brick]=await Promise.all([asset(KEN+'platform.glb'),asset(KEN+'platform-medium.glb'),asset(KEN+'platform-large.glb'),asset(KEN+'platform-grass-large-round.glb'),asset(KEN+'coin.glb'),asset(KEN+'flag.glb'),asset(KEN+'grass.glb'),asset(KEN+'brick.glb')]);cloneFit(round,{pos:[10,.03,-15],width:9});environmentAssets++;cloneFit(large,{pos:[12,.03,-24],width:10,rotY:.12});environmentAssets++;cloneFit(med,{pos:[7,.03,-33],width:7,rotY:-.12});environmentAssets++;for(const[x,z,w,r]of[[4,-18,4,.1],[16,-19,4,-.1],[5,-28,4,.2],[15,-31,4,-.2],[9,-39,4,.05]]){cloneFit(plat,{pos:[x,.03,z],width:w,rotY:r});environmentAssets++;}cloneFit(flag,{pos:[10,.03,-40],height:4});environmentAssets++;for(let i=0;i<10;i++){const o=cloneFit(coin,{pos:[8+Math.sin(i*.55)*4.6,1.2,-16-i*2.1],height:.8,rotY:i*.4});o.userData.spin=true;environmentAssets++;}for(let i=0;i<15;i++){cloneFit(grassObj,{pos:[2+(i%5)*3.2,.03,-13-Math.floor(i/5)*10],height:.5,rotY:i*.9});environmentAssets++;}for(let i=0;i<8;i++){cloneFit(brick,{pos:[15+(i%4)*1.35,.22,-35-Math.floor(i/4)*1.2],width:1.1,rotY:(i%2)*.05});environmentAssets++;}}catch(e){console.warn('Kenney assets unavailable; fallback remains playable',e)}}
function metallicPinkGhost(root){root.traverse(o=>{if(!o.isMesh||!o.material)return;const src=Array.isArray(o.material)?o.material:[o.material];const out=src.map(mat=>{const m=mat.clone();if(m.color){const c=m.color,lum=.2126*c.r+.7152*c.g+.0722*c.b;if(lum>.10&&!/eye|pupil/i.test(o.name||'')){m.color.set(0xf0a1d3);if('metalness'in m)m.metalness=.72;if('roughness'in m)m.roughness=.16;if(m.emissive){m.emissive.set(0x4d1439);m.emissiveIntensity=.38;}if('clearcoat'in m){m.clearcoat=1;m.clearcoatRoughness=.07;}if('envMapIntensity'in m)m.envMapIntensity=1.5;}}return m;});o.material=Array.isArray(o.material)?out:out[0];});const shine=new THREE.PointLight(0xff8fd5,2.3,5,2);shine.position.set(-.8,2.15,1.1);root.add(shine)}
let player=null,visual=null,adapter=null,mixer=null,elapsed=0;async function createPlayer(){player=new THREE.Group();player.position.set(0,.02,25);world.add(player);if(H.kind==='gamer'){adapter=createGamerBro(THREE,renderer,{colorway:H.colorway,detail:mobile?'low':'high',height:2.62});visual=adapter.root;adapter.setHome(0,0,0);adapter.setMotion('idle');player.add(visual);}else{const g=await loader.loadAsync(H.file);visual=g.scene;visual.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(visual),sz=b.getSize(new THREE.Vector3()),k=2.55/Math.max(sz.y,.001);visual.scale.setScalar(k);visual.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(visual);const ctr=b.getCenter(new THREE.Vector3());visual.position.set(-ctr.x,-b.min.y,-ctr.z);player.add(visual);if(H.metalPink)metallicPinkGhost(visual);if(g.animations?.length){mixer=new THREE.AnimationMixer(visual);const clip=g.animations.find(a=>/walk|run/i.test(a.name))||g.animations.find(a=>/idle/i.test(a.name))||g.animations[0];mixer.clipAction(clip).play();}}shadows(visual,!mobile);let visible=0;visual.traverse(o=>{if(o.isMesh&&camera.layers.test(o.layers))visible++});window.__characterMeshCount=visible;window.__characterReady=id;window.__playerPosition={x:player.position.x,z:player.position.z};}
const inp={x:0,y:0,run:false},keys={},sp=null;let vy=0,grounded=true,camYaw=0,camPitch=.34,camDist=7.4,lastLook=performance.now(),lookPointer=null,lastPX=0,lastPY=0,pinch=new Map();
function stickAt(e){const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,lim=r.width*.34;let x=e.clientX-cx,y=e.clientY-cy,d=Math.hypot(x,y);if(d>lim){x=x/d*lim;y=y/d*lim}inp.x=x/lim;inp.y=-y/lim;stick.style.transform=`translate3d(${x}px,${y}px,0)`;window.__inputState={x:inp.x,y:inp.y}}
function releaseStick(e){if(e&&sp!==null&&e.pointerId!==sp)return;sp=null;inp.x=inp.y=0;stick.style.transform='translate3d(0,0,0)';window.__inputState={x:0,y:0}}
pad.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();sp=e.pointerId;pad.setPointerCapture?.(e.pointerId);stickAt(e)},{passive:false});pad.addEventListener('pointermove',e=>{if(e.pointerId===sp){e.preventDefault();e.stopPropagation();stickAt(e)}},{passive:false});pad.addEventListener('pointerup',releaseStick,{passive:false});pad.addEventListener('pointercancel',releaseStick,{passive:false});
runBtn.onpointerdown=e=>{e.preventDefault();inp.run=true;runBtn.classList.add('active')};runBtn.onpointerup=runBtn.onpointercancel=runBtn.onpointerleave=()=>{inp.run=false;runBtn.classList.remove('active')};jumpBtn.onpointerdown=e=>{e.preventDefault();if(grounded){vy=7.6;grounded=false}jumpBtn.classList.add('active')};jumpBtn.onpointerup=jumpBtn.onpointercancel=()=>jumpBtn.classList.remove('active');addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'&&grounded){vy=7.6;grounded=false}if(e.code==='KeyE')fire()});addEventListener('keyup',e=>keys[e.code]=false);
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){pinch.set(e.pointerId,[e.clientX,e.clientY]);if(pinch.size===1){lookPointer=e.pointerId;lastPX=e.clientX;lastPY=e.clientY}return}lookPointer=e.pointerId;lastPX=e.clientX;lastPY=e.clientY;canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'){if(pinch.has(e.pointerId))pinch.set(e.pointerId,[e.clientX,e.clientY]);if(pinch.size===2){const a=[...pinch.values()],d=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);if(canvas._pd)camDist=THREE.MathUtils.clamp(canvas._base-(d-canvas._pd)*.012,4.6,11);else{canvas._pd=d;canvas._base=camDist}return}}if(e.pointerId!==lookPointer||pinch.size>1)return;camYaw-=(e.clientX-lastPX)*.0062;camPitch=THREE.MathUtils.clamp(camPitch+(e.clientY-lastPY)*.0045,.12,.72);lastPX=e.clientX;lastPY=e.clientY;lastLook=performance.now()});function endLook(e){pinch.delete(e.pointerId);canvas._pd=0;if(e.pointerId===lookPointer)lookPointer=null}canvas.addEventListener('pointerup',endLook);canvas.addEventListener('pointercancel',endLook);
let powerMode='unique',fx=[],powerFlash=0;const modes=['unique','star','orb','wave'];modeBtn.onclick=()=>{powerMode=modes[(modes.indexOf(powerMode)+1)%modes.length];modeBtn.querySelector('strong').textContent=powerMode.toUpperCase()};function forward(){return new THREE.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y))}function addFx(o,life,update){effects.add(o);fx.push({o,life,update});window.__powerCount=(window.__powerCount||0)+1}
function star(){const sh=new THREE.Shape();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?.43:1,x=Math.cos(a)*r,y=Math.sin(a)*r;i?sh.lineTo(x,y):sh.moveTo(x,y)}sh.closePath();const geo=new THREE.ShapeGeometry(sh),d=forward(),base=player.position.clone().add(new THREE.Vector3(0,1.35,0)).addScaledVector(d,1),cols=id==='citrus'?[0xff4fa3,0xffb33f,0x79e6ff,0xa875ff,0x75f09f]:[H.accent,0xff68cc,0xffc35a,0xffffff];for(let i=0;i<5;i++){const o=new THREE.Mesh(geo.clone(),new THREE.MeshBasicMaterial({color:cols[i%cols.length],side:THREE.DoubleSide,transparent:true})),v=new THREE.Vector3(d.x+(i-2)*.055,.025*(i-2),d.z).normalize();o.scale.setScalar(.16+i*.028);o.position.copy(base);addFx(o,1.15,(f,t,dt)=>{f.position.addScaledVector(v,dt*11);f.rotation.z+=dt*7;f.material.opacity=Math.max(0,t/.35)})}}
function orb(){const d=forward(),g=new THREE.Group(),o=new THREE.Mesh(new THREE.SphereGeometry(.34,18,14),new THREE.MeshStandardMaterial({color:H.accent,emissive:H.accent,emissiveIntensity:4.5,transparent:true}));g.add(o);for(let i=0;i<3;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(.52+i*.1,.024,8,44),new THREE.MeshBasicMaterial({color:i===1?0xffffff:H.accent,transparent:true,opacity:.8}));r.rotation.set(Math.PI/2,i*.7,i*.3);g.add(r)}g.position.copy(player.position).add(new THREE.Vector3(0,1.35,0)).addScaledVector(d,1);addFx(g,1.4,(f,t,dt)=>{f.position.addScaledVector(d,dt*9.2);f.rotation.y+=dt*5})}
function wave(){const g=new THREE.Group(),cols=id==='ghost'?[0xff9ed8,0xffffff,0x79efff]:id==='stump'?[0x74dd74,0xffd56c]:[H.accent,0xffffff];for(let i=0;i<3;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(1+i*.18,.06-i*.01,8,60),new THREE.MeshBasicMaterial({color:cols[i%cols.length],transparent:true,opacity:.72,depthWrite:false}));r.rotation.x=Math.PI/2;g.add(r)}g.position.copy(player.position);g.position.y=.12;addFx(g,.95,(f,t)=>{const a=1+(1-t/.95)*5.5;f.scale.setScalar(a);f.traverse(z=>{if(z.material)z.material.opacity=Math.max(0,t/.95*.72)})})}
function fire(){if(!player)return;const p=powerMode==='unique'?H.power:powerMode;p==='star'?star():p==='orb'?orb():wave();powerFlash=1;if(adapter?.setAction){adapter.setAction(true);setTimeout(()=>adapter?.setAction?.(false),240)}}actionBtn.onpointerdown=e=>{e.preventDefault();actionBtn.classList.add('active');fire()};actionBtn.onpointerup=actionBtn.onpointercancel=()=>actionBtn.classList.remove('active');
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize,{passive:true});resize();
let last=performance.now();const tmp=new THREE.Vector3(),desired=new THREE.Vector3(),look=new THREE.Vector3();function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,(now-last)/1000);last=now;elapsed+=dt;if(!player)return;let ix=inp.x+(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),iy=inp.y+(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),mag=Math.min(1,Math.hypot(ix,iy));if(mag>.001){const len=Math.max(1,Math.hypot(ix,iy));ix/=len;iy/=len;const f=new THREE.Vector3(-Math.sin(camYaw),0,-Math.cos(camYaw)),r=new THREE.Vector3(Math.cos(camYaw),0,-Math.sin(camYaw));tmp.copy(f).multiplyScalar(iy).addScaledVector(r,ix).normalize();const running=inp.run||keys.ShiftLeft||keys.ShiftRight,speed=running?7.3:4.5;player.position.addScaledVector(tmp,speed*mag*dt);const target=Math.atan2(tmp.x,tmp.z);player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,target,1-Math.exp(-dt*13));if(now-lastLook>850){const d=target+Math.PI,diff=Math.atan2(Math.sin(d-camYaw),Math.cos(d-camYaw));camYaw+=diff*(1-Math.exp(-dt*2.7))}}player.position.x=THREE.MathUtils.clamp(player.position.x,-23,23);player.position.z=THREE.MathUtils.clamp(player.position.z,-47,29);vy-=18.5*dt;player.position.y+=vy*dt;if(player.position.y<=.02){player.position.y=.02;vy=0;grounded=true}else grounded=false;powerFlash=Math.max(0,powerFlash-dt*2.5);if(adapter){adapter.setMotion(mag>.08?(inp.run||keys.ShiftLeft||keys.ShiftRight?'run':'walk'):'idle');adapter.update(elapsed,dt,powerFlash)}if(mixer)mixer.update(dt*(mag>.05?1.3:.72));if(visual&&!adapter&&!mixer&&mag>.05)visual.position.y=Math.sin(now*.012)*.025;const targetZone=player.position.z>2?'KAYKIT GARDENS':player.position.z>-11?'BRIDGE · MIX ZONE':'KENNEY SKY RUINS';if(zoneEl.textContent!==targetZone)zoneEl.textContent=targetZone;look.set(player.position.x,player.position.y+1.35,player.position.z);desired.set(look.x+Math.sin(camYaw)*Math.cos(camPitch)*camDist,look.y+Math.sin(camPitch)*camDist+1,look.z+Math.cos(camYaw)*Math.cos(camPitch)*camDist);camera.position.lerp(desired,1-Math.exp(-dt*8));camera.lookAt(look);for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.life-=dt;f.update?.(f.o,f.life,dt);if(f.life<=0){effects.remove(f.o);fx.splice(i,1)}}decor.traverse(o=>{if(o.userData?.spin)o.rotation.y+=dt*1.5});window.__playerPosition={x:player.position.x,z:player.position.z};renderer.render(scene,camera)}
(async()=>{try{progress('Loading your selected character…',20);await createPlayer();progress('Playable now · loading kit details in background…',62);window.__pass2Ready=true;requestAnimationFrame(frame);setTimeout(()=>boot.classList.add('hide'),120);Promise.allSettled([buildKayKit(),buildKenney()]).then(()=>{window.__environmentAssets=environmentAssets;window.__environmentSources={kaykit:true,kenney:true};progress(`Ready · ${environmentAssets} imported kit pieces`,100);});}catch(e){console.error(e);err.textContent=String(e?.message||e);fatal.classList.add('show')}})();
