import * as THREE from 'three';
import { createGamerBro } from '../playground-v2/gamer-bro.js?v=pass13';
import { createCrystalLibraryTubeV2 } from '../src/crystal-library-tube-v2.js?v=1';
import { createWorldSystem } from './world.js?v=13.1.0';
import { createAssetStreamer } from './assets.js?v=13.1.0';
import { createPowerSystem } from './powers.js?v=13.1.0';

window.__pass13ModuleStarted=true;window.__bootPhase='module-started';
const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const $=s=>document.querySelector(s),canvas=$('#game'),boot=$('#boot'),fatal=$('#fatal'),errorEl=$('#error'),statusEl=$('#status'),barEl=$('#bar'),objectiveEl=$('#objective'),heroNameEl=$('#heroName'),healthEl=$('#health'),coinsEl=$('#coins'),gemsEl=$('#gems'),toastEl=$('#toast'),pad=$('#pad'),stick=$('#stick'),jumpBtn=$('#jump'),runBtn=$('#run'),actionBtn=$('#action'),fxBtn=$('#fx'),menuBtn=$('#menu'),retryBtn=$('#retry');
const qp=new URLSearchParams(location.search),requested=qp.get('hero'),saved=localStorage.getItem('gamerBroCharacter'),heroId=requested==='gb1'||requested==='gb2'?requested:(saved==='gb1'||saved==='gb2'?saved:'gb2'),colorway=heroId==='gb1'?'pink':'teal';localStorage.setItem('gamerBroCharacter',heroId);heroNameEl.textContent=heroId.toUpperCase();menuBtn.onclick=()=>location.href='../';retryBtn.onclick=()=>location.reload();
const setPhase=(t,p)=>{window.__bootPhase=t;statusEl.textContent=t;barEl.style.width=`${p}%`};function toast(t,ms=1100){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),ms)}function fail(e){console.error(e);errorEl.textContent=`${e?.message||e||'Unknown startup failure'}\nPhase: ${window.__bootPhase||'unknown'}`;fatal.classList.add('show')}

const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,alpha:false,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=1.32;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1:1.35));renderer.shadowMap.enabled=!mobile;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x86c7df);scene.fog=new THREE.Fog(0xa9d6e2,72,168);const camera=new THREE.PerspectiveCamera(38,1,.12,220);camera.layers.enable(1);scene.add(new THREE.HemisphereLight(0xf0fbff,0x40573d,mobile?2:1.75));const sun=new THREE.DirectionalLight(0xffefd2,mobile?1.8:2.2);sun.position.set(-28,42,24);sun.castShadow=!mobile;if(!mobile){sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-65;sun.shadow.camera.right=65;sun.shadow.camera.top=65;sun.shadow.camera.bottom=-65;sun.shadow.camera.near=1;sun.shadow.camera.far=130;sun.shadow.bias=-.0002;sun.shadow.normalBias=.03}scene.add(sun);const rim=new THREE.DirectionalLight(0x7d73ff,.25);rim.position.set(28,20,-30);scene.add(rim);

const worldSys=createWorldSystem({scene,mobile,setPhase});const {world,mats,elev,routeX,buildWorld,groundAt,refreshBounds,zoneForZ,getBounds}=worldSys;let sites,bro=null,heroRoot=null,tube=null,tubeWarmPromise=null,tubeWarmReady=false;const heroBaseScale=new THREE.Vector3(1,1,1);
const player={x:0,y:0,z:0,yaw:Math.PI,vy:0,speed:0,grounded:true,jumpCount:0,holdJumpTimer:0,hearts:5,damageCooldown:0};const input={up:false,down:false,left:false,right:false,run:false,jump:false,jumpQueued:false},analog={x:0,y:0,active:false,pointerId:null};const WALK=9.375,RUN=15.875,GRAVITY=8.4,JUMP=5.15,DOUBLE=4.7,HOLD=3.95,HOLD_INTERVAL=.22,STEP=.95;
const checkpoints=[{z:25,x:routeX(25),y:elev(25)},{z:-24,x:routeX(-24),y:elev(-24)},{z:-60,x:routeX(-60),y:elev(-60)},{z:-100,x:routeX(-100),y:elev(-100)},{z:-143,x:routeX(-143),y:elev(-143)}];let checkpointIndex=0,coins=0,gems=0,springCooldown=0;
function updateHUD(){healthEl.textContent='♥'.repeat(Math.max(0,player.hearts))+'♡'.repeat(Math.max(0,5-player.hearts));coinsEl.textContent=String(coins);gemsEl.textContent=String(gems)}
function resetPlayer(death=false){const p=death?checkpoints[checkpointIndex]:{x:sites.spawn.x,z:sites.spawn.z,y:elev(sites.spawn.z)};player.x=p.x;player.z=p.z;player.y=(groundAt(player.x,player.z,false)??p.y)+.03;player.yaw=Math.PI;player.vy=0;player.speed=0;player.grounded=true;player.jumpCount=0;if(death)player.hearts=5;if(bro){bro.setMotion('idle');bro.setHome(player.x,player.z,player.yaw);heroRoot.position.y=player.y;heroRoot.scale.copy(heroBaseScale);bro.update(0,0,0)}updateHUD()}
async function createPlayer(){setPhase('Creating Gamer Bro…',48);bro=createGamerBro(THREE,renderer,{colorway,detail:mobile?'low':'high',height:2.62});heroRoot=bro.root;heroBaseScale.copy(heroRoot.scale);bro.all.forEach(m=>{m.layers.enable(0);m.layers.enable(1)});bro.setRoomLight(1);scene.add(heroRoot);resetPlayer(false);window.__characterReady=heroId}
function beginTubeWarm(){if(tubeWarmPromise)return tubeWarmPromise;tubeWarmPromise=tube.prewarm().then(()=>{tubeWarmReady=true;window.__tubeWarmReady=true}).catch(e=>{console.warn('[Pass13 tube prewarm]',e);tubeWarmPromise=null});return tubeWarmPromise}
function createTube(){tube=createCrystalLibraryTubeV2({renderer,scene,camera,bro,heroRoot,mobile,onComplete:()=>{objectiveEl.textContent='WORLD 1 COMPLETE · PASS 13 CLEAN REBUILD';retryBtn.classList.add('show');toast('WORLD 1 COMPLETE',2400)}});tube.root.position.set(sites.tube.x,sites.tube.y-.42,sites.tube.z);tube.entryRadius=Math.max(2.8,tube.entryRadius||0);window.__tubeComponent='crystal-library-v2-tube'}

const enemies=[];function makeEnemy(x,z,r=8.5,speed=2.7){const root=new THREE.Group();root.position.set(x,elev(z),z);const body=new THREE.Mesh(new THREE.DodecahedronGeometry(.65,0),mats.red.clone());body.position.y=.8;body.material.emissive.setHex(0x4a0d20);body.material.emissiveIntensity=.5;const eye=new THREE.Mesh(new THREE.SphereGeometry(.16,10,8),mats.cyan.clone());eye.position.set(0,.85,.57);root.add(body,eye);world.add(root);const e={root,body,eye,home:new THREE.Vector3(x,elev(z),z),radius:r,speed,hp:2,alive:true,hitSerial:-1,flash:0};enemies.push(e);return e}function spawnEnemies(){[[-5,-11,8],[9,-25,8.5],[17,-43,7.5],[-10,-70,9],[12,-88,8.5],[-12,-112,8.2],[15,-116,8.2],[-9,-127,7.5],[11,-132,7.5],[0,-150,9.5]].forEach(([x,z,r],i)=>makeEnemy(x,z,r,2.5+(i%3)*.25));window.__enemyCount=enemies.length}
let powers;function enemyBurst(e){for(let i=0;i<12;i++){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.08+Math.random()*.08),i%2?mats.cyan.clone():mats.violet.clone());m.position.copy(e.root.position).add(new THREE.Vector3(0,.8,0));scene.add(m);powers?.addDebris(m,new THREE.Vector3((Math.random()-.5)*5,2+Math.random()*3,(Math.random()-.5)*5),.75)}}function damageEnemy(e,serial){if(!e?.alive||e.hitSerial===serial)return false;e.hitSerial=serial;e.hp--;e.flash=.14;e.body.material.emissive.setHex(0xffffff);e.body.material.emissiveIntensity=1.2;if(e.hp<=0){e.alive=false;enemyBurst(e);world.remove(e.root);coins+=2;if(Math.random()<.35)gems++;updateHUD();toast('ENEMY DESTROYED · +2 COINS',850)}else toast('HIT · ONE MORE',520);return true}function damagePlayer(){if(player.damageCooldown>0||tube?.state!=='idle')return;player.damageCooldown=.85;player.hearts--;updateHUD();toast(`HIT · ${player.hearts} HEART${player.hearts===1?'':'S'} LEFT`,750);if(player.hearts<=0){toast('RESPAWNING AT CHECKPOINT',1200);setTimeout(()=>resetPlayer(true),480)}}
const collectibles=[];function coinMesh(x,z,y=.85){const m=new THREE.Mesh(new THREE.TorusGeometry(.23,.08,8,18),mats.gold.clone());m.rotation.x=Math.PI/2;m.position.set(x,elev(z)+y,z);world.add(m);collectibles.push({type:'coin',mesh:m,taken:false,baseY:m.position.y})}function gemMesh(x,z,y=.95){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.28,0),mats.cyan.clone());m.position.set(x,elev(z)+y,z);world.add(m);collectibles.push({type:'gem',mesh:m,taken:false,baseY:m.position.y})}function spawnCollectibles(){[[0,30],[-3,19],[-7,10],[1,-2],[7,-9],[-2,-19],[-7,-28],[5,-35],[7,-42],[7,-50],[4,-59],[-4,-66],[-12,-72],[-3,-80],[12,-87],[4,-96],[4,-105],[-10,-114],[-10,-126],[12,-130],[3,-140],[0,-151],[0,-157]].forEach(([x,z])=>coinMesh(x,z));[[-25,-1,3.45],[-24,-18,4.35],[27,-44,1.85],[-29,-80,5.05],[-26,-89,5.45],[-10,-127,4.05],[13,-130,4.65]].forEach(([x,z,h])=>gemMesh(x,z,h))}

const camTarget=new THREE.Vector3(),camLook=new THREE.Vector3();let camYaw=.08,camPitch=.34,camDistance=13.6,recenter=0,dragging=false,lastX=0,lastY=0;function updateCamera(dt){const portal=tube&&tube.state!=='idle';if(portal){camLook.set(tube.root.position.x,tube.root.position.y+2.9,tube.root.position.z);camTarget.lerp(camLook,.09);camYaw=THREE.MathUtils.damp(camYaw,.05,3,dt);camPitch=THREE.MathUtils.damp(camPitch,.12,3,dt);camDistance=THREE.MathUtils.damp(camDistance,12.2,3.2,dt)}else{camLook.set(player.x,player.y+1.45,player.z);camTarget.lerp(camLook,1-Math.exp(-8*dt));if(dragging||analog.active)recenter=0;else recenter+=dt;if(!dragging&&!analog.active&&recenter>.8){const behind=player.yaw+Math.PI,dy=Math.atan2(Math.sin(behind-camYaw),Math.cos(behind-camYaw));camYaw+=dy*(1-Math.exp(-1.8*dt));camPitch=THREE.MathUtils.damp(camPitch,.34,2.4,dt)}}const cp=Math.cos(camPitch),desired=new THREE.Vector3(camTarget.x+Math.sin(camYaw)*cp*camDistance,camTarget.y+Math.sin(camPitch)*camDistance+1,camTarget.z+Math.cos(camYaw)*cp*camDistance);camera.position.lerp(desired,1-Math.exp(-15*dt));const kick=powers?.cameraKick||0;if(kick>0){camera.position.x+=Math.cos(camYaw)*kick*.11;camera.position.y+=kick*.07;camera.position.z-=Math.sin(camYaw)*kick*.11}camera.lookAt(camTarget)}
function updateCheckpoint(){while(checkpointIndex<checkpoints.length-1&&player.z<checkpoints[checkpointIndex+1].z)checkpointIndex++}function updateZone(){const z=zoneForZ(player.z);objectiveEl.textContent=`${z.id} · ${z.name}  →  F · PORTAL ASCENT`}
function updatePlayer(dt){if(!bro||!tube||tube.state!=='idle')return;const kx=(input.right?1:0)-(input.left?1:0),ky=(input.up?1:0)-(input.down?1:0);let sx=analog.active?analog.x:kx,sy=analog.active?-analog.y:ky,len=Math.hypot(sx,sy);if(len<.075){sx=0;sy=0;len=0}const mag=Math.min(1,len);if(len>1){sx/=len;sy/=len}let dx=0,dz=0;if(len>0){const fx=-Math.sin(camYaw),fz=-Math.cos(camYaw),rx=Math.cos(camYaw),rz=-Math.sin(camYaw);dx=fx*sy+rx*sx;dz=fz*sy+rz*sx;const dl=Math.hypot(dx,dz)||1;dx/=dl;dz/=dl;const want=Math.atan2(dx,dz),diff=Math.atan2(Math.sin(want-player.yaw),Math.cos(want-player.yaw));player.yaw+=diff*(1-Math.exp(-11*dt))}const target=len>0?(input.run?RUN:WALK)*THREE.MathUtils.smoothstep(mag,.075,.9):0;player.speed=THREE.MathUtils.damp(player.speed,target,target>player.speed?8:12,dt);const ch=groundAt(player.x,player.z),nx=player.x+dx*player.speed*dt,nz=player.z+dz*player.speed*dt,nh=groundAt(nx,nz);if(nh!==null&&(ch===null||nh-ch<=STEP)){player.x=nx;player.z=nz}if(input.jumpQueued){if(player.grounded){player.vy=JUMP;player.grounded=false;player.jumpCount=1;player.holdJumpTimer=HOLD_INTERVAL}else if(player.jumpCount<2){player.vy=Math.max(player.vy,DOUBLE);player.jumpCount=2;player.holdJumpTimer=HOLD_INTERVAL}input.jumpQueued=false}if(input.jump&&!player.grounded){player.holdJumpTimer-=dt;if(player.holdJumpTimer<=0){player.vy=Math.max(player.vy,HOLD);player.holdJumpTimer=HOLD_INTERVAL}}player.vy-=GRAVITY*dt;player.y+=player.vy*dt;const g=groundAt(player.x,player.z);if(g!==null&&player.vy<=0&&player.y<=g+.05){player.y=g+.03;player.vy=0;player.grounded=true;player.jumpCount=0}else if(g===null||player.y>g+.09)player.grounded=false;if(player.y<getBounds().min.y-7){resetPlayer(true);toast('BACK AT CHECKPOINT',700)}updateCheckpoint();const motion=player.speed<.14?'idle':(player.speed<WALK*.92?'walk':'run');bro.setMotion(motion);bro.setHome(player.x,player.z,player.yaw);const pose=powers?.poseTimer||0;heroRoot.position.y=player.y+(pose>0?.07*Math.sin((.72-pose)*Math.PI*3):0);heroRoot.scale.copy(heroBaseScale).multiplyScalar(1+(pose>0?.03:0));const d=Math.hypot(player.x-sites.tube.x,player.z-sites.tube.z);if(d<tube.entryRadius&&player.grounded){if(tubeWarmReady||tube.prewarmed){player.speed=0;bro.setMotion('idle');tube.trigger();objectiveEl.textContent='CRYSTAL LIBRARY V2 · TRANSMISSION'}else{objectiveEl.textContent='PORTAL CHARGING…';beginTubeWarm()}}}
function updateWorld(dt,elapsed){player.damageCooldown=Math.max(0,player.damageCooldown-dt);springCooldown=Math.max(0,springCooldown-dt);if(springCooldown<=0&&player.grounded&&Math.hypot(player.x-27,player.z+44)<1.6){player.vy=8;player.grounded=false;player.jumpCount=1;springCooldown=1.1;toast('RIVERWORKS SPRING!',650)}for(const e of enemies){if(!e.alive)continue;e.flash=Math.max(0,e.flash-dt);if(e.flash<=0){e.body.material.emissive.setHex(0x4a0d20);e.body.material.emissiveIntensity=.5}const dx=player.x-e.root.position.x,dz=player.z-e.root.position.z,d=Math.hypot(dx,dz),hx=e.home.x-e.root.position.x,hz=e.home.z-e.root.position.z,hd=Math.hypot(hx,hz);if(d<e.radius){const inv=1/Math.max(.001,d);e.root.position.x+=dx*inv*e.speed*dt;e.root.position.z+=dz*inv*e.speed*dt;e.root.rotation.y=Math.atan2(dx,dz)}else if(hd>1){e.root.position.x+=hx/hd*e.speed*.55*dt;e.root.position.z+=hz/hd*e.speed*.55*dt}e.root.position.y=elev(e.root.position.z);if(d<1.25)damagePlayer()}for(const c of collectibles){if(c.taken)continue;c.mesh.rotation.y+=dt*2.6;c.mesh.position.y=c.baseY+Math.sin(elapsed*3+c.mesh.position.x)*.12;if(Math.hypot(player.x-c.mesh.position.x,player.z-c.mesh.position.z)<.9){c.taken=true;world.remove(c.mesh);if(c.type==='coin')coins++;else gems++;updateHUD();toast(c.type==='coin'?'+1 COIN':'+1 GEM',420)}}}
function bindControls(){const map={KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};addEventListener('keydown',e=>{if(map[e.code])input[map[e.code]]=true;if(e.code==='ShiftLeft'||e.code==='ShiftRight')input.run=true;if(e.code==='Space'){e.preventDefault();if(!input.jump)input.jumpQueued=true;input.jump=true}if(['KeyE','KeyX','KeyJ','KeyK'].includes(e.code))fire();if(e.code==='KeyC')cycle()});addEventListener('keyup',e=>{if(map[e.code])input[map[e.code]]=false;if(e.code==='ShiftLeft'||e.code==='ShiftRight')input.run=false;if(e.code==='Space')input.jump=false});function setStick(x,y){const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,lim=r.width*.34;let dx=x-cx,dy=y-cy,d=Math.hypot(dx,dy);if(d>lim){dx=dx/d*lim;dy=dy/d*lim}let nx=dx/lim,ny=dy/lim;if(Math.hypot(nx,ny)<.04){nx=0;ny=0}analog.x=nx;analog.y=ny;analog.active=true;stick.style.transform=`translate(${nx*lim}px,${ny*lim}px)`}pad.addEventListener('pointerdown',e=>{analog.pointerId=e.pointerId;pad.setPointerCapture(e.pointerId);setStick(e.clientX,e.clientY)});pad.addEventListener('pointermove',e=>{if(e.pointerId===analog.pointerId)setStick(e.clientX,e.clientY)});function stop(e){if(e.pointerId!==analog.pointerId)return;analog.active=false;analog.pointerId=null;analog.x=analog.y=0;stick.style.transform='translate(0,0)'}pad.addEventListener('pointerup',stop);pad.addEventListener('pointercancel',stop);function hold(btn,key){btn.addEventListener('pointerdown',e=>{e.preventDefault();if(key==='jump'&&!input.jump)input.jumpQueued=true;input[key]=true});const up=e=>{e.preventDefault();input[key]=false};btn.addEventListener('pointerup',up);btn.addEventListener('pointercancel',up)}hold(jumpBtn,'jump');hold(runBtn,'run');function fire(){if(powers.use()){actionBtn.classList.add('active');setTimeout(()=>actionBtn.classList.remove('active'),170)}}function cycle(){fxBtn.textContent=`POWER: ${powers.cycle()}`}actionBtn.addEventListener('pointerdown',e=>{e.preventDefault();fire()});fxBtn.addEventListener('pointerdown',e=>{e.preventDefault();cycle()});canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;dragging=true;lastX=e.clientX;lastY=e.clientY});addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;camYaw-=dx*.0032;camPitch=THREE.MathUtils.clamp(camPitch+dy*.0024,.05,.72)});addEventListener('pointerup',()=>dragging=false);addEventListener('wheel',e=>{camDistance=THREE.MathUtils.clamp(camDistance+Math.sign(e.deltaY)*.8,8.5,17.5)},{passive:true})}
let last=performance.now(),elapsed=0;function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();function loop(now=performance.now()){requestAnimationFrame(loop);const dt=Math.min(.033,Math.max(.001,(now-last)/1000));last=now;elapsed+=dt;updatePlayer(dt);powers.update(dt);updateWorld(dt,elapsed);updateZone();bro?.update(dt,player.speed,input.run?1:0);tube?.update(dt);updateCamera(dt);renderer.render(scene,camera)}
(async()=>{try{setPhase('Building clean World 1…',12);sites=buildWorld();refreshBounds();spawnEnemies();spawnCollectibles();updateHUD();await createPlayer();createTube();powers=createPowerSystem({scene,player,getBro:()=>bro,getTube:()=>tube,enemies,damageEnemy,toast});bindControls();setPhase('Ready',100);window.__world1Ready=true;window.__pass='pass13-v1-clean';window.__powerModes=powers.names.slice();boot.classList.add('hide');last=performance.now();loop();setTimeout(()=>beginTubeWarm(),mobile?1800:500);const streamer=createAssetStreamer({artRoot:worldSys.artRoot,mobile,elev,refreshBounds});setTimeout(()=>streamer.stream(),mobile?850:100)}catch(e){fail(e)}})();
