import * as THREE from 'three';

export function createPowerSystem({ scene, player, getBro, getTube, enemies, damageEnemy, toast }) {
  const names=['PRISM RAIL','GRAVITY NOVA','AURORA SWARM','RIFT DISC'];
  let index=0,cooldown=0,poseTimer=0,serial=0,cameraKick=0;
  const events=[],trails=[],debris=[];
  const energyMat=(c,o=.9)=>new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,depthWrite:false,blending:THREE.AdditiveBlending});
  const forward=()=>new THREE.Vector3(Math.sin(player.yaw),0,Math.cos(player.yaw));
  const nearest=(r=28)=>enemies.filter(e=>e.alive).map(e=>({e,d:Math.hypot(e.root.position.x-player.x,e.root.position.z-player.z)})).filter(o=>o.d<=r).sort((a,b)=>a.d-b.d).map(o=>o.e);

  function prism(s){const g=new THREE.Group();g.position.set(player.x,player.y+1.2,player.z);scene.add(g);const core=new THREE.Mesh(new THREE.SphereGeometry(.18,14,10),energyMat(0xbaffff,.96));g.add(core);const a=new THREE.Mesh(new THREE.TorusGeometry(.52,.045,8,28),energyMat(0x6ff5ff,.85));a.rotation.x=Math.PI/2;g.add(a);const b=a.clone();b.material=energyMat(0xc56cff,.8);b.rotation.y=Math.PI/2;g.add(b);events.push({type:'rail',serial:s,age:0,g,core,a,b,fired:false,beam:null});}
  function fireRail(ev){ev.fired=true;const d=forward(),L=28,beam=new THREE.Group();beam.position.set(player.x+d.x*L/2,player.y+1.2,player.z+d.z*L/2);beam.rotation.y=player.yaw;scene.add(beam);const out=new THREE.Mesh(new THREE.CylinderGeometry(.22,.42,L,14,1,true),energyMat(0x8b67ff,.26));out.rotation.x=Math.PI/2;beam.add(out);const inn=new THREE.Mesh(new THREE.CylinderGeometry(.06,.10,L,10),energyMat(0xc8ffff,.98));inn.rotation.x=Math.PI/2;beam.add(inn);ev.beam=beam;let best=null,bestT=1e9;for(const e of enemies){if(!e.alive)continue;const ex=e.root.position.x-player.x,ez=e.root.position.z-player.z,t=ex*d.x+ez*d.z;if(t<0||t>L)continue;const perp=Math.abs(ex*d.z-ez*d.x);if(perp<1.5&&t<bestT){best=e;bestT=t;}}if(best)damageEnemy(best,ev.serial);cameraKick=.8;}
  function nova(s){const g=new THREE.Group();g.position.set(player.x,player.y+1.05,player.z);scene.add(g);const shards=[];for(let i=0;i<8;i++){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.12,0),energyMat(i%2?0x77efff:0xbd67ff,.9));g.add(m);shards.push(m);}events.push({type:'nova',serial:s,age:0,g,shards,burst:false,shell:null,ring:null});}
  function burstNova(ev){ev.burst=true;ev.shell=new THREE.Mesh(new THREE.SphereGeometry(1,20,14),energyMat(0x9b5dff,.22));ev.shell.position.set(player.x,player.y+1,player.z);scene.add(ev.shell);ev.ring=new THREE.Mesh(new THREE.RingGeometry(.7,1,48),energyMat(0x72f5ff,.92));ev.ring.rotation.x=-Math.PI/2;ev.ring.position.set(player.x,player.y+.12,player.z);scene.add(ev.ring);cameraKick=.55;}
  function swarm(s){const g=new THREE.Group();g.position.set(player.x,player.y+1.1,player.z);scene.add(g);const colors=[0x64efff,0xa56cff,0xff76d7,0x76ff9b,0xffd25d];const stars=colors.map(c=>{const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.15,0),energyMat(c,.96));g.add(m);return{m,color:c,v:new THREE.Vector3(),target:null};});events.push({type:'swarm',serial:s,age:0,g,stars,released:false});}
  function releaseSwarm(ev){ev.released=true;const targets=nearest();ev.stars.forEach((s,i)=>{const wp=new THREE.Vector3();s.m.getWorldPosition(wp);scene.attach(s.m);s.m.position.copy(wp);s.target=targets.length?targets[i%targets.length]:null;const spread=(i-2)*.12,a=player.yaw+spread;s.v.set(Math.sin(a)*15,1.8+Math.abs(i-2)*.25,Math.cos(a)*15);});cameraKick=.35;}
  function disc(s){const d=forward(),g=new THREE.Group();g.position.set(player.x,player.y+1.15,player.z);scene.add(g);const t=new THREE.Mesh(new THREE.TorusGeometry(.52,.10,10,32),energyMat(0x7df4ff,.9));t.rotation.x=Math.PI/2;g.add(t);const c=new THREE.Mesh(new THREE.RingGeometry(.14,.34,24),energyMat(0xce6cff,.85));c.rotation.x=-Math.PI/2;g.add(c);events.push({type:'disc',serial:s,age:0,disc:g,dir:d,start:new THREE.Vector3(player.x,player.y+1.15,player.z)});}

  function use(){const bro=getBro(),tube=getTube();if(!bro||!tube||tube.state!=='idle'||cooldown>0)return false;const s=++serial;cooldown=.54;poseTimer=.72;bro.setAction(true);if(index===0)prism(s);else if(index===1)nova(s);else if(index===2)swarm(s);else disc(s);return true;}
  function cycle(){index=(index+1)%names.length;toast(names[index],700);return names[index];}
  function addDebris(m,v,life=.75){debris.push({m,v,age:0,life});}
  function update(dt){cooldown=Math.max(0,cooldown-dt);poseTimer=Math.max(0,poseTimer-dt);cameraKick=Math.max(0,cameraKick-dt*2.8);const bro=getBro();if(bro&&poseTimer<=0&&bro.action)bro.setAction(false);
    for(let i=events.length-1;i>=0;i--){const ev=events[i];ev.age+=dt;
      if(ev.type==='rail'){const t=Math.min(1,ev.age/.16),a=ev.age*22;ev.g.position.set(player.x,player.y+1.2,player.z);ev.a.rotation.z=a;ev.b.rotation.z=-a*1.25;ev.core.scale.setScalar(1+t*1.7);if(ev.age>.16&&!ev.fired)fireRail(ev);if(ev.beam)ev.beam.traverse(o=>{if(o.material?.opacity!=null)o.material.opacity*=Math.pow(.88,dt*60)});if(ev.age>.46){scene.remove(ev.g);if(ev.beam)scene.remove(ev.beam);events.splice(i,1);}}
      else if(ev.type==='nova'){ev.g.position.set(player.x,player.y+1,player.z);ev.shards.forEach((m,j)=>{const a=ev.age*11+j*Math.PI/4,r=.95-Math.min(.65,ev.age*2.6);m.position.set(Math.cos(a)*r,.15+Math.sin(a*1.7)*.24,Math.sin(a)*r)});if(ev.age>.2&&!ev.burst)burstNova(ev);if(ev.burst){const p=Math.min(1,(ev.age-.2)/.46),r=.8+p*8.8;ev.shell.scale.setScalar(r);ev.shell.material.opacity=.24*(1-p);ev.ring.scale.setScalar(r);ev.ring.material.opacity=.9*(1-p);for(const e of enemies){if(!e.alive)continue;const d=Math.hypot(e.root.position.x-player.x,e.root.position.z-player.z);if(d<r&&d>Math.max(0,r-2)){if(damageEnemy(e,ev.serial)){const nx=(e.root.position.x-player.x)/(d||1),nz=(e.root.position.z-player.z)/(d||1);e.root.position.x+=nx*1.1;e.root.position.z+=nz*1.1;}}}}if(ev.age>.74){scene.remove(ev.g);if(ev.shell)scene.remove(ev.shell);if(ev.ring)scene.remove(ev.ring);events.splice(i,1);}}
      else if(ev.type==='swarm'){ev.g.position.set(player.x,player.y+1.1,player.z);if(!ev.released){ev.stars.forEach((s,j)=>{const a=ev.age*13+j*Math.PI*2/5;s.m.position.set(Math.cos(a)*.82,.15+Math.sin(a*1.8)*.28,Math.sin(a)*.82)});if(ev.age>.22)releaseSwarm(ev);}else{let count=0;for(const s of ev.stars){if(!s.m.parent)continue;count++;if(s.target?.alive){const tp=s.target.root.position.clone().add(new THREE.Vector3(0,.8,0)),d=tp.sub(s.m.position).normalize();s.v.lerp(d.multiplyScalar(19),1-Math.exp(-8*dt));}s.v.y-=1.1*dt;s.m.position.addScaledVector(s.v,dt);s.m.rotation.x+=dt*14;s.m.rotation.y+=dt*17;if(Math.random()<.55){const tr=new THREE.Mesh(new THREE.SphereGeometry(.05,6,4),energyMat(s.color,.5));tr.position.copy(s.m.position);scene.add(tr);trails.push({m:tr,age:0,life:.25});}if(s.target?.alive&&s.m.position.distanceTo(s.target.root.position.clone().add(new THREE.Vector3(0,.8,0)))<.9){damageEnemy(s.target,ev.serial);scene.remove(s.m);s.m.parent=null;}}if(ev.age>1.05||count===0){ev.stars.forEach(s=>{if(s.m.parent)scene.remove(s.m)});scene.remove(ev.g);events.splice(i,1);}}}
      else if(ev.type==='disc'){const maxD=15,dur=.34,dist=ev.age<dur?(ev.age/dur)*maxD:Math.max(0,maxD-((ev.age-dur)/dur)*maxD);ev.disc.position.copy(ev.start).addScaledVector(ev.dir,dist);ev.disc.rotation.y+=dt*16;ev.disc.rotation.z+=dt*11;for(const e of enemies)if(e.alive&&e.root.position.distanceTo(ev.disc.position)<1.2)damageEnemy(e,ev.serial);if(ev.age>dur*2+.08){scene.remove(ev.disc);events.splice(i,1);}}
    }
    for(let i=trails.length-1;i>=0;i--){const t=trails[i];t.age+=dt;t.m.scale.setScalar(1+t.age*3.5);t.m.material.opacity=Math.max(0,.5*(1-t.age/t.life));if(t.age>t.life){scene.remove(t.m);trails.splice(i,1);}}
    for(let i=debris.length-1;i>=0;i--){const d=debris[i];d.age+=dt;d.v.y-=8*dt;d.m.position.addScaledVector(d.v,dt);d.m.rotation.x+=dt*9;d.m.rotation.y+=dt*11;d.m.material.opacity=Math.max(0,1-d.age/d.life);if(d.age>d.life){scene.remove(d.m);debris.splice(i,1);}}
  }
  return { names, use, cycle, update, addDebris, get poseTimer(){return poseTimer}, get cameraKick(){return cameraKick}, get currentName(){return names[index]} };
}
