import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createGamerBro} from '../playground-v2/gamer-bro.js?v=pass10';
import {createCrystalLibraryTubeV2} from '../src/crystal-library-tube-v2.js?v=1';

const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const qp=new URLSearchParams(location.search),requested=qp.get('hero'),saved=localStorage.getItem('gamerBroCharacter');
const id=requested==='gb1'||requested==='gb2'?requested:(saved==='gb1'||saved==='gb2'?saved:'gb2');
const colorway=id==='gb1'?'pink':'teal';localStorage.setItem('gamerBroCharacter',id);
const $=s=>document.querySelector(s),canvas=$('#game'),heroName=$('#heroName'),menu=$('#menu'),objective=$('#objective'),pad=$('#pad'),stick=$('#stick'),jumpBtn=$('#jump'),runBtn=$('#run'),actionBtn=$('#action'),retry=$('#retry'),toastEl=$('#toast'),boot=$('#boot'),status=$('#status'),bar=$('#bar'),fatal=$('#fatal'),errorEl=$('#error');
heroName.textContent=id.toUpperCase();menu.onclick=()=>location.href='../';
function progress(t,n){status.textContent=t;bar.style.width=n+'%'}
function toast(t,ms=1500){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),ms)}

const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=1.38;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1:1.35));
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8fcce3);scene.fog=new THREE.Fog(0xa3d1df,58,125);
const camera=new THREE.PerspectiveCamera(36,1,.15,170);camera.layers.enable(1);
scene.add(new THREE.HemisphereLight(0xebfbff,0x456044,1.85));
const sun=new THREE.DirectionalLight(0xffefd4,2.2);sun.position.set(-28,38,18);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:1536,mobile?1024:1536);sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;sun.shadow.camera.near=1;sun.shadow.camera.far=110;sun.shadow.bias=-.00025;sun.shadow.normalBias=.03;scene.add(sun);
const rim=new THREE.DirectionalLight(0x8d71ff,.28);rim.position.set(25,18,-24);scene.add(rim);

const world=new THREE.Group();scene.add(world);
const ray=new THREE.Raycaster(),down=new THREE.Vector3(0,-1,0),walkMeshes=[];let worldBounds=new THREE.Box3();
const mats={grass:new THREE.MeshStandardMaterial({color:0x69a449,roughness:.95}),path:new THREE.MeshStandardMaterial({color:0xc7aa79,roughness:.98}),stone:new THREE.MeshStandardMaterial({color:0x777a72,roughness:.9}),stone2:new THREE.MeshStandardMaterial({color:0x97998d,roughness:.9}),wood:new THREE.MeshStandardMaterial({color:0x7a4b2d,roughness:.9}),water:new THREE.MeshPhysicalMaterial({color:0x2f9abe,roughness:.15,transparent:true,opacity:.82}),roof:new THREE.MeshStandardMaterial({color:0x8f4d3c,roughness:.86}),plaster:new THREE.MeshStandardMaterial({color:0xe4d5ad,roughness:.95}),leaf:new THREE.MeshStandardMaterial({color:0x4f8c47,roughness:1})};
function elev(z){if(z>=-55)return 0;if(z<=-90)return 5;let t=(-55-z)/35;t=t*t*(3-2*t);return t*5}
function terrain(){const sx=18,sz=100,w=38,zMax=40,zMin=-151,pos=[],uv=[],idx=[];for(let iz=0;iz<=sz;iz++){const z=THREE.MathUtils.lerp(zMax,zMin,iz/sz),y=elev(z);for(let ix=0;ix<=sx;ix++){const x=THREE.MathUtils.lerp(-w/2,w/2,ix/sx);pos.push(x,y,z);uv.push(ix/sx,iz/sz)}}for(let iz=0;iz<sz;iz++)for(let ix=0;ix<sx;ix++){const a=iz*(sx+1)+ix,b=a+1,c=a+(sx+1),d=c+1;idx.push(a,b,c,b,d,c)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();const m=new THREE.Mesh(g,mats.grass);m.name='continuous-world1-terrain';m.receiveShadow=true;world.add(m);walkMeshes.push(m);return m}
function box(name,x,y,z,w,h,d,mat,ry=0,rx=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.name=name;m.position.set(x,y,z);m.rotation.set(rx,ry,0);m.castShadow=!mobile;m.receiveShadow=true;world.add(m);return m}
function cyl(name,x,y,z,r,h,mat){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,20),mat);m.name=name;m.position.set(x,y,z);m.castShadow=!mobile;m.receiveShadow=true;world.add(m);return m}
function tree(x,z,s=1){const y=elev(z);cyl('tree-trunk',x,y+.9*s,z,.28*s,1.8*s,mats.wood);const c=new THREE.Mesh(new THREE.ConeGeometry(1.2*s,2.5*s,10),mats.leaf);c.position.set(x,y+2.45*s,z);c.castShadow=!mobile;world.add(c)}
function house(x,z,scale=1,rot=0){const y=elev(z),g=new THREE.Group(),base=new THREE.Mesh(new THREE.BoxGeometry(4.5*scale,2.7*scale,3.8*scale),mats.plaster);base.position.y=1.35*scale;base.castShadow=!mobile;base.receiveShadow=true;g.add(base);const roof=new THREE.Mesh(new THREE.ConeGeometry(3.6*scale,2.2*scale,4),mats.roof);roof.position.y=3.55*scale;roof.rotation.y=Math.PI/4;roof.castShadow=!mobile;g.add(roof);const door=new THREE.Mesh(new THREE.BoxGeometry(.8*scale,1.6*scale,.16*scale),mats.wood);door.position.set(0,.8*scale,2*scale);g.add(door);g.position.set(x,y,z);g.rotation.y=rot;world.add(g)}
function arch(x,z,s=1,rot=0){const y=elev(z);box('ruin-pillar',x-1.65*s,y+1.7*s,z,.65*s,3.4*s,.75*s,mats.stone,rot);box('ruin-pillar',x+1.65*s,y+1.7*s,z,.65*s,3.4*s,.75*s,mats.stone,rot);box('ruin-lintel',x,y+3.35*s,z,3.95*s,.6*s,.8*s,mats.stone,rot)}
function buildWorld(){progress('Building one continuous World 1 landmass…',18);terrain();for(const [z,d] of [[18,35],[-12,25],[-51,10],[-73,31],[-108,29],[-133,20]])box('path',0,elev(z)+.035,z,5,.07,d,mats.path);for(const [x,z,s] of [[-11,30,1.05],[11,28,.9],[-12,16,.85],[12,9,1],[-10,-28,.75],[11,-30,.8],[-13,-94,.85],[13,-100,.85],[-12,-126,.85],[12,-139,.9]])tree(x,z,s);for(let i=0;i<6;i++){box('fence',-4.8,.55,29-i*4,.18,1.1,3.1,mats.wood);box('fence',4.8,.55,29-i*4,.18,1.1,3.1,mats.wood)}house(-9,-5,.9,.08);house(9,-7,1,-.12);house(-10,-15,.82,-.05);house(10,-17,.92,.12);house(-8,-23,.74,.06);house(8,-24,.78,-.08);box('village-square',0,.05,-15,11,.10,7,mats.path);cyl('well',-4,.65,-15,1.1,1.1,mats.stone);cyl('well-cap',-4,1.25,-15,1.35,.18,mats.stone2);box('river-left',-12,-.12,-40,14,.10,11,mats.water);box('river-right',12,-.12,-40,14,.10,11,mats.water);for(let z=-44.5;z<=-35.5;z+=1.05)box('bridge-plank',0,.10,z,6,.18,.86,mats.wood);for(const x of [-3.25,3.25]){for(let z=-44;z<=-36;z+=2)box('bridge-post',x,.9,z,.18,1.8,.18,mats.wood);box('bridge-rail',x,1.35,-40,.16,.18,9,mats.wood)}arch(0,-103,1.05);arch(-8,-110,.85,.08);arch(8,-114,.75,-.06);box('ruin-platform-a',-6,elev(-109)+.5,-109,4.5,1,4.5,mats.stone);box('ruin-platform-b',6,elev(-115)+.75,-115,4.5,1.5,4.5,mats.stone);box('ruin-platform-c',0,elev(-121)+1,-121,5.5,2,4.5,mats.stone);box('shrine-court',0,elev(-133)+.08,-133,17,.16,15,mats.stone2);box('shrine-step',0,elev(-138)+.22,-138,9,.44,5,mats.stone);for(const x of [-8,8]){cyl('shrine-column',x,elev(-132)+2,-132,.55,4,mats.stone);cyl('shrine-cap',x,elev(-132)+4.05,-132,.8,.2,mats.stone2)}arch(0,-144,1.25);world.updateMatrixWorld(true);worldBounds=new THREE.Box3().setFromObject(world);window.__worldSource='pass10-continuous-terrain-plus-kit-assets';window.__worldRoute='meadow-village-river-bridge-hillside-ruins-portal-shrine';window.__enemyCount=0;window.__continuousLand=true;window.__movementCollisionMeshes=1;return{spawn:{x:0,y:.02,z:31},tube:{x:0,y:elev(-138)+.44,z:-138}}}


// PASS 10 OPTION B ---------------------------------------------------------
// Pass 9C's continuous terrain stays the ONLY movement collision surface.
// Imported kit models are visual-only in this first art-direction pass.
const assetLoader=new GLTFLoader();
const assetRoot=new THREE.Group();assetRoot.name='pass10-imported-world-assets';world.add(assetRoot);
const assetBase='../assets/world-kit/';
const cityBase=assetBase+'kenney/city-builder/models/';
const kenneyPlat=assetBase+'kenney/platformer-kit/Models/GLB format/';
const kayBase=assetBase+'kaykit/platformer-pack/KayKit_Platformer_Pack_1.0_FREE/Assets/gltf/neutral/';
const assetCache=new Map();
async function loadTemplate(url){if(assetCache.has(url))return assetCache.get(url);const pr=assetLoader.loadAsync(url).then(g=>g.scene);assetCache.set(url,pr);return pr}
function prepModel(root){root.traverse(o=>{if(o.isMesh){o.castShadow=!mobile;o.receiveShadow=true;o.frustumCulled=true}});return root}
async function placeAsset(url,{x=0,z=0,y=null,height=null,width=null,scale=1,ry=0,name='kit-asset'}={}){
 try{
  const src=await loadTemplate(url),root=prepModel(src.clone(true));root.name=name;root.updateMatrixWorld(true);
  const box0=new THREE.Box3().setFromObject(root),size0=box0.getSize(new THREE.Vector3());let factor=scale;
  if(height)factor*=height/Math.max(.001,size0.y);else if(width)factor*=width/Math.max(.001,Math.max(size0.x,size0.z));
  root.scale.multiplyScalar(factor);root.rotation.y=ry;root.position.set(x,0,z);root.updateMatrixWorld(true);
  const box1=new THREE.Box3().setFromObject(root),baseY=(y==null?elev(z):y);root.position.y+=baseY-box1.min.y;
  assetRoot.add(root);return root;
 }catch(err){console.warn('[Pass10 asset skipped]',url,err);return null}
}
function removeProceduralDecor(){
 const removeNames=new Set(['tree-trunk','fence','village-square','well','well-cap','bridge-plank','bridge-post','bridge-rail','ruin-pillar','ruin-lintel','ruin-platform-a','ruin-platform-b','ruin-platform-c','shrine-column','shrine-cap']);
 for(const child of [...world.children]){
  if(child===assetRoot||walkMeshes.includes(child)||child.name==='path'||child.name==='river-left'||child.name==='river-right'||child.name==='shrine-court'||child.name==='shrine-step')continue;
  if(child.type==='Group'||removeNames.has(child.name)||(!child.name&&child.geometry?.type==='ConeGeometry'))world.remove(child);
 }
}
async function decorateWorld(){
 progress('Placing Kenney village and vegetation…',30);removeProceduralDecor();const jobs=[];
 const village=[['building-small-a.glb',-9,-5,6,.10],['building-small-b.glb',9,-7,6.2,-.12],['building-small-c.glb',-10,-15,6.3,.06],['building-small-d.glb',10,-17,6,-.08],['building-small-b.glb',-8,-24,5.5,.08],['building-small-a.glb',8,-25,5.6,-.05]];
 for(const [f,x,z,h,r] of village)jobs.push(placeAsset(cityBase+f,{x,z,height:h,ry:r,name:'kenney-village-building'}));
 jobs.push(placeAsset(cityBase+'pavement-fountain.glb',{x:-4,z:-15,width:3.8,name:'kenney-village-fountain'}));
 for(const [x,z,h,r] of [[-13,29,5.5,0],[13,27,4.8,.4],[-13,11,4.8,.7],[13,4,5.2,.2],[-14,-28,5,0],[14,-29,5,.5]])jobs.push(placeAsset(cityBase+'grass-trees.glb',{x,z,height:h,ry:r,name:'kenney-tree-cluster'}));
 for(const [x,z,r] of [[-6,-20,0],[6,-22,.6],[-8,-96,.4],[8,-100,-.5]])jobs.push(placeAsset(kenneyPlat+'barrel.glb',{x,z,height:1.2,ry:r,name:'kenney-barrel'}));
 for(const [x,z,r] of [[-11,-66,0],[11,-72,Math.PI],[-12,-82,.3],[12,-88,-.3]])jobs.push(placeAsset(kenneyPlat+'block-grass-large-slope.glb',{x,z,width:5.8,ry:r,name:'kenney-slope-accent'}));
 for(const [x,z,r] of [[-15,-58,0],[15,-62,Math.PI],[-15,-90,.2],[15,-94,-.2]])jobs.push(placeAsset(kenneyPlat+'block-grass-edge.glb',{x,z,width:4.2,ry:r,name:'kenney-grass-edge'}));
 progress('Placing KayKit bridge, ruins and route markers…',42);
 for(const [x,z,h,r] of [[0,-103,5,0],[-8,-111,4.4,.08],[8,-115,4.2,-.08],[0,-144,5.3,0]])jobs.push(placeAsset(kayBase+'arch_tall_neutral.gltf',{x,z,height:h,ry:r,name:'kaykit-ruin-arch'}));
 for(const [x,z,w,r] of [[-10,-105,4,0],[10,-108,4,Math.PI/2],[-10,-120,4,.15],[10,-124,4,-.15]])jobs.push(placeAsset(kayBase+'barrier_2x1x4_neutral.gltf',{x,z,width:w,ry:r,name:'kaykit-ruin-barrier'}));
 // Authored bridge deck + rails; continuous terrain remains hidden underneath for safe collision.
 for(const z of [-43.5,-40,-36.5])jobs.push(placeAsset(kayBase+'platform_6x2x1_neutral.gltf',{x:0,z,y:.03,width:6.1,ry:0,name:'kaykit-bridge-deck'}));
 for(const x of [-3.15,3.15])for(const z of [-43,-40,-37])jobs.push(placeAsset(kayBase+'railing_straight_double_neutral.gltf',{x,z,y:.20,width:3.0,ry:0,name:'kaykit-bridge-rail'}));
 // Readable route markers without giant HUD arrows.
 for(const [x,z,r] of [[3.7,27,Math.PI],[-3.7,-2,0],[3.8,-31,Math.PI],[-3.8,-55,0],[3.8,-91,Math.PI],[-3.8,-126,0]])jobs.push(placeAsset(kayBase+'signage_arrow_stand_neutral.gltf',{x,z,height:1.8,ry:r,name:'kaykit-route-sign'}));
 for(const [x,z,r] of [[-5,-101,0],[5,-118,Math.PI]])jobs.push(placeAsset(kayBase+'flag_A_neutral.gltf',{x,z,height:2.4,ry:r,name:'kaykit-ruin-flag'}));
 await Promise.all(jobs);window.__pass10Assets=true;window.__pass10AssetCount=assetRoot.children.length;window.__movementCollisionMeshes=1;
 progress(`Imported world assets ready · ${assetRoot.children.length} placed`,58);
}
// -------------------------------------------------------------------------

const heightCache=new Map();function hkey(x,z){return`${Math.round(x*10)},${Math.round(z*10)}`}function groundAt(x,z,cache=true){const key=hkey(x,z);if(cache&&heightCache.has(key))return heightCache.get(key);const top=worldBounds.max.y+18;ray.set(new THREE.Vector3(x,top,z),down);ray.far=(top-worldBounds.min.y)+30;const hit=ray.intersectObjects(walkMeshes,false)[0],y=hit?hit.point.y:null;if(cache)heightCache.set(key,y);return y}
let bro,heroRoot,tube,sites;const player={x:0,y:0,z:0,yaw:Math.PI,vy:0,speed:0,grounded:true,jumpCount:0,holdJumpTimer:0};const moveKeys={up:false,down:false,left:false,right:false,run:false,jump:false,jumpQueued:false},analogMove={x:0,y:0,active:false,pointerId:null};const STEP_HEIGHT=.70,GRAVITY=8.25,JUMP_V=5.05,DOUBLE_JUMP_V=4.65,HOLD_BOOST_V=3.95,HOLD_BOOST_INTERVAL=.22;
async function createPlayer(){progress('Restoring animated Gamer Bro movement…',45);bro=createGamerBro(THREE,renderer,{colorway,detail:mobile?'low':'high',height:2.62});heroRoot=bro.root;bro.all.forEach(m=>{m.layers.enable(0);m.layers.enable(1)});bro.setRoomLight(1);scene.add(heroRoot);resetPlayer();window.__characterReady=id;window.__playerPosition=player;window.__movementBaseline='crystal-library-v2';window.__cameraBaseline='crystal-library-v2'}
function resetPlayer(){player.x=sites.spawn.x;player.z=sites.spawn.z;player.y=(groundAt(player.x,player.z,false)??sites.spawn.y)+.02;player.yaw=Math.PI;player.vy=0;player.speed=0;player.grounded=true;player.jumpCount=0;if(bro){bro.setMotion('idle');bro.setHome(player.x,player.z,player.yaw);heroRoot.position.y=player.y;bro.update(0,0,0)}}
function createTube(){progress('Installing canonical Crystal Library v2 tube…',67);tube=createCrystalLibraryTubeV2({renderer,scene,camera,bro,heroRoot,mobile,onComplete:()=>{objective.textContent='WORLD 1 ROUTE COMPLETE · PASS 10';retry.classList.add('show');toast('ROUTE COMPLETE',2200)}});tube.root.position.set(sites.tube.x,sites.tube.y-.42,sites.tube.z);window.__tubeComponent='crystal-library-v2-tube';window.__tubePosition={...sites.tube};window.__portalRequiresEnemies=false}
const target=new THREE.Vector3(),targetLook=new THREE.Vector3();let yaw=.06,pitch=.34,distance=13.4,followDistance=13.4,recenterClock=0,dragging=false,lastX=0,lastY=0;function cameraDesired(dt){const portalActive=tube&&tube.state!=='idle';if(portalActive){targetLook.set(tube.root.position.x,tube.root.position.y+2.9,tube.root.position.z);target.lerp(targetLook,.085);yaw=THREE.MathUtils.damp(yaw,.06,3,dt);pitch=THREE.MathUtils.damp(pitch,.10,3,dt);distance=THREE.MathUtils.damp(distance,12.2,3.4,dt)}else{targetLook.set(player.x,player.y+1.45,player.z);target.lerp(targetLook,1-Math.exp(-8*dt));if(dragging||analogMove.active)recenterClock=0;else recenterClock+=dt;if(!dragging&&!analogMove.active&&recenterClock>.85){const behind=player.yaw+Math.PI,dy=Math.atan2(Math.sin(behind-yaw),Math.cos(behind-yaw));yaw+=dy*(1-Math.exp(-1.75*dt));pitch=THREE.MathUtils.damp(pitch,.34,2.5,dt)}distance=THREE.MathUtils.damp(distance,followDistance,3.8,dt)}const cp=Math.cos(pitch),desired=new THREE.Vector3(target.x+Math.sin(yaw)*cp*distance,target.y+Math.sin(pitch)*distance+1.05,target.z+Math.cos(yaw)*cp*distance);camera.position.lerp(desired,1-Math.exp(-16*dt));camera.lookAt(target)}
let actionCooldown=0,actionRing=null,actionPoseTimer=0;function useAction(){if(!bro||!tube||tube.state!=='idle'||actionCooldown>0)return;actionCooldown=.55;actionPoseTimer=.32;bro.setAction(true);actionBtn.classList.add('active');setTimeout(()=>actionBtn.classList.remove('active'),120);if(actionRing){scene.remove(actionRing);actionRing.geometry.dispose();actionRing.material.dispose()}actionRing=new THREE.Mesh(new THREE.RingGeometry(.5,1.05,48),new THREE.MeshBasicMaterial({color:0xa768ff,transparent:true,opacity:.78,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));actionRing.rotation.x=-Math.PI/2;actionRing.position.set(player.x,player.y+.08,player.z);scene.add(actionRing);actionRing.userData.age=0;window.__actionCount=(window.__actionCount||0)+1;toast('POWER / ACTION')}
function updateAction(dt){actionCooldown=Math.max(0,actionCooldown-dt);actionPoseTimer=Math.max(0,actionPoseTimer-dt);if(bro&&actionPoseTimer<=0&&bro.action)bro.setAction(false);if(!actionRing)return;actionRing.userData.age+=dt;const p=Math.min(1,actionRing.userData.age/.52);actionRing.scale.setScalar(1+p*4);actionRing.material.opacity=.78*(1-p);if(p>=1){scene.remove(actionRing);actionRing.geometry.dispose();actionRing.material.dispose();actionRing=null}}
function updatePlayer(dt){if(!bro||!tube||tube.state!=='idle')return;const kx=(moveKeys.right?1:0)-(moveKeys.left?1:0),ky=(moveKeys.up?1:0)-(moveKeys.down?1:0);let sx=analogMove.active?analogMove.x:kx,sy=analogMove.active?-analogMove.y:ky,len=Math.hypot(sx,sy);if(len<.075){sx=0;sy=0;len=0}const inputMag=Math.min(1,len);if(len>1){sx/=len;sy/=len}let dx=0,dz=0;if(len>0){const fx=-Math.sin(yaw),fz=-Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw);dx=fx*sy+rx*sx;dz=fz*sy+rz*sx;const dl=Math.hypot(dx,dz)||1;dx/=dl;dz/=dl;const desiredYaw=Math.atan2(dx,dz),diff=Math.atan2(Math.sin(desiredYaw-player.yaw),Math.cos(desiredYaw-player.yaw));player.yaw+=diff*(1-Math.exp(-10*dt))}const speedScale=THREE.MathUtils.smoothstep(inputMag,.075,.88),targetSpeed=len>0?(moveKeys.run?6.35:3.75)*speedScale:0;player.speed=THREE.MathUtils.damp(player.speed,targetSpeed,targetSpeed>player.speed?7.5:11,dt);const currentH=groundAt(player.x,player.z),nx=player.x+dx*player.speed*dt,nz=player.z+dz*player.speed*dt,nextH=groundAt(nx,nz);if(nextH!==null&&(currentH===null||nextH-currentH<=STEP_HEIGHT)){player.x=nx;player.z=nz}if(moveKeys.jumpQueued){if(player.grounded){player.vy=JUMP_V;player.grounded=false;player.jumpCount=1;player.holdJumpTimer=HOLD_BOOST_INTERVAL}else if(player.jumpCount<2){player.vy=Math.max(player.vy,DOUBLE_JUMP_V);player.jumpCount=2;player.holdJumpTimer=HOLD_BOOST_INTERVAL}moveKeys.jumpQueued=false}if(moveKeys.jump&&!player.grounded){player.holdJumpTimer-=dt;if(player.holdJumpTimer<=0){player.vy=Math.max(player.vy,HOLD_BOOST_V);player.holdJumpTimer=HOLD_BOOST_INTERVAL}}player.vy-=GRAVITY*dt;player.y+=player.vy*dt;const ground=groundAt(player.x,player.z);if(ground!==null&&player.vy<=0&&player.y<=ground+.04){player.y=ground+.02;player.vy=0;player.grounded=true;player.jumpCount=0}else if(ground===null||player.y>ground+.08)player.grounded=false;if(player.y<worldBounds.min.y-6){resetPlayer();toast('BACK AT THE MEADOW')}const motion=player.speed<.14?'idle':(player.speed<3.7?'walk':'run');bro.setMotion(motion);bro.setHome(player.x,player.z,player.yaw);heroRoot.position.y=player.y;window.__heroMotion=motion;const d=Math.hypot(player.x-sites.tube.x,player.z-sites.tube.z);if(d<tube.entryRadius&&player.grounded&&tube.prewarmed){player.speed=0;bro.setMotion('idle');tube.trigger();objective.textContent='CRYSTAL LIBRARY V2 · TRANSMISSION IN PROGRESS'}}
const keyMap={KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};addEventListener('keydown',e=>{if(keyMap[e.code])moveKeys[keyMap[e.code]]=true;if(e.code==='ShiftLeft'||e.code==='ShiftRight')moveKeys.run=true;if(e.code==='Space'){e.preventDefault();if(!moveKeys.jump)moveKeys.jumpQueued=true;moveKeys.jump=true}if(['KeyE','KeyX','KeyJ','KeyK'].includes(e.code))useAction()});addEventListener('keyup',e=>{if(keyMap[e.code])moveKeys[keyMap[e.code]]=false;if(e.code==='ShiftLeft'||e.code==='ShiftRight')moveKeys.run=false;if(e.code==='Space')moveKeys.jump=false});function setStick(x,y){const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,lim=r.width*.34;let dx=x-cx,dy=y-cy,d=Math.hypot(dx,dy);if(d>lim){dx=dx/d*lim;dy=dy/d*lim}let nx=dx/lim,ny=dy/lim;if(Math.hypot(nx,ny)<.035){nx=ny=0}analogMove.x=nx;analogMove.y=ny;analogMove.active=true;stick.style.transform=`translate(${nx*lim}px,${ny*lim}px)`}pad.addEventListener('pointerdown',e=>{analogMove.pointerId=e.pointerId;pad.setPointerCapture(e.pointerId);setStick(e.clientX,e.clientY)});pad.addEventListener('pointermove',e=>{if(e.pointerId===analogMove.pointerId)setStick(e.clientX,e.clientY)});function stopStick(e){if(e.pointerId!==analogMove.pointerId)return;analogMove.active=false;analogMove.pointerId=null;analogMove.x=analogMove.y=0;stick.style.transform='translate(0,0)'}pad.addEventListener('pointerup',stopStick);pad.addEventListener('pointercancel',stopStick);function hold(btn,key){btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);moveKeys[key]=true;if(key==='jump')moveKeys.jumpQueued=true;btn.classList.add('active')});const off=()=>{moveKeys[key]=false;btn.classList.remove('active')};btn.addEventListener('pointerup',off);btn.addEventListener('pointercancel',off)}hold(jumpBtn,'jump');hold(runBtn,'run');actionBtn.addEventListener('pointerdown',e=>{e.preventDefault();useAction()});canvas.addEventListener('pointerdown',e=>{if(e.target!==canvas)return;dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;yaw-=dx*.00245;pitch=THREE.MathUtils.clamp(pitch+dy*.0019,-.08,.78);recenterClock=0});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);canvas.addEventListener('wheel',e=>{followDistance=THREE.MathUtils.clamp(followDistance+e.deltaY*.008,7.2,18);e.preventDefault()},{passive:false});retry.onclick=()=>{tube.reset();resetPlayer();retry.classList.remove('show');objective.textContent='MEADOW → VILLAGE → BRIDGE → HILLSIDE → RUINS → PORTAL';toast('ROUTE RESTARTED')};
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();const clock=new THREE.Clock();let elapsed=0;function loop(){requestAnimationFrame(loop);const dt=Math.min(.033,clock.getDelta());elapsed+=dt;updatePlayer(dt);updateAction(dt);if(bro&&tube?.state==='idle')bro.update(elapsed,dt,0);tube?.update(elapsed,dt);cameraDesired(dt);renderer.render(scene,camera)}
(async()=>{try{sites=buildWorld();worldBounds=new THREE.Box3().setFromObject(world);await decorateWorld();world.updateMatrixWorld(true);worldBounds=new THREE.Box3().setFromObject(world);await createPlayer();createTube();progress('Prewarming tube and shaders…',82);await tube.prewarm();progress('World 1 Option B asset test ready',100);window.__pass='pass9-v1c';window.__world1Ready=true;window.__actionReady=true;window.__rigAnimationLive=true;setTimeout(()=>boot.classList.add('hide'),180);loop()}catch(err){console.error(err);errorEl.textContent=err?.stack||err?.message||String(err);fatal.classList.add('show')}})();