import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createGamerBro} from '../playground-v2/gamer-bro.js?v=pass3';

const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const CHARS={
 gb1:{name:'GB1',kind:'gamer',colorway:'pink',accent:0xff58b7,power:'volley'},
 gb2:{name:'GB2',kind:'gamer',colorway:'teal',accent:0x58e2e0,power:'volley'},
 citrus:{name:'Citrus',kind:'glb',file:'../pass1-v1/assets/recovered/characters/sprite_hero.glb',accent:0xff9a3d,power:'comet'},
 ghost:{name:'Ghost',kind:'glb',file:'../pass1-v1/assets/recovered/characters/ghost.glb',accent:0xf29bd7,power:'nova',metalPink:true},
 stump:{name:'Stump',kind:'glb',file:'../pass1-v1/assets/recovered/characters/stump.glb',accent:0x8ed267,power:'nova'},
 cthulhu:{name:'Cthulhu',kind:'glb',file:'../pass1-v1/assets/recovered/characters/cthulhu.glb',accent:0x9d66ff,power:'constellation'},
 yeti:{name:'Yeti',kind:'glb',file:'../pass1-v1/assets/recovered/characters/yeti.glb',accent:0xbfefff,power:'shatter'}
};
const qs=new URLSearchParams(location.search);let chosen=qs.get('hero')||localStorage.getItem('gamerBroCharacter')||'gb2';if(!CHARS[chosen])chosen='gb2';const H=CHARS[chosen];localStorage.setItem('gamerBroCharacter',chosen);
const $=s=>document.querySelector(s),canvas=$('#game'),heroName=$('#heroName'),menu=$('#menu'),coinCounter=$('#coinCounter'),checkpoint=$('#checkpoint'),powerModeBtn=$('#powerMode'),pad=$('#pad'),stick=$('#stick'),jumpBtn=$('#jump'),runBtn=$('#run'),actionBtn=$('#action'),toast=$('#toast'),boot=$('#boot'),status=$('#status'),bar=$('#bar'),fatal=$('#fatal'),errorEl=$('#error'),win=$('#win'),winText=$('#winText'),again=$('#again');heroName.textContent=H.name.toUpperCase();menu.onclick=()=>location.href='../';again.onclick=()=>location.reload();
const renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.25:1.65));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x86bee2);scene.fog=new THREE.Fog(0x86bee2,30,72);const camera=new THREE.PerspectiveCamera(45,1,.06,120);camera.layers.enable(1);const world=new THREE.Group(),fxRoot=new THREE.Group();scene.add(world,fxRoot);scene.add(new THREE.HemisphereLight(0xeaf8ff,0x566344,2.1));const sun=new THREE.DirectionalLight(0xfff1ca,3.2);sun.position.set(-24,32,16);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:1536,mobile?1024:1536);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;sun.shadow.camera.near=1;sun.shadow.camera.far=95;scene.add(sun);const rim=new THREE.DirectionalLight(0x99c6ff,.7);rim.position.set(18,10,-20);scene.add(rim);
const KEN='https://raw.githubusercontent.com/KenneyNL/Starter-Kit-3D-Platformer/main/models/';const loader=new GLTFLoader(),assetCache=new Map();function progress(t,n){status.textContent=t;bar.style.width=n+'%'}async function asset(name){if(assetCache.has(name))return assetCache.get(name);const p=loader.loadAsync(KEN+name).then(g=>g.scene);assetCache.set(name,p);return p}function prep(root){root.traverse(o=>{if(o.isMesh){o.castShadow=!mobile;o.receiveShadow=true;}});return root}
function metallicPinkGhost(root){root.traverse(o=>{if(!o.isMesh||!o.material)return;const arr=Array.isArray(o.material)?o.material:[o.material];const made=arr.map(mat=>{const m=mat.clone();if(m.color&&!/eye|pupil/i.test(o.name||'')){const l=.2126*m.color.r+.7152*m.color.g+.0722*m.color.b;if(l>.08){m.color.set(0xf0a1d3);if('metalness'in m)m.metalness=.72;if('roughness'in m)m.roughness=.14;if(m.emissive){m.emissive.set(0x541238);m.emissiveIntensity=.34;}if('clearcoat'in m){m.clearcoat=1;m.clearcoatRoughness=.055;}}}return m});o.material=Array.isArray(o.material)?made:made[0];});}
let player,visual,bro,mixer;async function buildPlayer(){player=new THREE.Group();world.add(player);player.position.set(0,.52,0);if(H.kind==='gamer'){bro=createGamerBro(THREE,renderer,{colorway:H.colorway,detail:mobile?'low':'high',height:2.62});visual=bro.root;visual.layers.enable(1);visual.traverse(o=>o.layers?.enable?.(1));player.add(visual);bro.setMotion?.('idle');}else{const g=await loader.loadAsync(H.file);visual=g.scene;visual.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(visual),sz=b.getSize(new THREE.Vector3()),k=2.5/Math.max(sz.y,.001);visual.scale.setScalar(k);visual.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(visual);const ctr=b.getCenter(new THREE.Vector3());visual.position.set(-ctr.x,-b.min.y,-ctr.z);if(H.metalPink)metallicPinkGhost(visual);prep(visual);player.add(visual);if(g.animations?.length){mixer=new THREE.AnimationMixer(visual);const clip=g.animations.find(a=>/idle/i.test(a.name))||g.animations[0];mixer.clipAction(clip).play();}}window.__characterReady=chosen;window.__characterMeshCount=0;visual.traverse(o=>{if(o.isMesh)window.__characterMeshCount++;});}

// Positions are transcribed from Kenney's authored scenes/main.tscn. We keep the route instead of designing another test map.
const PLATS=[
 ['platform.glb',0,0,0,-.118,2,2,false],['platform.glb',-15,0,4,-.118,2,2,false],['platform.glb',-21.925,.347,-2.684,.211,2,2,false],['platform.glb',-22.076,1.513,-4.765,-.21,2,2,false],['platform.glb',-3,2,-3,0,2,2,false],['platform.glb',-3,3,-5,-.261,2,2,false],
 ['platform-medium.glb',-3,0,0,-.088,3,3,false],['platform-medium.glb',-5,0,4,-.099,3,3,false],['platform-medium.glb',-14.942,.992,.128,-.377,3,3,false],['platform-medium.glb',0,3,-6,0,3,3,false],
 ['platform-falling.glb',-9,.419,4,.175,2,2,true],['platform-falling.glb',-12,-.315,4,-.105,2,2,true],['platform-falling.glb',-11.753,1.83,-2.306,.349,2,2,true],
 ['platform-grass-large-round.glb',-7,1,-2,0,5.2,5.2,false],['platform-grass-large-round.glb',-19.31,1,2.832,0,5.2,5.2,false]
];
const COINS=[[-3,.635,0],[-5,.635,4],[-7.044,1.97,-.33],[-7.044,1.97,-1.33],[-11.773,2.549,-2.282],[-14.811,1.689,.329],[-14.811,2.689,.329],[-14.965,.802,3.994],[0,5,-6],[-7.044,1.97,-2.33],[-6.709,5.339,-2.004],[-18.979,1.775,2.862],[-22.117,2.561,-4.757],[-22.117,3.321,-4.757]];
const colliders=[],falling=[],coinObjs=[];let flagObj=null;const fallbackMat=new THREE.MeshStandardMaterial({color:0x6fb05d,roughness:.88});function makeFallback(p){const g=new THREE.BoxGeometry(p[5],.5,p[6]),m=fallbackMat.clone();m.color.offsetHSL((p[1]*.013)%1,0,0);const o=new THREE.Mesh(g,m);o.position.set(p[1],p[2]+.25,p[3]);o.rotation.y=p[4];o.castShadow=!mobile;o.receiveShadow=true;world.add(o);return o}
async function addPlatform(p){const [file,x,y,z,yaw,w,d,isFalling]=p,fb=makeFallback(p);const c={x,y,z,yaw,w,d,h:.5,baseY:y,drop:0,falling:isFalling,state:'idle',timer:0,mesh:fb};colliders.push(c);if(isFalling)falling.push(c);try{const src=await asset(file),o=prep(src.clone(true));o.position.set(x,y,z);o.rotation.y=yaw;world.add(o);world.remove(fb);c.mesh=o;}catch(e){console.warn('platform fallback',file,e);}}
function makeCoinFallback(pos){const g=new THREE.TorusGeometry(.28,.09,8,18),m=new THREE.MeshStandardMaterial({color:0xffd33d,metalness:.35,roughness:.25,emissive:0x7b3f00,emissiveIntensity:.15});const o=new THREE.Mesh(g,m);o.position.set(...pos);o.rotation.y=Math.PI/2;o.castShadow=false;world.add(o);return o}async function addCoin(pos,i){let o=makeCoinFallback(pos);const c={o,pos:new THREE.Vector3(...pos),taken:false,phase:i*.37};coinObjs.push(c);try{const src=await asset('coin.glb'),real=prep(src.clone(true));real.position.set(...pos);world.add(real);world.remove(o);c.o=real;}catch{}}
async function addFlag(){try{const src=await asset('flag.glb');flagObj=prep(src.clone(true));flagObj.position.set(0,3.481,-6);flagObj.rotation.y=-Math.PI/4;world.add(flagObj);}catch{const pole=new THREE.Mesh(new THREE.CylinderGeometry(.045,.055,3,8),new THREE.MeshStandardMaterial({color:0xeeeeee}));pole.position.set(0,4.5,-6);const cloth=new THREE.Mesh(new THREE.PlaneGeometry(1.5,.8),new THREE.MeshStandardMaterial({color:0xff4f64,side:THREE.DoubleSide}));cloth.position.set(.75,5.3,-6);world.add(pole,cloth);flagObj=pole;}}
async function addClouds(){try{const src=await asset('cloud.glb');for(const p of[[4,5,-5,1],[-10,7,11,1.4],[-14,6,-8,1.6],[3,4,-3,1.2]]){const o=src.clone(true);o.position.set(p[0],p[1],p[2]);o.scale.setScalar(p[3]);world.add(o);}}catch{}}

function localXZ(x,z,c){const dx=x-c.x,dz=z-c.z,co=Math.cos(-c.yaw),si=Math.sin(-c.yaw);return{x:dx*co-dz*si,z:dx*si+dz*co}}function topOf(c){return c.baseY+c.drop+.5}function insideTop(x,z,c,margin=.18){const p=localXZ(x,z,c);return Math.abs(p.x)<=c.w/2-margin&&Math.abs(p.z)<=c.d/2-margin}function insideBody(x,z,c,r=.34){const p=localXZ(x,z,c);return Math.abs(p.x)<=c.w/2+r&&Math.abs(p.z)<=c.d/2+r}
const spawn=new THREE.Vector3(0,.52,0);let vx=0,vz=0,vy=0,grounded=false,standing=null;function respawn(msg='Respawn'){player.position.copy(spawn);vy=0;grounded=false;standing=null;showToast(msg);checkpoint.textContent='START';}
function solveHorizontal(nx,nz){for(const c of colliders){if(c.drop<-6)continue;const top=topOf(c),bottom=c.baseY+c.drop;if(player.position.y<top-.09&&player.position.y+1.65>bottom+.03&&insideBody(nx,nz,c,.32)){return{x:player.position.x,z:player.position.z};}}return{x:nx,z:nz}}
function solveVertical(prevY,newY){standing=null;if(vy<=0){let best=null,bestTop=-1e9;for(const c of colliders){if(c.drop<-6||!insideTop(player.position.x,player.position.z,c,.12))continue;const top=topOf(c);if(prevY>=top-.16&&newY<=top+.05&&top>bestTop){best=c;bestTop=top;}}if(best){newY=bestTop;vy=0;grounded=true;standing=best;if(best.falling&&best.state==='idle'){best.state='arming';best.timer=.55;}}else grounded=false;}return newY}
function updateFalling(dt){for(const c of falling){if(c.state==='arming'){c.timer-=dt;if(c.timer<=0){c.state='fall';c.timer=0;}}else if(c.state==='fall'){c.timer+=dt;c.drop-=dt*dt*11+dt*(1.3+c.timer*4.5);if(c.mesh)c.mesh.position.y=c.baseY+c.drop;if(c.drop<-8){c.state='reset';c.timer=2.3;}}else if(c.state==='reset'){c.timer-=dt;if(c.timer<=0){c.drop=0;c.state='idle';if(c.mesh)c.mesh.position.y=c.baseY;}}}}

const input={x:0,y:0,run:false},keys={};let stickPointer=null;function setStick(clientX,clientY){const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,lim=r.width*.34;let x=clientX-cx,y=clientY-cy,d=Math.hypot(x,y);if(d>lim){x=x/d*lim;y=y/d*lim;}input.x=x/lim;input.y=-y/lim;stick.style.transform=`translate3d(${x}px,${y}px,0)`}function clearStick(){stickPointer=null;input.x=input.y=0;stick.style.transform='translate3d(0,0,0)'}pad.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();stickPointer=e.pointerId;pad.setPointerCapture?.(e.pointerId);setStick(e.clientX,e.clientY)});pad.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer){e.preventDefault();setStick(e.clientX,e.clientY)}});pad.addEventListener('pointerup',clearStick);pad.addEventListener('pointercancel',clearStick);pad.addEventListener('touchstart',e=>{e.preventDefault();const t=e.changedTouches[0];setStick(t.clientX,t.clientY)},{passive:false});pad.addEventListener('touchmove',e=>{e.preventDefault();const t=e.changedTouches[0];setStick(t.clientX,t.clientY)},{passive:false});pad.addEventListener('touchend',clearStick,{passive:false});
runBtn.onpointerdown=e=>{e.preventDefault();input.run=true;runBtn.classList.add('active')};runBtn.onpointerup=runBtn.onpointercancel=()=>{input.run=false;runBtn.classList.remove('active')};function jump(){if(grounded){vy=7.25;grounded=false;standing=null;jumpBtn.classList.add('active');setTimeout(()=>jumpBtn.classList.remove('active'),110)}}jumpBtn.onpointerdown=e=>{e.preventDefault();jump()};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space')jump();if(e.code==='KeyE')firePower()});addEventListener('keyup',e=>keys[e.code]=false);
let camYaw=.78,camPitch=.34,camDist=8,lastLook=0,lookPointer=null,lastX=0,lastY=0,pinchDist=0;canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&e.isPrimary===false)return;lookPointer=e.pointerId;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==lookPointer)return;camYaw-=(e.clientX-lastX)*.006;camPitch=THREE.MathUtils.clamp(camPitch+(e.clientY-lastY)*.004,.12,.68);lastX=e.clientX;lastY=e.clientY;lastLook=performance.now()});canvas.addEventListener('pointerup',e=>{if(e.pointerId===lookPointer)lookPointer=null});canvas.addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();const a=e.touches[0],b=e.touches[1],d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);if(pinchDist)camDist=THREE.MathUtils.clamp(camDist-(d-pinchDist)*.012,5.2,11);pinchDist=d;}},{passive:false});canvas.addEventListener('touchend',()=>pinchDist=0,{passive:true});

const starShape=new THREE.Shape();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?.43:1,x=Math.cos(a)*r,y=Math.sin(a)*r;i?starShape.lineTo(x,y):starShape.moveTo(x,y)}starShape.closePath();const starGeo=new THREE.ShapeGeometry(starShape);const activeFx=[];function fwd(){return new THREE.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y)).normalize()}function starMesh(color,size=.25){const m=new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});const o=new THREE.Mesh(starGeo,m);o.scale.setScalar(size);return o}function pushFx(o,life,fn){fxRoot.add(o);activeFx.push({o,life,max:life,fn});window.__powerCount=(window.__powerCount||0)+1}
function projectile(color,offset=.0,speed=10,size=.23,life=1.1){const d=fwd(),right=new THREE.Vector3(d.z,0,-d.x),g=new THREE.Group(),main=starMesh(color,size);g.add(main);for(let i=1;i<=4;i++){const t=starMesh(i%2?0xffffff:color,size*(.55-i*.07));t.position.z=-i*.24;t.material.opacity=.65-i*.1;g.add(t)}g.position.copy(player.position).add(new THREE.Vector3(0,1.25,0)).addScaledVector(d,.8).addScaledVector(right,offset);g.rotation.y=player.rotation.y;pushFx(g,life,(o,left,dt)=>{o.position.addScaledVector(d,speed*dt);o.rotation.z+=dt*7;o.children.forEach((s,i)=>s.material&&(s.material.opacity=Math.max(0,left/life)*(i?0.65:1)))})}
function volley(){const cols=[H.accent,0xff69cb,0xffd75c,0x72eaff,0xffffff];[-.38,-.18,0,.18,.38].forEach((off,i)=>setTimeout(()=>projectile(cols[i%cols.length],off,11+i*.25,.2+i*.012,1.15),i*55))}
function comet(){const cols=chosen==='citrus'?[0xff4ca8,0xffa739,0xffe35b,0x71e8ff,0x9b70ff,0x7af09b]:[H.accent,0xffffff,0xff73cd],d=fwd(),g=new THREE.Group();for(let i=0;i<10;i++){const s=starMesh(cols[i%cols.length],i===0?.42:.22*(1-i*.055));s.position.z=-i*.28;s.position.y=Math.sin(i*1.7)*.08;s.material.opacity=1-i*.075;g.add(s)}g.position.copy(player.position).add(new THREE.Vector3(0,1.35,0)).addScaledVector(d,.85);g.rotation.y=player.rotation.y;pushFx(g,1.35,(o,left,dt)=>{o.position.addScaledVector(d,10.5*dt);o.rotation.z+=dt*4.4;o.children.forEach((s,i)=>{s.rotation.z-=dt*(3+i*.25);s.material.opacity=Math.max(0,left/1.35)*(1-i*.07)})})}
function nova(colors=[H.accent,0xffffff]){const g=new THREE.Group();g.position.copy(player.position).add(new THREE.Vector3(0,.32,0));for(let i=0;i<14;i++){const a=i*Math.PI*2/14,s=starMesh(colors[i%colors.length],.18+(i%3)*.025);s.userData.dir=new THREE.Vector3(Math.cos(a),.08+Math.sin(i*.8)*.08,Math.sin(a));s.rotation.z=a;g.add(s)}const ring=new THREE.Mesh(new THREE.RingGeometry(.65,.72,48),new THREE.MeshBasicMaterial({color:colors[0],side:THREE.DoubleSide,transparent:true,opacity:.6,depthWrite:false,blending:THREE.AdditiveBlending}));ring.rotation.x=-Math.PI/2;g.add(ring);pushFx(g,1.0,(o,left,dt)=>{const p=1-left;for(const s of o.children){if(s.userData.dir){s.position.addScaledVector(s.userData.dir,dt*(4.5+p*4));s.rotation.z+=dt*5;s.material.opacity=Math.max(0,left)}else{s.scale.setScalar(1+p*7);s.material.opacity=left*.55}}})}
function constellation(){const g=new THREE.Group();g.position.copy(player.position).add(new THREE.Vector3(0,1.2,0));const cols=[0x7a35ff,0xe06cff,0x66e5ff,0xffffff];for(let i=0;i<9;i++){const a=i*Math.PI*2/9,s=starMesh(cols[i%cols.length],.18+(i%2)*.07);s.position.set(Math.cos(a)*(.9+i*.035),(i%3-.7)*.24,Math.sin(a)*(.9+i*.035));s.userData.a=a;s.userData.r=.9+i*.035;g.add(s)}pushFx(g,1.45,(o,left,dt)=>{o.rotation.y+=dt*5.5;o.rotation.z+=dt*1.4;const p=1-left/1.45;o.scale.setScalar(1+p*1.8);o.position.y+=dt*.35;o.children.forEach(s=>s.material.opacity=Math.max(0,left/1.45))})}
function shatter(){const d=fwd(),right=new THREE.Vector3(d.z,0,-d.x),cols=[0xffffff,0xbff7ff,0x6fdcff,0x94a8ff];for(let i=0;i<11;i++){const o=(i-5)*.12;setTimeout(()=>projectile(cols[i%cols.length],o,9.5+(i%3)*1.4,.14+(i%4)*.018,.9),i*22)}}
let powerMode='unique';const modes=['unique','volley','nova','comet'];powerModeBtn.onclick=()=>{powerMode=modes[(modes.indexOf(powerMode)+1)%modes.length];powerModeBtn.querySelector('strong').textContent=powerMode.toUpperCase()};function firePower(){if(!player)return;actionBtn.classList.add('active');setTimeout(()=>actionBtn.classList.remove('active'),120);const p=powerMode==='unique'?H.power:powerMode;if(p==='volley')volley();else if(p==='comet')comet();else if(p==='constellation')constellation();else if(p==='shatter')shatter();else if(p==='nova')nova(chosen==='ghost'?[0xf49bd8,0xffffff,0xff6ec7]:chosen==='stump'?[0x84db72,0xffd866,0xffffff]:[H.accent,0xffffff]);}actionBtn.onpointerdown=e=>{e.preventDefault();firePower()};

let collected=0,won=false;function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1100)}function collectCoins(now,dt){for(const c of coinObjs){if(c.taken)continue;c.o.rotation.y+=dt*2.8;c.o.position.y=c.pos.y+Math.sin(now*.003+c.phase)*.08;if(c.o.position.distanceTo(player.position.clone().add(new THREE.Vector3(0,.7,0)))<.9){c.taken=true;c.o.visible=false;collected++;coinCounter.textContent=`COINS · ${collected} / ${COINS.length}`;showToast('✦ COIN '+collected);}}}function checkGoal(){if(won)return;const dx=player.position.x,dz=player.position.z+6;if(Math.hypot(dx,dz)<1.3&&player.position.y>3.15){won=true;winText.textContent=collected===COINS.length?`Perfect run — all ${COINS.length} coins collected.`:`Level clear — ${collected} / ${COINS.length} coins collected.`;win.classList.add('show');window.__levelClear=true;}}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize,{passive:true});resize();const camTarget=new THREE.Vector3(),desired=new THREE.Vector3(),move=new THREE.Vector3(),lastPos=new THREE.Vector3();let last=performance.now(),animTime=0;
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,(now-last)/1000);last=now;animTime+=dt;if(!player)return;updateFalling(dt);let ix=input.x+(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),iy=input.y+(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),mag=Math.min(1,Math.hypot(ix,iy));if(mag>.001){const len=Math.max(1,Math.hypot(ix,iy));ix/=len;iy/=len;const forward=new THREE.Vector3(-Math.sin(camYaw),0,-Math.cos(camYaw)),right=new THREE.Vector3(Math.cos(camYaw),0,-Math.sin(camYaw));move.copy(forward).multiplyScalar(iy).addScaledVector(right,ix).normalize();const speed=(input.run||keys.ShiftLeft||keys.ShiftRight)?6.8:4.25;const nx=player.position.x+move.x*speed*mag*dt,nz=player.position.z+move.z*speed*mag*dt,res=solveHorizontal(nx,nz);player.position.x=res.x;player.position.z=res.z;const target=Math.atan2(move.x,move.z),diff=Math.atan2(Math.sin(target-player.rotation.y),Math.cos(target-player.rotation.y));player.rotation.y+=diff*(1-Math.exp(-dt*13));if(now-lastLook>900){const targetCam=target+Math.PI,d=Math.atan2(Math.sin(targetCam-camYaw),Math.cos(targetCam-camYaw));camYaw+=d*(1-Math.exp(-dt*2.2));}}const prevY=player.position.y;vy-=18*dt;let ny=player.position.y+vy*dt;ny=solveVertical(prevY,ny);player.position.y=ny;if(player.position.y<-8)respawn('MISSED · RESPAWN');if(standing?.falling&&standing.state==='fall'&&standing.drop<-1.5)grounded=false;try{if(bro){bro.setMotion?.(mag>.1?(input.run?'run':'walk'):'idle');bro.update?.(animTime,dt,mag);}if(mixer)mixer.update(dt*(mag>.05?1.25:.8));}catch{}collectCoins(now,dt);checkGoal();camTarget.set(player.position.x,player.position.y+1.25,player.position.z);desired.set(camTarget.x+Math.sin(camYaw)*Math.cos(camPitch)*camDist,camTarget.y+Math.sin(camPitch)*camDist+.45,camTarget.z+Math.cos(camYaw)*Math.cos(camPitch)*camDist);camera.position.lerp(desired,1-Math.exp(-dt*8));camera.lookAt(camTarget);for(let i=activeFx.length-1;i>=0;i--){const f=activeFx[i];f.life-=dt;f.fn?.(f.o,f.life,dt);if(f.life<=0){fxRoot.remove(f.o);activeFx.splice(i,1)}}renderer.render(scene,camera);window.__playerPosition={x:player.position.x,y:player.position.y,z:player.position.z};}

(async()=>{try{progress('Loading your character…',12);await buildPlayer();progress('Loading Kenney platform set…',28);const tasks=PLATS.map(addPlatform);progress('Restoring Kenney authored layout…',46);await Promise.allSettled(tasks);progress('Adding original coin route…',66);await Promise.allSettled(COINS.map(addCoin));progress('Adding finish flag and scenery…',82);await Promise.allSettled([addFlag(),addClouds()]);progress('Activating collision, falling platforms and powers…',96);await new Promise(r=>setTimeout(r,100));window.__pass3Ready=true;window.__authoredPlatformCount=colliders.length;window.__coinCount=coinObjs.length;progress('Ready',100);setTimeout(()=>boot.classList.add('hide'),120);requestAnimationFrame(frame);}catch(e){console.error(e);errorEl.textContent=String(e?.message||e);fatal.classList.add('show')}})();
