import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';

// Pass 5 direct Crystal Gate integration. This deliberately avoids the old runtime
// discovery bridge and captures the live renderer/scene/camera on the first game render.
const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const loader=new GLTFLoader();
const nativeRender=THREE.WebGLRenderer.prototype.render;
const S={renderer:null,scene:null,camera:null,player:null,visual:null,root:null,core:null,coreMat:null,ring:null,halo:null,light:null,crystals:[],materials:[],particleGeo:null,particles:null,particleBase:null,box:new THREE.Box3(),bottom:0,top:3.3,position:new THREE.Vector3(-10,.1,7),yaw:0,phase:'boot',phaseAt:0,freeze:new THREE.Vector3(),warm:false,warming:false,ready:false,last:performance.now()};
window.__naturePortalBridge=true;
window.__portalDebug={module:'pass5-direct',loaded:true};

function toast(text,ms=1450){const el=document.getElementById('toast');if(!el)return;el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),ms);}
function fitRoot(root,target=5.35){root.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(root),sz=b.getSize(new THREE.Vector3()),k=target/Math.max(.001,sz.y);root.scale.multiplyScalar(k);root.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(root);const c=b.getCenter(new THREE.Vector3());root.position.x-=c.x;root.position.z-=c.z;root.position.y-=b.min.y;return root;}
function portalMaterial(){return new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},uCharge:{value:.18}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`varying vec2 vUv;uniform float uTime;uniform float uCharge;void main(){vec2 p=vUv-.5;float r=length(p)*2.;float a=atan(p.y,p.x);float swirl=sin(a*5.-r*12.+uTime*3.)*.5+.5;float bands=sin(r*22.-uTime*4.2+swirl*2.2)*.5+.5;float edge=smoothstep(1.,.79,r);float center=smoothstep(1.,.04,r);vec3 cyan=vec3(.16,.92,1.),pink=vec3(1.,.18,.72),violet=vec3(.42,.23,1.);vec3 col=mix(cyan,pink,swirl);col=mix(col,violet,bands*.34);float spark=pow(max(0.,sin(a*13.+uTime*5.-r*17.)),12.)*.45;float alpha=edge*center*(.34+.46*bands+.24*uCharge);gl_FragColor=vec4(col*(.74+bands*.7+spark+uCharge*.58),alpha);}`});}
function buildPortal(){const root=new THREE.Group();S.root=root;S.scene.add(root);root.position.copy(S.position);const dx=S.player.position.x-root.position.x,dz=S.player.position.z-root.position.z;S.yaw=Math.atan2(dx,dz);root.rotation.y=S.yaw;
  S.coreMat=portalMaterial();S.core=new THREE.Mesh(new THREE.CircleGeometry(1.58,64),S.coreMat);S.core.position.set(0,2.62,.08);S.core.renderOrder=4;root.add(S.core);
  const bronze=new THREE.MeshPhysicalMaterial({color:0xb87942,metalness:.78,roughness:.2,clearcoat:.8,clearcoatRoughness:.09,emissive:0x241006,emissiveIntensity:.23});S.ring=new THREE.Mesh(new THREE.TorusGeometry(1.72,.11,12,80),bronze);S.ring.position.y=2.62;root.add(S.ring);
  S.halo=new THREE.Mesh(new THREE.TorusGeometry(1.9,.04,8,80),new THREE.MeshBasicMaterial({color:0x84efff,transparent:true,opacity:.42,blending:THREE.AdditiveBlending,depthWrite:false}));S.halo.position.set(0,2.62,.04);root.add(S.halo);
  const mats=[0xff62c9,0x7aeaff,0xa879ff].map(c=>new THREE.MeshPhysicalMaterial({color:c,emissive:c,emissiveIntensity:1.2,roughness:.14,metalness:.08,clearcoat:1,clearcoatRoughness:.04,transparent:true,opacity:.95}));for(let i=0;i<8;i++){const a=i/8*Math.PI*2,c=new THREE.Mesh(new THREE.OctahedronGeometry(.23,0),mats[i%3]);c.scale.set(.65,1.85,.65);c.position.set(Math.cos(a)*2.02,2.62+Math.sin(a)*2.02,.07);c.rotation.z=-a+.4;root.add(c);S.crystals.push(c)}
  S.light=new THREE.PointLight(0x75eaff,7.5,13,1.7);S.light.position.set(0,2.65,1);root.add(S.light);
  loader.loadAsync('../pass1-v1/assets/recovered/kit/arch.glb').then(g=>{const arch=fitRoot(g.scene,5.35);arch.position.z=-.1;arch.traverse(o=>{if(o.isMesh){o.castShadow=!mobile;o.receiveShadow=true}});root.add(arch);window.__naturePortalArch=true}).catch(e=>console.warn('[Pass5 Crystal Gate] arch unavailable',e));
  window.__naturePortalPosition={x:root.position.x,y:root.position.y,z:root.position.z};window.__naturePortalReady=true;window.__naturePortalState='idle';S.ready=true;S.phase='idle';
}
function installDissolve(){S.visual.updateMatrixWorld(true);S.box.setFromObject(S.visual);S.bottom=S.box.min.y+.02;S.top=S.box.max.y-.02;const seen=new Set();S.visual.traverse(o=>{if(!o.isMesh||!o.material)return;const src=Array.isArray(o.material)?o.material:[o.material],out=[];for(const original of src){if(!original||original.isShaderMaterial){out.push(original);continue}const m=original.clone();const prior=m.onBeforeCompile?.bind(m),priorKey=m.customProgramCacheKey?.bind(m);m.onBeforeCompile=shader=>{prior?.(shader);shader.uniforms.uGBDissolve={value:0};shader.uniforms.uGBCut={value:-999};shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying float vGBWorldY;').replace('#include <project_vertex>','#include <project_vertex>\nvGBWorldY=(modelMatrix*vec4(transformed,1.0)).y;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nuniform float uGBDissolve;uniform float uGBCut;varying float vGBWorldY;').replace('#include <dithering_fragment>',`if(uGBDissolve>.5){float n=fract(sin(dot(gl_FragCoord.xy+vec2(vGBWorldY*17.13),vec2(12.9898,78.233)))*43758.5453);float th=uGBCut+(n-.5)*.24;if(vGBWorldY<th)discard;float edge=1.0-smoothstep(.02,.25,abs(vGBWorldY-uGBCut));gl_FragColor.rgb+=vec3(1.0,.16,.68)*edge*1.4;}\n#include <dithering_fragment>`);m.userData._gbPortalShader=shader};m.customProgramCacheKey=()=>`${priorKey?.()||''}|gb-pass5-dissolve-v1`;m.needsUpdate=true;S.materials.push(m);out.push(m);seen.add(original)}o.material=Array.isArray(o.material)?out:out[0]});
  const count=mobile?170:300,pos=new Float32Array(count*3),base=new Float32Array(count*3),col=new Float32Array(count*3),size=S.box.getSize(new THREE.Vector3()),center=S.box.getCenter(new THREE.Vector3());for(let i=0;i<count;i++){const j=i*3,x=center.x+(Math.random()-.5)*size.x*.82,y=S.bottom+Math.random()*(S.top-S.bottom),z=center.z+(Math.random()-.5)*size.z*.72;base[j]=x-S.player.position.x;base[j+1]=y-S.player.position.y;base[j+2]=z-S.player.position.z;pos[j]=x;pos[j+1]=y;pos[j+2]=z;const c=new THREE.Color([0xff59c7,0x75eaff,0xb080ff,0xffd75f][i%4]);col[j]=c.r;col[j+1]=c.g;col[j+2]=c.b}
  const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3).setUsage(THREE.DynamicDrawUsage));geo.setAttribute('color',new THREE.BufferAttribute(col,3));const mat=new THREE.PointsMaterial({size:mobile?.075:.09,vertexColors:true,transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false,sizeAttenuation:true});S.particles=new THREE.Points(geo,mat);S.particles.frustumCulled=false;S.scene.add(S.particles);S.particleGeo=geo;S.particleBase=base;window.__naturePortalPrepared=true}
function setDissolve(active,cut){for(const m of S.materials){const sh=m.userData._gbPortalShader;if(sh){sh.uniforms.uGBDissolve.value=active?1:0;sh.uniforms.uGBCut.value=cut}}}
function warm(){if(S.warming)return;S.warming=true;const done=()=>{S.warm=true;window.__naturePortalPrewarmed=true;window.__portalDebug.warm='ready'};try{const p=S.renderer.compileAsync?.(S.scene,S.camera);if(p?.then)p.then(done).catch(e=>{console.warn('[Pass5 Crystal Gate] compileAsync fallback',e);S.renderer.compile?.(S.scene,S.camera);done()});else{S.renderer.compile?.(S.scene,S.camera);done()}}catch(e){console.warn('[Pass5 Crystal Gate] prewarm fallback',e);done()}}
function findPlayer(scene){const ref=window.__playerPosition;if(!ref)return null;let found=null;scene.traverse(o=>{if(!found&&o.position===ref)found=o});return found}
function init(renderer,scene,camera){if(S.ready)return true;const p=findPlayer(scene);if(!p)return false;S.renderer=renderer;S.scene=scene;S.camera=camera;S.player=p;S.visual=p.children[0]||p;S.position.y=.1;installDissolve();buildPortal();if('requestIdleCallback'in window)requestIdleCallback(warm,{timeout:700});else setTimeout(warm,80);window.__naturePortalTarget='crystal-library';window.__portalDebug.initialized=true;return true}
function begin(now){if(S.phase!=='idle')return;if(!S.warm){warm();toast('CRYSTAL GATE · WARMING ENERGY');return}S.phase='charge';S.phaseAt=now;S.freeze.copy(S.player.position);window.__naturePortalState='charge';toast('CRYSTAL GATE · TRANSFER LOCKED',1700)}
function updateParticles(p){const arr=S.particleGeo.attributes.position.array,base=S.particleBase,center=S.position.clone().add(new THREE.Vector3(0,2.62,0));for(let i=0;i<arr.length;i+=3){const n=i/3,seed=(n*12.9898)%6.283,scatter=Math.sin(seed+p*8)*.25*(1-p),sx=S.freeze.x+base[i],sy=S.freeze.y+base[i+1],sz=S.freeze.z+base[i+2],pull=Math.max(0,(p-.12)/.88);arr[i]=THREE.MathUtils.lerp(sx,center.x,pull)+Math.cos(seed)*scatter;arr[i+1]=THREE.MathUtils.lerp(sy,center.y,pull)+p*.75+Math.sin(seed*1.7)*scatter;arr[i+2]=THREE.MathUtils.lerp(sz,center.z,pull)+Math.sin(seed)*scatter}S.particleGeo.attributes.position.needsUpdate=true}
function animate(now,dt){if(!S.ready)return;const t=now*.001;S.coreMat.uniforms.uTime.value=t;S.ring.rotation.z=t*.16;S.halo.rotation.z=-t*.28;S.halo.material.opacity=.34+Math.sin(t*2.3)*.08;for(let i=0;i<S.crystals.length;i++){const c=S.crystals[i];c.rotation.y+=dt*(.4+i*.02);c.material.emissiveIntensity=.9+Math.sin(t*2.8+i)*.33}S.light.intensity=7+Math.sin(t*3.1)*1.5;
  if(S.phase==='idle'){S.coreMat.uniforms.uCharge.value=.18;const d=Math.hypot(S.player.position.x-S.root.position.x,S.player.position.z-S.root.position.z);if(d<1.7)begin(now);return}
  S.player.position.copy(S.freeze);const e=(now-S.phaseAt)/1000;if(S.phase==='charge'){const p=Math.min(1,e/.55);S.coreMat.uniforms.uCharge.value=.18+p*.8;S.light.intensity=7+p*8;if(p>=1){S.phase='convert';S.phaseAt=now;window.__naturePortalState='convert';setDissolve(true,S.bottom-.16)}}else if(S.phase==='convert'){const p=Math.min(1,e/.66),cut=THREE.MathUtils.lerp(S.bottom-.16,S.top+.2,p);setDissolve(true,cut);S.particles.material.opacity=Math.min(.92,p*1.2);updateParticles(p*.7);S.coreMat.uniforms.uCharge.value=1+p*.35;if(p>=1){S.phase='dissipate';S.phaseAt=now;window.__naturePortalState='dissipate';S.visual.visible=false}}else if(S.phase==='dissipate'){const p=Math.min(1,e/.48);S.particles.material.opacity=.9*(1-p*.45);updateParticles(.7+p*.3);S.coreMat.uniforms.uCharge.value=1.35-p*.18;if(p>=1){S.phase='afterglow';S.phaseAt=now;window.__naturePortalState='afterglow'}}else if(S.phase==='afterglow'){const p=Math.min(1,e/.52);S.particles.material.opacity=.48*(1-p);S.coreMat.uniforms.uCharge.value=1.17-p*.42;S.light.intensity=16*(1-p)+7;if(p>=1){window.__naturePortalState='transfer';const hero=encodeURIComponent(localStorage.getItem('gamerBroCharacter')||'gb2');location.href=`../hybrid-v09/?from=diorama-adventure&hero=${hero}&portal=prewarmed`}}
}
THREE.WebGLRenderer.prototype.render=function(scene,camera){const now=performance.now(),dt=Math.min(.04,(now-S.last)/1000);S.last=now;if(window.__pass5Ready&&!S.ready){try{init(this,scene,camera)}catch(e){console.error('[Pass5 Crystal Gate] init failed',e);window.__portalDebug.error=String(e)}}if(S.ready){animate(now,dt);if(S.phase!=='idle'){const center=S.position.clone().add(new THREE.Vector3(0,2.5,0)),side=new THREE.Vector3(Math.sin(S.yaw+1.05)*6.4,3.2,Math.cos(S.yaw+1.05)*6.4);camera.position.lerp(center.clone().add(side),1-Math.exp(-dt*2.3));camera.lookAt(center.clone().lerp(S.freeze.clone().add(new THREE.Vector3(0,1.4,0)),.42))}}return nativeRender.call(this,scene,camera)};
