import * as THREE from 'three';

export function createEnemySystem({parent,groundAt,getPlayerPosition,damagePlayer,onEnemyKilled=()=>{},toast=()=>{}}){
  const enemies=[];let nextId=1;const tmp=new THREE.Vector3();
  const dark=new THREE.MeshStandardMaterial({color:0x202638,roughness:.52,metalness:.08});
  const dark2=new THREE.MeshStandardMaterial({color:0x101624,roughness:.55});
  const yellow=new THREE.MeshStandardMaterial({color:0xffdc43,emissive:0xe89400,emissiveIntensity:.34,roughness:.4});
  const red=new THREE.MeshStandardMaterial({color:0xf3485f,roughness:.48});
  const pale=new THREE.MeshStandardMaterial({color:0xd9e4e7,roughness:.55});
  const cyan=new THREE.MeshStandardMaterial({color:0x42dce9,emissive:0x168ca3,emissiveIntensity:.18,roughness:.38});
  function addMesh(g,geo,mat,pos=[0,0,0],scale=[1,1,1]){const m=new THREE.Mesh(geo,mat);m.position.set(...pos);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=false;g.add(m);return m}
  function eyes(g,y=.9,z=.66,spread=.26){for(const s of [-1,1]){const eye=addMesh(g,new THREE.SphereGeometry(.105,12,8),yellow,[s*spread,y,z],[1,.72,.45]);eye.name='glow-eye'}}
  function makePatrol(){const g=new THREE.Group();addMesh(g,new THREE.SphereGeometry(.68,20,14),dark,[0,.72,0],[1,1,.94]);addMesh(g,new THREE.SphereGeometry(.57,18,12),dark2,[0,.68,.12],[1,.9,.88]);eyes(g,.84,.59,.25);for(const s of [-1,1]){addMesh(g,new THREE.SphereGeometry(.18,12,8),yellow,[s*.38,.13,.03],[1.05,.55,1.25])}const cap=addMesh(g,new THREE.CylinderGeometry(.48,.43,.18,18),red,[0,1.31,0]);cap.rotation.z=.02;addMesh(g,new THREE.BoxGeometry(.63,.08,.28),red,[0,1.24,.2]);g.userData.kind='patrol';return g}
  function makeSpiker(){const g=new THREE.Group();addMesh(g,new THREE.SphereGeometry(.72,20,14),dark,[0,.73,0],[1,1,.95]);eyes(g,.81,.62,.24);const dirs=[[1,0,0],[-1,0,0],[0,0,1],[0,0,-1],[.7,.65,.2],[-.7,.65,.2],[0,.88,-.25]];for(const [x,y,z] of dirs){const sp=addMesh(g,new THREE.ConeGeometry(.15,.55,7),pale,[x*.68,.68+y*.68,z*.68]);const q=new THREE.Vector3(x,y,z).normalize();sp.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),q)}for(const s of [-1,1])addMesh(g,new THREE.SphereGeometry(.16,10,8),yellow,[s*.34,.12,.02],[1,.5,1.15]);g.userData.kind='spiker';return g}
  function makeFlyer(){const g=new THREE.Group();addMesh(g,new THREE.SphereGeometry(.6,20,14),dark,[0,.9,0],[1,.88,.96]);eyes(g,.94,.55,.23);addMesh(g,new THREE.CylinderGeometry(.32,.38,.18,14),red,[0,1.42,0]);const mast=addMesh(g,new THREE.CylinderGeometry(.055,.055,.4,8),pale,[0,1.64,0]);const rotor=new THREE.Group();rotor.position.y=1.84;g.add(rotor);for(const a of [0,Math.PI/2]){const blade=addMesh(rotor,new THREE.BoxGeometry(1.45,.05,.18),cyan);blade.rotation.y=a}rotor.name='rotor';g.userData.rotor=rotor;g.userData.kind='flyer';return g}
  function telegraphMesh(){const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(.86,.06,8,34),new THREE.MeshBasicMaterial({color:0xff536e,transparent:true,opacity:.8,depthWrite:false}));ring.rotation.x=Math.PI/2;ring.position.y=.045;g.add(ring);const cone=new THREE.Mesh(new THREE.ConeGeometry(.13,.44,9),new THREE.MeshBasicMaterial({color:0xffe0e5,transparent:true,opacity:.9,depthWrite:false}));cone.position.y=2.25;cone.rotation.z=Math.PI;g.add(cone);g.visible=false;return g}
  function spawnOne(spec,index){const root=spec.kind==='spiker'?makeSpiker():spec.kind==='flyer'?makeFlyer():makePatrol();root.position.set(spec.x,spec.y,spec.z);parent.add(root);const e={id:nextId++,root,home:new THREE.Vector3(spec.x,spec.y,spec.z),hp:2,alive:true,state:'patrol',timer:.5+index*.12,alertRadius:spec.kind==='flyer'?10:8.8,attackRange:spec.kind==='spiker'?1.85:2.25,walkSpeed:spec.kind==='spiker'?1.45:spec.kind==='flyer'?2.1:2.3,lungeSpeed:spec.kind==='spiker'?4.4:6.3,hitSerial:-1,telegraph:telegraphMesh(),knock:new THREE.Vector3(),didContact:false,deathTimer:0,patrolPhase:index*1.75,kind:spec.kind||'patrol',baseY:spec.y};root.add(e.telegraph);enemies.push(e);return e}
  async function spawnAll(spawns){for(let i=0;i<spawns.length;i++)spawnOne(spawns[i],i);window.__pass17EnemyModelsReady=enemies.length;window.__pass17EnemyKinds=[...new Set(enemies.map(e=>e.kind))];document.documentElement.dataset.enemies=String(enemies.length);document.documentElement.dataset.enemyKinds=window.__pass17EnemyKinds.join(',');return enemies}
  function setState(e,state,time=0){e.state=state;e.timer=time;e.didContact=false;e.telegraph.visible=state==='windup'}
  function faceToward(e,x,z,dt,rate=10){const want=Math.atan2(x-e.root.position.x,z-e.root.position.z),d=Math.atan2(Math.sin(want-e.root.rotation.y),Math.cos(want-e.root.rotation.y));e.root.rotation.y+=d*(1-Math.exp(-rate*dt))}
  function updateEnemy(e,dt,t){
    const rotor=e.root.userData.rotor;if(rotor)rotor.rotation.y+=dt*12;
    if(!e.alive){e.deathTimer+=dt;e.root.rotation.z+=dt*3.5;e.root.scale.multiplyScalar(Math.max(.94,1-dt*1.5));e.root.position.y-=dt*.18;if(e.deathTimer>1)e.root.visible=false;return}
    e.root.position.addScaledVector(e.knock,dt);e.knock.multiplyScalar(Math.exp(-8*dt));const p=getPlayerPosition(tmp),dx=p.x-e.root.position.x,dz=p.z-e.root.position.z,d=Math.hypot(dx,dz);const gy=groundAt(e.root.position.x,e.root.position.z);if(gy!==null){const targetY=gy+(e.kind==='flyer'?2.2+.28*Math.sin(t*2.5+e.patrolPhase):0);e.root.position.y=THREE.MathUtils.damp(e.root.position.y,targetY,12,dt)}e.timer-=dt;
    if(e.state==='patrol'){const rad=e.kind==='flyer'?2.2:1.5,tx=e.home.x+Math.sin(t*.58+e.patrolPhase)*rad,tz=e.home.z+Math.cos(t*.52+e.patrolPhase)*rad;faceToward(e,tx,tz,dt,3);e.root.position.x=THREE.MathUtils.damp(e.root.position.x,tx,1.2,dt);e.root.position.z=THREE.MathUtils.damp(e.root.position.z,tz,1.2,dt);if(d<e.alertRadius){setState(e,'alert');toast('ENEMY ALERT',360)}}
    else if(e.state==='alert'){faceToward(e,p.x,p.z,dt,11);if(d>e.alertRadius*1.5)setState(e,'patrol',.4);else if(d<e.attackRange)setState(e,'windup',e.kind==='spiker'?.62:.46);else if(d>.001){const s=e.walkSpeed*dt;e.root.position.x+=dx/d*s;e.root.position.z+=dz/d*s}}
    else if(e.state==='windup'){faceToward(e,p.x,p.z,dt,15);const pulse=.92+.12*Math.sin((.6-Math.max(0,e.timer))*35);e.telegraph.scale.setScalar(pulse);e.root.scale.setScalar(.96+.04*Math.sin(t*24));if(e.timer<=0){e.root.scale.setScalar(1);setState(e,'lunge',e.kind==='spiker'?.22:.3)}}
    else if(e.state==='lunge'){faceToward(e,p.x,p.z,dt,18);const f=new THREE.Vector3(Math.sin(e.root.rotation.y),0,Math.cos(e.root.rotation.y));e.root.position.addScaledVector(f,e.lungeSpeed*dt);if(!e.didContact&&d<1.28){e.didContact=true;damagePlayer()}if(e.timer<=0)setState(e,'recover',e.kind==='spiker'?.8:.58)}
    else if(e.state==='recover'){if(e.timer<=0)setState(e,d<e.alertRadius?'alert':'patrol',.25)}else if(e.state==='hit'){e.root.rotation.z=Math.sin(t*35)*.12;if(e.timer<=0){e.root.rotation.z=0;setState(e,d<e.alertRadius*1.3?'alert':'patrol',.2)}}e.telegraph.rotation.z+=dt*2.5
  }
  function update(dt,t){for(const e of enemies)updateEnemy(e,dt,t)}
  function damage(e,serial,{force=5,source=null}={}){if(!e||!e.alive||e.hitSerial===serial)return false;e.hitSerial=serial;e.hp--;if(source){const dx=e.root.position.x-source.x,dz=e.root.position.z-source.z,l=Math.hypot(dx,dz)||1;e.knock.set(dx/l*force,1.0,dz/l*force)}if(e.hp<=0){e.alive=false;setState(e,'dead');e.deathTimer=0;onEnemyKilled(e)}else{setState(e,'hit',.32);toast('DIRECT HIT · ONE MORE',480)}return true}
  function living(){return enemies.filter(e=>e.alive)}
  return{enemies,spawnAll,update,damage,living};
}
