from pathlib import Path
p=Path('pass11-v1/app.js')
s=p.read_text()
s=s.replace("const enemies=[],shots=[],pulses=[],collectibles=[],debris=[];","const enemies=[],shots=[],pulses=[],collectibles=[],debris=[];let actionSerial=0;",1)
s=s.replace("flash:0};enemies.push(e)","flash:0,lastActionId:-1};enemies.push(e)",1)
s=s.replace("function hitEnemy(e){if(!e.alive)return;e.hp--;","function hitEnemy(e,actionId){if(!e.alive||e.lastActionId===actionId)return;e.lastActionId=actionId;e.hp--;",1)
s=s.replace("function makeShot(angle,color=0x77efff,speed=24){","function makeShot(angle,color=0x77efff,speed=24,actionId=actionSerial){",1)
s=s.replace("shots.push({m,dx:Math.sin(angle),dz:Math.cos(angle),speed,age:0,hit:new Set()})","shots.push({m,dx:Math.sin(angle),dz:Math.cos(angle),speed,age:0,hit:new Set(),actionId})",1)
s=s.replace("function makePulse(){","function makePulse(actionId=actionSerial){",1)
s=s.replace("pulses.push({m,age:0,hit:new Set()})","pulses.push({m,age:0,hit:new Set(),actionId})",1)
s=s.replace("const a=player.yaw;if(powerStyle===0)","const a=player.yaw;actionSerial++;if(powerStyle===0)",1)
s=s.replace("hitEnemy(e);s.age=9","hitEnemy(e,s.actionId);s.age=9")
s=s.replace("p.hit.add(e);hitEnemy(e)","p.hit.add(e);hitEnemy(e,p.actionId)")
p.write_text(s)
print('Pass 11 damage gate applied')
