import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { createGamerBro } from './gamer-bro.js?v=1';

const stage=document.getElementById('stage');
const boot=document.getElementById('boot');
const fatal=document.getElementById('fatal');
const fatalText=document.getElementById('fatalText');
const hud=document.getElementById('hud');
const missionEl=document.getElementById('mission');
const statsEl=document.getElementById('stats');
const cooldownEl=document.getElementById('cooldowns');
const selectEl=document.getElementById('select');
const gridEl=document.getElementById('characterGrid');
const resultEl=document.getElementById('result');
const resultText=document.getElementById('resultText');
const replayBtn=document.getElementById('replayBtn');
const attackBtn=document.getElementById('attackBtn');
const specialBtn=document.getElementById('specialBtn');
const jumpBtn=document.getElementById('jumpBtn');
const dashBtn=document.getElementById('dashBtn');
const stick=document.getElementById('stick');
const stickKnob=document.getElementById('stickKnob');

try{
const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const renderer=new THREE.WebGLRenderer({antialias:!mobile,powerPreference:'high-performance'});
renderer.outputColorSpace=THREE.SRGBColorSpace;
renderer.toneMapping=THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure=1.13;
renderer.shadowMap.enabled=true;
renderer.shadowMap.type=THREE.PCFSoftShadowMap;
renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.35:1.75));
stage.appendChild(renderer.domElement);

const scene=new THREE.Scene();
scene.background=new THREE.Color(0x8ec9ea);
scene.fog=new THREE.Fog(0x94c9e2,50,125);
const camera=new THREE.PerspectiveCamera(48,1,.1,220);
const composer=new EffectComposer(renderer);
composer.addPass(new RenderPass(scene,camera));
const bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),mobile?.32:.46,.52,.76);
composer.addPass(bloom);composer.addPass(new OutputPass());

scene.add(new THREE.HemisphereLight(0xeefdff,0x244f32,1.72));
const sun=new THREE.DirectionalLight(0xffe0aa,3.4);sun.position.set(-18,30,18);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);sun.shadow.camera.left=-44;sun.shadow.camera.right=44;sun.shadow.camera.top=44;sun.shadow.camera.bottom=-44;sun.shadow.camera.near=1;sun.shadow.camera.far=100;sun.shadow.bias=-.00025;scene.add(sun);
const fill=new THREE.DirectionalLight(0x98d9ff,.62);fill.position.set(16,12,-18);scene.add(fill);

const world=new THREE.Group();world.name='RecoveredTrainingGround';scene.add(world);
const effects=new THREE.Group();scene.add(effects);
const enemiesRoot=new THREE.Group();scene.add(enemiesRoot);
const collectibleRoot=new THREE.Group();scene.add(collectibleRoot);
const brickRoot=new THREE.Group();scene.add(brickRoot);

const grassMat=new THREE.MeshStandardMaterial({color:0x72bc58,roughness:.82,metalness:0,side:THREE.DoubleSide});
const grassLight=new THREE.MeshStandardMaterial({color:0x88cf69,roughness:.82,side:THREE.DoubleSide});
const stoneMat=new THREE.MeshStandardMaterial({color:0x8494a0,roughness:.9,metalness:.01});
const stoneDark=new THREE.MeshStandardMaterial({color:0x687681,roughness:.94});
const woodMat=new THREE.MeshStandardMaterial({color:0x8a542d,roughness:.78});
const ropeMat=new THREE.MeshStandardMaterial({color:0xa8753f,roughness:.98});
const brickMat=new THREE.MeshStandardMaterial({color:0xa96f35,roughness:.82,emissive:0x2b1005,emissiveIntensity:.08});
const leafMat=new THREE.MeshStandardMaterial({color:0xffa329,emissive:0xff6312,emissiveIntensity:1.1,roughness:.32,metalness:.08});
const crestMat=new THREE.MeshStandardMaterial({color:0xffd568,emissive:0xff8a19,emissiveIntensity:1.85,roughness:.25,metalness:.15});
const glowBlue=new THREE.MeshStandardMaterial({color:0xdaf8ff,emissive:0x7ee7ff,emissiveIntensity:3.6,roughness:.12,transparent:true,opacity:.9});

function shadows(obj,cast=true,receive=true){obj.traverse?.(o=>{if(o.isMesh){o.castShadow=cast;o.receiveShadow=receive;}});return obj;}
function addMesh(g,m,p=[0,0,0],r=[0,0,0],s=[1,1,1],parent=world){const q=new THREE.Mesh(g,m);q.position.set(...p);q.rotation.set(...r);q.scale.set(...s);q.castShadow=true;q.receiveShadow=true;parent.add(q);return q;}
function beam(a,b,r=.06,mat=ropeMat,parent=world){const A=new THREE.Vector3(...a),B=new THREE.Vector3(...b),d=B.clone().sub(A),len=d.length();const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,len,8),mat);m.position.copy(A).add(B).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function seeded(seed=1234567){let n=seed>>>0;return()=>{n=(1664525*n+1013904223)>>>0;return n/4294967296;};}const rnd=seeded(0xBADA55);

function makeIrregularIsland(points,y,depth,grass=grassMat){const shape=new THREE.Shape();points.forEach(([x,z],i)=>i?shape.lineTo(x,z):shape.moveTo(x,z));shape.closePath();const sideGeo=new THREE.ExtrudeGeometry(shape,{depth,bevelEnabled:true,bevelSegments:2,bevelSize:.42,bevelThickness:.28});sideGeo.rotateX(Math.PI/2);const side=new THREE.Mesh(sideGeo,stoneMat);side.position.y=y;side.castShadow=true;side.receiveShadow=true;world.add(side);const cx=points.reduce((s,p)=>s+p[0],0)/points.length,cz=points.reduce((s,p)=>s+p[1],0)/points.length,pos=[];for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];pos.push(cx,0,cz,a[0],0,a[1],b[0],0,b[1]);}const topGeo=new THREE.BufferGeometry();topGeo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));topGeo.computeVertexNormals();const top=new THREE.Mesh(topGeo,grass);top.position.y=y+.12;top.renderOrder=2;top.receiveShadow=true;world.add(top);return{side,top};}

const mainPoly=[[-15,11],[-12,15],[-5,16],[4,15],[13,13],[16,7],[15,-3],[11,-9],[5,-11],[-3,-11],[-11,-8],[-16,-2],[-17,6]];
makeIrregularIsland(mainPoly,0,4.2);
const sidePoly=[[-22,3],[-18,6],[-14,4],[-13,-1],[-16,-5],[-22,-4],[-24,-1]];
makeIrregularIsland(sidePoly,1.7,3.4,grassLight);
const upperPoly=[[-10,-16],[-6,-13],[4,-13],[10,-16],[11,-25],[7,-30],[-7,-30],[-11,-25]];
makeIrregularIsland(upperPoly,6.1,5.2,grassLight);

for(let i=0;i<3;i++)addMesh(new THREE.CylinderGeometry(5.5-i*.75,5.9-i*.75,.72,36),new THREE.MeshStandardMaterial({color:0xa5abb0,roughness:.77}),[0,6.25+i*.55,-24]);
const shrineBeam=addMesh(new THREE.CylinderGeometry(1.05,1.05,8.5,28,1,true),glowBlue,[0,11.1,-24]);
shrineBeam.material.depthWrite=false;
for(let i=0;i<5;i++){const a=i*Math.PI*2/5;const gem=addMesh(new THREE.OctahedronGeometry(.48,0),glowBlue,[Math.cos(a)*2.1,13.4+Math.sin(i)*.2,-24+Math.sin(a)*2.1],[.2,a,0]);gem.userData.floatPhase=i*.8;}

function addRopeBridge(a,b,width=3.6,planks=13){const A=new THREE.Vector3(...a),B=new THREE.Vector3(...b),dir=B.clone().sub(A);for(let i=0;i<planks;i++){const t=i/(planks-1),p=A.clone().lerp(B,t);p.y-=Math.sin(Math.PI*t)*.35;const plank=addMesh(new THREE.BoxGeometry(width,.18,.58),woodMat,[p.x,p.y,p.z],[0,0,0]);plank.rotation.y=Math.atan2(dir.x,dir.z);}const side=new THREE.Vector3(dir.z,0,-dir.x).normalize().multiplyScalar(width*.62);for(const sgn of[-1,1]){let prev=null;for(let i=0;i<22;i++){const t=i/21,p=A.clone().lerp(B,t).add(side.clone().multiplyScalar(sgn));p.y+=1.7-Math.sin(Math.PI*t)*.45;if(prev)beam(prev.toArray(),p.toArray(),.07,ropeMat);prev=p;}}}
addRopeBridge([0,.45,-9.5],[0,6.4,-16.1],3.6,14);
for(let i=0;i<7;i++){const t=i/6;addMesh(new THREE.BoxGeometry(2.25,.42,1.5),stoneMat,[-14.4-i*1.22,.35+t*1.45,3.7-i*.92],[0,.15*(i%2),0],[1,1,1]);}
for(const [x,z,s] of [[-30,-30,10],[-18,-42,12],[17,-43,13],[30,-28,10],[-35,15,11],[34,17,9]]) addMesh(new THREE.ConeGeometry(s*.56,s*1.45,5),new THREE.MeshStandardMaterial({color:0x557485,roughness:1}),[x,-1,z],[0,rnd()*1.3,0],[1,1,1],world).castShadow=false;

function tree(x,z,y=0,red=false,scale=1){const g=new THREE.Group();g.position.set(x,y,z);g.scale.setScalar(scale);world.add(g);const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.32,.52,4.6,9),new THREE.MeshStandardMaterial({color:0x6e4028,roughness:1}));trunk.position.y=2.25;trunk.rotation.z=.06;trunk.castShadow=true;g.add(trunk);const mat=new THREE.MeshStandardMaterial({color:red?0x7e151b:0x3b7619,roughness:.95});for(const [ox,oy,oz,sc] of [[0,4.5,0,1.3],[-.7,4.2,.1,.9],[.75,4.0,.2,.95],[.1,5.1,-.2,.8]]){const q=new THREE.Mesh(new THREE.IcosahedronGeometry(1.15,2),mat);q.position.set(ox,oy,oz);q.scale.setScalar(sc);q.castShadow=true;q.receiveShadow=true;g.add(q);}return g;}
function bush(x,z,y=0,scale=1){const g=new THREE.Group();g.position.set(x,y,z);g.scale.setScalar(scale);world.add(g);const m=new THREE.MeshStandardMaterial({color:0x376d1d,roughness:.9});for(let i=0;i<7;i++){const q=new THREE.Mesh(new THREE.IcosahedronGeometry(.48,1),m);q.position.set((rnd()-.5)*1.6,.35+rnd()*.5,(rnd()-.5)*1.2);q.castShadow=true;g.add(q);}for(let i=0;i<9;i++){const f=new THREE.Mesh(new THREE.SphereGeometry(.06,7,5),new THREE.MeshStandardMaterial({color:0xc99cff,emissive:0x54297a,emissiveIntensity:.3}));f.position.set((rnd()-.5)*1.8,.35+rnd()*.75,(rnd()-.5)*1.3);g.add(f);}return g;}
function fern(x,z,y=0,scale=1){const g=new THREE.Group();g.position.set(x,y,z);g.scale.setScalar(scale);world.add(g);const m=new THREE.MeshStandardMaterial({color:0x1e5a2f,roughness:.95,side:THREE.DoubleSide});for(let i=0;i<7;i++){const leaf=new THREE.Mesh(new THREE.ConeGeometry(.34,1.75,5,1,true),m);leaf.position.y=.55;leaf.rotation.z=.72;leaf.rotation.y=i*Math.PI*2/7;leaf.castShadow=true;g.add(leaf);}return g;}
function rock(x,z,y=0,s=1){return addMesh(new THREE.DodecahedronGeometry(.75,0),stoneDark,[x,y+.35,z],[rnd()*.3,rnd()*3,.1],[s*1.2,s*.65,s],world);}
function fence(x,z,y=0,ry=0,len=4){const g=new THREE.Group();g.position.set(x,y,z);g.rotation.y=ry;world.add(g);for(const sx of[-len/2,len/2])addMesh(new THREE.BoxGeometry(.22,2.2,.22),woodMat,[sx,1.1,0],[0,0,0],[1,1,1],g);for(const yy of[.62,1.45])addMesh(new THREE.BoxGeometry(len,.18,.16),woodMat,[0,yy,0],[0,0,0],[1,1,1],g);return g;}
for(const p of [[-12,9,0,1,1.1],[12,9,0,0,1],[-10,-5,0,0,.95],[10,-5,0,1,.9],[-6,-20,6.1,0,.85],[6,-20,6.1,1,.92],[-19,1,1.7,0,.75]])tree(...p);
for(const [x,z,y,s] of [[-9,7,0,1],[9,6,0,1],[-8,-5,0,.9],[8,-4,0,.9],[-4,-18,6.1,.8],[5,-19,6.1,.8],[-18,-2,1.7,.8]])bush(x,z,y,s);
for(const [x,z,y,s] of [[-6,10,0,.8],[-2,8,0,.8],[7,10,0,.85],[-9,1,0,.8],[8,0,0,.8],[-6,-7,0,.8],[6,-7,0,.8],[-16,2,1.7,.7],[4,-16,6.1,.7]])fern(x,z,y,s);
for(let i=0;i<34;i++){const a=rnd()*Math.PI*2,rr=3+rnd()*12,x=Math.cos(a)*rr,z=2+Math.sin(a)*rr;if(z<-8)continue;rock(x,z,0,.32+rnd()*.55);}
fence(-12,5,0,0,4);fence(12,4,0,0,4);fence(-7,-7,0,.4,4);fence(7,-7,0,-.4,4);fence(-6,-18,6.1,.3,3.5);fence(6,-18,6.1,-.3,3.5);

const surfaces=[];
function rectSurface(x,z,w,d,y,ry=0){surfaces.push({type:'rect',x,z,w,d,y,ry});}
function rampSurface(x1,z1,y1,x2,z2,y2,w){surfaces.push({type:'ramp',x1,z1,y1,x2,z2,y2,w});}
rectSurface(0,2,28,23,0);rectSurface(-18.5,0,10,10,1.7);rectSurface(0,-22.5,19,15,6.1);rampSurface(0,-9.5,.45,0,-16.1,6.4,3.6);
for(let i=0;i<7;i++){const t=i/6;rectSurface(-14.4-i*1.22,3.7-i*.92,2.4,1.8,.55+t*1.45);}
function surfaceHeight(x,z){let best=null;for(const s of surfaces){if(s.type==='rect'){const c=Math.cos(-s.ry),q=Math.sin(-s.ry),dx=x-s.x,dz=z-s.z,lx=dx*c-dz*q,lz=dx*q+dz*c;if(Math.abs(lx)<=s.w/2&&Math.abs(lz)<=s.d/2)best=Math.max(best??-Infinity,s.y);}else{const dx=s.x2-s.x1,dz=s.z2-s.z1,L=Math.hypot(dx,dz),ux=dx/L,uz=dz/L,px=x-s.x1,pz=z-s.z1,t=(px*ux+pz*uz)/L,side=Math.abs(px*(-uz)+pz*ux);if(t>=0&&t<=1&&side<=s.w/2)best=Math.max(best??-Infinity,s.y1+(s.y2-s.y1)*t);}}return best;}

function mapleShape(scale=1){const pts=[[0,1.25],[-.18,.58],[-.68,.82],[-.45,.25],[-1,.08],[-.46,-.17],[-.62,-.73],[-.1,-.48],[0,-1.25],[.1,-.48],[.62,-.73],[.46,-.17],[1,.08],[.45,.25],[.68,.82],[.18,.58]];const sh=new THREE.Shape();pts.forEach(([x,y],i)=>i?sh.lineTo(x*scale,y*scale):sh.moveTo(x*scale,y*scale));sh.closePath();return sh;}
const leafGeo=new THREE.ExtrudeGeometry(mapleShape(.22),{depth:.07,bevelEnabled:true,bevelSegments:1,bevelSize:.025,bevelThickness:.02});leafGeo.center();
const crestGeo=new THREE.ExtrudeGeometry(mapleShape(.55),{depth:.16,bevelEnabled:true,bevelSegments:2,bevelSize:.05,bevelThickness:.04});crestGeo.center();
const leaves=[];const crests=[];
function addLeaf(x,y,z){const m=new THREE.Mesh(leafGeo,leafMat);m.position.set(x,y,z);m.rotation.x=-.2;m.castShadow=true;collectibleRoot.add(m);leaves.push({mesh:m,baseY:y,collected:false,phase:rnd()*6});return m;}
function addCrest(x,y,z,id){const m=new THREE.Mesh(crestGeo,crestMat);m.position.set(x,y,z);m.castShadow=true;collectibleRoot.add(m);const halo=new THREE.PointLight(0xff9e2c,2.8,6,2);m.add(halo);crests.push({id,mesh:m,baseY:y,collected:false,phase:rnd()*6});return m;}
for(const [x,z,y] of [[-8,8,.8],[-5,8,.8],[-2,8,.8],[2,8,.8],[5,8,.8],[8,8,.8],[-9,2,.8],[-6,2,.8],[6,2,.8],[9,2,.8],[-8,-5,.8],[-4,-6,.8],[4,-6,.8],[8,-5,.8],[-18,3,2.5],[-20,0,2.5],[-17,-2,2.5],[-5,-20,6.9],[0,-19,6.9],[5,-20,6.9]])addLeaf(x,y,z);
addCrest(-19,2.75,-2,'west');addCrest(10,.9,-7,'east');addCrest(0,7.25,-27,'shrine');

const bricks=[];
function addBrick(x,y,z,wallId){const m=new THREE.Mesh(new THREE.BoxGeometry(1.4,.72,.78),brickMat.clone());m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;brickRoot.add(m);bricks.push({mesh:m,hp:2,alive:true,wallId});return m;}
function brickWall(cx,cz,y,cols=6,rows=3,spacing=1.55,wallId='wall'){for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const off=(c-(cols-1)/2)*spacing+(r%2?spacing*.5:0);addBrick(cx+off,y+.42+r*.78,cz,wallId);}}
brickWall(0,7.0,0,7,3,1.55,'gateA');brickWall(-15.0,1.7,1.7,5,3,1.5,'gateB');brickWall(7.8,-5.4,0,4,3,1.5,'gateC');

const palettes={water:{body:0x49baf5,limb:0x54c6ff,eye:0x07111a,accent:0x7ed9ff},fire:{body:0xf36b22,limb:0xff7c2b,eye:0x070b10,accent:0xffa347},earth:{body:0x62b84d,limb:0x66c153,eye:0xff79d8,accent:0x8ad265},ghost:{body:0x985be8,limb:0xa16af0,eye:0xff89df,accent:0xc594ff}};
function phys(color,rough=.32,clear=.65,emissive=0,ei=0){return new THREE.MeshPhysicalMaterial({color,roughness:rough,metalness:.02,clearcoat:clear,clearcoatRoughness:.22,emissive,emissiveIntensity:ei});}
function makeSprite(kind,scale=1){const P=palettes[kind],root=new THREE.Group(),bob=new THREE.Group();root.add(bob);const body=new THREE.Mesh(new THREE.SphereGeometry(1,36,28),phys(P.body,kind==='earth'?.78:.22,kind==='earth'?.08:.9));body.scale.set(.88,1.15,.72);body.position.y=1.33;body.castShadow=true;body.receiveShadow=true;bob.add(body);const eyeMat=phys(P.eye,.08,1,kind==='ghost'?0x6a164c:0,kind==='ghost'?.5:0);for(const x of[-.29,.29]){const e=new THREE.Mesh(new THREE.SphereGeometry(.16,22,16),eyeMat);e.scale.set(.72,1.15,.55);e.position.set(x,1.48,.67);e.castShadow=true;bob.add(e);}const limbMat=phys(P.limb,.24,.85);for(const side of[-1,1]){const arm=new THREE.Mesh(new THREE.SphereGeometry(.24,22,16),limbMat);arm.scale.set(.65,1.3,.62);arm.position.set(side*.87,1.2,.02);arm.rotation.z=side*.38;arm.castShadow=true;bob.add(arm);const foot=new THREE.Mesh(new THREE.SphereGeometry(.28,22,16),limbMat);foot.scale.set(1.1,.58,1.35);foot.position.set(side*.36,.18,.14);foot.castShadow=true;bob.add(foot);}if(kind==='water'){for(let i=0;i<5;i++){const q=new THREE.Mesh(new THREE.SphereGeometry(.09+i*.008,16,12),phys(0x66d4ff,.08,1,0x3ebfff,.65));q.position.set((i%2?-.12:.1)+Math.sin(i)*.08,2.42+i*.13,.02);bob.add(q);}}if(kind==='fire'){for(const x of[-.28,0,.28]){const spike=new THREE.Mesh(new THREE.ConeGeometry(.18,.72,7),phys(0xff7d29,.25,.75));spike.position.set(x,2.48-Math.abs(x)*.2,0);spike.rotation.z=-x*.6;spike.castShadow=true;bob.add(spike);}}if(kind==='earth'){const bark=phys(0x84552f,.9,.05);for(let i=0;i<6;i++){const a=(i-2.5)*.27,q=new THREE.Mesh(new THREE.BoxGeometry(.25,.64,.24),bark);q.position.set(Math.sin(a)*.75,2.15,Math.cos(a)*.72);q.rotation.z=a*.18;q.rotation.y=a;q.castShadow=true;bob.add(q);}const leaf=new THREE.Mesh(new THREE.IcosahedronGeometry(.38,1),phys(0x6fbf55,.8,.08));leaf.scale.set(1.1,.55,.95);leaf.position.set(0,2.6,-.05);leaf.castShadow=true;bob.add(leaf);}if(kind==='ghost'){body.material.transparent=true;body.material.opacity=.94;const tail=new THREE.Mesh(new THREE.ConeGeometry(.62,1.0,10),phys(P.body,.2,.8,0x4b167f,.32));tail.position.set(0,.32,-.08);tail.rotation.z=Math.PI;tail.castShadow=true;bob.add(tail);}const shadow=new THREE.Mesh(new THREE.CircleGeometry(.72,24),new THREE.MeshBasicMaterial({color:0x13251b,transparent:true,opacity:.24,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.03;root.add(shadow);root.scale.setScalar(scale);return{root,update(t,move=0,action=0){bob.position.y=.07*Math.sin(t*2.2)+(move?Math.abs(Math.sin(t*7))*0.05:0);bob.rotation.z=.025*Math.sin(t*1.4);body.rotation.y=.04*Math.sin(t*.8);bob.scale.setScalar(action?1+.05*Math.sin(action*Math.PI):1);}};}

const CHARACTERS={gamer:{name:'GAMER BRO',subtitle:'Prism Blaster · Nova Shockwave',attack:'PRISM BOLT',special:'NOVA SHOCKWAVE',color:'#f28c42',attackCD:.34,specialCD:5.2,speed:7.2,jump:7.4},water:{name:'WATER SPRITE',subtitle:'Bubble Shot · Tidal Burst',attack:'BUBBLE SHOT',special:'TIDAL BURST',color:'#55c7ff',attackCD:.48,specialCD:4.6,speed:7.5,jump:7.6},fire:{name:'FIRE SPRITE',subtitle:'Fireball · Inferno Bloom',attack:'FIREBALL',special:'INFERNO BLOOM',color:'#ff7024',attackCD:.52,specialCD:5.5,speed:7.1,jump:7.2},earth:{name:'EARTH SPRITE',subtitle:'Rock Punch · Seismic Slam',attack:'ROCK PUNCH',special:'SEISMIC SLAM',color:'#66bd54',attackCD:.62,specialCD:6.0,speed:6.5,jump:6.9},ghost:{name:'GHOST SPRITE',subtitle:'Spectral Lance · Phase Rush',attack:'SPECTRAL LANCE',special:'PHASE RUSH',color:'#a66df1',attackCD:.4,specialCD:4.8,speed:7.8,jump:7.8}};
for(const [id,c] of Object.entries(CHARACTERS)){const b=document.createElement('button');b.className='characterCard';b.dataset.character=id;b.innerHTML=`<div class="orb ${id}Orb"></div><strong>${c.name}</strong><small>${c.subtitle}</small>`;gridEl.appendChild(b);}

const player={root:new THREE.Group(),visual:null,kind:'gamer',pos:new THREE.Vector3(0,.05,12),vel:new THREE.Vector3(),grounded:false,health:6,maxHealth:6,lives:3,attackCD:0,specialCD:0,dashCD:0,invuln:0,actionAge:0,actionType:'',facing:new THREE.Vector3(0,0,-1)};scene.add(player.root);let bro=null;
function setPlayerVisual(kind){while(player.root.children.length)player.root.remove(player.root.children[0]);player.kind=kind;bro=null;if(kind==='gamer'){bro=createGamerBro(THREE,renderer,{detail:mobile?'low':'high',height:2.62,colorway:'teal'});const holder=new THREE.Group();holder.add(bro.root);bro.setHome(0,0,0);bro.setRoomLight(.9);player.root.add(holder);player.visual={root:holder,update:(t,move,action)=>{bro.setMotion(move>.65?'run':move>.05?'walk':'idle');bro.setAction(action>0);bro.update(t,1/60,action>0?1:0);}};}else{player.visual=makeSprite(kind,1.02);player.root.add(player.visual.root);}player.root.position.copy(player.pos);}

const ENEMY_STATS={water:{hp:3,speed:2.2,range:9,cool:.0},fire:{hp:4,speed:2.8,range:2.1,cool:.0},earth:{hp:6,speed:1.65,range:2.0,cool:.0},ghost:{hp:3,speed:2.3,range:8,cool:.0}};
const enemySpawns=[['water',-8,5,0],['fire',7,5,0],['earth',-18,0,1.7],['ghost',10,-5,0],['fire',-5,-6,0],['water',4,-18,6.1],['earth',-4,-24,6.1],['ghost',6,-25,6.1]];
const enemies=[];
function spawnEnemy(kind,x,z,y){const v=makeSprite(kind,.86),e={kind,root:v.root,visual:v,pos:new THREE.Vector3(x,y,z),vel:new THREE.Vector3(),hp:ENEMY_STATS[kind].hp,maxHp:ENEMY_STATS[kind].hp,alive:true,attackCD:rnd()*1.1,hitFlash:0,stun:0,phase:rnd()*8};e.root.position.copy(e.pos);enemiesRoot.add(e.root);enemies.push(e);return e;}
enemySpawns.forEach(a=>spawnEnemy(...a));

const projectiles=[];
function projMaterial(color,emissive=color){return new THREE.MeshStandardMaterial({color,emissive,emissiveIntensity:2.5,roughness:.18,transparent:true,opacity:.96});}
function fireProjectile({origin,dir,speed=15,damage=1,radius=.22,color=0xffffff,owner='player',life=2.2,pierce=0,splash=0,brickDamage=1,knock=2}){const mesh=new THREE.Mesh(new THREE.SphereGeometry(radius,14,10),projMaterial(color));mesh.position.copy(origin);effects.add(mesh);projectiles.push({mesh,vel:dir.clone().normalize().multiplyScalar(speed),damage,owner,life,pierce,splash,brickDamage,knock,radius,hit:new Set()});return mesh;}
function spawnRing(pos,color,r0=.6,r1=6,dur=.45){const mesh=new THREE.Mesh(new THREE.RingGeometry(r0,r0+.18,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.85,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));mesh.rotation.x=-Math.PI/2;mesh.position.copy(pos);mesh.position.y+=.12;effects.add(mesh);effects.userData.anim??=[];effects.userData.anim.push({mesh,age:0,dur,r0,r1});}
function debris(pos,color=0xa96f35,count=8){for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(.16+.2*rnd(),.12+.16*rnd(),.12+.18*rnd()),new THREE.MeshStandardMaterial({color,roughness:.9}));m.position.copy(pos);m.rotation.set(rnd()*3,rnd()*3,rnd()*3);effects.add(m);effects.userData.debris??=[];effects.userData.debris.push({mesh:m,vel:new THREE.Vector3((rnd()-.5)*5,2+rnd()*4,(rnd()-.5)*5),age:0});}}
function damageBrick(b,amount,hitPos){if(!b.alive)return false;b.hp-=amount;b.mesh.material.emissive.setHex(0xff6a16);b.mesh.material.emissiveIntensity=1.2;setTimeout(()=>{if(b.alive){b.mesh.material.emissive.setHex(0x2b1005);b.mesh.material.emissiveIntensity=.08;}},80);if(b.hp<=0){b.alive=false;b.mesh.visible=false;debris(hitPos||b.mesh.position,0xa96f35,3);if(rnd()<.5)addLeaf(b.mesh.position.x,b.mesh.position.y+.4,b.mesh.position.z);return true;}return false;}
function breakBricksRadius(pos,radius,damage=2){let n=0;for(const b of bricks){if(b.alive&&b.mesh.position.distanceTo(pos)<radius){if(damageBrick(b,damage,b.mesh.position))n++;}}return n;}
function hitEnemy(e,damage,knock=0,from=null){if(!e.alive)return;e.hp-=damage;e.hitFlash=.16;if(from&&knock){const d=e.pos.clone().sub(from);d.y=0;if(d.lengthSq()>.01)e.vel.add(d.normalize().multiplyScalar(knock));}if(e.hp<=0){e.alive=false;e.root.visible=false;debris(e.pos,parseInt(CHARACTERS[e.kind]?.color?.slice(1)||'ffffff',16),12);for(let i=0;i<2;i++)addLeaf(e.pos.x+(i-.5)*.8,e.pos.y+1.1,e.pos.z+(rnd()-.5)*.5);}}
function damageEnemiesRadius(pos,radius,damage,knock=4){let n=0;for(const e of enemies){if(e.alive&&e.pos.distanceTo(pos)<radius){hitEnemy(e,damage,knock,pos);e.stun=.7;n++;}}return n;}

const keys=new Set();let attackPressed=false,specialPressed=false,jumpPressed=false,dashPressed=false;let pointerDown=false,lastPX=0,cameraYaw=0,cameraPitch=.26;const stickAxis={x:0,z:0};
addEventListener('keydown',e=>{keys.add(e.code);if(e.repeat)return;if(e.code==='KeyF'||e.code==='KeyE')attackPressed=true;if(e.code==='KeyQ')specialPressed=true;if(e.code==='Space')jumpPressed=true;if(e.code==='ShiftLeft'||e.code==='ShiftRight')dashPressed=true;if(e.code==='KeyC')openSelect();if(e.code==='KeyR')restart();});addEventListener('keyup',e=>keys.delete(e.code));
renderer.domElement.addEventListener('pointerdown',e=>{pointerDown=true;lastPX=e.clientX;renderer.domElement.setPointerCapture?.(e.pointerId);});addEventListener('pointermove',e=>{if(!pointerDown)return;const dx=e.clientX-lastPX;lastPX=e.clientX;cameraYaw-=dx*.006;});addEventListener('pointerup',()=>pointerDown=false);
for(const [btn,fn] of [[attackBtn,()=>attackPressed=true],[specialBtn,()=>specialPressed=true],[jumpBtn,()=>jumpPressed=true],[dashBtn,()=>dashPressed=true]])btn.addEventListener('pointerdown',e=>{e.preventDefault();fn();});
let stickId=null;function updateStick(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,L=Math.hypot(dx,dy),max=42,k=L>max?max/L:1,nx=dx*k,ny=dy*k;stickKnob.style.transform=`translate(${nx}px,${ny}px)`;stickAxis.x=nx/max;stickAxis.z=ny/max;}
stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);updateStick(e);});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickId)updateStick(e);});stick.addEventListener('pointerup',e=>{if(e.pointerId===stickId){stickId=null;stickAxis.x=stickAxis.z=0;stickKnob.style.transform='';}});

let playing=false,victory=false,leavesCollected=0,crestsCollected=0,clock=0,last=performance.now();
function chooseCharacter(kind){setPlayerVisual(kind);selectEl.classList.remove('show');playing=true;restart(false);hud.classList.remove('hidden');}
gridEl.addEventListener('click',e=>{const b=e.target.closest('[data-character]');if(b)chooseCharacter(b.dataset.character);});
function openSelect(){playing=false;selectEl.classList.add('show');}
function restart(resetSelect=false){victory=false;resultEl.classList.remove('show');player.health=player.maxHealth;player.lives=3;player.pos.set(0,.15,12);player.vel.set(0,0,0);player.attackCD=player.specialCD=player.dashCD=player.invuln=0;player.root.visible=true;player.root.position.copy(player.pos);for(const b of bricks){b.alive=true;b.hp=2;b.mesh.visible=true;}for(let i=0;i<enemies.length;i++){const e=enemies[i],sp=enemySpawns[i];e.alive=true;e.hp=e.maxHp;e.root.visible=true;e.pos.set(sp[1],sp[3],sp[2]);e.vel.set(0,0,0);e.attackCD=rnd();e.root.position.copy(e.pos);}for(const l of leaves){l.collected=false;l.mesh.visible=true;}for(const c of crests){c.collected=false;c.mesh.visible=true;}leavesCollected=0;crestsCollected=0;for(const p of projectiles)p.mesh.removeFromParent();projectiles.length=0;if(resetSelect)openSelect();updateHUD();}
replayBtn.addEventListener('click',()=>restart(false));

function movePlayer(dt){const C=CHARACTERS[player.kind];let ax=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+stickAxis.x;let az=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+stickAxis.z;const L=Math.hypot(ax,az);if(L>1){ax/=L;az/=L;}const sy=Math.sin(cameraYaw),cy=Math.cos(cameraYaw),wx=ax*cy+az*sy,wz=az*cy-ax*sy;const moveLen=Math.hypot(wx,wz);if(moveLen>.05)player.facing.set(wx,0,wz).normalize();player.vel.x=THREE.MathUtils.damp(player.vel.x,wx*C.speed,player.grounded?15:6,dt);player.vel.z=THREE.MathUtils.damp(player.vel.z,wz*C.speed,player.grounded?15:6,dt);if(moveLen<.05&&player.grounded){player.vel.x=THREE.MathUtils.damp(player.vel.x,0,9,dt);player.vel.z=THREE.MathUtils.damp(player.vel.z,0,9,dt);}if(jumpPressed&&player.grounded){player.vel.y=C.jump;player.grounded=false;}if(dashPressed&&player.dashCD<=0){player.dashCD=1.25;player.invuln=.28;player.vel.x=player.facing.x*14;player.vel.z=player.facing.z*14;spawnRing(player.pos,0xffffff,.3,2.1,.25);}jumpPressed=false;dashPressed=false;player.vel.y-=18*dt;const prev=player.pos.clone();player.pos.addScaledVector(player.vel,dt);for(const b of bricks){if(!b.alive)continue;const dx=player.pos.x-b.mesh.position.x,dz=player.pos.z-b.mesh.position.z;if(dx*dx+dz*dz<1.0&&Math.abs((player.pos.y+.8)-b.mesh.position.y)<1.4){player.pos.x=prev.x;player.pos.z=prev.z;player.vel.x*=.15;player.vel.z*=.15;break;}}const h=surfaceHeight(player.pos.x,player.pos.z);const prevH=surfaceHeight(prev.x,prev.z);if(h!=null&&prevH!=null&&h>prevH+1.1&&player.pos.y<h+1.1){player.pos.x=prev.x;player.pos.z=prev.z;player.vel.x*=.1;player.vel.z*=.1;}const hh=surfaceHeight(player.pos.x,player.pos.z);if(hh!=null&&player.vel.y<=0&&player.pos.y<=hh+.05&&player.pos.y>=hh-1.1){player.pos.y=hh+.05;player.vel.y=0;player.grounded=true;}else if(hh==null||player.pos.y>hh+.12)player.grounded=false;if(player.pos.y<-8)loseLife();player.root.position.copy(player.pos);if(moveLen>.05)player.root.rotation.y=THREE.MathUtils.damp(player.root.rotation.y,Math.atan2(player.facing.x,player.facing.z),12,dt);player.visual?.update(clock,moveLen,Math.max(0,player.actionAge));}
function loseLife(){player.lives--;if(player.lives<=0){player.health=0;playing=false;resultText.textContent='Out of lives. R to retry or C to choose another character.';resultEl.classList.add('show');return;}player.health=player.maxHealth;player.pos.set(0,.15,12);player.vel.set(0,0,0);player.invuln=1.5;}

function attack(){const C=CHARACTERS[player.kind];if(player.attackCD>0)return;player.attackCD=C.attackCD;player.actionAge=.32;const origin=player.pos.clone().add(new THREE.Vector3(0,1.25,0)).add(player.facing.clone().multiplyScalar(.8));if(player.kind==='gamer')fireProjectile({origin,dir:player.facing,speed:19,damage:2,radius:.2,color:0x69efff,life:2.2,brickDamage:2,knock:3});else if(player.kind==='water')fireProjectile({origin,dir:player.facing,speed:15,damage:1,radius:.31,color:0x61cfff,life:2.7,brickDamage:1,knock:5});else if(player.kind==='fire')fireProjectile({origin,dir:player.facing,speed:16,damage:2,radius:.27,color:0xff6a24,life:2.5,splash:2.2,brickDamage:2,knock:4});else if(player.kind==='earth'){const p=player.pos.clone().add(player.facing.clone().multiplyScalar(1.7));spawnRing(p,0xc08a48,.25,2.2,.28);damageEnemiesRadius(p,2.2,3,5);breakBricksRadius(p,2.5,2);}else if(player.kind==='ghost')fireProjectile({origin,dir:player.facing,speed:22,damage:2,radius:.22,color:0xc790ff,life:2.5,pierce:4,brickDamage:2,knock:2});}
function special(){const C=CHARACTERS[player.kind];if(player.specialCD>0)return;player.specialCD=C.specialCD;player.actionAge=.55;if(player.kind==='gamer'){spawnRing(player.pos,0x8eeeff,.4,6.2,.5);damageEnemiesRadius(player.pos,6,3,7);breakBricksRadius(player.pos,6.2,3);}else if(player.kind==='water'){spawnRing(player.pos,0x4ecfff,.6,5.5,.6);damageEnemiesRadius(player.pos,5.2,2,12);breakBricksRadius(player.pos,4.6,2);}else if(player.kind==='fire'){spawnRing(player.pos,0xff6424,.5,6.5,.55);damageEnemiesRadius(player.pos,6.2,4,5);breakBricksRadius(player.pos,5.7,3);for(let i=0;i<12;i++){const d=new THREE.Vector3(Math.sin(i*Math.PI/6),.08,Math.cos(i*Math.PI/6));fireProjectile({origin:player.pos.clone().add(new THREE.Vector3(0,1,0)),dir:d,speed:8,damage:1,radius:.15,color:0xff9a31,life:.9,brickDamage:1});}}else if(player.kind==='earth'){spawnRing(player.pos,0xffc15a,.7,7.6,.62);damageEnemiesRadius(player.pos,7,3,10);breakBricksRadius(player.pos,8,5);player.vel.y=4.2;}else if(player.kind==='ghost'){player.invuln=.8;const start=player.pos.clone(),end=start.clone().add(player.facing.clone().multiplyScalar(8));for(const e of enemies){if(!e.alive)continue;const rel=e.pos.clone().sub(start),t=THREE.MathUtils.clamp(rel.dot(player.facing)/8,0,1),near=start.clone().lerp(end,t);if(e.pos.distanceTo(near)<1.9)hitEnemy(e,3,7,start);}for(const b of bricks){if(!b.alive)continue;const rel=b.mesh.position.clone().sub(start),t=THREE.MathUtils.clamp(rel.dot(player.facing)/8,0,1),near=start.clone().lerp(end,t);if(b.mesh.position.distanceTo(near)<1.5)damageBrick(b,4,b.mesh.position);}player.pos.copy(end);const h=surfaceHeight(player.pos.x,player.pos.z);if(h!=null)player.pos.y=Math.max(player.pos.y,h+.05);spawnRing(start,0xb980ff,.2,3.2,.35);spawnRing(player.pos,0xb980ff,.2,3.2,.35);}}

function updateEnemies(dt){for(const e of enemies){if(!e.alive)continue;e.hitFlash=Math.max(0,e.hitFlash-dt);e.stun=Math.max(0,e.stun-dt);e.attackCD=Math.max(0,e.attackCD-dt);if(e.stun<=0){const to=player.pos.clone().sub(e.pos),dist=Math.hypot(to.x,to.z);to.y=0;if(dist>0.1)to.normalize();if(e.kind==='fire'||e.kind==='earth'){if(dist>1.65){e.vel.x=THREE.MathUtils.damp(e.vel.x,to.x*ENEMY_STATS[e.kind].speed,4,dt);e.vel.z=THREE.MathUtils.damp(e.vel.z,to.z*ENEMY_STATS[e.kind].speed,4,dt);}else if(e.attackCD<=0){e.attackCD=e.kind==='earth'?1.5:1.0;enemyHitPlayer(e.kind==='earth'?2:1,e.pos,5);spawnRing(e.pos,e.kind==='earth'?0xb87e40:0xff6e2a,.2,2.2,.28);}}else{if(dist>5.5){e.vel.x=THREE.MathUtils.damp(e.vel.x,to.x*ENEMY_STATS[e.kind].speed,3,dt);e.vel.z=THREE.MathUtils.damp(e.vel.z,to.z*ENEMY_STATS[e.kind].speed,3,dt);}else{e.vel.x=THREE.MathUtils.damp(e.vel.x,0,5,dt);e.vel.z=THREE.MathUtils.damp(e.vel.z,0,5,dt);if(e.attackCD<=0){e.attackCD=e.kind==='ghost'?1.25:1.55;fireProjectile({origin:e.pos.clone().add(new THREE.Vector3(0,1.1,0)),dir:player.pos.clone().sub(e.pos).setY(.15),speed:e.kind==='ghost'?10:8,damage:1,radius:e.kind==='ghost'?.22:.3,color:e.kind==='ghost'?0xb574ff:0x5acaff,owner:'enemy',life:3,knock:3});}}}}e.pos.addScaledVector(e.vel,dt);const h=surfaceHeight(e.pos.x,e.pos.z);if(h!=null)e.pos.y=THREE.MathUtils.damp(e.pos.y,h,10,dt);else{e.pos.x-=e.vel.x*dt;e.pos.z-=e.vel.z*dt;e.vel.multiplyScalar(.2);}e.root.position.copy(e.pos);if(Math.hypot(e.vel.x,e.vel.z)>.1)e.root.rotation.y=Math.atan2(e.vel.x,e.vel.z);e.visual.update(clock+e.phase,Math.min(1,e.vel.length()/3),e.hitFlash>0?1:0);e.root.scale.setScalar(.86*(e.hitFlash>0?1+.05*Math.sin(clock*50):1));}}
function enemyHitPlayer(damage,from,knock=4){if(player.invuln>0||!playing)return;player.health-=damage;player.invuln=1.0;const d=player.pos.clone().sub(from);d.y=0;if(d.lengthSq()>.01){d.normalize();player.vel.x+=d.x*knock;player.vel.z+=d.z*knock;}player.vel.y=Math.max(player.vel.y,3.2);spawnRing(player.pos,0xff4466,.1,1.8,.2);if(player.health<=0)loseLife();}

function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.life-=dt;p.mesh.position.addScaledVector(p.vel,dt);p.mesh.rotation.y+=dt*5;if(p.owner==='player'){for(const e of enemies){if(!e.alive||p.hit.has(e))continue;if(e.pos.distanceTo(p.mesh.position)<.75+p.radius){p.hit.add(e);hitEnemy(e,p.damage,p.knock,p.mesh.position);if(p.splash>0)damageEnemiesRadius(p.mesh.position,p.splash,1,3);p.pierce--;if(p.pierce<0){p.life=0;break;}}}for(const b of bricks){if(!b.alive||p.life<=0)continue;if(b.mesh.position.distanceTo(p.mesh.position)<.9){damageBrick(b,p.brickDamage,b.mesh.position);p.pierce--;if(p.pierce<0){p.life=0;break;}}}}else if(p.mesh.position.distanceTo(player.pos.clone().add(new THREE.Vector3(0,1,0)))<.72){enemyHitPlayer(p.damage,p.mesh.position,p.knock);p.life=0;}if(p.life<=0){p.mesh.removeFromParent();projectiles.splice(i,1);}}}
function collect(){for(const l of leaves){if(!l.collected&&l.mesh.position.distanceTo(player.pos)<1.05){l.collected=true;l.mesh.visible=false;leavesCollected++;spawnRing(l.mesh.position,0xffa62f,.1,1.2,.24);}}for(const c of crests){if(!c.collected&&c.mesh.position.distanceTo(player.pos)<1.35){c.collected=true;c.mesh.visible=false;crestsCollected++;spawnRing(c.mesh.position,0xffd75f,.2,2.6,.45);player.health=Math.min(player.maxHealth,player.health+2);}}}
function objective(){const alive=enemies.filter(e=>e.alive).length,unlocked=crestsCollected>=3&&alive===0;shrineBeam.material.opacity=unlocked?.98:.35;shrineBeam.material.emissiveIntensity=unlocked?5.5:1.2;if(unlocked&&player.pos.distanceTo(new THREE.Vector3(0,6.2,-24))<4&&!victory){victory=true;playing=false;spawnRing(player.pos,0xe9faff,.6,8,.75);player.root.visible=false;setTimeout(()=>{resultText.textContent=`${CHARACTERS[player.kind].name} · Maple Leaves ${leavesCollected}/${leaves.length} · all enemies defeated · 3/3 crests recovered.`;resultEl.classList.add('show');},450);}}
function updateCollectibles(dt){for(const l of leaves){if(l.collected)continue;l.mesh.rotation.y+=dt*2.2;l.mesh.position.y=l.baseY+Math.sin(clock*2.4+l.phase)*.12;}for(const c of crests){if(c.collected)continue;c.mesh.rotation.y+=dt*1.5;c.mesh.position.y=c.baseY+Math.sin(clock*1.8+c.phase)*.18;}for(const q of world.children){if(q.userData.floatPhase!=null){q.rotation.y+=dt*.7;q.position.y+=Math.sin(clock*1.6+q.userData.floatPhase)*.0007;}}}
function updateEffects(dt){for(const a of effects.userData.anim||[]){a.age+=dt;const t=Math.min(1,a.age/a.dur),r=THREE.MathUtils.lerp(a.r0,a.r1,t);a.mesh.scale.setScalar(r/Math.max(.001,a.r0));a.mesh.material.opacity=(1-t)*.82;if(t>=1)a.mesh.removeFromParent();}effects.userData.anim=(effects.userData.anim||[]).filter(a=>a.age<a.dur);for(const d of effects.userData.debris||[]){d.age+=dt;d.vel.y-=12*dt;d.mesh.position.addScaledVector(d.vel,dt);d.mesh.rotation.x+=dt*4;d.mesh.rotation.y+=dt*3;if(d.age>1.1){d.mesh.material.transparent=true;d.mesh.material.opacity=Math.max(0,1-(d.age-1.1)*2.5);}if(d.age>1.5)d.mesh.removeFromParent();}effects.userData.debris=(effects.userData.debris||[]).filter(d=>d.age<1.5);}
function updateCamera(dt){const target=player.pos.clone().add(new THREE.Vector3(0,1.25,0)),dist=8.5,height=3.7,desired=new THREE.Vector3(target.x+Math.sin(cameraYaw)*dist,target.y+height,target.z+Math.cos(cameraYaw)*dist);camera.position.lerp(desired,1-Math.exp(-7*dt));camera.lookAt(target);}
function updateHUD(){const C=CHARACTERS[player.kind],alive=enemies.filter(e=>e.alive).length,hearts='♥'.repeat(Math.max(0,player.health))+'♡'.repeat(Math.max(0,player.maxHealth-player.health));statsEl.textContent=`${C.name}\nHEALTH ${hearts}  LIVES ${player.lives}\nENEMIES ${alive}  LEAVES ${leavesCollected}/${leaves.length}  CRESTS ${crestsCollected}/3`;cooldownEl.textContent=`F ${C.attack} ${player.attackCD>0?player.attackCD.toFixed(1)+'s':'READY'}\nQ ${C.special} ${player.specialCD>0?player.specialCD.toFixed(1)+'s':'READY'}\nSHIFT DASH ${player.dashCD>0?player.dashCD.toFixed(1)+'s':'READY'}`;missionEl.textContent=alive>0?`BREAK THE BRICK BARRIERS · DEFEAT ${alive} HOSTILE SPRITES · FIND ${3-crestsCollected} MAPLE CREST${3-crestsCollected===1?'':'S'}`:crestsCollected<3?`HOSTILES CLEARED · FIND ${3-crestsCollected} REMAINING MAPLE CREST${3-crestsCollected===1?'':'S'}`:'SHRINE AWAKENED · CLIMB THE ROPE BRIDGE AND ENTER THE LIGHT';}
function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;clock+=dt;player.attackCD=Math.max(0,player.attackCD-dt);player.specialCD=Math.max(0,player.specialCD-dt);player.dashCD=Math.max(0,player.dashCD-dt);player.invuln=Math.max(0,player.invuln-dt);player.actionAge=Math.max(0,player.actionAge-dt);if(playing){if(attackPressed)attack();if(specialPressed)special();attackPressed=specialPressed=false;movePlayer(dt);updateEnemies(dt);updateProjectiles(dt);collect();objective();}else{attackPressed=specialPressed=jumpPressed=dashPressed=false;player.visual?.update(clock,0,0);}updateCollectibles(dt);updateEffects(dt);updateCamera(dt);updateHUD();composer.render();requestAnimationFrame(loop);}
function resize(){renderer.setSize(innerWidth,innerHeight,false);composer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/Math.max(1,innerHeight);camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();setPlayerVisual('gamer');camera.position.set(0,4.5,20);boot.classList.add('hidden');fatal.style.display='none';requestAnimationFrame(loop);
}catch(err){console.error(err);boot.classList.add('hidden');fatal.style.display='flex';fatalText.textContent=String(err?.stack||err);}
