export function createPortalV2(THREE,{mobile=false}={}){
  const root=new THREE.Group();root.name='HybridPortalM2Room01';
  const dummy=new THREE.Object3D();
  const radialTexture=(size=128)=>{const c=document.createElement('canvas');c.width=c.height=size;const g=c.getContext('2d'),rg=g.createRadialGradient(size/2,size/2,0,size/2,size/2,size/2);rg.addColorStop(0,'rgba(255,255,255,1)');rg.addColorStop(.28,'rgba(220,180,255,.46)');rg.addColorStop(1,'rgba(125,55,255,0)');g.fillStyle=rg;g.fillRect(0,0,size,size);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;};
  const glowTex=radialTexture();
  const metalDark=new THREE.MeshPhysicalMaterial({color:0x14131b,metalness:.94,roughness:.20,clearcoat:.30,clearcoatRoughness:.12});
  const metalMid=new THREE.MeshPhysicalMaterial({color:0x626875,metalness:.92,roughness:.17,clearcoat:.34,clearcoatRoughness:.10});
  const metalLight=new THREE.MeshPhysicalMaterial({color:0xb8c3d2,metalness:.89,roughness:.14,clearcoat:.42,clearcoatRoughness:.08});
  const bronze=new THREE.MeshPhysicalMaterial({color:0x9b6c36,metalness:.92,roughness:.23,clearcoat:.24,clearcoatRoughness:.16});
  const blackRubber=new THREE.MeshStandardMaterial({color:0x0b0a11,roughness:.86});
  const glowPurple=new THREE.MeshStandardMaterial({color:0xd7b8ff,emissive:0x8a2bff,emissiveIntensity:5.6,roughness:.16});
  const glowCyan=new THREE.MeshStandardMaterial({color:0xc9faff,emissive:0x29d8ff,emissiveIntensity:5.2,roughness:.15});
  const glassMat=new THREE.MeshPhysicalMaterial({color:0xd8f7ff,roughness:.025,metalness:0,transmission:mobile?.55:.91,thickness:.50,ior:1.46,side:mobile?THREE.FrontSide:THREE.DoubleSide,depthWrite:false,clearcoat:1,clearcoatRoughness:.02,iridescence:mobile?0:.10,iridescenceIOR:1.3});
  const glassEdge=new THREE.MeshPhysicalMaterial({color:0xf2fdff,roughness:.04,metalness:.01,transmission:mobile?.25:.55,thickness:.10,ior:1.42,depthWrite:false,clearcoat:1,emissive:0x244d75,emissiveIntensity:.22});
  function mesh(geo,mat,y=0,cast=true){const m=new THREE.Mesh(geo,mat);m.position.y=y;m.castShadow=cast;m.receiveShadow=true;root.add(m);return m;}
  mesh(new THREE.CylinderGeometry(2.30,2.42,.32,64),metalDark,.18);
  mesh(new THREE.CylinderGeometry(2.16,2.25,.20,64),metalMid,.43);
  mesh(new THREE.CylinderGeometry(1.94,2.03,.12,64),bronze,.60);
  mesh(new THREE.CylinderGeometry(1.77,1.77,.09,64),blackRubber,.70);
  mesh(new THREE.CylinderGeometry(1.62,1.62,.07,64),metalLight,.77);
  mesh(new THREE.CylinderGeometry(1.50,1.50,.025,64),glowCyan,.82,false);
  const chamber=mesh(new THREE.CylinderGeometry(1.52,1.52,4.40,64,1,true),glassMat,3.04,false);chamber.renderOrder=5;
  for(const a of [Math.PI*.18,Math.PI*.82,Math.PI*1.18,Math.PI*1.82]){const s=mesh(new THREE.CylinderGeometry(.018,.018,4.18,8),glassEdge,3.04,false);s.position.x=Math.cos(a)*1.545;s.position.z=Math.sin(a)*1.545;s.renderOrder=6;}
  mesh(new THREE.CylinderGeometry(1.70,1.70,.10,64),blackRubber,5.31);
  mesh(new THREE.CylinderGeometry(1.92,1.82,.13,64),bronze,5.43);
  mesh(new THREE.CylinderGeometry(2.18,2.05,.22,64),metalMid,5.60);
  mesh(new THREE.CylinderGeometry(2.36,2.24,.34,64),metalDark,5.84);
  const ringMeshes=[];
  function ring(y,r,mat=glowPurple,tubeRadius=.04){const m=new THREE.Mesh(new THREE.TorusGeometry(r,tubeRadius,12,64),mat);m.rotation.x=Math.PI/2;m.position.y=y;root.add(m);ringMeshes.push(m);const halo=new THREE.Mesh(new THREE.TorusGeometry(r,.12,8,48),new THREE.MeshBasicMaterial({color:mat===glowCyan?0x50dcff:0xb54cff,transparent:true,opacity:.05,blending:THREE.AdditiveBlending,depthWrite:false}));halo.rotation.x=Math.PI/2;halo.position.y=y;root.add(halo);ringMeshes.push(halo);}
  ring(.82,1.56,glowCyan,.035);ring(.90,1.43,glowPurple,.03);ring(5.18,1.57,glowPurple,.04);ring(5.28,1.44,glowCyan,.03);
  const pylonGeo=new THREE.BoxGeometry(.16,4.72,.16),pylonInst=new THREE.InstancedMesh(pylonGeo,metalDark,4);pylonInst.castShadow=true;root.add(pylonInst);
  const pylonGlowInst=new THREE.InstancedMesh(new THREE.BoxGeometry(.055,3.85,.035),glowPurple,4);root.add(pylonGlowInst);
  for(let i=0;i<4;i++){const a=i*Math.PI/2+Math.PI/4,x=Math.cos(a)*1.83,z=Math.sin(a)*1.83;dummy.position.set(x,3.04,z);dummy.rotation.set(0,-a+.78,0);dummy.updateMatrix();pylonInst.setMatrixAt(i,dummy.matrix);dummy.position.set(x*.998,3.04,z*.998);dummy.updateMatrix();pylonGlowInst.setMatrixAt(i,dummy.matrix);}pylonInst.instanceMatrix.needsUpdate=true;pylonGlowInst.instanceMatrix.needsUpdate=true;
  const accents=new THREE.InstancedMesh(new THREE.BoxGeometry(.34,.10,.10),bronze,16);root.add(accents);for(let i=0;i<16;i++){const a=i/16*Math.PI*2,r=2.03;dummy.position.set(Math.cos(a)*r,.53,Math.sin(a)*r);dummy.rotation.set(0,-a,0);dummy.updateMatrix();accents.setMatrixAt(i,dummy.matrix);}accents.instanceMatrix.needsUpdate=true;
  const panelFrame=mesh(new THREE.BoxGeometry(.94,.54,.18),metalDark,1.00);panelFrame.position.z=2.12;panelFrame.rotation.x=-.08;
  const panelScreen=mesh(new THREE.CylinderGeometry(.20,.20,.035,8),glowCyan,1.00,false);panelScreen.rotation.x=Math.PI/2;panelScreen.position.z=2.225;
  const panelRing=mesh(new THREE.TorusGeometry(.28,.045,10,8),bronze,1.00);panelRing.rotation.x=Math.PI/2;panelRing.position.z=2.24;panelRing.rotation.z=Math.PI/8;
  const glowSprites=[];function glowAt(y,scale,color,opacity){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTex,color,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,opacity}));s.position.set(0,y,0);s.scale.set(scale,scale,1);s.userData.baseScale=scale;s.userData.baseOpacity=opacity;root.add(s);glowSprites.push(s);return s;}glowAt(.86,4.1,0xb54cff,.10);glowAt(5.22,3.8,0x50dcff,.09);glowAt(3.04,2.8,0x8c3dff,.04);
  const energyMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},uFill:{value:.10},uIntensity:{value:.22},uDissolve:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`varying vec2 vUv;uniform float uTime;uniform float uFill;uniform float uIntensity;uniform float uDissolve;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){float y=vUv.y,x=vUv.x;float fill=1.0-smoothstep(uFill-.045,uFill+.045,y);float s1=sin(x*34.0+y*18.0-uTime*4.0+sin(y*13.0+uTime*1.7)*2.2);float s2=sin(x*21.0-y*37.0+uTime*2.8+sin(x*9.0-uTime)*1.5);float filament=pow(max(0.0,.5+.5*s1),5.0);float wisps=pow(max(0.0,.5+.5*s2),7.0);float braid=pow(max(0.0,.5+.5*sin(x*13.0+y*52.0-uTime*6.2)),9.0);float grain=hash(floor(vec2(x*118.0,y*168.0)+uTime*2.0));float idle=.055*(filament+wisps);float a=(idle+fill*(.11+.40*filament+.19*wisps+.14*braid+.12*step(.987,grain)))*uIntensity;float drain=1.0-smoothstep(1.0-uDissolve-.10,1.0-uDissolve+.10,y);a*=mix(1.0,drain,step(.001,uDissolve));vec3 cyan=vec3(.10,.74,1.0),violet=vec3(.68,.10,1.0);vec3 col=mix(cyan,violet,.46+.34*sin(y*9.0+uTime*1.2));gl_FragColor=vec4(col,a);}`});
  const energyColumn=mesh(new THREE.CylinderGeometry(1.28,1.28,4.08,48,1,true),energyMat,3.04,false);energyColumn.receiveShadow=false;energyColumn.renderOrder=2;
  const discMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},uIntensity:{value:.28}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`varying vec2 vUv;uniform float uTime;uniform float uIntensity;void main(){vec2 p=vUv-.5;float r=length(p)*2.0,a=atan(p.y,p.x);float rings=.5+.5*sin(44.0*r-uTime*5.0+sin(a*6.0+uTime*1.8)*2.0);float spokes=.5+.5*sin(a*10.0+r*18.0-uTime*3.0);float fade=1.0-smoothstep(.72,1.0,r);float alpha=(.10+.42*pow(rings,5.0)+.18*pow(spokes,8.0))*fade*uIntensity;vec3 c=mix(vec3(.15,.8,1.0),vec3(.78,.16,1.0),r);gl_FragColor=vec4(c,alpha);}`});
  const floorDisc=new THREE.Mesh(new THREE.CircleGeometry(1.44,48),discMat);floorDisc.rotation.x=-Math.PI/2;floorDisc.position.y=.87;root.add(floorDisc);const topDisc=floorDisc.clone();topDisc.material=discMat.clone();topDisc.rotation.x=Math.PI/2;topDisc.position.y=5.19;root.add(topDisc);
  const risingRings=[];for(let i=0;i<7;i++){const m=new THREE.Mesh(new THREE.TorusGeometry(1.08,.018,8,44),new THREE.MeshBasicMaterial({color:i%2?0xb44dff:0x56dcff,transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false}));m.rotation.x=Math.PI/2;m.position.y=1.0+i*.55;root.add(m);risingRings.push(m);}
  const maxParticles=mobile?90:180,particleGeo=new THREE.BufferGeometry(),particlePos=new Float32Array(maxParticles*3),seeds=[];for(let i=0;i<maxParticles;i++)seeds.push({a:Math.random()*Math.PI*2,r:.22+Math.sqrt(Math.random())*1.05,s:.45+Math.random()*1.15,y:Math.random(),w:Math.random()});particleGeo.setAttribute('position',new THREE.BufferAttribute(particlePos,3));const particleMat=new THREE.PointsMaterial({color:0xd7a6ff,size:.035,transparent:true,opacity:.30,depthWrite:false,blending:THREE.AdditiveBlending});const particles=new THREE.Points(particleGeo,particleMat);root.add(particles);
  const lightLow=new THREE.PointLight(0x8c3dff,6,15,2);lightLow.position.set(0,1.25,.15);root.add(lightLow);const lightHigh=new THREE.PointLight(0x53ddff,4.5,14,2);lightHigh.position.set(0,5.75,0);root.add(lightHigh);
  let charge=0,targetCharge=0;
  function setCharge(v){targetCharge=THREE.MathUtils.clamp(v,0,1);}
  function update(t,dt){charge=THREE.MathUtils.damp(charge,targetCharge,4.5,dt);energyMat.uniforms.uTime.value=t;energyMat.uniforms.uFill.value=.12+charge*.84;energyMat.uniforms.uIntensity.value=.28+charge*1.65;discMat.uniforms.uTime.value=t;topDisc.material.uniforms.uTime.value=t;discMat.uniforms.uIntensity.value=.22+charge*.85;topDisc.material.uniforms.uIntensity.value=.20+charge*.82;for(let i=0;i<risingRings.length;i++){const r=risingRings[i],p=(t*.46+i/risingRings.length)%1;r.position.y=.95+p*4.2;r.scale.setScalar(.78+p*.56);r.material.opacity=(.02+charge*.48)*Math.sin(Math.PI*p);}for(let i=0;i<seeds.length;i++){const q=seeds[i],y=(q.y+t*q.s*.18)%1,a=q.a+t*(.18+q.w*.25),r=q.r*(.88+.15*Math.sin(t+q.w*8));particlePos[i*3]=Math.cos(a)*r;particlePos[i*3+1]=.94+y*4.05;particlePos[i*3+2]=Math.sin(a)*r;}particleGeo.attributes.position.needsUpdate=true;particleMat.opacity=.18+charge*.42;lightLow.intensity=5+charge*16;lightHigh.intensity=4+charge*12;for(const s of glowSprites){s.material.opacity=s.userData.baseOpacity*(1+charge*2.4);const sc=s.userData.baseScale*(1+charge*.20*Math.sin(t*5));s.scale.set(sc,sc,1);}ringMeshes.forEach((r,i)=>{if(r.material.opacity!=null&&r.material.transparent)r.material.opacity=.04+charge*.20;else if(r.material.emissiveIntensity!=null)r.material.emissiveIntensity=(i%2?5.1:5.7)*(1+charge*.45);});panelScreen.material.emissiveIntensity=4.5+charge*4;}
  return{root,setCharge,update,get charge(){return charge;},energyMat,chamber};
}
