import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { createGamerBro } from '/playground-v2/gamer-bro.js?v=106';
import { createPortalV2 } from '/room01-v1/portal-v2.js?v=106';
import { createV04Sprite } from '/room01-v1/v04-sprites.js?v=106';

const $=id=>document.getElementById(id);
const stage=$('stage'),boot=$('boot'),fatal=$('fatal'),fatalText=$('fatalText'),hud=$('hud'),missionEl=$('mission'),statsEl=$('stats'),cooldownEl=$('cooldowns'),selectEl=$('select'),gridEl=$('characterGrid'),resultEl=$('result'),resultText=$('resultText'),replayBtn=$('replayBtn'),attackBtn=$('attackBtn'),specialBtn=$('specialBtn'),jumpBtn=$('jumpBtn'),dashBtn=$('dashBtn'),stick=$('stick'),stickKnob=$('stickKnob'),changeBtn=$('changeBtn');

try{
const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;
const renderer=new THREE.WebGLRenderer({antialias:!mobile,powerPreference:'high-performance'});
renderer.outputColorSpace=THREE.SRGBColorSpace;
renderer.toneMapping=THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure=1.15;
renderer.shadowMap.enabled=true;
renderer.shadowMap.type=THREE.PCFSoftShadowMap;
renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile?1.25:1.7));
stage.appendChild(renderer.domElement);

const scene=new THREE.Scene();
scene.background=new THREE.Color(0x0f0924);
scene.fog=new THREE.FogExp2(0x0f0924,mobile?.018:.0145);
const camera=new THREE.PerspectiveCamera(46,1,.1,150);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));
const bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),mobile?.64:.88,.56,.528);composer.addPass(bloom);composer.addPass(new OutputPass());

scene.add(new THREE.AmbientLight(0x21152f,.26));
scene.add(new THREE.HemisphereLight(0x39255a,0x160e0b,.33));
const key=new THREE.DirectionalLight(0xffcf9d,1.15);key.position.set(-12,20,13);key.castShadow=true;key.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);key.shadow.camera.left=-32;key.shadow.camera.right=32;key.shadow.camera.top=35;key.shadow.camera.bottom=-35;key.shadow.camera.near=.5;key.shadow.camera.far=80;key.shadow.bias=-.0003;scene.add(key);
const violetRim=new THREE.DirectionalLight(0x7154ff,.62);violetRim.position.set(15,11,-25);scene.add(violetRim);

const world=new THREE.Group();world.name='Room01CrystalTrainingChamber';scene.add(world);
const effects=new THREE.Group(),enemyRoot=new THREE.Group(),collectibleRoot=new THREE.Group(),brickRoot=new THREE.Group();scene.add(effects,enemyRoot,collectibleRoot,brickRoot);
const loader=new GLTFLoader();

const stone=new THREE.MeshStandardMaterial({color:0x554863,roughness:.88,metalness:.02,emissive:0x100817,emissiveIntensity:.08});
const stoneDark=new THREE.MeshStandardMaterial({color:0x251c31,roughness:.94,metalness:.02,emissive:0x09050e,emissiveIntensity:.06});
const floorMat=new THREE.MeshStandardMaterial({color:0x665772,roughness:.77,metalness:.03,emissive:0x180d23,emissiveIntensity:.12});
const bronze=new THREE.MeshStandardMaterial({color:0x8f643e,roughness:.43,metalness:.55,emissive:0x211006,emissiveIntensity:.08});
const brickMat=new THREE.MeshStandardMaterial({color:0x865031,roughness:.84,metalness:.02,emissive:0x241008,emissiveIntensity:.10});
const leafMat=new THREE.MeshStandardMaterial({color:0xffa32c,emissive:0xff5e11,emissiveIntensity:2.15,roughness:.32,metalness:.08});
const crestMat=new THREE.MeshStandardMaterial({color:0xffdc72,emissive:0xff8a18,emissiveIntensity:3.1,roughness:.22,metalness:.14});
const crystalMats=[
 new THREE.MeshPhysicalMaterial({color:0xb9a0ff,roughness:.09,transmission:mobile?.15:.72,thickness:.35,ior:1.58,emissive:0x6740ba,emissiveIntensity:2.4}),
 new THREE.MeshPhysicalMaterial({color:0x80e6ff,roughness:.08,transmission:mobile?.12:.68,thickness:.34,ior:1.54,emissive:0x2a91bc,emissiveIntensity:2.5}),
 new THREE.MeshPhysicalMaterial({color:0xff91dd,roughness:.10,transmission:mobile?.10:.64,thickness:.30,ior:1.50,emissive:0xa42d77,emissiveIntensity:2.35})
];
function addMesh(g,m,p=[0,0,0],r=[0,0,0],s=[1,1,1],parent=world){const q=new THREE.Mesh(g,m);q.position.set(...p);q.rotation.set(...r);q.scale.set(...s);q.castShadow=true;q.receiveShadow=true;parent.add(q);return q;}
function chamferShape(w,d,c=.8){const h=w/2,k=d/2,s=new THREE.Shape();s.moveTo(-h+c,-k);s.lineTo(h-c,-k);s.lineTo(h,-k+c);s.lineTo(h,k-c);s.lineTo(h-c,k);s.lineTo(-h+c,k);s.lineTo(-h,k-c);s.lineTo(-h,-k+c);s.closePath();return s;}
function platform(x,z,y,w,d,depth=1.2){const sh=chamferShape(w,d,Math.min(1.1,Math.min(w,d)*.11));const geo=new THREE.ExtrudeGeometry(sh,{depth,bevelEnabled:true,bevelSegments:1,bevelSize:.16,bevelThickness:.10});geo.rotateX(Math.PI/2);geo.translate(0,depth*.48,0);addMesh(geo,stoneDark,[x,y-depth,z]);const top=new THREE.ShapeGeometry(sh);top.rotateX(-Math.PI/2);addMesh(top,floorMat,[x,y+.03,z]);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(top),new THREE.LineBasicMaterial({color:0xa17a9d,transparent:true,opacity:.33}));edge.position.set(x,y+.055,z);world.add(edge);rectSurface(x,z,w-.35,d-.35,y+.06);return{x,z,y,w,d};}
function bridge(x,z,y,w,d,ry=0){addMesh(new THREE.BoxGeometry(w+.45,.65,d+.2),stoneDark,[x,y-.33,z],[0,ry,0]);addMesh(new THREE.BoxGeometry(w,.16,d),floorMat,[x,y+.02,z],[0,ry,0]);for(const side of[-1,1]){const sx=Math.cos(ry)*side*(w/2-.12),sz=-Math.sin(ry)*side*(w/2-.12);addMesh(new THREE.BoxGeometry(.12,.16,d),bronze,[x+sx,y+.15,z+sz],[0,ry,0]);}rectSurface(x,z,w-.18,d-.05,y+.1,ry);}
function stairs(x1,z1,y1,x2,z2,y2,w=3.2){const dx=x2-x1,dz=z2-z1,d=Math.hypot(dx,dz),ry=Math.atan2(dx,dz),n=Math.max(7,Math.ceil(d/.75));for(let i=0;i<n;i++){const t=(i+.5)/n,yy=THREE.MathUtils.lerp(y1,y2,(i+1)/n);addMesh(new THREE.BoxGeometry(w,.28,d/n*1.08),i%3?floorMat:stone,[x1+dx*t,yy-.14,z1+dz*t],[0,ry,0]);}rampSurface(x1,z1,y1+.1,x2,z2,y2+.1,w-.15);}

const surfaces=[];
function rectSurface(x,z,w,d,y,ry=0,dynamic=null){surfaces.push({type:'rect',x,z,w,d,y,ry,dynamic});}
function rampSurface(x1,z1,y1,x2,z2,y2,w){surfaces.push({type:'ramp',x1,z1,y1,x2,z2,y2,w});}
function surfaceHeight(x,z){let best=null;for(const s of surfaces){if(s.type==='rect'){let sx=s.x,sz=s.z,sy=s.y;if(s.dynamic){sx=s.dynamic.position.x;sz=s.dynamic.position.z;sy=s.dynamic.position.y+.18;}const c=Math.cos(-s.ry),q=Math.sin(-s.ry),dx=x-sx,dz=z-sz,lx=dx*c-dz*q,lz=dx*q+dz*c;if(Math.abs(lx)<=s.w/2&&Math.abs(lz)<=s.d/2)best=Math.max(best??-Infinity,sy);}else{const dx=s.x2-s.x1,dz=s.z2-s.z1,L=Math.hypot(dx,dz),ux=dx/L,uz=dz/L,px=x-s.x1,pz=z-s.z1,t=(px*ux+pz*uz)/L,side=Math.abs(px*(-uz)+pz*ux);if(t>=0&&t<=1&&side<=s.w/2)best=Math.max(best??-Infinity,s.y1+(s.y2-s.y1)*t);}}return best;}

// Dense, authored-looking chamber topology: no giant empty floor.
platform(0,20,0,12,9);bridge(0,14.3,0,4.6,3.4);platform(0,9,0,15,8.4);bridge(0,4.1,0,5.0,2.6);platform(0,-1,0,19,8.2);
platform(-12,-8,2.55,9,10);stairs(-7,-3.5,.08,-10,-5.0,2.55,3.4);
platform(0,-13,3.55,14,9.5);stairs(0,-5.0,.08,0,-8.0,3.55,3.6);
platform(0,-25,5.15,14,10);stairs(0,-17.5,3.6,0,-20.2,5.15,3.8);
platform(12,-8,1.25,7.5,8.5);
bridge(7.8,-4.7,.65,3.2,4.8,.67);

const moving=[];for(let i=0;i<3;i++){const m=addMesh(new THREE.BoxGeometry(3.0,.42,2.3),i%2?stone:floorMat,[8.3+i*3.0,1.1,-12.5-i*2.2]);m.userData.phase=i*1.8;m.userData.baseX=m.position.x;moving.push(m);rectSurface(m.position.x,m.position.z,2.8,2.15,m.position.y+.2,0,m);}

// Deep void.
const voidPlane=addMesh(new THREE.PlaneGeometry(80,100),new THREE.MeshBasicMaterial({color:0x090311,side:THREE.DoubleSide}),[0,-7,-5],[-Math.PI/2,0,0],[1,1,1]);voidPlane.receiveShadow=false;
for(let i=0;i<35;i++){const a=i/35*Math.PI*2,r=26+(i%5)*1.3;addMesh(new THREE.BoxGeometry(2.0+Math.random()*2,8+Math.random()*15,2+Math.random()*2),stoneDark,[Math.sin(a)*r,-3+Math.random()*3,-6+Math.cos(a)*r],[0,a,0],[1,1,1]);}

// Crystals: bright features against the dark frame.
const shardGeo=new THREE.OctahedronGeometry(.46,0);for(let i=0;i<(mobile?70:120);i++){const x=(Math.random()-.5)*38,z=-31+Math.random()*58,y=10+Math.random()*8-Math.abs(x)*.07,sc=.25+Math.random()*.8;const q=addMesh(shardGeo,crystalMats[i%3],[x,y,z],[Math.random(),Math.random()*6,Math.random()],[sc*.55,sc*1.5,sc*.55]);q.castShadow=false;}
for(const [x,y,z,s,c] of [[-7,1.0,10,1.5,0],[7,1.0,9,1.3,1],[-15,3.2,-8,1.8,2],[10,1.8,-7,1.3,0],[-5,4.2,-14,1.7,1],[5,4.2,-14,1.7,2]]){const q=addMesh(shardGeo,crystalMats[c],[x,y,z],[.2,.4,0],[s*.65,s*1.8,s*.65]);const light=new THREE.PointLight([0xa979ff,0x55dfff,0xff6ecc][c],mobile?3.2:5.2,7,2);light.position.set(x,y+1,z);scene.add(light);}

// Warm counterpoint lights.
for(const [x,y,z] of [[-17,5,4],[17,5,4],[-17,5,-12],[17,5,-12],[-9,7,-25],[9,7,-25]]){const l=new THREE.PointLight(0xff943e,mobile?2.1:3.5,9,2);l.position.set(x,y,z);scene.add(l);addMesh(new THREE.SphereGeometry(.09,8,6),new THREE.MeshStandardMaterial({color:0xffd19a,emissive:0xff7b2a,emissiveIntensity:5}),[x,y,z]);}

// Same-domain authored library dressing already vendored by the project.
const envTemplates={};
async function loadGLB(url){return await new Promise((res,rej)=>loader.load(url,res,undefined,rej));}
function cloneSized(sceneObj,{w,h,d,tint=0xffffff}={}){const g=sceneObj.clone(true);g.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=true;if(o.material){o.material=o.material.clone();if(o.material.color)o.material.color.multiply(new THREE.Color(tint));}}});g.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(g),size=box.getSize(new THREE.Vector3()),ctr=box.getCenter(new THREE.Vector3());const sx=w? w/Math.max(size.x,.001):1,sy=h?h/Math.max(size.y,.001):1,sz=d?d/Math.max(size.z,.001):1;g.scale.set(sx,sy,sz);g.position.set(-ctr.x*sx,-box.min.y*sy,-ctr.z*sz);const wrap=new THREE.Group();wrap.add(g);return wrap;}
async function buildLibraryDress(){const [gate,book,lamp,stairAsset]=await Promise.allSettled([
 loadGLB('../hybrid-v09/assets/kenney/dungeon/gate.glb'),loadGLB('../hybrid-v09/assets/kenney/furniture/bookcaseOpen.glb'),loadGLB('../hybrid-v09/assets/kenney/furniture/lampWall.glb'),loadGLB('../hybrid-v09/assets/kenney/dungeon/stairs.glb')]);
 if(gate.status==='fulfilled')envTemplates.gate=gate.value.scene;if(book.status==='fulfilled')envTemplates.book=book.value.scene;if(lamp.status==='fulfilled')envTemplates.lamp=lamp.value.scene;if(stairAsset.status==='fulfilled')envTemplates.stairs=stairAsset.value.scene;
 if(envTemplates.gate){for(const z of[18,10,1,-8,-16,-25])for(const side of[-1,1]){const g=cloneSized(envTemplates.gate,{w:5.8,h:8.5,d:1.4,tint:0x74607d});g.position.set(side*18,0,z);g.rotation.y=side>0?-Math.PI/2:Math.PI/2;world.add(g);}}
 if(envTemplates.book){for(const z of[16,7,-2,-11,-20])for(const side of[-1,1]){const b=cloneSized(envTemplates.book,{w:5.1,h:6.2,d:1.15,tint:0x705566});b.position.set(side*17.25,.25,z);b.rotation.y=side>0?-Math.PI/2:Math.PI/2;world.add(b);}}
 if(envTemplates.lamp){for(const z of[15,3,-9,-21])for(const side of[-1,1]){const l=cloneSized(envTemplates.lamp,{w:.9,h:1.2,d:.8,tint:0xffb26f});l.position.set(side*16.6,5.0,z);l.rotation.y=side>0?-Math.PI/2:Math.PI/2;world.add(l);}}
}

// Portal M2 visual foundation, moved to the far end as the earned room exit.
const portal=createPortalV2(THREE,{mobile});portal.root.position.set(0,5.25,-25.0);portal.root.scale.setScalar(.90);world.add(portal.root);portal.setCharge(.08);

// Maple collectibles.
function mapleShape(scale=1){const pts=[[0,1.25],[-.18,.58],[-.68,.82],[-.45,.25],[-1,.08],[-.46,-.17],[-.62,-.73],[-.1,-.48],[0,-1.25],[.1,-.48],[.62,-.73],[.46,-.17],[1,.08],[.45,.25],[.68,.82],[.18,.58]];const sh=new THREE.Shape();pts.forEach(([x,y],i)=>i?sh.lineTo(x*scale,y*scale):sh.moveTo(x*scale,y*scale));sh.closePath();return sh;}
const leafGeo=new THREE.ExtrudeGeometry(mapleShape(.24),{depth:.08,bevelEnabled:true,bevelSegments:1,bevelSize:.025,bevelThickness:.02});leafGeo.center();const crestGeo=new THREE.ExtrudeGeometry(mapleShape(.55),{depth:.16,bevelEnabled:true,bevelSegments:2,bevelSize:.05,bevelThickness:.04});crestGeo.center();
const leaves=[],crests=[];function addLeaf(x,y,z){const m=new THREE.Mesh(leafGeo,leafMat);m.position.set(x,y,z);m.castShadow=false;collectibleRoot.add(m);leaves.push({mesh:m,baseY:y,phase:Math.random()*6,collected:false});}function addCrest(x,y,z){const m=new THREE.Mesh(crestGeo,crestMat);m.position.set(x,y,z);collectibleRoot.add(m);const l=new THREE.PointLight(0xff9f29,4.5,7,2);m.add(l);crests.push({mesh:m,baseY:y,phase:2.1,collected:false});}
for(const p of [[-3,1,19],[0,1,18],[3,1,19],[-5,1,9],[0,1,9],[5,1,9],[-7,1,-1],[0,1,-1],[7,1,-1],[-13,3.5,-7],[-11,3.5,-10],[10,2.2,-8],[13,2.2,-10],[-4,4.5,-13],[4,4.5,-13],[0,6.0,-22]])addLeaf(...p);addCrest(0,4.65,-14.5);
let leavesCollected=0,crestCollected=0;

// Power-up: optional side-route overcharge.
const powerCrystal=addMesh(new THREE.OctahedronGeometry(.65,0),crystalMats[1],[-13,4.1,-10],[0,.4,0],[1,1.8,1],collectibleRoot);const powerLight=new THREE.PointLight(0x51ddff,5,7,2);powerCrystal.add(powerLight);let powerTaken=false,overcharge=0;

// Breakable brick barriers. They are physical until destroyed.
const bricks=[];function addBrick(x,y,z,wallId,ry=0){const m=addMesh(new THREE.BoxGeometry(1.45,.74,.82),brickMat.clone(),[x,y,z],[0,ry,0],[1,1,1],brickRoot);bricks.push({mesh:m,hp:2,alive:true,wallId,ry});return m;}function wall(cx,cz,y,cols,rows,id,axis='x'){for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const off=(c-(cols-1)/2)*1.52+(r%2?.76:0);addBrick(axis==='x'?cx+off:cx,y+.42+r*.78,axis==='z'?cz+off:cz,id,axis==='z'?Math.PI/2:0);}}
wall(0,14.1,0,6,3,'entry');wall(-12,-3.8,2.55,5,3,'secret');wall(0,-9.0,3.55,6,3,'crest');
function brickBlocks(nx,nz,py){for(const b of bricks){if(!b.alive)continue;const p=b.mesh.position;if(Math.abs(py-p.y)>1.5)continue;const c=Math.cos(-b.ry),s=Math.sin(-b.ry),dx=nx-p.x,dz=nz-p.z,lx=dx*c-dz*s,lz=dx*s+dz*c;if(Math.abs(lx)<1.0&&Math.abs(lz)<.72)return true;}return false;}

const CHARACTERS={
 gamer:{name:'GAMER BRO',subtitle:'Prism Bolt · Nova Shockwave',color:'#52d7ff',attack:'PRISM BOLT',special:'NOVA SHOCKWAVE',speed:7.3,jump:7.5,attackCD:.32,specialCD:4.8},
 dash:{name:'DASH / CITRUS',subtitle:'Citrus Bolt · Cape Cyclone',color:'#ff8b2e',attack:'CITRUS BOLT',special:'CAPE CYCLONE',speed:8.2,jump:8.0,attackCD:.30,specialCD:4.2},
 water:{name:'WATER SPRITE',subtitle:'Bubble Shot · Tidal Burst',color:'#59c6ff',attack:'BUBBLE SHOT',special:'TIDAL BURST',speed:7.5,jump:7.7,attackCD:.38,specialCD:4.6},
 fire:{name:'FIRE SPRITE',subtitle:'Fireball · Inferno Bloom',color:'#ff7628',attack:'FIREBALL',special:'INFERNO BLOOM',speed:7.1,jump:7.4,attackCD:.44,specialCD:5.0},
 earth:{name:'EARTH SPRITE',subtitle:'Stone Punch · Seismic Slam',color:'#79c65b',attack:'STONE PUNCH',special:'SEISMIC SLAM',speed:6.4,jump:6.8,attackCD:.58,specialCD:5.7},
 ghost:{name:'GHOST SPRITE',subtitle:'Spectral Lance · Phase Rush',color:'#b67cff',attack:'SPECTRAL LANCE',special:'PHASE RUSH',speed:7.9,jump:7.9,attackCD:.36,specialCD:4.2}
};
for(const [id,c] of Object.entries(CHARACTERS)){const b=document.createElement('button');b.className='characterCard';b.dataset.character=id;b.style.setProperty('--accent',c.color);b.innerHTML=`<div class="modelGlyph ${id}"></div><strong>${c.name}</strong><small>${c.subtitle}</small>`;gridEl.appendChild(b);}

const player={root:new THREE.Group(),visual:null,kind:'gamer',pos:new THREE.Vector3(0,.12,21),vel:new THREE.Vector3(),grounded:false,health:6,maxHealth:6,lives:3,attackCD:0,specialCD:0,dashCD:0,invuln:0,facing:new THREE.Vector3(0,0,-1),entering:false,entryT:0};scene.add(player.root);let bro=null;
async function setPlayerVisual(kind){const C=CHARACTERS[kind];if(!C)return;while(player.root.children.length)player.root.remove(player.root.children[0]);player.kind=kind;bro=null;if(kind==='gamer'){bro=createGamerBro(THREE,renderer,{detail:mobile?'low':'high',height:2.62,colorway:'teal'});bro.setHome(0,0,0);bro.setRoomLight(.52);const holder=new THREE.Group();holder.add(bro.root);player.root.add(holder);player.visual={root:holder,play:(n)=>bro.setAction(n!=='Idle'&&n!=='Walk'),update:(dt,moving,action)=>{bro.setMotion(moving>.55?'run':moving>.04?'walk':'idle');bro.setAction(action);bro.update(performance.now()/1000,dt,action?1:0);}};}else{const v=createV04Sprite(THREE,kind,{height:kind==='earth'?2.5:kind==='dash'?2.48:2.34,mobile});player.root.add(v.root);player.visual=v;}player.root.position.copy(player.pos);}

const enemies=[];
const enemySpawns=[['ghost',-5,8,0],['fire',5,7,0],['earth',-4,-1,0],['water',7,-2,0],['ghost',-12,-8,2.55],['earth',3,-13,3.55],['fire',-3,-13,3.55]];
async function spawnEnemy(kind,x,z,y){const v=createV04Sprite(THREE,kind,{height:kind==='earth'?2.25:1.88,mobile}),root=v.root;root.position.set(x,y,z);enemyRoot.add(root);const tank=kind==='earth';const e={kind,visual:v,root,pos:new THREE.Vector3(x,y,z),vel:new THREE.Vector3(),hp:tank?6:4,maxHp:tank?6:4,alive:true,attackCD:.4+Math.random(),stun:0,hit:0,phase:Math.random()*6};enemies.push(e);return e;}

const projectiles=[];function pmat(color){return new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:3.2,roughness:.15,transparent:true,opacity:.97});}function fireProjectile({origin,dir,speed=16,damage=1,radius=.22,color=0xffffff,owner='player',life=2.5,pierce=0,brickDamage=1,knock=2,splash=0}){const m=new THREE.Mesh(new THREE.SphereGeometry(radius,12,8),pmat(color));m.position.copy(origin);effects.add(m);projectiles.push({mesh:m,vel:dir.clone().normalize().multiplyScalar(speed),damage,owner,life,pierce,brickDamage,knock,splash,hit:new Set(),radius});return m;}
function ringFx(pos,color,r0=.25,r1=5,dur=.45){const m=new THREE.Mesh(new THREE.RingGeometry(r0,r0+.14,44),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.82,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));m.rotation.x=-Math.PI/2;m.position.copy(pos);m.position.y+=.15;effects.add(m);effects.userData.rings??=[];effects.userData.rings.push({m,age:0,dur,r0,r1});}
function debris(pos,color=0x865031,count=5){for(let i=0;i<count;i++){const m=addMesh(new THREE.BoxGeometry(.13+.2*Math.random(),.12+.18*Math.random(),.12+.18*Math.random()),new THREE.MeshStandardMaterial({color,roughness:.9}),pos.toArray(),[Math.random()*3,Math.random()*3,Math.random()*3],[1,1,1],effects);effects.userData.debris??=[];effects.userData.debris.push({m,v:new THREE.Vector3((Math.random()-.5)*4,2+Math.random()*4,(Math.random()-.5)*4),age:0});}}
function damageBrick(b,n=1){if(!b.alive)return false;b.hp-=n;b.mesh.material.emissive.setHex(0xff5a15);b.mesh.material.emissiveIntensity=1.5;if(b.hp<=0){b.alive=false;b.mesh.visible=false;debris(b.mesh.position.clone(),0x865031,4);if(Math.random()<.45)addLeaf(b.mesh.position.x,b.mesh.position.y+.6,b.mesh.position.z);return true;}setTimeout(()=>{if(b.alive){b.mesh.material.emissive.setHex(0x241008);b.mesh.material.emissiveIntensity=.10;}},90);return false;}function breakRadius(pos,r,dmg=2){for(const b of bricks)if(b.alive&&b.mesh.position.distanceTo(pos)<r)damageBrick(b,dmg);}
function hitEnemy(e,dmg,knock=0,from=null){if(!e.alive)return;e.hp-=dmg;e.hit=.17;e.stun=.35;e.visual.play('HitRecieve',true);if(from&&knock){const d=e.pos.clone().sub(from).setY(0);if(d.lengthSq()>.01)e.vel.add(d.normalize().multiplyScalar(knock));}if(e.hp<=0){e.alive=false;e.root.visible=false;debris(e.pos.clone().add(new THREE.Vector3(0,.7,0)),parseInt(CHARACTERS[e.kind].color.slice(1),16),7);for(let i=0;i<2;i++)addLeaf(e.pos.x+(i-.5)*.8,e.pos.y+1,e.pos.z+(Math.random()-.5)*.5);}}function damageEnemies(pos,r,dmg,knock=4){for(const e of enemies)if(e.alive&&e.pos.distanceTo(pos)<r)hitEnemy(e,dmg,knock,pos);}

const keys=new Set();let attackPressed=false,specialPressed=false,jumpPressed=false,dashPressed=false,pointerDown=false,lastPX=0,cameraYaw=Math.PI,cameraPitch=.26;const stickAxis={x:0,z:0};
addEventListener('keydown',e=>{keys.add(e.code);if(e.repeat)return;if(e.code==='KeyF'||e.code==='KeyE')attackPressed=true;if(e.code==='KeyQ')specialPressed=true;if(e.code==='Space')jumpPressed=true;if(e.code.startsWith('Shift'))dashPressed=true;if(e.code==='KeyC')openSelect();if(e.code==='KeyR')restart();});addEventListener('keyup',e=>keys.delete(e.code));renderer.domElement.addEventListener('pointerdown',e=>{pointerDown=true;lastPX=e.clientX;renderer.domElement.setPointerCapture?.(e.pointerId);});addEventListener('pointermove',e=>{if(pointerDown){cameraYaw-=(e.clientX-lastPX)*.006;lastPX=e.clientX;}});addEventListener('pointerup',()=>pointerDown=false);
for(const [b,fn] of [[attackBtn,()=>attackPressed=true],[specialBtn,()=>specialPressed=true],[jumpBtn,()=>jumpPressed=true],[dashBtn,()=>dashPressed=true]])b.addEventListener('pointerdown',e=>{e.preventDefault();fn();});let stickId=null;function stickMove(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,L=Math.max(1,Math.hypot(dx,dy)),max=r.width*.32,k=Math.min(1,max/L);stickAxis.x=dx/max*k;stickAxis.z=dy/max*k;stickKnob.style.transform=`translate(${dx*k}px,${dy*k}px)`;}stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickId)stickMove(e);});for(const ev of['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(ev,e=>{if(stickId===e.pointerId){stickId=null;stickAxis.x=stickAxis.z=0;stickKnob.style.transform='';}});

function movePlayer(dt){if(player.entering)return;const C=CHARACTERS[player.kind],forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-stickAxis.z,right=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+stickAxis.x,len=Math.min(1,Math.hypot(forward,right));const f=new THREE.Vector3(-Math.sin(cameraYaw),0,-Math.cos(cameraYaw)),r=new THREE.Vector3(Math.cos(cameraYaw),0,-Math.sin(cameraYaw)),wish=f.multiplyScalar(forward).add(r.multiplyScalar(right));if(wish.lengthSq()>.001)wish.normalize();let speed=C.speed*(overcharge>0?1.08:1);if(dashPressed&&player.dashCD<=0){player.dashCD=1.15;player.vel.x+=wish.x*10;player.vel.z+=wish.z*10;ringFx(player.pos,parseInt(C.color.slice(1),16),.15,2.2,.25);}dashPressed=false;player.vel.x=THREE.MathUtils.damp(player.vel.x,wish.x*speed*len,8,dt);player.vel.z=THREE.MathUtils.damp(player.vel.z,wish.z*speed*len,8,dt);const old=player.pos.clone();player.pos.x+=player.vel.x*dt;player.pos.z+=player.vel.z*dt;if(brickBlocks(player.pos.x,player.pos.z,player.pos.y)){player.pos.x=old.x;player.pos.z=old.z;player.vel.x=player.vel.z=0;}const ground=surfaceHeight(player.pos.x,player.pos.z);if(player.grounded&&jumpPressed){player.vel.y=C.jump;player.grounded=false;player.visual?.play('Jump',true);}jumpPressed=false;player.vel.y-=19*dt;player.pos.y+=player.vel.y*dt;if(ground!=null&&player.pos.y<=ground+.08&&player.vel.y<=0){player.pos.y=ground+.08;player.vel.y=0;player.grounded=true;}else if(ground==null)player.grounded=false;if(player.pos.y<-7)loseLife();if(wish.lengthSq()>.01){player.facing.lerp(wish,.25).normalize();player.root.rotation.y=Math.atan2(player.facing.x,player.facing.z);}player.root.position.copy(player.pos);player.visual?.update(dt,len,player.attackCD>.01&&player.attackCD>CHARACTERS[player.kind].attackCD-.12);}
function loseLife(){if(player.entering)return;player.lives--;if(player.lives<=0){player.lives=3;leavesCollected=0;}player.health=player.maxHealth;player.pos.set(0,.15,20);player.vel.set(0,0,0);player.grounded=false;player.invuln=1.2;player.root.position.copy(player.pos);}

function attack(){const C=CHARACTERS[player.kind];if(player.attackCD>0||player.entering)return;player.attackCD=C.attackCD*(overcharge>0?.62:1);player.visual?.play('Attack',true);const origin=player.pos.clone().add(new THREE.Vector3(0,1.25,0)),dir=player.facing.clone(),bonus=overcharge>0?1:0,color=parseInt(C.color.slice(1),16);switch(player.kind){case'gamer':fireProjectile({origin,dir,speed:23,damage:2+bonus,radius:.20,color:0x65e5ff,pierce:1,brickDamage:2,knock:4});break;case'dash':fireProjectile({origin,dir,speed:26,damage:2+bonus,radius:.18,color:0xffa342,pierce:1,brickDamage:2,knock:5});break;case'water':fireProjectile({origin,dir,speed:19,damage:2+bonus,radius:.31,color:0x67d8ff,splash:1.6,brickDamage:2,knock:7});break;case'ghost':fireProjectile({origin,dir,speed:25,damage:2+bonus,radius:.20,color,life:2.7,pierce:4,brickDamage:2,knock:2});break;case'earth':{const p=player.pos.clone().add(dir.clone().multiplyScalar(1.7));ringFx(p,color,.2,2.3,.28);damageEnemies(p,2.4,3+bonus,6);breakRadius(p,2.7,3);}break;case'fire':fireProjectile({origin,dir,speed:18,damage:2+bonus,radius:.27,color,splash:2.0,brickDamage:3,knock:4});break;}}
function special(){const C=CHARACTERS[player.kind];if(player.specialCD>0||player.entering)return;player.specialCD=C.specialCD*(overcharge>0?.72:1);player.visual?.play('Power',true);const color=parseInt(C.color.slice(1),16),dmg=overcharge>0?4:3;switch(player.kind){case'gamer':ringFx(player.pos,0x74dfff,.4,7,.55);damageEnemies(player.pos,6.5,dmg,8);breakRadius(player.pos,6.5,4);break;case'dash':{ringFx(player.pos,0xffa43e,.35,6.3,.52);damageEnemies(player.pos,5.8,dmg+1,9);breakRadius(player.pos,5.8,4);for(let i=0;i<10;i++){const d=new THREE.Vector3(Math.sin(i*Math.PI/5),.04,Math.cos(i*Math.PI/5));fireProjectile({origin:player.pos.clone().add(new THREE.Vector3(0,1,0)),dir:d,speed:11,damage:1,radius:.13,color:0xffa43e,life:.9,brickDamage:1});}break;}case'water':ringFx(player.pos,0x6ce6ff,.45,7.2,.72);damageEnemies(player.pos,6.8,dmg,13);breakRadius(player.pos,5.2,3);for(const e of enemies)if(e.alive&&e.pos.distanceTo(player.pos)<7)e.stun=1.0;break;case'ghost':{player.invuln=1;const start=player.pos.clone(),end=start.clone().add(player.facing.clone().multiplyScalar(8));damageEnemies(start.clone().lerp(end,.5),5,dmg,9);for(const b of bricks)if(b.alive){const rel=b.mesh.position.clone().sub(start),t=THREE.MathUtils.clamp(rel.dot(player.facing)/8,0,1),near=start.clone().lerp(end,t);if(b.mesh.position.distanceTo(near)<1.6)damageBrick(b,5);}const h=surfaceHeight(end.x,end.z);if(h!=null){player.pos.copy(end);player.pos.y=h+.1;}ringFx(start,color,.2,3,.3);ringFx(player.pos,color,.2,3,.3);break;}case'earth':ringFx(player.pos,color,.6,8,.65);damageEnemies(player.pos,7,dmg+1,11);breakRadius(player.pos,8,6);player.vel.y=4;break;case'fire':ringFx(player.pos,color,.5,7,.58);damageEnemies(player.pos,6.5,dmg+1,6);breakRadius(player.pos,6.2,5);for(let i=0;i<12;i++){const d=new THREE.Vector3(Math.sin(i*Math.PI/6),.05,Math.cos(i*Math.PI/6));fireProjectile({origin:player.pos.clone().add(new THREE.Vector3(0,1,0)),dir:d,speed:9,damage:1,radius:.14,color,life:1,brickDamage:1});}break;}}

function enemyHitPlayer(dmg,from,knock=4){if(player.invuln>0||!playing||player.entering)return;player.health-=dmg;player.invuln=.9;const d=player.pos.clone().sub(from).setY(0);if(d.lengthSq()>.01){d.normalize();player.vel.x+=d.x*knock;player.vel.z+=d.z*knock;}player.vel.y=Math.max(player.vel.y,3);ringFx(player.pos,0xff4264,.1,1.5,.22);if(player.health<=0)loseLife();}
function updateEnemies(dt){for(const e of enemies){if(!e.alive)continue;e.stun=Math.max(0,e.stun-dt);e.attackCD=Math.max(0,e.attackCD-dt);e.hit=Math.max(0,e.hit-dt);if(e.stun<=0){const to=player.pos.clone().sub(e.pos),dist=Math.hypot(to.x,to.z);to.y=0;if(dist>.01)to.normalize();const ranged=e.kind==='ghost'||e.kind==='water'||e.kind==='fire';if(ranged){if(dist>5){e.vel.x=THREE.MathUtils.damp(e.vel.x,to.x*2.1,3,dt);e.vel.z=THREE.MathUtils.damp(e.vel.z,to.z*2.1,3,dt);}else{e.vel.x=THREE.MathUtils.damp(e.vel.x,0,5,dt);e.vel.z=THREE.MathUtils.damp(e.vel.z,0,5,dt);if(e.attackCD<=0){e.attackCD=1.25+Math.random()*.35;fireProjectile({origin:e.pos.clone().add(new THREE.Vector3(0,1.1,0)),dir:player.pos.clone().sub(e.pos).setY(.12),speed:e.kind==='water'?10:9,damage:1,radius:.22,color:parseInt(CHARACTERS[e.kind].color.slice(1),16),owner:'enemy',life:3,knock:3});e.visual.play('Bite_InPlace',true);}}}else{if(dist>1.8){e.vel.x=THREE.MathUtils.damp(e.vel.x,to.x*(e.kind==='earth'?1.5:2.4),4,dt);e.vel.z=THREE.MathUtils.damp(e.vel.z,to.z*(e.kind==='earth'?1.5:2.4),4,dt);}else if(e.attackCD<=0){e.attackCD=e.kind==='earth'?1.55:1.05;enemyHitPlayer(e.kind==='earth'?2:1,e.pos,5);e.visual.play('Bite_InPlace',true);}}}
 const old=e.pos.clone();e.pos.addScaledVector(e.vel,dt);const h=surfaceHeight(e.pos.x,e.pos.z);if(h!=null)e.pos.y=THREE.MathUtils.damp(e.pos.y,h+.05,10,dt);else{e.pos.copy(old);e.vel.multiplyScalar(.2);}e.root.position.copy(e.pos);if(Math.hypot(e.vel.x,e.vel.z)>.08)e.root.rotation.y=Math.atan2(e.vel.x,e.vel.z);e.visual.update(dt,Math.hypot(e.vel.x,e.vel.z)>.15,false);}}
function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.life-=dt;p.mesh.position.addScaledVector(p.vel,dt);if(p.owner==='player'){for(const e of enemies){if(!e.alive||p.hit.has(e))continue;if(e.pos.clone().add(new THREE.Vector3(0,.8,0)).distanceTo(p.mesh.position)<.75+p.radius){p.hit.add(e);hitEnemy(e,p.damage,p.knock,p.mesh.position);if(p.splash)damageEnemies(p.mesh.position,p.splash,1,3);p.pierce--;if(p.pierce<0){p.life=0;break;}}}for(const b of bricks){if(!b.alive||p.life<=0)continue;if(b.mesh.position.distanceTo(p.mesh.position)<.9){damageBrick(b,p.brickDamage);p.pierce--;if(p.pierce<0){p.life=0;break;}}}}else if(p.mesh.position.distanceTo(player.pos.clone().add(new THREE.Vector3(0,1,0)))<.8){enemyHitPlayer(p.damage,p.mesh.position,p.knock);p.life=0;}if(p.life<=0){p.mesh.removeFromParent();projectiles.splice(i,1);}}}

function collectThings(){for(const l of leaves){if(!l.collected&&l.mesh.position.distanceTo(player.pos)<1.0){l.collected=true;l.mesh.visible=false;leavesCollected++;ringFx(l.mesh.position,0xffa332,.08,1.1,.23);}}for(const c of crests){if(!c.collected&&c.mesh.position.distanceTo(player.pos)<1.35){c.collected=true;c.mesh.visible=false;crestCollected=1;player.health=Math.min(player.maxHealth,player.health+2);ringFx(c.mesh.position,0xffd66e,.2,3.2,.5);}}if(!powerTaken&&powerCrystal.visible&&powerCrystal.position.distanceTo(player.pos)<1.35){powerTaken=true;powerCrystal.visible=false;overcharge=12;ringFx(powerCrystal.position,0x65e6ff,.2,4,.55);}}
function updateCollectibles(dt,t){for(const l of leaves)if(!l.collected){l.mesh.rotation.y+=dt*2;l.mesh.position.y=l.baseY+Math.sin(t*2.4+l.phase)*.12;}for(const c of crests)if(!c.collected){c.mesh.rotation.y+=dt*1.5;c.mesh.position.y=c.baseY+Math.sin(t*1.8+c.phase)*.18;}if(!powerTaken){powerCrystal.rotation.y+=dt;powerCrystal.position.y=4.1+Math.sin(t*2)*.16;}for(const m of moving){m.position.x=m.userData.baseX+Math.sin(t*.8+m.userData.phase)*1.15;}}
function updateFx(dt){for(const a of effects.userData.rings||[]){a.age+=dt;const t=Math.min(1,a.age/a.dur),r=THREE.MathUtils.lerp(a.r0,a.r1,t);a.m.scale.setScalar(r/Math.max(.01,a.r0));a.m.material.opacity=(1-t)*.82;if(t>=1)a.m.removeFromParent();}effects.userData.rings=(effects.userData.rings||[]).filter(a=>a.age<a.dur);for(const d of effects.userData.debris||[]){d.age+=dt;d.v.y-=12*dt;d.m.position.addScaledVector(d.v,dt);d.m.rotation.x+=dt*4;if(d.age>1)d.m.material.transparent=true,d.m.material.opacity=Math.max(0,1-(d.age-1)*2.5);if(d.age>1.4)d.m.removeFromParent();}effects.userData.debris=(effects.userData.debris||[]).filter(d=>d.age<1.4);}

let portalUnlocked=false,playing=false,victory=false,clock=0,last=performance.now();const portalWorld=new THREE.Vector3(0,5.25,-25);
function objective(dt){const alive=enemies.filter(e=>e.alive).length;portalUnlocked=crestCollected===1&&alive===0;portal.setCharge(portalUnlocked?1:.10);if(portalUnlocked&&!player.entering&&player.pos.distanceTo(portalWorld)<2.4){player.entering=true;player.entryT=0;player.vel.set(0,0,0);ringFx(player.pos,0x86eaff,.3,4.5,.6);}if(player.entering){player.entryT+=dt;portal.setCharge(1);const p=Math.min(1,player.entryT/.85);player.root.scale.setScalar(Math.max(.02,1-p));player.root.position.y=player.pos.y+p*1.3;if(player.entryT>.88)player.root.visible=false;if(player.entryT>1.02&&!victory){victory=true;playing=false;resultText.textContent=`${CHARACTERS[player.kind].name} · ${leavesCollected}/${leaves.length} Maple Leaves · Crest recovered · chamber guards defeated.`;resultEl.classList.add('show');}}}
function updateCamera(dt){const target=player.pos.clone().add(new THREE.Vector3(0,1.25,0)),dist=8.8,height=3.3;const desired=new THREE.Vector3(target.x+Math.sin(cameraYaw)*dist,target.y+height,target.z+Math.cos(cameraYaw)*dist);camera.position.lerp(desired,1-Math.exp(-7*dt));camera.lookAt(target);}
function updateHUD(){const C=CHARACTERS[player.kind],alive=enemies.filter(e=>e.alive).length,hearts='♥'.repeat(Math.max(0,player.health))+'♡'.repeat(Math.max(0,player.maxHealth-player.health));statsEl.textContent=`${C.name}\nHEALTH ${hearts}  LIVES ${player.lives}\nENEMIES ${alive}  LEAVES ${leavesCollected}/${leaves.length}  CREST ${crestCollected}/1`;cooldownEl.textContent=`F ${C.attack} ${player.attackCD>0?player.attackCD.toFixed(1)+'s':'READY'}\nQ ${C.special} ${player.specialCD>0?player.specialCD.toFixed(1)+'s':'READY'}\nSHIFT DASH ${player.dashCD>0?player.dashCD.toFixed(1)+'s':'READY'}${overcharge>0?`\nOVERCHARGE ${overcharge.toFixed(1)}s`:''}`;if(alive>0)missionEl.textContent=`BREAK THE BARRIERS · DEFEAT ${alive} CHAMBER GUARD${alive===1?'':'S'} · FIND THE MAPLE CREST`;else if(!crestCollected)missionEl.textContent='GUARDS CLEARED · RECOVER THE MAPLE CREST';else missionEl.textContent=portalUnlocked?'PORTAL ONLINE · CLIMB TO THE STASIS CHAMBER':'PORTAL LOCKED';}

function openSelect(){if(player.entering)return;selectEl.classList.add('show');playing=false;hud.classList.add('hidden');}
async function chooseCharacter(id){const card=[...gridEl.children].find(b=>b.dataset.character===id);if(card){card.disabled=true;card.querySelector('small').textContent='Loading…';}try{await setPlayerVisual(id);selectEl.classList.remove('show');hud.classList.remove('hidden');playing=true;}catch(e){console.error(e);alert('That character model could not load. Try another.');}finally{if(card){card.disabled=false;card.querySelector('small').textContent=CHARACTERS[id].subtitle;}}}
gridEl.addEventListener('click',e=>{const b=e.target.closest('.characterCard');if(b)chooseCharacter(b.dataset.character);});changeBtn.addEventListener('click',openSelect);replayBtn.addEventListener('click',()=>restart(true));
function restart(showSelect=false){resultEl.classList.remove('show');victory=false;player.entering=false;player.entryT=0;player.root.visible=true;player.root.scale.setScalar(1);player.pos.set(0,.12,21);player.vel.set(0,0,0);player.health=player.maxHealth;player.lives=3;player.attackCD=player.specialCD=player.dashCD=0;player.root.position.copy(player.pos);for(const b of bricks){b.alive=true;b.hp=2;b.mesh.visible=true;}for(const l of leaves){l.collected=false;l.mesh.visible=true;}for(const c of crests){c.collected=false;c.mesh.visible=true;}leavesCollected=0;crestCollected=0;powerTaken=false;powerCrystal.visible=true;overcharge=0;for(const e of enemies){e.alive=true;e.hp=e.maxHp;e.root.visible=true;e.stun=0;e.attackCD=.4+Math.random();}playing=!showSelect;if(showSelect)openSelect();}

async function init(){await buildLibraryDress();await Promise.all(enemySpawns.map(a=>spawnEnemy(...a)));await setPlayerVisual('gamer');player.root.position.copy(player.pos);camera.position.set(0,5.5,29);boot.classList.add('hidden');hud.classList.add('hidden');fatal.style.display='none';requestAnimationFrame(loop);}
function loop(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;clock=now/1000;player.attackCD=Math.max(0,player.attackCD-dt);player.specialCD=Math.max(0,player.specialCD-dt);player.dashCD=Math.max(0,player.dashCD-dt);player.invuln=Math.max(0,player.invuln-dt);overcharge=Math.max(0,overcharge-dt);if(playing){if(attackPressed)attack();if(specialPressed)special();attackPressed=specialPressed=false;movePlayer(dt);updateEnemies(dt);updateProjectiles(dt);collectThings();objective(dt);}else if(!player.entering){attackPressed=specialPressed=jumpPressed=dashPressed=false;player.visual?.update(dt,0,false);}updateCollectibles(dt,clock);updateFx(dt);portal.update(clock,dt);updateCamera(dt);updateHUD();composer.render();requestAnimationFrame(loop);}
function resize(){renderer.setSize(innerWidth,innerHeight,false);composer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/Math.max(1,innerHeight);camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
init().catch(err=>{console.error(err);boot.classList.add('hidden');fatal.style.display='flex';fatalText.textContent=String(err?.stack||err);});
}catch(err){console.error(err);boot.classList.add('hidden');fatal.style.display='flex';fatalText.textContent=String(err?.stack||err);}
